### ISSUE TITLE
Issues with display of available processors

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1004]
# Describe the issue
There is a new method of displaying and enabling / disabling processors (audio, synth, special, etc.) which has some issues:

- Some processors are not available, e.g. Internet Radio
- The list does not get updated when required
- There is an unknown variable `plugin_name` used in function `generate_engines_config_file`
- Default plugin description is "Lorem ipsum..." which was fine for testing but shouldn't be shown to users - replace with more appropriate default text

# To Reproduce
## Steps to reproduce the behavior:
1. Add Generator Chain
2. Bold press SELECT to show the list of all generators
 ## Expected behaviour
Internet Radio is in the list.
## Actual behaviour
Internet Radio is not in the list.
# Additional context
`generate_engines_config_file` is only called under some conditions. I would recommend this be called after every update so that any changes to processor config (e.g. new processor) are recognised.

Also fix `plugin_name` not being defined before being used in `generate_engines_config_file`.

Whilst there we could also implement #1003. (Use LV2 description instead of default description if available.)

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: Behringer UMC1820
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21, ADS1115@0x4A
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 42% (1607M/3793M)
SD Card: 76% (21G/29G)
Temperature: 50.1ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (c575089) 
zynthian-ui: oram (2e99008)
zynthian-sys: oram (2ad9a16)
zynthian-data: oram (0db799e)
zynthian-webconf: oram (d9caf80)
```

**Comment by riban-bw** [comment]
I have fixed some of this. @jofemodo please validate the fixes.

**Comment by jofemodo** [comment]
Ups! I forgot to review this. I thought the issues vanished by some bizarre charm but now i see the real wizard's hand behind. Jejeje!
