### ISSUE TITLE
zyncoder_test not working in oram

### ISSUE THREAD

**Issue by zer0brain** [zynthian/zynthian-issue-tracking#1007]
**Describe the bug**
Testing Custom wiring with .zyncoder_test 

**To Reproduce**
1. Connect with SSH
2. run ./zyncoder_test

**Expected behavior**
output of switch and Encoder mapping

**Screenshots**
(venv) root@zynthian:/zynthian/zyncoder/build# ./zyncoder_test
Starting ZynCore...
ZynCore: Setting-up 16 x Zynswitches...
ZynCore->setup_zynswitch(0, 27, ...): Can't request line -2104421088 from RPI GPIO
ZynCore->setup_zynswitch(1, 24, ...): Can't request line -2104421088 from RPI GPIO
ZynCore->setup_zynswitch(2, 21, ...): Can't request line -2104421088 from RPI GPIO
ZynCore->setup_zynswitch(3, 4, ...): Can't request line -2104421088 from RPI GPIO
ZynCore->setup_zynswitch(4, 5, ...): Can't request line -2104421088 from RPI GPIO
ZynCore->setup_zynswitch(5, 6, ...): Can't request line -2104421088 from RPI GPIO
ZynCore->setup_zynswitch(6, 13, ...): Can't request line -2104421088 from RPI GPIO
ZynCore->setup_zynswitch(7, 19, ...): Can't request line -2104421088 from RPI GPIO
ZynCore: Setting-up 4 x Zynpots (zyncoders)...
ZynCore->setup_zyncoder(0, 17, 18): Can't request line from RPI GPIO
ZynCore->setup_zyncoder(1, 22, 23): Can't request line from RPI GPIO
ZynCore->setup_zyncoder(2, 15, 20): Can't request line from RPI GPIO
ZynCore->setup_zyncoder(3, 25, 14): Can't request line from RPI GPIO
ZynCore->gpiod_start_callbacks: Callback thread created successfully
ZynCore->init_poll_zynswitches(): Zynswitches poll thread created successfully
Segmentation fault

**Setup:**
IMG: 2024-03-01-zynthianos-bookworm-aarch64-oram-2403-1 with latest update.

Raspberry Pi 4 Model B Rev 1.2
Audio: [Steinberg UR22 MKII](https://192.168.1.172/hw-audio)
Display: [Pi 7 Touchscreen Display 800x480](https://192.168.1.172/hw-display)
Wiring: [CUSTOM](https://192.168.1.172/hw-wiring)
I2C: [MCP23017@0x20, ADS1115@0x48](https://192.168.1.172/hw-wiring)
Profile: [myprofile](https://192.168.1.172/hw-wiring)

zyncoder: oram (c575089)
zynthian-ui: [oram (35af058)](https://github.com/zynthian/zynthian-ui/commit/35af058cfa80b36ea98c16ecbdeacee1c99040c1)
zynthian-sys: [oram (609b7e7)](https://github.com/zynthian/zynthian-sys/commit/609b7e7fff2be3983dd0a5df5ec0f73938c547bb)
zynthian-data: [oram (0db799e)](https://github.com/zynthian/zynthian-data/commit/0db799e07f61fc05153be18ba9ef998537b0eb66)
zynthian-webconf: [oram (d9caf80)](https://github.com/zynthian/zynthian-webconf/commit/d9caf806bf2b2a57e649aad2fedcb1081faf4a36)

**Comment by jofemodo** [comment]
I can't reproduce with current version or perhaps it was solved by a recent commit.
