### ISSUE TITLE
Can't select Fluidsynth soundfont

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1018]
# Describe the issue
There has been a change to how soundfonts are displayed in Fluidsynth. Soundfonts with multiple instruments seem to have an asterisk suffixe but selecting these does not show the list of instruments.
# To Reproduce
## Steps to reproduce the behavior:
1. Add Fluidsynth chain
2. Select AirFont320
 ## Expected behaviour
List of instruments in AirFont320 soundfont shown.
## Actual behaviour
Falls back to mixer view. It is not possible to select instruments.
# Additional context
Log message:
```
WARNING:zynthian_engine_fluidsynth.load_soundfont: SoundFont '/zynthian/zynthian-data/soundfonts/sf2/AirFont320*.sf2' can't be loaded
```

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: Behringer UMC1820
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21, ADS1115@0x4A
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 43% (1650M/3792M)
SD Card: 68% (19G/29G)
Temperature: 50.6ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (c575089) 
zynthian-ui: oram (7fe4584)
zynthian-sys: feature/jamulus (55bb81a)
zynthian-data: feature/jamulus (b948b2e)
zynthian-webconf: oram (5dc999d)
```

**Comment by jofemodo** [comment]
I never implemented the asterisk thing. This should be an issue. I will check.

**Comment by jofemodo** [comment]
The strange "*" files were created by some unknown event some weeks ago. Probably an install recipe.
The issue can be solved by running this command:

`rm -f $ZYNTHIAN_DATA_DIR/soundfonts/sf2/*\**`

a patch has been added to the update script.
