### ISSUE TITLE
ORAM: LV2 preset plugins are not selectable

### ISSUE THREAD

**Issue by ToFFmashines** [zynthian/zynthian-issue-tracking#1019]
**Describe the bug**
LV2 presets created in natural GUI cannot be selected in Zynthian UI. The preset selection step between specifying the midi channel for the chain and setting the engine only flashes and cannot be returned to preset setting page.

**To Reproduce**
Make chain with for example GeonKIck, drumkv1, samplv1 or synthv1 engine.
Set and save lv2 preset.
In webconf SOFTWARE / Engines click on Search for Presets
Reboot
Make chain with LV2 plugin engine 

**Setup:**
HARDWARE
Raspberry Pi 400 Rev 1.1
Audio: [Behringer UMC404HD](http://zynthian.local/hw-audio)
Display: [WaveShare 7 HDMI+USB 1024x600](http://zynthian.local/hw-display)
Wiring: [DUMMIES](http://zynthian.local/hw-wiring)
I2C: [Not detected](http://zynthian.local/hw-wiring)
Profile:
SYSTEM
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 19% (723M/3792M)
SD Card: 59% (17G/29G)
Temperature: 46.7ºC
Overclock: [None](http://zynthian.local/hw-options)
SOFTWARE
zyncoder: [oram (c575089)](https://github.com/zynthian/zyncoder/commit/c575089dba5e8eb32df94a63386f404ec4282205)
zynthian-ui: [oram (0aa0003)](https://github.com/zynthian/zynthian-ui/commit/0aa0003421d047110cc6a00af2f1d4888a69bd7f)
zynthian-sys: [oram (c016b36)](https://github.com/zynthian/zynthian-sys/commit/c016b36cbe22195ba748d102ae493afd54fff476)
zynthian-data: [oram (97355e2)](https://github.com/zynthian/zynthian-data/commit/97355e206fe63a954564cce08837d6c4a3c276d8)
zynthian-webconf: [oram (5dc999d)](https://github.com/zynthian/zynthian-webconf/commit/5dc999d11811db6616d21648cb951d01597fa09b)

**Comment by jofemodo** [comment]
Sorry, i can't reproduce the issue. It's working perfectly OK for me.
I created a synth chain with drumkv1, then created and saved 2 presets. Then click the "search for presets" button.
Then, i re-loaded the processor. Running processors don't refresh the preset list and need to be restarted. Perhaps this is the issue?

**Comment by ToFFmashines** [comment]
The problem used to occur on the early version of oram, now it doesn't occur anymore, please close as solved by a higher power :-)
