### ISSUE TITLE
Mouse fails on Category in Engine selection.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1020]
**Describe the bug**
If using purely a mouse you are unable to alter the category parameter correctly.
Yjr value is displayed as the mouse interacts with v4TR encoder and the value is seen to change but the centre display area does not reflect a change.

**To Reproduce**
1. Go to Engine selection
2. Use Mouse to alter category parameter.

**Expected behavior**
Should have functionality akin to Encoders & QWERTY

zyncoder: [oram (c575089)](https://github.com/zynthian/zyncoder/commit/c575089dba5e8eb32df94a63386f404ec4282205)
zynthian-ui: [feature/jamulus (86b966c)](https://github.com/zynthian/zynthian-ui/commit/86b966c92670cb59ca26d8bbd0e4000692f851ee)
zynthian-sys: [feature/jamulus (55bb81a)](https://github.com/zynthian/zynthian-sys/commit/55bb81a584a3bfb49747e995326f97b7204cb9d7)
zynthian-data: [feature/jamulus (b948b2e)](https://github.com/zynthian/zynthian-data/commit/b948b2ed59e1700e5c73507583ae811ee695ef26)
zynthian-webconf: [oram (4c5d7a5)](https://github.com/zynthian/zynthian-webconf/commit/4c5d7a5b625e0c9069e50b9618370161473d7092)

Happens on Pure oram.

**Comment by jofemodo** [comment]
You can also use "horizontal swipe" on the list to move across categories.
QWERTY also works OK with left/right arrows.
