### ISSUE TITLE
Zero-centered parameters should have the visual red arc in the UI start at 12 o'clock rather than 7 o'clock

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#1021]
Continuous parameters in the Zynthian UI are always graphically rendered with a red arc, starting in the 7 o'clock position (or thereabouts) and growing clockwise as the parameter value is increased, up to a maximum of extending from 7 o'clock all the way around to 5 o'clock.

However, for parameters which are bipolar and have a zero value in the middle, it would be an advantage if the length of the arc were at minimum when the parameter value is zero.

My suggestion is that zero-centered values have the arc start at the 12 o'clock position, growing clockwise when the parameter is increased above zero (up to a maximum of 5 o'clock or whatever the exact maximum position is today), and growing counter-clockwise when the parameter is decreased below zero, down to the 7 o'clock position. That way, visually, when the parameter is at zero (in the middle), the red arc would be at its minimum size, which would make it easier to 'aim' for the zero position when setting the parameter. It would enhance the feeling of having a detent at the zero position, which a lot of synthesizers have, for instance instruments having a bipolar filter envelope modulation control (e.g. the Korg Polysix).

**Comment by riban-bw** [comment]
There is also a numerical display of the value so you do see where centre is but this could be a useful visual enhancement.

We need to consider how this is detected and where the null point is shown, e.g. a parameter with range -2 to +10 may want the null at 9 o'clock. We also need to consider how logarithmic scales work.

**Comment by riban-bw** [comment]
This kind of offset display is only relevant for controls that have a minimum value less than or equal to zero and a maximum value greater than or equal to zero. I am working on a solution...
