### ISSUE TITLE
setBfree not working when changing MIDI channel

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1025]
# Describe the issue
Changing the MIDI channel of setBfree stops it working.
# To Reproduce
## Steps to reproduce the behavior:
1. Add a chain with setBfree
2. Enable Activ mode for the MIDI input
3. Check it works
4. Change the MIDI channel for the chain
 ## Expected behaviour
Sounds when playing MIDI with chain selected.
## Actual behaviour
No sound when playing MIDI with chain selected.
# Additional context
Changing the MIDI channel back to its original value starts working again. Other instruments do not show this flaw.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20, MCP23017@0x21, ADS1115@0x48
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 24% (447M/1846M)
SD Card: 25% (14G/57G)
Temperature: 47.2ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (c575089) 
zynthian-ui: oram (4daa3b2)
zynthian-sys: oram (99700c2)
zynthian-data: oram (97355e2)
zynthian-webconf: oram (3f1dae4)
```

**Comment by jofemodo** [comment]
setBfree can't be changed to other MIDI channel while running. I will fix it.
