### ISSUE TITLE
Touch inverted

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1028]
# Describe the issue
The touch interface is inverted on the V5. This is a fairly new issue / regression.
# To Reproduce
## Steps to reproduce the behavior:
1. Open on-screen keyboard, e.g. change name of chain
2. Touch an on-screen key
 ## Expected behaviour
The touched key is selected.
## Actual behaviour
A different key is selected.
# Additional context
This was not happening until fairly recently so looks like a regression.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 19% (751M/3792M)
SD Card: 85% (24G/29G)
Temperature: 54.0ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (c575089) 
zynthian-ui: oram (4daa3b2)
zynthian-sys: oram (13cb66d)
zynthian-data: oram (97355e2)
zynthian-webconf: oram (3f1dae4)
```

**Comment by riban-bw** [comment]
Solution seems to be to disable rotation, e.g. in screen config:
```
display_lcd_rotate=2
dtoverlay=rpi-ft5406,touchscreen-inverted-x=0,touchscreen-inverted-y=0
```
Has a recent driver update changed the behaviour of this screen or maybe some other touch interface modifications?

**Comment by jofemodo** [comment]
This has been solved by a recent commit.

https://github.com/zynthian/zynthian-sys/commit/58c14e342bd16f89fbaae898ed8d262d22e389d3
