### ISSUE TITLE
amSynth crashes MOD

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#103]
**Describe the bug**
Adding amSynth to a MOD pedalboard restarts Zynthian UI.

**To Reproduce**
1. Add MOD layer
2. Within MOD-UI add amSynth to pedal board
3. Zynthian restarts

**Expected behaviour**
amSynth should be added to pedal board.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: DUMMIES
GPIO Expander: Not detected

SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: 2019-12-19
Memory: 18% (169M/926M)
SD Card: 82% (11G/14G)
Temperature: 54.8ºC

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (dd960ca)
zynthian-sys: master (7ecb396)
zynthian-data: master (3d44cc8)
zynthian-webconf: master (9fd249a)

**Comment by jofemodo** [comment]
Duplicate in #91
