### ISSUE TITLE
Aeolus core dumps in Oram Bookworm 64

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#1035]
# Describe the issue
Playing Auelus snapshot after some notes a continuous noise is produced
# To Reproduce
load Aeouls in a chain
set Midi channel 1
choose Manual I
choose Well tempered
choose General
choose Preset 01
## Steps to reproduce the behavior:
1. Just play some notes till you get the issue
2. Noise is generated and you have to reboot
 ## Expected behaviour
## Actual behaviour
A clear and concise description of what actually happens.
# Screenshots
# Additional context

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 8% (625M/7810M)
SD Card: 58% (32G/59G)
Temperature: 55.5ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (84612a6) 
zynthian-ui: oram (901df2c)
zynthian-sys: oram (de001cc)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (8fd2665)

**Comment by jofemodo** [comment]
I can confirm this behavior in Oram Bookworm 64 bits. When running from the native GUI without OSC, it seems to work nicely. It seems related with the OSC implementation.

**Comment by riban-bw** [comment]
Is this resolved by https://github.com/zynthian/aeolus/commit/818aa450bac7437737e06824b057090fbb17e914?

**Comment by Piattica** [comment]
I played for a while without issues. So for me it is solved


*       Paolo Piattica
 *


Il giorno gio 23 mag 2024 alle ore 08:07 riban-bw ***@***.***>
ha scritto:

**Comment by riban-bw** [comment]
Thanks @Piattica! I will close the ticket.
