### ISSUE TITLE
ORAM 2403: setBfree issue (not possible create a split using same MIDI channel as the other splits)

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#1036]
**Describe the bug**
setBfree: not possible create a split using same MIDI channel as the other splits

**To Reproduce**
a) Add an instrument chain → setBfree
b) → MIDI CHANNEL 1
c) → Upper + Lower
d) → Sine
e) → Blues 1

On mixer now I have:
chain 1: setBfree/Upper Blues 1
chain 2: setBfree/Lower LCello

Both channels respond to MIDI CHANNEL 1 but not in the same time:
if cursor is on chain 1 you play Upper Blues 1
if cursor is on chain 2 you play Lower LCello
if cursor is on Main you still play Lower LCello

**Expected behavior**
It should be possible to set MIDI channel and notes range for each chain

**Setup ***
Hardware
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
System
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 8% (625M/7810M)
SD Card: 58% (32G/59G)
Temperature: 55.5ºC
Overclock: None
MIDI & UI
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
Software
zyncoder: oram (84612a6) 
zynthian-ui: oram (901df2c)
zynthian-sys: oram (de001cc)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (8fd2665)

**Comment by jofemodo** [comment]
Fixed!. setBfree is now fully integrated with "chain_manager".
