### ISSUE TITLE
Qmidinet has stopped working.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1037]
**Describe the bug**
.Qmidinet has stopped working.

**To Reproduce**
1. Go to admin
2. Attempt to turn on qmidinet..'
zyncoder: oram (84612a6)
zynthian-ui: oram (9d5c179)
zynthian-sys: oram (7c9dfd3)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (3b48f5c)

**Comment by riban-bw** [comment]
More info required. What is the failure mode? Are there any logs or error messages? What is the behaviour of the UI?

**Comment by wyleu** [comment]
The UI doesn't allow qmidinet to be selected.

It was enabled and working upon updating it wasn't working on start up and couldnt be selected.

Can be started successfully with systemctl start qmidinet.service

**Comment by riban-bw** [comment]
Is the option available in the menu?

**Comment by wyleu** [comment]
It's available but it doesn't activate.

Looks like qmidinet.service is not starting on first boot.

Upon reboot the problem returns

**Comment by riban-bw** [comment]
I can't reproduce this. Qmidinet appears to toggle on demand.

Okay I think I see it now. If you enable qmidinet then reboot it appears you can't subsequently restart it.

**Comment by riban-bw** [comment]
Sorry - my bad! I had added guard code to avoid unrequired start / stop of services which was evident in the UI during cleaning or snapshot loading but this had stopped the initial state from being set correctly. It is now fixed.

**Comment by wyleu** [comment]
Naughty, naughty Riban...
