### ISSUE TITLE
ORAM : after update, error stopping BLUETOOTH

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#1038]
# Describe the issue
At loading this error is shown: **error stopping BLUETOOTH**
# To Reproduce
## Steps to reproduce the behavior:
1. switch on.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 9% (750M/7810M)
SD Card: 59% (33G/59G)
Temperature: 41.3ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (84612a6) 
zynthian-ui: oram (75c32d8)
zynthian-sys: oram (7c9dfd3)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (3b48f5c)
```

**Comment by Piattica** [comment]
after this updated is fixed:

zyncoder: [oram (84612a6)](https://github.com/zynthian/zyncoder/commit/84612a664704684ce74fe986cad31917895999fd)
zynthian-ui: [oram (ea5bde0)](https://github.com/zynthian/zynthian-ui/commit/ea5bde029348dbcb31cc353f53a45869b4329d0d)
zynthian-sys: [oram (7c9dfd3)](https://github.com/zynthian/zynthian-sys/commit/7c9dfd3aa912f12df23f81f6171796213719ca4b)
zynthian-data: [oram (db0355a)](https://github.com/zynthian/zynthian-data/commit/db0355a5c8f23f314c7959d3e2aed01b665fc788)
zynthian-webconf: [oram (3b48f5c)](https://github.com/zynthian/zynthian-webconf/commit/3b48f5caaf7ed3cdaa010e2e32ca290ba2c8d999)

**Comment by riban-bw** [comment]
Excellent! I was a bit suprised it was broken by the previous commit but glad the next one fixed it.
