### ISSUE TITLE
Segmentation fault when clearing all

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1041]
# Describe the issue
I was using the touch screen to Remove All when I saw errors on the GUI before Zynthian restarted. Looking at the log I see it encountered a segmentation fault.
# To Reproduce
## Steps to reproduce the behavior:
1. Using the touchscreen, press Remove All
## Expected behaviour
All chains are removed.
## Actual behaviour
A segmentation error occured.
# Additional context
I cannot reproduce on demand. The log for the error is below. I have seen that Remove All will sometime error trying to start touchosc2midi.service and sometimes it does not which is odd but possibly irrelevant.
```
May 24 16:58:25 zynthian-v5-64 startx[4262]: WARNING:zynthian_gui_bluetooth.process_dynamic_ports: Command '['bluetoothctl', 'info', 'CB:12:CC:65:5F:46']' returned non-zero exit status 1.
May 24 16:58:36 zynthian-v5-64 startx[4262]: WARNING:zynthian_gui_bluetooth.toggle_ble_trust: Failed to complete toggle BLE device action: Command '['bluetoothctl', 'pair', 'CB:12:CC:65:5F:46']' timed ou>
May 24 16:59:36 zynthian-v5-64 startx[4232]: ./zynthian.sh: line 234:  4262 Segmentation fault      ./zynthian_main.py
May 24 16:59:37 zynthian-v5-64 startx[8024]: /zynthian/config/img/fb_zynthian_message.png is 800x480 PNG image, color type RGB_ALPHA, 8 bit
May 24 16:59:37 zynthian-v5-64 startx[8024]:   Zooming image by 100%...done
May 24 16:59:37 zynthian-v5-64 startx[8024]:   Merging...done
May 24 16:59:37 zynthian-v5-64 startx[8024]:   Building XImage...done
May 24 16:59:48 zynthian-v5-64 startx[8034]: ZynCore: Setting-up 20+4 x Zynswitches...
May 24 16:59:48 zynthian-v5-64 startx[8034]: ZynCore: Setting-up Zynpots => 4 x PEC11 ...
```
I don't _think_ the bluetooth stuff is relevant, having occured a minute earlier but could be related.
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 16% (614M/3792M)
SD Card: 95% (26G/29G)
Temperature: 48.2ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (84612a6) 
zynthian-ui: oram (27d8317)
zynthian-sys: oram (7a6c26f)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (5f6f937)
```

**Comment by riban-bw** [comment]
I have added module `faulthandler` to my local copy of zynthian in a bid to capture what is causing this but I can't currently trigger the bug.

**Comment by jofemodo** [comment]
Note i changed some memory related code with my last zynseq changes, so perhaps it got solved. Let's see if it triggers again.

**Comment by riban-bw** [comment]
I have tried to reproduce this but cannot. There has been some work on the C/C++ libs which _may_ have resolved it.

Note: Use of `faulthandler` in `zynthian_main.py` may prove useful for similar issue tracking. I have not added this as it may add an undesirable overhead but we could add it in future or maybe have a ENV VAR that can be passed to enable it.

I will close this ticket as it is not serving any useful purpose.
