### ISSUE TITLE
Allow configuration of audio with user friendly parameters

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1044]
**Is your feature request related to a problem? Please describe.**
In webconf you can reconfigure the audio interface by first selecting custom then entering some cryptic parameters into the jackd configuration field. It would be better if we could set parameters in a user friendly way.

**Describe the solution you'd like**
Allow user to select parameters like:

- Soundcard
- Samplerate
- Buffer size

**Describe alternatives you've considered**
The wiki can describe the parameters but it is often a source of confusion.

**Additional context**
The soundcard selection could automatically populate the `hw:` element of jackd config.
We could have a database of configuration to assist users.

**Comment by jofemodo** [comment]
Note that not all buffer sizes and sample rates works for every soundcard.
Anyway, it think it could be interesting to have these 2 parameters in separated fields. Not for now, OK?
This is the typical change that you enter the rabbit hole and ups!!! it's a lot deeper than you thought!! This has not been changed from the very beginning, so we should be prepared to have some surprises, or perhaps not ...

**Comment by riban-bw** [comment]
I started working on this in dev branch 1044_soundcard_configuration. Much of the functionality is implemented but there are issues...

**Comment by riban-bw** [comment]
I think the implementation in the dev branch works quite well. User may select from lists for:

- Soundcard device (lists only currently installed / detected soundcards)
- Samplerate (32000, 44100, 48000, 96000)
- Buffer size (64, 128, 256, 512, 1024, 2048)
- Number of buffers (2, 3)
- 16-bit mode (toggle)
- Soft x-run mode (toggle)

These parameters are reset when a known soundcard is selected. The soundcard device will show (not detected) if a card is selected that is not currently installed or working.

Jackd options is updated dynamically, even if a kit is selected which allows modification of these parameters for a kit, e.g. to set a different samplerate.

There is a warning that some parameters may not work and an indication of the calculated software latency (with a warning that the actual latency may be larger due to soundcard hardware).

**Comment by riban-bw** [comment]
~~The config does not get applied if a kit is selected. Need to fix this~~... FIXED!

**Comment by riban-bw** [comment]
Deployed to stable 2409.4.
