### ISSUE TITLE
Zynthian restarts when changing Pianoteq parameters

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1045]
# Describe the issue
If you change a pianoteq parameter in webconf, e.g. Samplerate, the whole zynthian UI is restarted. This is surely not required - especially if Pianteq is not even loaded as an engine?

# To Reproduce
## Steps to reproduce the behavior:
1. In webconf SOFTWARE->Pianoteq, change Pianoteq samplerate
2. Press "Save Config" button
 ## Expected behaviour
Pianoteq config is saved.
## Actual behaviour
UI restarts
# Additional context
I am not sure that we need to restart the config at all and if Pianoteq is loaded we could restart Pianoteq engine only.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 13% (504M/3792M)
SD Card: 95% (26G/29G)
Temperature: 52.5ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: (no branch, rebasing oram) (5d34713) 
zynthian-ui: oram (864b9de)
zynthian-sys: oram (b71bafd)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (5f6f937)
```

**Comment by jofemodo** [comment]
But it's required if Pianoteq is loaded as an engine and currently we can't know if Pianoteq is running. Well, indeed we could look for the "pianoteq" process, but it's quite ugly. Do you think this is really needed?

**Comment by jofemodo** [comment]
Done!
