### ISSUE TITLE
Errors in zyncoder detected by static code analysis

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1048]
# Describe the issue
Running static code analysis tool `cppcheck` on zyncoder shows there are errors in the codebase.
# To Reproduce
## Steps to reproduce the behavior:
1. Run `cppcheck /zynthian/zyncoder`
 ## Expected behaviour
No errors.
## Actual behaviour
The following errors are detected:
```
/zynthian/zynthian-ui/zyncoder/zynads1115.c(305): error: syntax error: <)
/zynthian/zynthian-ui/zyncoder/zynrv112.c(58): error: Code 'boost::circular_buffer' is invalid C code. Use --std or --language to configure the language.
```
# Additional context
I have fixed some errors but these two need a _grown-up_!
I do not know what is intended in the while loop of the first error.
The second looks like boost C++ library is being used in C source code. Boost is a C++ library and does not suppport C. It _may_ work but is not guaranteed to do so now or in the future. I recommend either replacing the Boost method with another ring buffer or changing the code to be C++. The former seems the most appropriate path (rather than refactoring into a higher level language). 

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 35% (1332M/3792M)
SD Card: 95% (26G/29G)
Temperature: 44.3ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (d25a811) 
zynthian-ui: oram (ce42f64)
zynthian-sys: oram (ae582d3)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (eb9e08d)
```

**Comment by jofemodo** [comment]
OK! I just checked and no need to worry about these messages!
+ The first one should not be shown. It's a macro, not a function. cppcheck should know this ;-)
+ The second one is because i'm mixing C++ and C syntax in a not very orthodox way, but it works and i haven't found a better way. This code is quite tested and i never get segfaults, i think it's safe to ignore it. Anyway, it's Z2 code ;-)
