### ISSUE TITLE
Give clue to the error when Zynthian fails to start

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1049]
**Is your feature request related to a problem? Please describe.**
If Zynthian fails to start it will display an error on the screen. This gives the IP address (if it is assigned) and the exit code but does not give more clues to why the start has failed.

**Describe the solution you'd like**
Catch the errors that have caused zynthian to fail and try to deduce the cause. Some causes can be identified (or at least guessed), e.g. soundcard missing or not configured correctly.

**Comment by riban-bw** [comment]
When Zynthian begins it initialises the zyncore lib (zynthian_gui_config.py: `lib_zyncore = lib_zyncore_init()`). There is a try/except around this which may indicate an issue with GPI config but zyncore will attempt to start jack2 with default parameters if it is not already running which is undesirable behaviour. We want to catch the lack of jack2 and provide an indication to the user. (The current behaviour adds confusion to configuration investigation.) This can be resolved by passing `JackNoStartServer` to `jack_client_open` in zynmidirouter `init_jack_midi`.

`lib_zyncore_init` is called in zynthian_gui_config but should actually be called from non-gui code as it is a core, non-gui element. It starts all the core modules including zynmidirouter, gpiod, zynpot, etc. It may be advantageous for a failure of any of these modules to be indicated. Maybe we could add a zyncore function to return the status of each element (maybe a bitwise flag) and ability to get human readable errors (although they can be (already mostly are) presented in the library stdout / errout which is reported as zynthian runtime output (recorded in systemd log and viewable with journalctl).

I have coded some fixes for some of this but not yet committed. These code changes only limit startup with better logging. They don't actually provide UI feedback as desired by this feature request. That needs extraction of useful info and creation of a splash screen with this info embedded.

**Comment by jofemodo** [comment]
Solved in:

+ https://github.com/zynthian/zyncoder/commit/b5c87b717605a6296ce195736538e209f718dde3
+ https://github.com/zynthian/zyncoder/commit/912103f7d19b5d5f84bafb1ebcc85ce9f9f7ab97
+ https://github.com/zynthian/zyncoder/commit/a7976d833bb2afcd8ac101a42a6ee60cc737f8de

and:

+ https://github.com/zynthian/zynthian-ui/commit/e918f529275a63f14f863d5dc1e33c7293f79985
