### ISSUE TITLE
Missing script send_osc

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1051]
# Describe the issue
The zynthian service script includes reference to `send_osc` which is used to gracefully close zynthian but `send_osc` is not present so the systemd script fails.
# To Reproduce
## Steps to reproduce the behavior:
1. At command line send, `systemctl stop zynthian`
2. Observe logs for systemd service, e.g. `journalctl -ruzynthian`
 ## Expected behaviour
Zynthian stops without error.
## Actual behaviour
An error occurs:
```
May 30 08:57:37 zynthian-v4 (send_osc)[57954]: zynthian.service: Failed to locate executable send_osc: No such file or directory
May 30 08:57:37 zynthian-v4 (send_osc)[57954]: zynthian.service: Failed at step EXEC spawning send_osc: No such file or directory
```
# Additional context
I don't recall where the `send_osc` script was installed but it simply despatched an OSC message.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 37% (1433M/3792M)
SD Card: 85% (24G/29G)
Temperature: 51.6ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (d25a811) 
zynthian-ui: oram (7e944a7)
zynthian-sys: oram (d14dc8d)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (eb9e08d)
```

**Comment by jofemodo** [comment]
send_osc is now installed in a python virtual environment and it's not in the default PATH. I fixed in the service files.
