### ISSUE TITLE
Bug: Unable to enable VNC in latest oram (240522)

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#1052]
**Describe the bug**
Enabling VNC in the UI configuration in the webconf does not enable 'VNC UI' or 'VNC Engines' in the webconf Interface menu.

**To Reproduce**
1. Enable vnc in the UI configuration in the webconf and click Save. This works without problems, and reviewing parameter shows that the VNC box is still ticked.
2. However, the menu items 'VNC UI' and 'VNC Engines' never show up in the Interface menu

**Expected behavior**
When vnc is enabled 'VNC UI' and 'VNC Engines' items should show up in the Interface menu so that new browser tabs/windows with these items can be opened.
**Setup:**
 - SD-image: Latest oram 240522.
 - Hardware Config: Zynthian V4

**Comment by riban-bw** [comment]
If I disable VNC from webconf then refresh the dashboard, I still see VNC-UI although this is not working. This may not be relevant.

If I enable VNC from webconf then both links are there and I can access both VNC UI & Desktop.

**Comment by riban-bw** [comment]
May I check that you are refeshing the dashboard after enabling VNC? There is an issue that the dashboard menus are not dynmamically updated so you need to enable VNC, save, wait a few seconds (let's say 10s) then refresh the dashboard, e.g. click the Zynthian icon at the top left.

**Comment by polluxsynth** [comment]
Indeed when writing the ticket, I hadn't tried refreshing the dashboard. However, I've tried again now: waited 10s or more, clicked on the Zynthian logo, then on Interface, but the VNC menus are not there, even though the Enable VNC Server box is still ticked.

![zynthian-novnc](https://github.com/zynthian/zynthian-issue-tracking/assets/6740739/0060f330-4876-4b4b-991e-c6ca525c207a)

Even tried logging in and accessing Zynthian from another web browser (Chrome) after enabling the VNC server but it's still the same: No VNC items in the Interface menu.

**Comment by riban-bw** [comment]
Okay - starting from a Oram image 240522 I see that `/zynthian/zynthian-sw/noVNC/utils/novnc_proxy` is missing. 

@jofemodo please fix this in the image / update.

**Comment by gitnob** [comment]
As I wrote in discourse, obviously noVNC is not installed, "/zynthian/zynthian-sys/scripts# recipes/install_noVNC.sh" could be called or should have been called before. After this it works.

**Comment by jofemodo** [comment]
Ups! It seems that i deleted the package by error when trying tio free some space to make the image to fit in 16GB SSDs.
It's restored again. Simply update.

**Comment by polluxsynth** [comment]
Just to confirm: Updated my oram installation and the VNC menu items are back now. Thanks!
