### ISSUE TITLE
USB start up/shut down noise   . . . .

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#106]
**Describe the bug**
USB Audio start up is VERY noisy ! 
Can this be silenced or is it the fault of the USB device? 

**To Reproduce**
1. Turn off Zynth.
2. Turn up audio channel connected to USB device 
3. Turn on Zynth
4. Watch your speakers destroy themselves !! (loud start up impulse for m USB device ) 

**Expected behavior**
I would expect a device to start up silently. Might just be an overhead of USB but I'd like to hear that it can't be done from someone. 

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
![image](https://user-images.githubusercontent.com/79083/71322159-7b576c80-24bc-11ea-9e8d-4318b43fbe39.png)

**Additional context**

**Comment by jofemodo** [comment]
You should conduct a deeper research about this issue. What about other USB-audio-device / users?
What is the origin of this noise? It would be nice to know the root of the issue ...

**Comment by wyleu** [comment]
Might be a re-config issue. Ive not been able to re-generate it. IF no reports in 3 days close.
