### ISSUE TITLE
Bug: LV2 plugins sometimes miss sustain pedal messages in oram

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#1062]
**Describe the bug**
When playing using the sustain pedal, when there is a lot of note activity, sustain pedal events are sometimes missed, causing notes to hang (if the pedal up message is missed) or not to sustain as they are expected to (if the pedal down message is missed).

**To Reproduce**
One way to trigger it is when playing using "legato pedaling" (a classic pianist term), i.e. using the sustain pedal to hold notes while moving from one note or chord to another, releasing the pedal at the same time as new notes are played. When playing in this way, sooner or later notes will sustain that shouldn't, indicating the pedal up message was missed, or a pedal down message will be missed, causing notes not to sustain as they would be expected to.

Another way is to first press the sustain pedal, then play a staccato chord at the same time as releasing the sustain pedal, where the symptom is that the notes sustain even though the pedal is released. For me it happens at least once out of five or ten attempts. It also happens with single notes but less frequently.

Note events themselves don't seem to get lost.

Note that the sustain pedal indicator on the MIDI Controllers page for the plugin seems to correctly follow the sustain pedal status, it's just the MIDI stream that reaches the plugin that seems to be a problem. I've also captured the MIDI stream going into Zynthian, verifying that the pedal messages where in fact there (for instance, at one point I got an inadvertent pedal sustain when the MIDI data was 176 64 127  176 64 0  144 60 53 1 28 60 64, i.e. MIDI CC 64 (pedal) on, MIDI CC 64 (pedal) off, Note on no 60 velocity 53, Note off no 60 velocity 64).

I've tried this with OB-Xd, MiMi-d and Dexed and all of them have the problem in oram, but work fine in stable. ZynAddSubFX on the other hand doesn't experience this problem in neither, leading me to believe it's related to LV2 plugins. I was going to try TAL NoiseMaker too, but it seems it doesn't honor the sustain pedal at all so it's not of much help here.

**Expected behavior**
All sustain pedal events should be honored.

**Screenshots**

**Setup:**
 - SD-image: oram (240522, updated)
 - Hardware Config (v4)

Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO](http://192.168.0.11/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.0.11/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.0.11/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, MCP4728@0x61](http://192.168.0.11/hw-wiring)

 - Software Versions

zyncoder: oram (b5c87b7)
zynthian-ui: [oram (c030c6c)](https://github.com/zynthian/zynthian-ui/commit/c030c6c096158cf06b025c3bc85137b5d906483f)
zynthian-sys: [oram (ce896ec)](https://github.com/zynthian/zynthian-sys/commit/ce896ec5d6cacc130a1c53577c9bd4433061ca25)
zynthian-data: [oram (db0355a)](https://github.com/zynthian/zynthian-data/commit/db0355a5c8f23f314c7959d3e2aed01b665fc788)
zynthian-webconf: [oram (c27fea2)](https://github.com/zynthian/zynthian-webconf/commit/c27fea2d817b520aaa6ce4c17ed3d2c4a58a1eb2)

**Additional context**
Since MiMi-d and OB-Xd are based on the same original source code, it might point to a bug in the plugin that for some reason only manifests itself in oram. They do use different plugin frameworks though: OB-Xd uses a modified (DISTRHO-Ports) JUCE framework, while MiMi-d uses DPF. Furthermore, the key assign code has been completely rewritten for MiMi-d compared to OB-Xd, so it at least it shouldn't be related to a problem with the key assigner. Furthermore, this doesn''t explain that Dexed has the same issue.

**Comment by riban-bw** [comment]
Currently, the most obvious differentiation is that this is only occuring on LV2 plugins. We should test further with native apps, e.g. Pianoteq, linuxsampler, sfizz, fluidsynth. If we can't get it to occur in those and we can get it to occur in other LV2 plugins then we can have some confidence that is the differentiation - but that may be more challenging to resolve as we may find the issue is outside the zynthian codebase!

**Comment by polluxsynth** [comment]
Agreed. I can test on a few more plugins.

Assuming it is LV2-related, my immediate suspect would be jalv; I haven't checked if it has been upgraded between stable and oram.

**Comment by polluxsynth** [comment]
Here's what I've tested so far:
- ZynAddSubFX: I don't know if I goofed up when testing this the other day, but today I can't get the sustain pedal to have any effect on the plugin itself, even though the pedal state is reflected in the 'sustain' parameter on the 'mode' page in the ZynAddSubFX UI. (Also tried rebooting the Zynthian with no change). Changing the parameter in the UI doesn't do anything either as far as the plugin is concerned. Interestingly enough, this goes for other parameters which have a CC number listed underneath the graphic parameter value display in the UI, such as 'volume', 'filter cutoff' and 'filter resonance'; 'panning' however, which has no CC listed, works as expected.
- LinuxSampler: Same as for ZynAddSubFX: Pedal state shows up in UI but does not cause plugin to react. Similarly, setting the value in the UI has no effect either, and as for ZynAddSubFX this goes for things like volume as well.
- fluidsynth: Same as LinuxSampler.
- Pianoteq (stage demo version): I couldn't get this one to play anything at all, no matter which notes I tried.
- Sfizz: This reacts as MiMi-d, Dexed and OB-Xd: pedal works but occasional pedal messages seem to get lost. Volume and pedal parameters in the UI have the expected influence on the plugins. I couldn't get the filter cutoff or resonance parameters to do anything though, but perhaps they only work on certain patches. Same for the portamento parameters.

**Comment by polluxsynth** [comment]
Here's another symptom: Say I have 8 chains configured, with MiMi-d on chain 1. If chain 1 is selected in the mixer display, the sustain pedal works as described in this ticket. If however the output (Main) is selected, by touching it on the touch screen, note events are played on the MiMi-d as before, but the sustain pedal does not cause any reaction at all. (This is with Multitimbral Mode off in the MIDI Input Device menu).

**Comment by riban-bw** [comment]
I triggered the issue with stuck notes on LV2 instrument whilst capturing the MIDI from zynmidirouter:
```
   0: b1 40 00 control change (channel  1): controller  64, value   0
   0: b1 40 7f control change (channel  1): controller  64, value 127
   3: 91 48 5f note on  (channel  1): pitch  72, velocity  95
 210: 91 4f 62 note on  (channel  1): pitch  79, velocity  98
  71: 91 4c 62 note on  (channel  1): pitch  76, velocity  98
  34: 81 48 40 note off (channel  1): pitch  72, velocity  64
   0: 81 4c 40 note off (channel  1): pitch  76, velocity  64
 111: 81 4f 40 note off (channel  1): pitch  79, velocity  64
```
The first command (CC64 off) is likely to be from the previous release but I show it here to demonstrate that all CC from zynmidid appear to be at time 0.

This shows that the sustain pedal CC up/off does not seem to be sent. The display shows the control as being cleared so the MIDI feed to the UI seems to work but not the CC to the plugin via jack MIDI.

**Comment by riban-bw** [comment]
MIDI CC go through a lot of Python code (we should probably optimise that!). The fact that the UI indicates the correct value shows that the CC code is being run but the bit that sends the MIDI appears to fail sometimes. That is `zynthian_controller::send_midi_cc`.

Adding debug here shows that `send_midi_cc` is calling `lib_zyncore.zmop_send_ccontrol_change` with the correct parameters so the fault may lie within zynmidirouter.

**Comment by riban-bw** [comment]
Is it possible that the CC message is being added to the jack frame at position zero, but after other events (like note off) have been added? Jack expects messages to be added in order and may drop out-of-order messages.

Addd debug to zynmidirouter and proven that attempt to send CC fails with error code -22.

**Comment by riban-bw** [comment]
Setting the time of messages from the ringbuffer to end-of-frame (`nframes - 1`) fixes this issue but it moves all ring buffer events later. This _may_ be undesirable. The previous flaw was that all messages from UI (including CC) were sent at time=0 which adds similar jitter but the solution to put ringbuffer events all at the end of the frame may include events that are not CC and may result in out-of-order events. I will do some more investigation. This _may_ not be an issue or there may be a way to improve the timing.

**Comment by polluxsynth** [comment]
Having events end up out of order sounds risky on the face of it but I can't say I understand the intricacies of the implementation enough to supply any meaningful criticism.

At any rate, I upgraded my oram installation last night, and oodled about a bit with the sustain pedal and MiMi-d, and I can confirm the problem is no longer present. I didn't notice any other strange behavior such as might occur if events end up out of order either.
