### ISSUE TITLE
Zynthian start up fails: ModuleNotFoundError: No module named 'vcgencmd'

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1068]
zyncoder: oram (a7976d8)
zynthian-ui: oram (b254907)
zynthian-sys: oram (d542728)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (cce8b07)

**Comment by riban-bw** [comment]
Will you provide logs? This should be resolved by [this commit](https://github.com/zynthian/zynthian-ui/commit/199670bf888184f37f3ba0ed04b6d1fe5fa80f13) but maybe it is somewhere else in the code.

**Comment by riban-bw** [comment]
I am on a V4, fully updated. If I open a terminal and start a Python interpreter and enter, `import vcgencmd` I see the error ModuleNotFoundError. If I run Zynthian on the same machine I do not see this error. Are you 100% sure that you are fully up to date with no stale files on that machine?

**Comment by jofemodo** [comment]
This was solved 2 days ago
