### ISSUE TITLE
Lost ability to drag a note into position in pattern editor.

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1069]
# Describe the issue
A previous implementation of pattern editor allowed a note to be dragged into position. When first adding a note you could drag until the right position was found. After adding a note you could drag to move the note. Neither of these features are present in the current implementation. The advantage of these features is that a user could acurately position a note on a small grid or when a touch offset was present, e.g. due to parallex or poor calibration.
# To Reproduce
## Steps to reproduce the behavior:
1. Pattern editor
2. Tap and drag
 ## Expected behaviour
A note is positioned in the final drag position.
## Actual behaviour
Grid is dragged (scrolled).
# Additional context
To retain the ability to scroll the grid, a two finger drag could be used. (This wouldn't work on a single touch screen like V4.) Scrollbars could be added. (These could be small on V4 where a stylus is recommended hence has small touch focus point.)

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 16% (613M/3792M)
SD Card: 86% (24G/29G)
Temperature: 45.7ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (a7976d8) 
zynthian-ui: oram (199670b)
zynthian-sys: oram (d542728)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (c27fea2)
```

**Comment by riban-bw** [comment]
This may be related to issue #1066.

I like both behaviours but do believe a user is disadvantaged by not being able to drag notes to the right position.

**Comment by riban-bw** [comment]
Can we revert to previous behaviour where dragging the keyboard scrolls vertically and dragging on the grid does note placement? We could add 2 finger drag on the grid for vertical & horizontal scrolling. We could add drag on timeline for horizontal scrolling. This gives us single & multitouch scrolling and provides the previous behaviour of note placement.

**Comment by jofemodo** [comment]
I just tested and it works. You simply need to bold-push before start dragging
