### ISSUE TITLE
Log error -  Can't access undervoltage sensor

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1074]
# Describe the issue
On a Raspberry Pi 5 running Oram, during startup Zynthian logs the error:

```
ERROR:zynthian_state_manager.start: Can't access undervoltage sensor.
```
# To Reproduce
## Steps to reproduce the behavior:
1. Start Zynthian
2. Examine journal log
 ## Expected behaviour
No errors.
## Actual behaviour
ERROR:zynthian_state_manager.start: Can't access undervoltage sensor.

# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: Dummy device
Display: Generic HDMI Display
Wiring: DUMMIES
I2C: Not detected
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-05-21
Memory: 8% (703M/8048M)
SD Card: NA (NA/NA)
Temperature: 48.3ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (a7976d8) 
zynthian-ui: oram (4980d55)
zynthian-sys: oram (dcc37e6)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (cce8b07)
```

**Comment by jofemodo** [comment]
I can't reproduce the error in my Pi5.
This is the fragment of code that generates the error:

```
        try:
            self.hwmon_undervolt_file = open('/sys/class/hwmon/hwmon1/in0_lcrit_alarm')
        except:
            try:
                self.hwmon_undervolt_file = open(
                    '/sys/devices/platform/soc/soc:firmware/raspberrypi-hwmon/hwmon/hwmon2/in0_lcrit_alarm')
            except:
                self.hwmon_undervolt_file = None
                logging.error("Can't access undervoltage sensor.")

```

Could you check what is the right path for the undervoltage sensor in your RPI5?

**Comment by riban-bw** [comment]
Under `/sys/class/hwmon/` there are 5 directories: `hwmon0` - `hwmon4`.  `in0_lcrit_alarm` appears at `/sys/class/hwmon/hwmon4/in0_lcrit_alarm`.

It is possible that the hardware monitors are created dynamically and have different paths on each boot or that they have different hardware parameters / configurations that make them appear with a consistent path per device but may differ between devices. It may also be possible that different Raspberry Pi devices have different chips. I read somewhere (but can't find detail now) that CPC manufacture Raspberry Pi under license. I have a RPi5 from CPC so it is plausible there are subtle differences.

It may be worth adding a function to search for `in0_lcrit_alarm` under `/sys/class/hwmon` at startup.
