### ISSUE TITLE
Webconf upload snapshot - .backup is too prominent

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1076]
# Describe the issue
When uploading a snapshot in webconf, the .backup folder is selected by default. This can be have many snapshots in it so the list stretches down the page and it may not be obvious that this is very unlikely to be the location you want to upload / download snapshots. It would be better if the .backup folder was less prominent, e.g. closed and at the bottom of the list.
# To Reproduce
## Steps to reproduce the behavior:
1. Go to webconf, LIBRARY->Snapshots
 ## Expected behaviour
The main bank 000 is shown.
## Actual behaviour
The .backup folder is shown
# Screenshots
![image](https://github.com/zynthian/zynthian-issue-tracking/assets/3158323/08d0f777-7ea7-4729-adea-769b455a6ad5)
# Additional context
The .backup folder is open and at top each time you revisit the page.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 37% (1404M/3792M)
SD Card: 88% (24G/29G)
Temperature: 41.8ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (a7976d8) 
zynthian-ui: oram (b53cbe6)
zynthian-sys: oram (b8541bc)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (b098993)
```

**Comment by jofemodo** [comment]
Currently we are saving the full history of latest state snapshot. Well, indeed we save full history for each snapshot.
We could check if this could be an issue (disk space?) and delete older ones.
By now, i'm going to simply "hide" the list in the webconf, so it's not so intrusive.
