### ISSUE TITLE
Startup log warnings about tuna.lv2 version

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1077]
# Describe the issue
During Zynthian startup, it logs warnings about tuna.lv2 versions. It looks like there may be multiple instances installed and it is figuring out which one to use.
# To Reproduce
## Steps to reproduce the behavior:
1. Start Zynthian
2. Check journal logs
 ## Expected behaviour
No erros or warnings
## Actual behaviour
Warnings logged:
```
lilv_world_load_bundle(): warning: Replacing version 1286.0 of <http://gareus.org/oss/lv2/tuna#one> from <file:///usr/local/lib/lv2/tuna.lv2/>
lilv_world_load_bundle(): note: New version 1546.0 found in <file:///zynthian/zynthian-my-data/presets/lv2/tuna.lv2/>
lilv_world_load_bundle(): warning: Replacing version 1286.0 of <http://gareus.org/oss/lv2/tuna#two> from <file:///usr/local/lib/lv2/tuna.lv2/>
lilv_world_load_bundle(): note: New version 1546.0 found in <file:///zynthian/zynthian-my-data/presets/lv2/tuna.lv2/>
```
# Additional context
It would be good to lose all warnings and errors so that it is clear when we have a real issue.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 13% (496M/3792M)
SD Card: 88% (24G/29G)
Temperature: 44.8ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (a7976d8) 
zynthian-ui: oram (b53cbe6)
zynthian-sys: oram (b8541bc)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (b098993)
```

**Comment by riban-bw** [comment]
There seem to be two instances:

- /zynthian/zynthian-my-data/presets/lv2/tuna.lv2
- /usr/local/lib/lv2/tuna.lv2/

We should probably remove one of these.

**Comment by riban-bw** [comment]
I see that debian package `x42-plugins` provides many plugins including tuna. If we remove the deb package we lose the other plugins.

**Comment by jofemodo** [comment]
This package has been removed in latest image. It's also removed in update patch 20240222.1.
Perhaps something failed in the update process in your image.
I will close because i can't reproduce the issue in fresh images nor updated images.
