### ISSUE TITLE
Audio not routed to output

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#108]
**Describe the bug**
Sometimes, adding a new synth engine results in no audio output. Reasserting the output routing can fix this.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Linux Sampler layer on channel 1 - instrument works fine.
2. Add a second instance of Linux Sampler on channel 2 - no sound from channel 2
3. From layer menu, bold click on layer 2 and toggle audio routing off and on.
4. Sound can now be heard from channel 2.

**Expected behaviour**
When a layer is added it should be routed to the output and work.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: 2019-12-20
Memory: 9% (363M/3906M)
SD Card: 44% (12G/28G)
Temperature: 33.0ºC

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (a000211)
zynthian-sys: master (7ecb396)
zynthian-data: master (3d44cc8)
zynthian-webconf: master (30d3cc4)

**Additional context**
This was from a clean image install using two sample libraries uploaded to Zynthian: 
- Maestro Concert Grand (see Mats Helgesson's page - request not to link)
- http://www.sullivang.net/sample-files (pianet)

**Comment by jofemodo** [comment]
I can't reproduce ...
Can you reconfirm this issue with a updated SD?

**Comment by jofemodo** [comment]
Hi @riban-bw !

Could you re-confirm this issue?

Thanks

**Comment by jofemodo** [comment]
Hi @riban-bw !
I think this is solved by https://github.com/zynthian/zynthian-ui/commit/f2887c9680ec5e6b9d35d954c573cff460ecc4a8
