### ISSUE TITLE
Dead end menu "ZS3 subsnapshot details"

### ISSUE THREAD

**Issue by linuxnow** [zynthian/zynthian-issue-tracking#1080]
**Describe the bug**
The subsnapshot details menu is a dead end. You cannot exit.

**To Reproduce**
1. Bold press  learn
2. Move to any ZS3 subsnapshot
3. Bold press select
4. Select "Restore options..."

**Expected behavior**
Inside the menu you have several actions related to the subsnapshot.
You should be able to execute them and you should be able to press Back and exit.
Nothing works, neither bac, not trying to reboot. It gets stuck here.

[last_state.zip](https://github.com/user-attachments/files/16021302/last_state.zip)

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.2
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-05-21
Memory: 29% (1109M/3792M)
SD Card: 13% (14G/117G)
Temperature: 56.0ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (628f3fb) 
zynthian-ui: oram (371f6df)
zynthian-sys: oram (4461148)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (f31699f)
```

**Comment by jofemodo** [comment]
Dear pau, your issue report is the worst i have received in my life ;-DDD

**Comment by jofemodo** [comment]
I will try top reproduce, but a log report will be really appreciated!

**Comment by jofemodo** [comment]
I can't reproduce. I tried in V4 and V5 but it works for me.
You must be more explicit in the steps and send the logs.

**Comment by riban-bw** [comment]
I too can not reproduce. @linuxnow Please provide more detail, else this ticket will be closed. We to resolve fix all Oram issues before release so please help us to reproduce your issue.

**Comment by linuxnow** [comment]
After selecting Restore options this bug happens and then you cannot use the UI anymore


Jun 18 16:39:51 zynthian2 startx[4261]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 18 16:39:51 zynthian2 startx[4261]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 162, in build_view
Jun 18 16:39:51 zynthian2 startx[4261]: self.fill_list()
Jun 18 16:39:51 zynthian2 startx[4261]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_option.py", line 95, in fill_list
Jun 18 16:39:51 zynthian2 startx[4261]: self.options = self.options_cb()
Jun 18 16:39:51 zynthian2 startx[4261]: ^^^^^^^^^^^^^^^^^
Jun 18 16:39:51 zynthian2 startx[4261]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 110, in zs3_restoring_options_cb
Jun 18 16:39:51 zynthian2 startx[4261]: for chain_id, chain_state in state["chains"].items():
Jun 18 16:39:51 zynthian2 startx[4261]: ~~~~~^^^^^^^^^^
Jun 18 16:39:51 zynthian2 startx[4261]: KeyError: 'chains'

**Comment by riban-bw** [comment]
@linuxnow will you supply a snapshot for when this occurs. Also a screenshot of your webconf dashboard. (It is always best to report tickets using the webconf "Report Issue" button that provides us with more info.)

Also, the log extract you provided is truncated. The first line has "^^^^^^^^^^" which indicate it is referring to an error on the previous line of the log. It is useful to get all the lines in the same time period. We gain a lot of context from the lines surrounding an error.

**Comment by linuxnow** [comment]
I finally got back to my zynthian and here's the full log.

un 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 18 => Quint 5 1/3
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 19 => Quint 2 2/3
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 24 => Flöte 2
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 25 => Cymbel VI
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 26 => Mixtur
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 27 => Trumpet
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 28 => I+II
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 29 => I+III
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 64 => Sustain
Jun 22 01:09:51 zynthian2 startx[929]: WARNING:zynthian_state_manager.load_zs3: Failed to restore MIDI learning 91 => Reverb
Jun 22 01:14:03 zynthian2 startx[929]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: (3, 'S')
Jun 22 01:14:03 zynthian2 startx[929]: Traceback (most recent call last):
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2298, in cuia_thread_task
Jun 22 01:14:03 zynthian2 startx[929]: self.zynswitch_short(i)
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1913, in zynswitch_short
Jun 22 01:14:03 zynthian2 startx[929]: self.screens[self.current_screen].switch_select('S')
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 346, in switch_select
Jun 22 01:14:03 zynthian2 startx[929]: self.click_listbox(None, t)
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 337, in click_listbox
Jun 22 01:14:03 zynthian2 startx[929]: self.select_action(self.index, t)
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 74, in select_action
Jun 22 01:14:03 zynthian2 startx[929]: self.last_action()
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 86, in zs3_restoring_submenu
Jun 22 01:14:03 zynthian2 startx[929]: self.zyngui.show_screen('option')
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 586, in show_screen
Jun 22 01:14:03 zynthian2 startx[929]: if not self.screens[screen].build_view():
Jun 22 01:14:03 zynthian2 startx[929]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 162, in build_view 
Jun 22 01:14:03 zynthian2 startx[929]: self.fill_list()
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_option.py", line 95, in fill_list
Jun 22 01:14:03 zynthian2 startx[929]: self.options = self.options_cb()
Jun 22 01:14:03 zynthian2 startx[929]: ^^^^^^^^^^^^^^^^^
Jun 22 01:14:03 zynthian2 startx[929]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 110, in zs3_restoring_options_cb
Jun 22 01:14:03 zynthian2 startx[929]: for chain_id, chain_state in state["chains"].items():
Jun 22 01:14:03 zynthian2 startx[929]: ~~~~~^^^^^^^^^^
Jun 22 01:14:03 zynthian2 startx[929]: KeyError: 'chains'

**Comment by riban-bw** [comment]
@linuxnow will you supply a snapshot for when this occurs. Also a screenshot of your webconf dashboard. (It is always best to report tickets using the webconf "Report Issue" button that provides us with more info.)

**Comment by linuxnow** [comment]
I have reported the issue directly from webconf. Still happens.

[Edit by @riban to merge tickets]

# UI log
```
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Sound Speed
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Wall distance
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Lid
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Damper Position
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Last Damper
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Damping Duration
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Reverb Envelope
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Reverb Resampling
Jun 27 21:34:56 zynthian2 startx[3066]: WARNING:zynthian_chain_manager.midi_control_change: Can't manage control feedback for CH2:CC11 => 396032
Jun 27 21:34:56 zynthian2 startx[3066]: WARNING:zynthian_chain_manager.midi_control_change: Can't manage control feedback for CH2:CC7 => 395008
Jun 27 21:59:41 zynthian2 startx[3066]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: (3, 'S')
Jun 27 21:59:41 zynthian2 startx[3066]: Traceback (most recent call last):
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2310, in cuia_thread_task
Jun 27 21:59:41 zynthian2 startx[3066]: self.zynswitch_short(i)
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1925, in zynswitch_short
Jun 27 21:59:41 zynthian2 startx[3066]: self.screens[self.current_screen].switch_select('S')
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 346, in switch_select
Jun 27 21:59:41 zynthian2 startx[3066]: self.click_listbox(None, t)
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 337, in click_listbox
Jun 27 21:59:41 zynthian2 startx[3066]: self.select_action(self.index, t)
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 74, in select_action
Jun 27 21:59:41 zynthian2 startx[3066]: self.last_action()
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 86, in zs3_restoring_submenu
Jun 27 21:59:41 zynthian2 startx[3066]: self.zyngui.show_screen('option')
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 586, in show_screen
Jun 27 21:59:41 zynthian2 startx[3066]: if not self.screens[screen].build_view():
Jun 27 21:59:41 zynthian2 startx[3066]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 162, in build_view
Jun 27 21:59:41 zynthian2 startx[3066]: self.fill_list()
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_option.py", line 95, in fill_list
Jun 27 21:59:41 zynthian2 startx[3066]: self.options = self.options_cb()
Jun 27 21:59:41 zynthian2 startx[3066]: ^^^^^^^^^^^^^^^^^
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 110, in zs3_restoring_options_cb
Jun 27 21:59:41 zynthian2 startx[3066]: for chain_id, chain_state in state["chains"].items():
Jun 27 21:59:41 zynthian2 startx[3066]: ~~~~~^^^^^^^^^^
Jun 27 21:59:41 zynthian2 startx[3066]: KeyError: 'chains' 
```

**Comment by riban-bw** [comment]
I have reproduced this with the attached snapshot. I added a step to the "To Reproduce" steps. You have to select "Restore options..." to triger the issue.

Now that we have a reprducible workflow, we can debug and resolve. Thanks.

**Comment by riban-bw** [comment]
There is an option to restore the individual chain configurations. Because this snapshot does not have any chain specific configuration, an error occurs. I am testing a fix now...

**Comment by riban-bw** [comment]
@linuxnow how did you create this snapshot? It has many ZS3, some of which do not have high-level chain info but I don't know how to create such a snapshot / ZS3. Was this converted from an older version snapshot?

**Comment by linuxnow** [comment]
I created a snapshot from scratch because importing old ones didn't work for me before fixing the import procedure.
I'm 95% sure, so don't take it for granted, I might be wrong.
