### ISSUE TITLE
Engine/bank/prest header not updated when manually selecting a subsnapshot

### ISSUE THREAD

**Issue by linuxnow** [zynthian/zynthian-issue-tracking#1081]
**Describe the bug**
When you manually select a subsnapshot, the fitst line of the screen that describes the engine and preset is not updated with the loaded ZS3.

**To Reproduce**
1. Bold press Learn
2. Select a subsnapshot
3. Press select

**Expected behavior**
On the top of the screen of the select chain you should see the engine name/bank/preset, but this line is not updated.

**Setup:**
Latest oram

**Comment by riban-bw** [comment]
This is by design.

The topbar shows the loaded snapshot. Changes to ZS3 within that snapshot do not change the loaded snapshot and hence the title does not change.
