### ISSUE TITLE
Audio signal in main chain does not work correctly for pre-fader effects

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#1082]
# Describe the issue
Audio FX in main output chain set parallel to incoming signal, not serial.
# To Reproduce
## Steps to reproduce the behavior:
1. add a gain fx into main audio chain and reduce gain to -40db
2. Send any signal to main output
 ## Expected behaviour
Reduction of volume to nearly -40 db
## Actual behaviour
Unaffected audio signal is passing

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.2
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 22% (853M/3792M)
SD Card: 24% (14G/58G)
Temperature: 55.0ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 0 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (e0014fe) 
zynthian-ui: oram (cebdeae)
zynthian-sys: oram (bdd16d8)
zynthian-data: oram (9958411)
zynthian-webconf: oram (2dba270)
```

**Comment by riban-bw** [comment]
What is the source of your audio? Any other chains, e.g. synths will pass through the main chain's effects.

It looks like there could be an issue with some source modules, e.g. audio player.

Please provide more detail of the configuration where this issue occurs. Provide a snapshot and describe how you are creating the audio signal that is not being properly processed.

**Comment by gitnob** [comment]
I have to be more precise. After update to actual oram..

Adding a gain FX to prefade position and reduce this FX to -40db. I can still hear the sounds from the single chains. Tried with signal from audio chain, from puredata, from calf monosynth.

But with the effect in post fader location everything works fine.

I edited the main issue description text a little bit.
I'll send snapshot later.

**Comment by gitnob** [comment]
Here is a snapshot, that is not working correctly on my freshly updated oram V4 zynth.
[013-bypass main chain prefader fx.zss.zip](https://github.com/user-attachments/files/15839536/013-bypass.main.chain.prefader.fx.zss.zip)
calf monosynth is controlled by midi channel 2

**Comment by riban-bw** [comment]
That snapshot looks like an old format and I cannot open it. Will you please validate it is a proper snapshot saved from Oram?

**Comment by gitnob** [comment]
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [HifiBerry DAC+ ADC PRO](http://zynthianoram.fritz.box/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthianoram.fritz.box/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthianoram.fritz.box/hw-wiring)
I2C: [MCP23017@0x20](http://zynthianoram.fritz.box/hw-wiring)
Profile: [v4_stage](http://zynthianoram.fritz.box/hw-wiring)

zyncoder: oram (e0014fe)
zynthian-ui: [oram (453726c)](https://github.com/zynthian/zynthian-ui/commit/453726cd58a74b59e34f3deb7b981b8b6d2e5c00)
zynthian-sys: [oram (8602194)](https://github.com/zynthian/zynthian-sys/commit/86021940f8af896213e50ca9ca16d64080a7a874)
zynthian-data: [oram (e222e11)](https://github.com/zynthian/zynthian-data/commit/e222e116a1967e38075a96e2bf25aa051f796d30)
zynthian-webconf: [oram (2dba270)](https://github.com/zynthian/zynthian-webconf/commit/2dba270ccbe2497d27a2f491dd910756034c3f5a)

It's absolutely freshly updated. The heart is green!
Downloaded it via webconf, zipped it and uploaded it!

**Comment by gitnob** [comment]
I attached the complete signal flow in the pdf file, I've deleted the custom lv2 plugin from the snapshot I sent you before. 

The actual snapshot which shows the issue on my freshly updated oram V4 system:
[013-bypass main chain prefader fx.zss.zip](https://github.com/user-attachments/files/15845857/013-bypass.main.chain.prefader.fx.zss.zip)

Issue: "gain-01"  (pre-fader plugin) is not silencing the audio from the outputs of the single chains on the system output. "gain02-" (post-fader plugin) does this.
It seems as if zynmixer is bypassing signal directly to the main mixer output.
My suggestion: some coding error in zynmixer.

Regards

[pre-fader-issue-02.pdf](https://github.com/user-attachments/files/15845855/pre-fader-issue-02.pdf)

**Comment by riban-bw** [comment]
Okay - after some discussion in the forum we have identified the issue.

- Chain 1: Special chain with MDA TestTone. Disconnect audio out from main mix. Connect audio out to Chain 2.
- Chain 2: Empty audio chain, routed to main mix (as per default output routing).
- Add 2 instances of Gain 2x2 to Main Mixbus, pre-fader, in series
- Observe tone is present on both outputs
- Within patchage, manually disconnect one audio signal between the two Gain 2x2 plugins.
- Expect no audio on main output for that channel but actually it falls in level

So this proves that the internal normalisation is not being disconnected when a chain is routed to another chain.

The attached snapshot represents the simple test case.
[014-Issue #1082.zip](https://github.com/user-attachments/files/15846144/014-Issue.1082.zip)

**Comment by riban-bw** [comment]
Line 748 in zynthian_autoconnect.py: `state_manager.zynmixer.normalise(chain_manager.chains[chain_id].mixer_chan, 0 in chain_manager.chains[chain_id].audio_out)` is the only attempt to handle audio mixer internal normalisation. This is oversimplistic. It enables normalisation if the chain is routed to main mixbus but it should disable if that chain has post-fader effects or the main-mixbus has pre-fader effects.
