### ISSUE TITLE
Midi control of audio FX in main chain not possible with external controller in multitimbral mode

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#1083]
# Describe the issue
Audio FX in main chain seem not to get external midi CCs if device is in mutlitimral mode, allthough learning was possible.
# To Reproduce
## Steps to reproduce the behavior:
1. Use an external midi controller in multitimbral mode or a Zynthian Knob with Midi CC sending of value
2. put for example calf vintage delay into the FX of main chain.
3. push learn knob on zynthian
4. Turn knob for the "Active" function of vintage delay.
 (midi CC is learned)
5. change external controller for this CC
 ## Expected behaviour
External controller controls this parameter of vintage delay
## Actual behaviour
Learning is possible, but using does not work.
# Additional context
Learning and using in a regular audio chain with audio fx does work.
If I use a zynthian V4's switch with Midi CC Switch function, it doesn't work neither for the main chain CC control.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.2
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 22% (853M/3792M)
SD Card: 24% (14G/58G)
Temperature: 55.0ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 0 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (e0014fe) 
zynthian-ui: oram (cebdeae)
zynthian-sys: oram (bdd16d8)
zynthian-data: oram (9958411)
zynthian-webconf: oram (2dba270)
```

**Comment by riban-bw** [comment]
I cannot reproduce this.

- Add "Gain" plugin to main chain (pre-fader)
- Press "learn" to enter MIDI learn mode
- Adjust physical encoder to target the learn at the "Gain" parameter
- Send MIDI CC 60, value 100
  - The control indicates it has learned MIDI CC 60 - '60' is displayed below control
- Send MIDI CC 60
  - The Gain control moves in sympathy with the CC messages

**Comment by gitnob** [comment]
@riban-bw , I tried it again and discovered, that it is dependant whether the midi inpüut device is set to multitimbral or not in the admin's Midi Input Device settings.

I can control the gain, if the external controller is NOT in multitimbral mode, but cannot control if the external midi controller is in multitimbral mode.

Please try it again with the external midi input set to multitimbral.

Also try to switch any function in the main chain's FX line with a zynthian buttons (switch 1-4 for V4). 
Same issue:
set switch 2 i.e. to MIDI CC SWITCH on CC100, learn a on/off control in the FX, and try to use it. It does learn, but it does not react.

**Comment by gitnob** [comment]
OK, no issue anymore. I didn't realize that there is the chain and global midi learning.
If I use the latter, it works as expected. I was not aware of these two different options.
