### ISSUE TITLE
V3 with RPi3 failed to complete update

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1085]
# Describe the issue
A software update was started from the UI admin menu but after some time, the machine locked up and never recovered.
# To Reproduce
## Steps to reproduce the behavior:
1. Start update from UI admin menu
 ## Expected behaviour
Update completes.
## Actual behaviour
Update did not complete. Screen showed last action was "Regenerating engines DB: engines ...".
# Screenshots
![image](https://github.com/zynthian/zynthian-issue-tracking/assets/3158323/c8872834-c554-4237-a116-745278c72565)
# Additional context
I could ping the machine but ssh and webconf would not connect and the UI was frozen. I had to remove the power to recover. I then run update from webconf during which I monitored resources using htop. 1 core ran at 100% whilst others sta around 60%. Memory crept up towards 80%. The process completed this time with log entries:
```
Regenerating engines DB: engines ...
INFO:root:Command took 47s
```

I had NoizMaker and ObXd chains loaded which may have contributed to resource load, e.g. RAM usage.

# Configuration
## Hardware
```
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: ZynADAC
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_studio
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 46% (422M/907M)
SD Card: 97% (26G/29G)
Temperature: 52.6ºC
Overclock: Medium
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (e0014fe) 
zynthian-ui: oram (453726c)
zynthian-sys: oram (7c452c8)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (2dba270)
```

**Comment by riban-bw** [comment]
I wonder if this was a resource issue? Maybe RAM was exhausted? We could offload the update (and maybe other operations) to a seperate service that can be spun up on demand and not be part of main UI process. Such a mechanism may allow better monitoring and control of process / module resource usage.

**Comment by le51** [comment]
I had that issue too, but so far, since latest Oram build, all software went smoothly on my Pi3

**Comment by jofemodo** [comment]
Perhaps a resources issue. I will close . Please open if it happens again!
