### ISSUE TITLE
Issue: dead end menu in ZS3 details

### ISSUE THREAD

**Issue by linuxnow** [zynthian/zynthian-issue-tracking#1099]
# Describe the issue

Same bug already reported but using "Report issue".

# UI log
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Sound Speed
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Wall distance
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Lid
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Damper Position
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Last Damper
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Damping Duration
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Reverb Envelope
Jun 27 21:34:38 zynthian2 startx[3066]: WARNING:zynthian_engine_pianoteq.get_params: Unknown parameter Reverb Resampling
Jun 27 21:34:56 zynthian2 startx[3066]: WARNING:zynthian_chain_manager.midi_control_change: Can't manage control feedback for CH2:CC11 => 396032
Jun 27 21:34:56 zynthian2 startx[3066]: WARNING:zynthian_chain_manager.midi_control_change: Can't manage control feedback for CH2:CC7 => 395008
Jun 27 21:59:41 zynthian2 startx[3066]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: (3, 'S')
Jun 27 21:59:41 zynthian2 startx[3066]: Traceback (most recent call last):
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2310, in cuia_thread_task
Jun 27 21:59:41 zynthian2 startx[3066]: self.zynswitch_short(i)
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1925, in zynswitch_short
Jun 27 21:59:41 zynthian2 startx[3066]: self.screens[self.current_screen].switch_select('S')
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 346, in switch_select
Jun 27 21:59:41 zynthian2 startx[3066]: self.click_listbox(None, t)
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 337, in click_listbox
Jun 27 21:59:41 zynthian2 startx[3066]: self.select_action(self.index, t)
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 74, in select_action
Jun 27 21:59:41 zynthian2 startx[3066]: self.last_action()
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 86, in zs3_restoring_submenu
Jun 27 21:59:41 zynthian2 startx[3066]: self.zyngui.show_screen('option')
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 586, in show_screen
Jun 27 21:59:41 zynthian2 startx[3066]: if not self.screens[screen].build_view():
Jun 27 21:59:41 zynthian2 startx[3066]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 162, in build_view
Jun 27 21:59:41 zynthian2 startx[3066]: self.fill_list()
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_option.py", line 95, in fill_list
Jun 27 21:59:41 zynthian2 startx[3066]: self.options = self.options_cb()
Jun 27 21:59:41 zynthian2 startx[3066]: ^^^^^^^^^^^^^^^^^
Jun 27 21:59:41 zynthian2 startx[3066]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zs3_options.py", line 110, in zs3_restoring_options_cb
Jun 27 21:59:41 zynthian2 startx[3066]: for chain_id, chain_state in state["chains"].items():
Jun 27 21:59:41 zynthian2 startx[3066]: ~~~~~^^^^^^^^^^
Jun 27 21:59:41 zynthian2 startx[3066]: KeyError: 'chains' 

[last_state.zip](https://github.com/user-attachments/files/16021302/last_state.zip)

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.2
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-05-21
Memory: 29% (1109M/3792M)
SD Card: 13% (14G/117G)
Temperature: 56.0ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (628f3fb) 
zynthian-ui: oram (371f6df)
zynthian-sys: oram (4461148)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (f31699f)
```

**Comment by riban-bw** [comment]
I have merged with ticket #1080.
