### ISSUE TITLE
MIDI input not working in Aruk RC2

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#11]
**Describe the bug**
A fresh install of Aruk RC2 would not trigger any MIDI.

**To Reproduce**
1. Download, unzip and flash https://os.zynthian.org/2019-05-23-zynthianos-stretch-lite-1.0.0-RC2.zip
2. Connect USB and MIDI keyboards.
3. Boot RC2 image - allow reboot.
4. Add Fluidsynth layer on MIDI channel 1 loading GM soundfont
5. Play USB and MIDI keyboards.
6. Remove and reconnect USB MIDI keyboard
7. Use MIDI Recorder to play a midi file
**Expected behaviour**
Audio output.
**Actual behaviour**
No audio output. No indication of MIDI.

Applying updates and rebooting fixed the issue.

**Comment by jofemodo** [comment]
But, if applying updates solved the problem, the issue is solved, true? ;-)

**Comment by riban-bw** [comment]
I guess so. I wasn't sure the updated actually fixed the problem and wanted to make sure you were aware of an issue and that it was definitely fixed in an update. Let's close this.
