### ISSUE TITLE
Dexed does not support panic

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#110]
**Describe the bug**
Zynthian can send all notes off (and other panic type signals) but Dexed does not react correctly to these so hung notes are not cleared.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Dexed layer
2. Play and hold a note
3. Send ALL NOTES OFF
4. Note continues to sound

**Expected behaviour**
Currently sounding notes should clear when ALL NOTES OFF message is sent / received.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: 2019-12-20
Memory: 9% (371M/3906M)
SD Card: 44% (12G/28G)
Temperature: 32.0ºC

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (a000211)
zynthian-sys: master (7ecb396)
zynthian-data: master (3d44cc8)
zynthian-webconf: master (30d3cc4)

**Comment by jofemodo** [comment]
Could you confirm that ALL_SOUNDS_OFF also fail?
It should work ...

**Comment by jofemodo** [comment]
Eoooo! Please, i would need an answer about my last question ... ;-)

**Comment by riban-bw** [comment]
ALL_SOUND_OFF succeeds.

**Comment by jofemodo** [comment]
OK! Then this is not a zynthian-specific problem, but a dexed problem.
Perhaps @dcoredump would like to solve it if you open an issue in the dexed repo ...

**Comment by dcoredump** [comment]
I will take a look at this, but currently I am AFK for 5-6 weeks.

Am 15. Januar 2020 16:18:39 MEZ schrieb "Jośe Fernando Moyano" <notifications@github.com>:
>OK! Then this is not a zynthian-specific problem, but a dexed problem.
>Perhaps @dcoredump would like to solve it if you open an issue in the
>dexed repo ...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/zynthian/zynthian-issue-tracking/issues/110#issuecomment-574707102

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
