### ISSUE TITLE
Issue: Touchscreen issue in Arranger view

### ISSUE THREAD

**Issue by le51** [zynthian/zynthian-issue-tracking#1109]
# Describe the issue
Touchscreen doesn't respond as advertised in doc
# To Reproduce
## Steps to reproduce the behavior:
1. A touch display is needed
2. Go in Arranger view.
3. Click on the pattern number located bottom left
4. Nothing happens
 ## Expected behaviour
As in StepSeq user guide, a pattern selection pop up box with buttons should appear
## Actual behaviour
No effect
# Additional context
Same thing on another setup with a 7inch HDMI+USB touch display.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.2
Audio: Behringer UMC404HD
Display: MIPI DSI 800x480 (inverted)
Wiring: DUMMIES
I2C: Not detected
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 29% (1125M/3792M)
SD Card: 49% (14G/29G)
Temperature: 52.5ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (628f3fb) 
zynthian-ui: oram (564a889)
zynthian-sys: oram (4461148)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (f31699f)
```

**Comment by riban-bw** [comment]
This was due to Arranger not being updated when parameter editor was changed. I have also removed the constraint that this only occurs when touch widgets are enabled. It now works in all modes. Wiki has been updated.

**Comment by le51** [comment]
Ok, it works as advertised. Great thank you.
