### ISSUE TITLE
VNC connection touchscreen tablet unresponsive to back. Mixer page cannot be accessed

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1116]
**Describe the bug**
Upon attempting to operate a remote zynthian accessed via zynthian based hotspot was un-responsive to attempts to operate back button from the touchscreen. So the mixer display could not be accessed. OTher menu commands worked and the touchscreen could access other interface functions.
Worked from USB connected mouse. 

Can't access device ( it's elsewhere) to get version but it's current today ( 11/7/2024)

![Photo from +44 7748 966809](https://github.com/zynthian/zynthian-issue-tracking/assets/79083/099448cf-c582-49a9-b3c1-ac1eff5a1c69)

**Comment by riban-bw** [comment]
I have fully tested touch UI via VNC in Oram with touch navigation enabled and it all works. There is an issue with tablets that interpret prolonged touch as a gesture which interferes with zynthian's bold/long press detection. There is little we can do about that so (Android) tablets are a poor UI for zynthian.

I am closing this issue. Feel free to reopen with more info if necessary.
