### ISSUE TITLE
Bug : ORAM - Sooperlooper

### ISSUE THREAD

**Issue by shieman** [zynthian/zynthian-issue-tracking#1119]
Hi

I am testing SooperLooper, i ,found that these functions do not work (i verifyed with opened sooperlooper native gui) :

Mute_quant, Overdub_quant, Replace_quant,
Enable_sync, Playback_sync, Relative_sync,
Round.

My system is up to date and that’s not a sooperlooper bug, but an osc communication broken link between zynthian and sooperlooper.

Thanks

**Comment by riban-bw** [comment]
Fixed:
- mute_quant
- overdub_quant
- replace_quant

These parameters were not broken:
- enable_sync
- playback_sync
- relative_sync
- round
