### ISSUE TITLE
Issue: routing MIDI between chains (e.g. midi-chain -> instrument-chain) doesn't work

### ISSUE THREAD

**Issue by johanekamp** [zynthian/zynthian-issue-tracking#1120]
# Describe the issue
I wanted to create a midi-chain from which I can route midi notes to (several) other chains. That wasn't possible as also described here in the [discourse](https://discourse.zynthian.org/t/new-testing-image-bookworm-oram-64bits/9222/348?u=jojo_action)
# To Reproduce
## Steps to reproduce the behavior:
* create instrument-chain
* create a midi-chain
* navigate midi-chain > chain-options > midi out
* here now try to select that instrument-chain
* I cannot make that connection, the checkbox stays unchecked and in UI-Log I get the following message:
`Jul 22 17:57:41 zynthian startx[908]: ERROR:zynthian_gui_midi_config.select_action: 'NoneType' object has no attribute 'aliases'`
 ## Expected behaviour
It should be possible to route midi from any chain to any chain like described in the [wiki](https://wiki.zynthian.org/index.php/Oram_TESTING_Zynthian_UI_Users_Guide) under number 6.1
## Actual behaviour
No connection were made.
Checkbox stays unchecked 
Error in UI Log (see above)
# Screenshots
-none-
# Additional context
-none-
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: ZynADAC
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_studio
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-06-26
Memory: 8% (695M/7810M)
SD Card: 24% (13G/59G)
Temperature: 43.3ºC
Overclock: Medium
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (48972ce) 
zynthian-ui: oram (4e060e8)
zynthian-sys: oram (5affa51)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (f31699f)
```

**Comment by riban-bw** [comment]
Routing of audio between chains works. It simply adds the chain to the list of destinations then autoconnect checks this.

MIDI routing performed directly within zynmidirouter, i.e. it is handled differently to audio chain routing. The code in zynthian_gui_midi_config at line 300 gets the second value from the list which, for a chain is None, and attempts to set the MIDI route for an zmop.

There needs to be quite a bit of work to make this work. We need to pick up the output of the chain (last MIDI effect or zmop if no effects in chain) and route it to the input of the destination chain (first MIDI effect, synth input or MIDI outputs if no effects in chain, e.g. empty MIDI chain). There is a lot of logic to add which could be quite intrusive.

The first question is why? What are the workflows that require routing one MIDI chain to another MIDI chain?

For now I think we should disable the ability to route MIDI chains to other chains whilst we consider if there is a benefit.

**Comment by riban-bw** [comment]
I have pushed a temporary fix to not show chains in the list of destinations for a MIDI chain.

**Comment by jofemodo** [comment]
I fixed the issue and now it works again as expected:

https://github.com/zynthian/zynthian-ui/commit/ed1758f6af38f8ac40e98ad1dc032505f4c56ddd

Thanks!
