### ISSUE TITLE
Display of help text in GUI on Engines & Effects

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#113]
**Is your feature request related to a problem? Please describe.**
There is some confusion over Aelous tuning, which is not equal tempered. Other engines have other 'charctristics'

**Describe the solution you'd like**
When an engine or effect is selected in the Add Layer menus, display help text in the central display area

**Describe alternatives you've considered**
A copiously updated User Manual :-D

**Additional context**
Would best be heavily restricted with little other than a certain number ( smallest display limits and no need to scroll) of characters.

**Comment by riban-bw** [comment]
A brief description of each plugin as well as its complexity and user rating is now shown in the processor selection screen. The descriptions still need to be populated but I will close this issue because the functionality is implemented.
