### ISSUE TITLE
Remove function of LAYER button changing chain selection

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1131]
**Is your feature request related to a problem? Please describe.**
The original workflow for Zynthian used the LAYER switch to move selection of the current layer (now called chain). This allowed selection to be changed for Stage mode (now called Active mode). It was only a forward nudge with wrap-around so provided some useful feature although suboptimal.

Since we moved to the Mixer view centric model, it has become far easier to select chains, using the SELECT encoder or left/right buttons in Mixer view. You can also use left/right buttons in control view. This gives a much improved workflow, with user able to move freely through the chains.

My request is to consider whether the use of the LAYER button continues to make sense? There is a more comfortable and versatile way of selecting chain now, using the Mixer view. It continues to confuse me when the chain changes after a press of the LAYER button, even after many years of usage.

A V4 (or earlier) does not have left / right buttons so still relies on the LAYER button to step forwards through chains when in the Control view. How many users depend on this feature? If it remains desirable to change chain from the Control view, would another mechanism that allows free selection be more useful, e.g. press LAYER then rotate LAYER?

**Describe the solution you'd like**
Remove function to change chain when LAYER encoder is short pressed.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
This function has triggered some unexpected behaviour, e.g. if a chain is emtpy. That should be resolved seperately.

**Comment by riban-bw** [comment]
I don't think it is worth implementing a selector on the LAYER encoder rotation. It is simple to bold press BACK and use the SELECT encoder. This is very intuitive and by far my preferred way to select chains. I rarely use the LAYER button.

If we consider this change, we should gather opinion from the community of users.

**Comment by jofemodo** [comment]
Bold click + rotate to change instrument? And you need to look at the screen?
I'm not going to buy this. Some users are going to dislike this. When having 2-4 chains current workflow is perfectly OK.
Perhaps with a greater number of chains it's not so nice, but then you can use the bold-layer + rotate.
I wouldn't change this behavior unless you propose a better action for short-layer in control screen ;-)

**Comment by riban-bw** [comment]
Bold click + rotate is no different to bold BACK + rotate SELECT really and the latter offers visual feedback.

Now that some of the issues with this have been resolved (particularly the issue with empty chains) it is less impactful. I hear what you say about some users finding it useful with few chains so I will close this request as rejected.
