### ISSUE TITLE
VNC opens from the webconf button with the password preloaded.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1143]
**Is your feature request related to a problem? Please describe.**
The VNC display from the webconf challenges for a password to operate this requires an physical interaction on the part of the user to access a facility that may be used as a purely read only resource. 
If this were to open directly without the need for the password. iT is likely that the user will use this facility more, widening the flexibility of their access to zynthian. 

From a security perspective, the password is already required to gain access to the webconf.

I know at present it can be preloaded to a browser and this is certainly useful but it does require the password is displayed in plain sight.

**Comment by riban-bw** [comment]
I guess you want a method of opening VNC without password but not using the current method that encodes the plain-text password in the URL.

Maybe there could be some config in the web based VNC to allow/ authorise connections automatically but I'm not sure how.

I use a shortcut and go full screen if I want to hide the URL

**Comment by wyleu** [comment]
No I don't mind calling the url command line with the visible password. In some situations I can actually think where that would be beneficial. 

It really only needs the seeding of the VNC options in the webconf with vnc.html?autoconnect=true&password=opensynth

I suspect that more people would use the VNC facilities if they didn't have to type in a password to activate the display. Particularly within read only scenarios. It also means the GUI can be driven by a mouse without the use of a keyboard....  

Even thou' I've just found an old one of mine that is probably going to get some serious use around the cajon.

**Comment by riban-bw** [comment]
I agree that is would be advantageous to allow single click access to VNC from webconf but I worry that there are users who will be concerned if the password is shown in plain text.

**Comment by wyleu** [comment]
IF the password is opensynth then auto complete, if it's changed confront the user....

Leaking opensynth is no problem because its already in public domain.

**Comment by jofemodo** [comment]
It can't be done easily, sorry. We should modify the VNC client, that we don't control and we don't want to fork. They maintainers  would never accept a patch like this.
