### ISSUE TITLE
500 Error on accessing lib snapshot

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1144]
**Describe the bug**
I attempted to uplaod the attached .zss file. it didn't complete and since then lib snapshot produces a 500 error

Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]: ERROR:web.log_exception: Uncaught exception GET /lib-snapshot (192.168.0.120)
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]: HTTPServerRequest(protocol='http', host='zynthian-rack6.local', method='GET', uri='/lib-snapshot', version='HTTP/1.1', remote_ip='192.168.0.120')
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]: Traceback (most recent call last):
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:     result = method(*self.path_args, **self.path_kwargs)
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 3301, in wrapper
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:     return method(self, *args, **kwargs)
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:   File "/zynthian/zynthian-webconf/lib/snapshot_config_handler.py", line 54, in get
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:     ssdata = self.get_snapshots_data()
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:              ^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:   File "/zynthian/zynthian-webconf/lib/snapshot_config_handler.py", line 229, in get_snapshots_data
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:     return self.walk_directory(SnapshotConfigHandler.SNAPSHOTS_DIRECTORY)
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:   File "/zynthian/zynthian-webconf/lib/snapshot_config_handler.py", line 297, in walk_directory
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:     snapshot['nodes'] = self.walk_directory(fullpath, idx, bank_num, bank_name)
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:   File "/zynthian/zynthian-webconf/lib/snapshot_config_handler.py", line 292, in walk_directory
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:     'prog_details': prog_details
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]:                     ^^^^^^^^^^^^
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]: UnboundLocalError: cannot access local variable 'prog_details' where it is not associated with a value
Aug 14 15:14:49 zynthian-rack6 zynthian_webconf.sh[730]: ERROR:web.log_request: 500 GET /lib-snapshot (192.168.0.120) 38.92ms

**To Reproduce**
1. Go to 'Snaphot lib'
2. Click on 'Upload'
3. Upload https://discourse.zynthian.org/t/vocoder/6863/3?u=wyleu

**Expected behavior**
I Should be able to upload this .zss file.

zyncoder: oram (62626a8)
zynthian-ui: oram (25998d6)
zynthian-sys: oram (5affa51)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (0327ac4)

**Comment by riban-bw** [comment]
The bug occurs in zynthian_legacy_snapshot.py line 479 where `zs3["mixer"] is expected to be a dictionary but is actually a list.

I have assigned Oram milestone because this breaks backwards compatibility (legacy snapshot support).
