### ISSUE TITLE
ZynSampler fails to load waveform with mono files

### ISSUE THREAD

**Issue by oscaracena** [zynthian/zynthian-issue-tracking#1145]
On ZynSampler, when the loaded file is mono, `soundfile.read()` returns a one-dimensional array, and this will cause a problem generating the waveform. This line produces an `IndexError`:

```python
# zyngui/zynthian_widget_audioplayer.py:491
av = a[frame][channel] * self.v_zoom
```

There is an easy fix; according to the [soundfile docs](https://python-soundfile.readthedocs.io/en/0.11.0/#soundfile.read), just passing the argument `always_2d=True` to the `read()` method will fix the problem.

**Comment by riban-bw** [comment]
I confirm this is an issue and am surprised and embarrased in equal measures because I fixed this once! I will take a look now. It has been flagged to be fixed before Oram release because it is a breaking feature.

**Comment by riban-bw** [comment]
Thanks @oscaracena. I have implemented your suggestion and whilst in there, fixed a couple of other waveform display issues, particularly improving message shown when no audio is available in the file. (I wonder if we should open such files but that is a different topic.)

**Comment by oscaracena** [comment]
My pleasure! Thank you to you for fixing it so quick! 🙂👍
