### ISSUE TITLE
Swapping between snapshots Drone and DronX7 gives errors.

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1147]
# Describe the issue
When swapping between two snapshots Drone and DronX7, there are errors in the log that suggest some routing attempt is being made on the old snapshot.
# To Reproduce
## Steps to reproduce the behavior:
1. Load snapshot [007-DronX7.zip](https://github.com/user-attachments/files/16641974/007-DronX7.zip)
2. Load snapshot [008-Drone.zip](https://github.com/user-attachments/files/16642292/008-Drone.zip)
 ## Expected behaviour
Snapshots load without error.
## Actual behaviour
Snapshots load with errors in log.
# Additional context
Loading Drone gives errors:
```
Aug 16 23:21:56 zynthian-v5-64 startx[5341]: WARNING:zynthian_legacy_snapshot.convert_state: No audio routing info for processor Shiroverb-00 in chain 0!
Aug 16 23:21:56 zynthian-v5-64 startx[5341]: WARNING:zynthian_legacy_snapshot.convert_state: No audio routing info for processor Shiroverb-00 in chain 0!
Aug 16 23:22:23 zynthian-v5-64 startx[5341]: ERROR:zynthian_state_manager.load_zs3: Failed to restore processor 9 state => 9
```

Shiroverb is not even in snapshot Drone! This error occurs right at the start of snapshot loading.
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 51% (1964M/3792M)
SD Card: 95% (26G/29G)
Temperature: 76.9ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (62626a8) 
zynthian-ui: oram (8844634)
zynthian-sys: oram (5affa51)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (0327ac4)
```

**Comment by jofemodo** [comment]
Fixed by updating the Drone snapshot.
