### ISSUE TITLE
ZamGrains CPU high (with GUI)

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1148]
# Describe the issue
When ZamGrains plugin is running with VNC enabled it consumes 50% CPU on all 4 cores.
# To Reproduce
## Steps to reproduce the behavior:
1. Add ZamGrains to a chain.
## Expected behaviour
Consumes little CPU.
## Actual behaviour
Consumes much CPU.
# Additional context
The non-gui jalv instance consumes very low CPU.
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 48% (1834M/3792M)
SD Card: 95% (26G/29G)
Temperature: 57.4ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (62626a8) 
zynthian-ui: oram (8844634)
zynthian-sys: oram (5affa51)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (0327ac4)
```

**Comment by jofemodo** [comment]
As ZamGrains is not enabled by default and i don't think it has a review. We could warn about this in the description. And we could do this with other plugins. Indeed i already did with some of the reviewed ones ;-)

**Comment by jofemodo** [comment]
OK! I added this:

"High CPU consumption when native GUI (VNC) is enabled."
