### ISSUE TITLE
USB Audio in's are Mono'd in capture.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#115]
**Describe the bug**
The selection of a USB input device defaults to a Mono mix of Left & Right input channels

**To Reproduce**
Select USB device
Play stereo sound into device
Only channel one responds to a mono mix of the input.

**Expected behavior**
I would expect Stereo devices to appear as stereo within the zynautoconnect

**Screenshots**
https://discourse.zynthian.org/t/audio-setup/2647/28

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
![image](https://user-images.githubusercontent.com/79083/71783417-67445c80-2fde-11ea-96aa-86ef176b796c.png)

**Additional context**
I'm hoping to use a stereo USB mic (Blue Yeti) to record church bells in stereo using a zynth built into the bell tower above the bell frame (2 metres up :-D ).

**Comment by jofemodo** [comment]
Is this a "USB Audio" specific problem? I mean, could you confirm that it works with a I2S card? ;-)

**Comment by wyleu** [comment]
Yep it's not an issue on a audio injector where left input goes to left and
right input goes to right. There are some patchage images on the forum that
demonstrate this

**Comment by jofemodo** [comment]
Could you you check if it's a generic USB-Audio problem or a device-specific problem? I mean, could you test with a different USB-Audio device?

**Comment by wyleu** [comment]
![mono_usb_setup](https://user-images.githubusercontent.com/79083/72275746-6cc92480-3626-11ea-873e-c176a120e60b.png)
![patchage_of-UA222](https://user-images.githubusercontent.com/79083/72275747-6cc92480-3626-11ea-9655-41f08dc3be48.png)

I've tried the yeti mic on a Pi running Audacity and it records in Stereo but that would be an alsa connection

**Comment by jofemodo** [comment]
Hi @wyleu !
I just solved this:

    https://github.com/zynthian/zynthian-ui/issues/194

I think it could be related with this one, so please, try again.

**Comment by wyleu** [comment]
![image](https://user-images.githubusercontent.com/79083/72608895-a4341b80-391b-11ea-9738-98b0a8e48a77.png)

Looks like a fix !!
