### ISSUE TITLE
ZynSampler: CUE playback is delayed by a few ms

### ISSUE THREAD

**Issue by oscaracena** [zynthian/zynthian-issue-tracking#1152]
**Describe the bug**
When I set a CUE point somewhere, and I reproduce it, the audio is delayed and does not start on CUE point, but an amount of time later (around 30 ms).

**To Reproduce**
1. Add a chain with ZynSampler, and load the provided sample file. 
2. Press C4# to play the second CUE point, which marks a pluck sound.

**Expected behavior**
The audio should start at the very specific moment marked by the CUE point, not later.

**Setup:**
* zyncoder: oram (62626a8)
* zynthian-ui: oram (8844634)
* zynthian-sys: oram (5affa51)
* zynthian-data: oram (e222e11)
* zynthian-webconf: oram (0327ac4)

**Sample file with CUE points:**
* [timings+cue.zip](https://github.com/user-attachments/files/16677415/timings%2Bcue.zip) with CUE points at 00:01 (A tone), 00:03 (pluck sound) and 00:05 (white noise) seconds.

**Comment by riban-bw** [comment]
I have started to investigate this. It would help to have some more information. @oscaracena you say that there is approx. 30ms discrepency. What are the audio settings of your zynthian? (FYI Using the Report Issue button in webconf would have provided this info and hence reduced the effort in investigating.)

You say that the audio starts approx. 30ms later. Do you mean the audio starts immediately but 30ms offset within the sample or do you mean the audio starts 30ms after the key press but at the correct sample offset?

**Comment by riban-bw** [comment]
I have made a change to zynsampler that should reduce latency of MIDI trigger and _may_ fix this issue. @oscaracena please test Vangelis (testing) branch.

**Comment by oscaracena** [comment]
Hello @riban-bw, and thanks for checking this issue! 😃 The problem is not the latency, but the offset. When the CUE point is triggered, it starts around 30 ms later in the track. Or, at least, that's what I saw. I'll try to find the time to check it again and update this.

**Comment by riban-bw** [comment]
I am not seeing significant change in latency in this fix. The results look similar so the planned fix doesn't work but maybe it has inadverently fixed your issue. 😄 

[Edit] Actually, I am not seeing the original issue in either fixed/non-fixed version. The audio seems to start cleanly, not part way through the sample. Zooming into the recorded waveform I see it starting nicely from zero and increasing to very small values before increasing further. There is about 340 sample delay between zynsampler starting and MiMi-d sound starting when triggered from same MIDI note-on.
