### ISSUE TITLE
Zynthian Controlling with note commands 

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#116]
![9](https://user-images.githubusercontent.com/55761217/72627526-f6d9fb80-394c-11ea-8e39-8b4202b3a8a1.png)

If I try to control the zynthian with note commands, I have different results regarding of the source I use.
I always send the notes E2, F3, F#3, C4, F2, E3, D3, B-2 (Means: select up, select short, select options, Snapshot short, select down, back short, back options, all sounds off. 

Note: The notes, sendet by Impulse are 1 octave deeper than it is shown in the zynthian user guide)

If I use the Korg nanoKontrol2 everything is ok. Evrything works well.
![10](https://user-images.githubusercontent.com/55761217/72626165-7ca87780-394a-11ea-95f1-250dfbc8c7e6.png)

If I use the Pads of the Impulse via USB-Midi-cable I only receive the all-sounds-off-command.
![11](https://user-images.githubusercontent.com/55761217/72626534-31db2f80-394b-11ea-865e-0b06c7ac4f51.png)
This behavior is new. Some weeks ago, I coult send the commands via Impulse-Pads too.

Some weeks ago I connected the impulse direct via USB-cable. Everything works. But suddenly I had doubble triggers. Then I used the USB-Out jack only for power and the Midi-communication via Midi-Out and USB-MIDI-Cable. (no picture)

My target is to have a propper communication regardless what way I use.

**Comment by jofemodo** [comment]
I don't think it's a zynthian problem. It seems more a problem with your device. It could be a problem with the device not being properly powered. Are you sure you power supply is not the problem? How many devices are connected to the zynthian?

Anyway, i can't reproduce the problem, so i can't do nothing about it. I would need much more info ...

**Comment by Mickinator** [comment]
Hi Jose,
with the next steps I will send you Midi-Ox Protocolls witch show that all send-devices send the same data.
You can see right now in the WebConf -prints above, that zynthian filters or changes some data. For Example: if I send commands via USB-Midi-cable Zynthian ONLY receives All-note-off (b-2)
