### ISSUE TITLE
Can't stop Test MIDI

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1170]
# Describe the issue
After starting the Test MIDI function in admin menu, there seems no way to stop it.
# To Reproduce
## Steps to reproduce the behavior:
1. Go to admin menu.
2. Select "Test MIDI" to start playback.
3. Select "Test MIDI" again to stop playback.
 ## Expected behaviour
MIDI playback stops.
## Actual behaviour
MIDI playback continues.
# Additional context
Similar workflow for "Test Audio" works so expect same behavior for "Test MIDI".

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.4
Audio: ZynADAC
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20, MCP23017@0x21, ADS1115@0x48
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 35% (649M/1846M)
SD Card: 26% (14G/57G)
Temperature: 52.1ºC
Overclock: Medium
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (62626a8) 
zynthian-ui: oram (1a86c76)
zynthian-sys: oram (5affa51)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (0327ac4)
```

**Comment by riban-bw** [comment]
@jofemodo the function to play MIDI test file sets `zyngui.alt_mode` but I don't think this performs a useful function.

**Comment by jofemodo** [comment]
Yes, it allows to simply push STOP to stop MIDI demo

**Comment by riban-bw** [comment]
Yes - but it doesn't work! Setting ALT does not seem to actually enable alt mode.
