### ISSUE TITLE
Touch navigation issues

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1172]
# Describe the issue
Whilst documenting the touch interface it has become evident that several navigation workflows are suboptimal or not implemented. This ticket lists the changes required to improve navigation via touch.

- ~~"Onscreen buttons" should be relablled "Touch navigation".~~
- ~~Touch navigation should enable / disable all touch navigation but leave other touch functions enabled.~~
- ~~Bold touch mixer title should switch to zynpad.~~
- ~~Short tap title should only show main menu from mixer.~~
- ~~Globally, short press of status should show transport: toggle audio record, toggle MIDI record, etc.~~
- ~~Globally, bold press of status should show ZS3 menu.~~
- ~~Globally, long press of status should stop all sounds. (Could this cause accidental trigger when trying to access ZS3. Would this be too bad? - you are already going to change the sound.)~~
- ~~Bold touch topbar back button should show to Mixer view.~~
- ~~Bold touch title should not show mixer.~~
- ~~Chain control view onscreen buttons - There are 2 buttons that are not implemented by other gestures.~~
- Mixer MIDI learn needs consideration. This may be easier after implementing Chain Control View style configuration.
- ~~Need back button when mixer MIDI pre/learn enabled.~~
- ~~Chain Control View drag control to enter MIDI learn should allow subsequent drag to enter absolute MIDI learn.~~
- ~~How to enter / exit X-Y CC view?~~
- Bold BACK enables undo/redo. Is this intuitive enough?
- ~~Adjust pan/balance not possible with touch - could use horizontal drag on fader which would need a deadzone / hysteresis.~~

**Comment by riban-bw** [comment]
Implemented many of the features and enhancements. Strikethrough in issue detail shows what is done. Remaining changes require more in-depth work so spearating to individual commits.

**Comment by jofemodo** [comment]
When it has sense, i think we should mimic physical switches interface as much as possible, The reasons:

1.) Easier to maintain
2.) Easier to document
3.) Easier to learn. Specially when moving from a touch-only device to one with physical switches and reverse.

**Comment by riban-bw** [comment]
I have tried to align the touch navigation with V4 navigation where it makes sense. Sometimes, if this is not possible or there is a significantly better implementation, I deviate. I am testing the changes I made today to validate the designe choices.

**Comment by riban-bw** [comment]
Closing this issue as most is now done. The remaining issue with mixer MIDI learn is not just touch so I will create a separate ticket to track it..
