### ISSUE TITLE
Issue: Midi CC learning of mixer chains panning not reacting to external potentiometers consistently

### ISSUE THREAD

**Issue by Aethercircle** [zynthian/zynthian-issue-tracking#1178]
# Describe the issue
Oram does not respond consistently to some potentiometers on an external controller synth, that have been assigned to the panning control of mixer chains. After Midi-learning on each chain, linked to different external encoders, some incoming CC messages happen to control the panning of two chains at once.

## Steps to reproduce the behaviour:

1. Create a snapshot of at least six chains, with whatever synths/processors engaged.
2. Individually Midi-learn the panning control of each chain (crtl + .), through six encoders/pots on an external Midi control surface/keyboard/synth.
3. At the end of the Midi-learning process, try and set the panning of the chains with the six related encoders/pots.

 ## Expected behaviour
Each encoder should independently set the panning position of just its connected chain.

## Actual behaviour
Some encoders affect two proximal or distant chains at once.

# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: Generic USB device
Display: Waveshare 15.6 Touchscreen Display 1920x1080
Wiring: DUMMIES
I2C: Not detected

External controller synth: Modal Cobalt 8, latest OS revision.

Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-06-26
Memory: 25% (2070M/8048M)
SD Card: NA (NA/NA)
Temperature: 36.7ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (62626a8) 
zynthian-ui: oram (1a86c76)
zynthian-sys: oram (5affa51)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (0327ac4)
```

**Comment by riban-bw** [comment]
Please provide a snapshot that demonstrates this issue.

**Comment by riban-bw** [comment]
I have tested and not reproduced the issue. There has been a change to the code that fixed stale MIDI CC binding not being removed so maybe this was the cause.
