### ISSUE TITLE
Show chain level in dB when setting it

### ISSUE THREAD

**Issue by pl-gauthier** [zynthian/zynthian-issue-tracking#1180]
The level in dB is never displayed in the main mixer window when we are **setting the level** of a given chain.

I think the current chain level should be at the very least displayed when editing said level. 

There the solution of going down in the chain menu and look around in the right section to see what is its current level but that ain't quite handy in a live performance.

Here is a crude GIF I made to represent what could be a solution.
![Audio_mixer](https://github.com/user-attachments/assets/e72006bb-0c30-48cf-93c0-32c351960f8a)

**Comment by tunagenes** [comment]
I find the flashing-alternating db-channel numbers to be visually jarring. I'd suggest just putting the number and units at the top of the channel underneath the loudspeaker icon.

**Comment by riban-bw** [comment]
Is it the value of the fader or the value of the DPM (signal) that you want to see?
Is the dB value relative to full scale or a nominal 0dB point?
What is the benefit of seeing this value? (Just because we can, does not mean we have to!!!)

**Comment by pl-gauthier** [comment]
> I find the flashing-alternating db-channel numbers to be visually jarring.

Well, this is a crude gimp example, it would not flash in real life obviously. It would just *show up* (not flash) when edited.

> Is it the value of the fader or […]

The value of the fader.

> Is the dB value relative to full scale or […]

dBFS seems sensible since it is what's beneath the hood (I think).

> What is the benefit of seeing this value?

I was doing a live show with some chains e.g. : [Vocal, Keyboard, Bass, Drum]. And one person in the crowd came and told me my vocals were a tiny bit too low in respect to the rest. I quickly bended down below my keyboard to lower the rest. I selected the chain, turned the level knob and realized that there was no indication what so ever of what I was doing. My sound engineer reflex what to lower everything by 3dB but had no reference besides the "fader" graphic going up or down pixel by pixel. Every mixer (quasi ever) have a dB reference to the fader e.g.: [-∞, 0dB, +15dB]

So, yeah, I would have hope for the level to be seen somewhere.

OP here :
https://discourse.zynthian.org/t/mixer-audio-levels-in-decibel-db/9918

**Comment by riban-bw** [comment]
To manage expectations - this will not be considered until after oram is released. We are not adding new features before release.

I worry about the amount of space on the screen. Some large displays may be okay but there is more useful stuff I would pefer to see onscreen.

How about an indication of current value only during adjust, like adjusting the tempo in zynpad with the first encoder? The value appears in the topbar and updates whilst adjusting then disappears about a second after adjustment stops. There is a precedent for this behaviour so it could be simpler to implement than other solutions. If course, if there is a better way, we could use that.

Regarding values - I think pan/balance should be percentage left/right, e.g. -100% to +100% with 0% in the centre. Fader should be the amount of gain or attenuation applied to the signal in dB, e.g. -200dB to +6dB with 0dB at unity gain. (I can't actually remember the scale but that sounds about right.) Fully down (muted) would show -∞db or 🔇.

**Comment by pl-gauthier** [comment]
Oops ! Duplicate of https://github.com/zynthian/zynthian-issue-tracking/issues/571
