### ISSUE TITLE
QMIDINET accepting input but not outputting

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1181]
**Describe the bug**
QMIDINet accepts control input but seem not to generate MIDI output/

**To Reproduce**
1. Go to MIDI OUt in Admin
2. Select QMIDInet on
3. Play notes on connected keyboard
4. See error No MIDI output in webconf MIDI log or on externally connected QMIDINet components.

**Expected behavior**
Upon selecting QMIDInet in MIDI out midi data played into th zynth should appear on qmidinet network. It works for a connected 5 pin MIDI output.

**Setup:**

zyncoder: [oram (62626a8)](https://github.com/zynthian/zyncoder/commit/62626a81147add277cc772fa6770df39e6efb2cc)
zynthian-ui: [oram (1ba0568)](https://github.com/zynthian/zynthian-ui/commit/1ba0568a1ecc7f8d7887e9df7038a38d88fee853)
zynthian-sys: [oram (c4f12ea)](https://github.com/zynthian/zynthian-sys/commit/c4f12ea7e3e23ccaf85f97d486f03d0ee247b58f)
zynthian-data: [oram (e222e11)](https://github.com/zynthian/zynthian-data/commit/e222e116a1967e38075a96e2bf25aa051f796d30)
zynthian-webconf: [oram (b70f1bc)](https://github.com/zynthian/zynthian-webconf/commit/b70f1bc74f16d783fad8088885331421d0f5ac5d)

**Comment by riban-bw** [comment]
Have you enabled MIDI input for the keyboard and MIDI output to QMIDInet in a MIDI chain? You need to set up a route from the keyboard to the MIDI destination which we do with MIDI chains.

**Comment by wyleu** [comment]
Have you enabled MIDI input for the keyboard?    yes.

I can hear helm playing on the selected MIDI channel (5) and I have added a midi Thru component in both series and parallel but I do not see any action on the QMIDInet display in MIDI log.

**Comment by riban-bw** [comment]
You don't need MIDI thru plugin. Have you enabled Qmidinet on the chain output?

**Comment by wyleu** [comment]
Have you enabled Qmidinet on the chain output?
![midi_qmidinet](https://github.com/user-attachments/assets/137c23c1-24e8-4a79-bbd4-e5e2a8a52eb1)

**Comment by wyleu** [comment]
![midi_qmidinet2](https://github.com/user-attachments/assets/57cc7f67-7693-4334-86d7-b1dc3f24fcf1)

**Comment by wyleu** [comment]
https://discourse.zynthian.org/t/oram-questions/10013/5?u=wyleu  

And what happened to MIDI OUT? I am having the problem, that I enter first zynthian via USB and want to pass the messsage via DIN to the second zynthian. But the message isn’t routed to the DIN ports. I can’t see the checkboxes in webconf either.

This has changed a lot. The old approach was simple, but very limited. You have to create a “route” so MIDI-IN can get out the zynthian. The more simple way is creating a MIDI chain with “all channels” selected and no processors (none). This will act as a MIDI-THRU to the selected MIDI-OUT devices (you have to select the MIDI-OUT devices from the chain options submenu!)
