### ISSUE TITLE
Report a version number in Engine LV2 dialog.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1185]
**Is your feature request related to a problem? Please describe.**
With lv2 plugins it can be difficult to know which particular version of the plugin you have loaded.

**Describe the solution you'd like**
Report a version number or date or similar in the LV2 webconf display.

**Describe alternatives you've considered**
Lots of struggling around locating files and trying to extract version numbers

MiMi-D updates are being tested and I want to know how current my version is, without resorting to command line.

**Comment by riban-bw** [comment]
This could prove challenging to be consistent as different plugins may not provide this info (in the same way).

**Comment by riban-bw** [comment]
There is no version info available for most (all) LV2 plugins. Displaying date / file location is not useful for most users and clogs screen space. Plugins provided by zynthian image / updates should not require this feature. Users wanting to delve into the guts should use command line tools such as `lv2ls` and `lv2info` to get information about installed plugins and `ps` to see running instances.
