### ISSUE TITLE
CUIA for capture workflow

### ISSUE THREAD

**Issue by ToFFmashines** [zynthian/zynthian-issue-tracking#1188]
**Is your feature request related to a problem? Please describe.**
The current way to capture work with Zynthian is described here:
https://discourse.zynthian.org/t/v5-user-guide-on-the-way/8390/11
I'm not happy with having to turn recording on and off from the admin menu. The reason is that this action is recorded, that is, the recording starts in the admin menu and also ends there. Of course, it is possible to crop the resulting video and edit the times in the log file. But it's annoying extra work.

**Describe the solution you'd like**
I suggest adding START_CAPTURE_WORKFLOW and STOP_CAPTURE_WORKFLOW commands to CUIA. And also TOGGLE_CAPTURE_WORKFLOW if it is possible. 
This solution will enable recording workflow to be started and stopped using external controllers from any Zynthian screen.

**Describe alternatives you've considered**
I have no other alternative

**Comment by riban-bw** [comment]
Done. CUIA are:

- START_WORKFLOW_CAPTURE
- STOP_WORKFLOW_CAPTURE
