### ISSUE TITLE
Preview Parameter when scrolling in Page mode.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1189]
**Is your feature request related to a problem? Please describe.**
When entering page mode select ( the grey list) as you scroll you do not get to see the parameters offered in that page.
**Describe the solution you'd like**
As the grey list is scrolled display the parameters in that page in their greyed form.  Release Short press selects that page, back encoder short press returns to page you were on .

**Additional context**
![page-display](https://github.com/user-attachments/assets/7b00460e-c904-4432-88ae-9ba30d8afda8)

Useful for locating a particular parameter without labouriously going through each page.

zyncoder: oram (62626a8)
zynthian-ui: oram (c84526e)
zynthian-sys: oram (3e390f2)
zynthian-data: oram (53dfae0)
zynthian-webconf: oram (b70f1bc)

**Comment by riban-bw** [comment]
Odd! I thought this was implemented. Maybe a regression?

**Comment by wyleu** [comment]
Well it's nice to get them as a feature request rather than a Bug...

**Comment by riban-bw** [comment]
This is fixed. (I am not sure what commit fixed it!) Still can't do this with touch though.
