### ISSUE TITLE
Sustain Pedal forgotten previous settings.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1193]
**Describe the bug**
Long standing Patches have lost their sustain settings across multiple engines. Works when Re Midi learn is used on each individual engine.. 

**To Reproduce**
1. Press Sustain Pedal on connected device

**Comment by jofemodo** [comment]
Sorry, i don't understand. I can't reproduce the issue. Perhaps you should be more detailed about how to reproduce this issue.
