### ISSUE TITLE
System restore does not seem to restore everything

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#121]
**Describe the bug**
Restoring from a system backup does not seem to set the Zynthian environmental variables like SOUNDCARD_NAME.

**To Reproduce**
Steps to reproduce the behaviour:
1. Within webconf, navigate to SYSTEM->Backup/Restore
2. Select "System Backup" tab then click "BACKUP" button to create a backup.
3. Navigate to HARDWARE->Audio, change "Soundcard" and click "SAVE".
4. Navigate to SYSTEM->Backup/Restore
5. Select "Restore" tab then click "RESTORE" button.
6. Drag previously saved file to drop area (or navigate to select it from file system) and click "UPLOAD" button.
7. Observe `/etc` file restore in subsequent log.
8. Navigate to HARDWARE->Audio.

**Expected behaviour**
Soundcard is restored to backed-up version.

**Actual behaviour**
Soundcard is not restored.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: Not detected
SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: 2020-01-15
Memory: 7% (287M/3906M)
SD Card: 37% (9.7G/28G)
Temperature: 44.0ºC
SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (256b9af)
zynthian-sys: master (fea8da4)
zynthian-data: master (ba48e1b)
zynthian-webconf: master (10822b4)

**Comment by jofemodo** [comment]
I think it's fixed now. Anyway, after a system restore, a reboot "almost" mandatory.
