### ISSUE TITLE
Mapping channel aftertouch to MIDI-CC shows no response

### ISSUE THREAD

**Issue by Jimi-Heinrich** [zynthian/zynthian-issue-tracking#122]
**Describe the bug**
After succesfully mapping channel aftertouch to MIDI-CC, channel aftertouch does not alter chosen parameter 

**To Reproduce**
0. Using LaunchpadX on USB-Port Firmware1.02
1. Go into webconfig, advanced MIDI-settings
2. In "Midi filter rules" enter: "MAP CP => CC#15", and save
3. load Synthlayer, e.g. ZynAddSubFX
4. Go to instrument paramter, e.g. cutoff
5. Click on learn and wiggle corresponding knob
6. Send channel aftertouch message
7. "15" is shwon beneath parameter (e.g. cutoff)
8. Error: sending channel aftertouch does not alter parameter (e.g. cutoff)

**Expected behavior**
The paramter should react to channel aftertouch after mapping

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (7b4aaae)
zynthian-sys: master (bc028a0)
zynthian-data: master (0d64d0f)
zynthian-webconf: master (30d3cc4)

**Comment by jofemodo** [comment]
It works for me!

https://www.youtube.com/watch?v=J-mjjiPoEUg&feature=youtu.be

I used the same MIDI filter rule than you.

Please, repeat the procedure and send a video ...

Regards!

**Comment by jofemodo** [comment]
BTW, could you send a screenshot of the webconf's dashboard?

Regards

**Comment by Jimi-Heinrich** [comment]
OK, I'm at it, but I can't get into webconfig after reboot now. Will take a bit... I'll send screenshot and video asap. 

This for confirmation, I'm really sending channel aftertouch: 

![channel presure from Launchpad X](https://user-images.githubusercontent.com/60140248/72808796-9b648200-3c5a-11ea-9a61-a04a6f86ae4f.png)

There is a thing with the LaunchpadX, though: it has two different ports for sending MIDI Data:  DAW-OUT[0] and MIDI-OUT[1] in that particular enumeration order.

**Comment by Jimi-Heinrich** [comment]
All went well after a snapshot reload and then clean reboot:

Video of the process (should run in VLC):
[aftertouch to MIDIcc.zip](https://github.com/zynthian/zynthian-issue-tracking/files/4091351/aftertouch.to.MIDIcc.zip)

MIDIconfig:
![Screenshot_2020-01-21 Zynthian MIDI Configuration channel aftertocuh to MIDICC15](https://user-images.githubusercontent.com/60140248/72810408-c8fefa80-3c5d-11ea-9aa1-943e6e05850c.png)

hope that helps a little

**Comment by jofemodo** [comment]
+ I can't reproduce the problem with my Behringer MÖTOR 61, that is the only keyboard with aftertouch i have. I will ask for a launchpad for testing

+ Anyway, could you send the zynthian's MIDI log output?

Thanks

**Comment by Jimi-Heinrich** [comment]
Hm, I can see the LaunchpadX channels, but even with "show all messages" I can't see any entrys. Hitting play/pause does nothing for me.

**Comment by jofemodo** [comment]
Could you try enabling the "Single channel mode"?

**Comment by Jimi-Heinrich** [comment]
That worked for sure:
![MIDILog aftertouch LaunchpadX](https://user-images.githubusercontent.com/60140248/72910250-9249e280-3d38-11ea-85e3-c70c678c2fbb.png)

As I said, the LPX has a somewhat quirky MIDI-enumeration. The first channel is for the DAW-related messages (communicationg with ableton live etc.). The second one for the "normal" messages coming from CC-controllers or the MIDI-grid(+aftertouch)

**Comment by jofemodo** [comment]
Could you send me a screenshot from webconf''s MIDI port config?

**Comment by Jimi-Heinrich** [comment]
Yes Sir:
![MIDIport config aftertouch LPX](https://user-images.githubusercontent.com/60140248/72911424-57e14500-3d3a-11ea-975d-30dfd2e187e7.png)

**Comment by jofemodo** [comment]
But open the MIDI ports dialog, having your pad-controller connected, of course.

**Comment by Jimi-Heinrich** [comment]
Sorry I'm not that fluid (pun intended), here you go:
![MIDIport config aftertouch LPX 2](https://user-images.githubusercontent.com/60140248/72912270-af33e500-3d3b-11ea-8f71-a310f00224e6.png)

**Comment by wyleu** [comment]
The training manual is writing it's self here !!! :-C

**Comment by jofemodo** [comment]
Any progress/change on this issue? I still can't reproduce the problem ...

**Comment by Jimi-Heinrich** [comment]
Sorry, didn't know the ball was in my park... 

But no, the behaviour is still there (latest update 1 hour ago). I can map aftertouch to cc15 but after that are unable to use it. What further tests could I do?

I forgot to mention: when using the controller section of the LivePadX, assigning and using CC works like a charm. Aftertouch and CC are coming out the same MIDI-Port, so it is strange it doenst take aftertouch.

**Comment by jofemodo** [comment]
Hi Jimi!
Could you re-confirm this issue with the latest nightly builds:

https://os.zynthian.org/2020-03-10-zynthianos-buster-lite-1.0.0.zip

or

https://os.zynthian.org/2020-03-09-zynthianos-buster-lite-1.0.0.zip

Thanks!

**Comment by Jimi-Heinrich** [comment]
Hey!
Yes, the issue still stays the same. No response to aftertouch after mapping to CC15 and learning.

**Comment by jofemodo** [comment]
Hi @Jimi-Heinrich !
Could you re-rest with the latest image updated to the last?
I've testing and i can't reproduce the problem, but i didn't in the past either ...

**Comment by Jimi-Heinrich** [comment]
Ok,


will do so the next week - as I need to do a complete update - also eying on RPi4. but thats for another time. This is really a strange issue…. 

Let me know if I can help with log files or similar..

**Comment by Jimi-Heinrich** [comment]
Something changed. For good and for worse.

_worse:_
When I now use the mapping, (Channel Pressure => CC15) it isn't recognized by the learn function anymore.

**BUT**

_good:_
When I use a mapping, that reflects the default CC of that parameter (e.g. CC74 for cutoff in zynaddsubFX) - ¡¡IT WORKS!!

The only thing left now, is to define a  baseline and a range of that parameter modulation. 
E.g. channel pressure starts cutoff (CC74) at say 24 and goes to maximum 80. This should be done in the mapping window.

Maybe something like:
MAP CP => CC#74, b24, r80

which means the above: map aftertouch 0-127 to CC74 24-80

That way it would be really useful as a performance feature.

**Comment by jofemodo** [comment]
This is not correct! You have to put the "#" between CP and the number .... Also, CC#7420:100 is not correct syntax.
If you want to map the CC values, you could take a look to the MIDI FXs ...

**Comment by Jimi-Heinrich** [comment]
Sorry, 

my bad! I misunderstood the wiki entry. So there are no option for maping actual CC value ranges to other value ranges? That would be tremendously helpful!

Strangely enough I encountered the following.

When I type in this rule and boot up:

![Bildschirmfoto 2020-12-04 um 09 56 37](https://user-images.githubusercontent.com/60140248/101143487-3ec24980-3617-11eb-80c8-039ceb9b5a59.png)

The mapping doesn't work. But when I go into the webui MIDIoptions and press 'Save' again, with the exact same rule, it suddenly start working. Hope this helps.

**Comment by Jimi-Heinrich** [comment]
Sorry, 

my bad! I misunderstood the wiki entry. So there are no option for maping actual CC value ranges to other value ranges? That would be tremendously helpful!

Strangely enough I encountered the following.

When I type in this rule and boot up:

![Bildschirmfoto 2020-12-04 um 09 56 37](https://user-images.githubusercontent.com/60140248/101143487-3ec24980-3617-11eb-80c8-039ceb9b5a59.png)

The mapping doesn't work. But when I go into the webui MIDIoptions and press 'Save' again, with the exact same rule, it suddenly start working. Hope this helps.



EDIT:

I tried again and this seems to be persisting for me. I use this rule:

MAP CH#2 CP => CH#2 CC#74

When I boot up, it won't work. But if I go into MIDI-Options and simply press 'Save' again, it starts working.

**Comment by Jimi-Heinrich** [comment]
OK, to close this issue: I upgraded to RPi4 and used the last stable image (2020-09-05-zynthianos-buster-lite-armhf-1.0.0) for a clean install: IT NOW WOKRS ! only "problem" is the "missing" scalability, but that is another issue. Many thanks.
