### ISSUE TITLE
Multitrack recorder does not record main chain audio, but single audio chain audio

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#1229]
When I select multitrack recording on main chain, audio tracks are not recorded, although output is send to hardware DAC.

On another special kit (kind of productive kit), some chains are recorded on the main chain, but some aren’t. This special kit uses a multichannel input/output device, which is working correctly.

I used the following snapshot:
[014-multitrack isssue 01.zss.zip](https://github.com/user-attachments/files/17282938/014-multitrack.isssue.01.zss.zip)

I’ve made a UI-log to show the issue.
[ui_sesion-20241007135946.zip](https://github.com/user-attachments/files/17282940/ui_sesion-20241007135946.zip)

#  Steps to reproduce the issue
- Create any audio chains (i.e. 4 zynaddsubfx's).
- Set all chain's "Audio Out" to “Main mixbus” and “Record chain”.
- Start some patterns on the 4 synths → audio signals is heard on hardware audio out.
- Press recording button and record to multitrack file.
-  Stop recording and examine new wav file with i.e. Zynsampler.

# Expected behaviour:
the multitrack file contains all 5 audio signals (chain 1-4 + main chain)
The stream of the main chain containing the sum of all the single chain signals.

# Actual behaviour:
Only the single chain audio streams are in the multitrack file, main chain recording is silent, but a silent audio stream is in the multitrack file.
([2024-10-07_14_00_03.001.zip](https://github.com/user-attachments/files/17282963/2024-10-07_14_00_03.001.zip))
Directly listening doesn't help, you have to download and inspect the wav file, or inspect it with zynsampler.

# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-10-02
Memory: 17% (1437M/8052M)
SD Card: 51% (15G/29G)
Temperature: 54.3ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 0 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (71de6d2) 
zynthian-ui: oram (f43f293)
zynthian-sys: oram (a717e49)
zynthian-data: oram (ddfa009)
zynthian-webconf: oram (b530397)
```

Regards

**Comment by riban-bw** [comment]
This is fixed in Vangelis (testing). Should be deployed to Oram in next point release.
