### ISSUE TITLE
Noise spikes when changing zs3 sub snapshots with continued audio input.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1239]
**Describe the bug**
When sub snapshots are used to change settings, considerable noise spikes are generated switching between different zs3 snapshots.

**To Reproduce**
1. Install last_State.zss 
[last_state.zss.zip](https://github.com/user-attachments/files/17362685/last_state.zss.zip)

2. Use PC 5 & 6 to switch between zs3 states
3. Hear switching noise on transition

**Expected behavior**
A clean switch between these states. When used as a guitar effects pedal you frequently want to change quickly between bars. The noise renders this difficult as it's important to make sure there is no input audio 

**Setup:**
zyncoder: [vangelis (1dd6f7a)](https://github.com/zynthian/zyncoder/commit/1dd6f7a2776410a6b93aea9f447a0322acc93936)
zynthian-ui: [vangelis (b2eaca7)](https://github.com/zynthian/zynthian-ui/commit/b2eaca756b4a7e7284df415374bf7bb172ef541c)
zynthian-sys: [vangelis (f842566)](https://github.com/zynthian/zynthian-sys/commit/f8425664b2a69cc7701f05c49d4ad18c109d7ec9)
zynthian-data: [oram (ddfa009)](https://github.com/zynthian/zynthian-data/commit/ddfa009f7ff55c455c7a07d0349f645ee8219354)
zynthian-webconf: [vangelis (bd99d05)](https://github.com/zynthian/zynthian-webconf/commit/bd99d05e52cb808ea5d7b98f98a07c3459cdde97)

**Additional context**
Needs addressing to allow zs3 to be used in this context.

**Comment by riban-bw** [comment]
The supplied snapshot does not have any zs3. Please provide a snapshot with zs3 that will trigger the issue.

**Comment by wyleu** [comment]
[Noise-spike.001.zip](https://github.com/user-attachments/files/17363747/Noise-spike.001.zip)
 Here is the zss & the wav file. On changing from PC 5 to PC 6 a noise spike is heard. Not noticeable going the other way. Does it depend on the chain component? IF so we need to discover which are the villains in the ones we offer.

**Comment by riban-bw** [comment]
I think I see what is going on. In PR6, one of the chains has distortion. There is a short period when that chain is not muted and hence you get a short unexpected burst of distorted signal. Going the other way does not exhibit this because PR5 does not have the distortion in the chain.

So it looks like chains are being muted / unmuted in an order that does not best suit the changes in configuration. We could look at muting output during a ZS3 change similar to what is done during snapshot load but would need to ensure this did not interfere unduely with signal, e.g. a user may wish a chain to continue sounding during a ZS3 change - which is quite likely so any muting may need to be inteligent and chain based.

**Comment by riban-bw** [comment]
A proposal to fix this is to:

- Mute all chains that are muted in the new zs3
- Apply all other zs3 config
- Unmute any chains that are not muted in new zs3

I think this should resolve this issue and be more robust without interferring with other signals.

**Comment by riban-bw** [comment]
I have implemented a fix in Vangelis (testing). Please test and validate the fix. This introduces a small delay loading zs3 only when required so that the appropriate chains can be muted (with soft mute appling). The delay is one jack cycle, e.g. 5.3ms at 48000fps, 256 frames.

**Comment by wyleu** [comment]
Fixed by 

zyncoder: vangelis (1dd6f7a)
zynthian-ui: vangelis (f1510ab)
zynthian-sys: vangelis (f842566)
zynthian-data: vangelis (ddfa009)
zynthian-webconf: vangelis (bd99d05)

**Comment by wyleu** [comment]
Reopened in anticipation of release.
