### ISSUE TITLE
Library PReset Search does not function..

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1242]
**Describe the bug**
The webconf preset search feature in the library section no longer functions. 
Reported in this thread [https://discourse.zynthian.org/t/ability-to-search-for-presets-by-name/7718/8?u=wyleu](url)

**To Reproduce**
1. Go to webconf library 
2. Click on 'Presets and soundfonts'
3. Attempt to search 

**Expected behavior**
The library search function should search for sounds matching the search criteria.

**Screenshots**

**Setup:**
zyncoder: [vangelis (1dd6f7a)](https://github.com/zynthian/zyncoder/commit/1dd6f7a2776410a6b93aea9f447a0322acc93936)
zynthian-ui: [vangelis (f1510ab)](https://github.com/zynthian/zynthian-ui/commit/f1510ab3ce771c1335bb864a780ff78a39fe3f60)
zynthian-sys: [vangelis (f842566)](https://github.com/zynthian/zynthian-sys/commit/f8425664b2a69cc7701f05c49d4ad18c109d7ec9)
zynthian-data: [vangelis (ddfa009)](https://github.com/zynthian/zynthian-data/commit/ddfa009f7ff55c455c7a07d0349f645ee8219354)
zynthian-webconf: [vangelis (bd99d05)](https://github.com/zynthian/zynthian-webconf/commit/bd99d05e52cb808ea5d7b98f98a07c3459cdde97)

**Additional context**
It appears the file requested has been relocated. 

instead of https://musical-artifacts.com/artifacts.json

https://data.musical-artifacts.com/json/artifacts.json    should be used.

**Comment by riban-bw** [comment]
musical-artifacts site seems to be down. We need to wait to see if this is a peristent (permanent) issue. It is plausible they have exhausted their funding or it could be a temporary outage. There is little info about the outage at the moment.

**Comment by riban-bw** [comment]
Musical-Artifacts site is back up and this feature is now working. I will close the ticket as it was due to an upstream availability issue. Anyone wishing to contribute to the upkeep of musical-artifacts can [donate](https://streamelements.com/musicalartifacts/tip).

**Comment by Potajito** [comment]
Is it confirmed that this is fixed? Is preset search working for everyone?
Searching for presets on the zynthian webconf UI has never worked for me. Even trying to search for the exact string of a preset.
I don't think the availability of https://musical-artifacts.com/ has anything to do with it (it has always been available on my end at least).
If webconf is looking for https://musical-artifacts.com/artifacts.json that is never going to return anything, instead, it should use https://data.musical-artifacts.com/json/artifacts.json if it needs the full json.
The only way the url https://musical-artifacts.com/artifacts.json returns anything it's if querying it, like "https://musical-artifacts.com/artifacts.json?q=cabin"
