### ISSUE TITLE
Provide a means to switch on/off MIDI learning of UI elements.

### ISSUE THREAD

**Issue by Patchbungles** [zynthian/zynthian-issue-tracking#126]
When using touchscreen, UI parameters get assigned to MIDI controllers. 
Assignment seems to happen without my say-so.

It needs a switch in webconf so that learning is OFF by default.
Perhaps a screen mock-up in webconf so that individual elements can be ticked [x] or not [ ] for learning depending on usage.

**Comment by jofemodo** [comment]
This has been recently improved and it works a lot better now. Activating MIDI learn by error is now quite difficult.
