### ISSUE TITLE
CV support?

### ISSUE THREAD

**Issue by mxmilkiib** [zynthian/zynthian-issue-tracking#127]
I've read the forum thread regarding planned support for [control voltage](https://discourse.zynthian.org/t/cv-gate-input-output/3182) but I was wondering what the specifics of what-is-needing-done are? I'm curious given the growing support for [JACK/LV2 CV](https://linuxmusicians.com/viewtopic.php?f=1&t=20701&p=112242).

**Comment by jofemodo** [comment]
Take a look to this:

https://wiki.zynthian.org/index.php/Adding_Extra_I/O_with_the_Zynaptik_Module

The current state of CV-Gate imeplementation on zynthian is:

+ We have 4 analog inputs that can be assigned to MIDI CC, Pitch Bending or Chan Press.
+ These analog inputs work in the range of 0-5V. It would be nice to have a CV-IN circuit that would adapt different CV signals to the 0-5V range. It would be a nice contribution!!
+ We have up to 20 extra digital inputs that could be used as "Gate-IN" but ...
+ There is no software implementation for this, although it could be done quite easily.

Regards,

**Comment by jofemodo** [comment]
Development of CV/Gate is being addressed by this ticket: https://github.com/zynthian/zynthian-issue-tracking/issues/368
