### ISSUE TITLE
Indication of green builds on https://os.zynthian.org

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#128]
A commonly asked question in the forum is which OS build to download and install. The answer is invariably, "...the latest on https://os.zynthian.org which is green on https://jenkins.zynthian.org/job/ZynthianOS"".
Quite often the latter qualification is missed and needs to be added to the reply, catching out users - or users just download the latest without realising this.

It would be advantageous if https://os.zynthian.org clearly indicated the most recent green build.

There are several ways this could be accomplished:

- Have a link to the latest green build at the top of current page, i.e. "This is the build you are looking for" type link
- Have separate pages for green builds and all builds
- Show the build status of each image on https://os.zynthian.org
- Have different pages for green builds and none green builds
- Only show green builds

I have listed these in my order of preference but think the simplest to implement may be appropriate.

**Describe alternatives you've considered**
There is already a message on https://os.zynthian.org stating that users should check https://jenkins.zynthian.org/job/ZynthianOS for green builds. This could be made more prominent. It is already in bold but the grey text of that section makes it all recede so may easily be missed.

There could be a link on the wiki, forum or elsewhere to the current green build. It makes sense to have a link to the latest _stable_ build and latest _cutting edge_ build somewhere.

**Additional context**
This request is in response to a FAQ. Making this process more seamless should reduce (community) support burden and make Zynthian more attractive to new users by reducing friction.

**Comment by jofemodo** [comment]
It's solved now-
