### ISSUE TITLE
Issue: cannot use sooperlooper selected loop to select loop 1

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-issue-tracking#1285]
# Describe the issue
A clear and concise description of what the issue is.
# To Reproduce
## Steps to reproduce the behavior:
1. Add sooperlooper
2. Add three more loops
3. Navigate to Global Loop
4. Use selected loop knob

 ## Expected behaviour
The loop selection should move between loops 1-4
## Actual behaviour

The selected loop goes between loops 2-4

# Screenshots
# Additional context

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.1
Audio: HifiBerry DAC+
Display: PiScreen 3.5 (v2)
Wiring: MCP23017_ENCODERS
I2C: MCP23017@0x20
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-10-02
Memory: 83% (758M/907M)
SD Card: 20% (22G/117G)
Temperature: 60.8ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (71de6d2) 
zynthian-ui: oram (f43f293)
zynthian-sys: oram (105c12d)
zynthian-data: oram (ddfa009)
zynthian-webconf: oram (b530397)
```

**Comment by riban-bw** [comment]
Yep! I noticed that whilst doing some SL enhancements. It is fixed in dev branch but other work needs doing there. I will either complete that work or port the fix to vangelis... when I find time.

**Comment by riban-bw** [comment]
Fixed in vangelis (testing). Ready for deploy to oram (stable) on next point release.
