### ISSUE TITLE
Issue:when saving a zs3, it resets its restore settings

### ISSUE THREAD

**Issue by lanmower** [zynthian/zynthian-issue-tracking#1287]
# Describe the issue
1 save a zs3, it resets the restore settings
# To Reproduce

## Steps to reproduce the behavior:
1. zs3 save
2. check restore options, they'll all be on
 ## Expected behaviour
keeping the restore options can be helpful
## Actual behaviour
restore options are reset every time
# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: Generic USB device
Display: Generic HDMI/DSI Display
Wiring: DUMMIES
I2C: Not detected
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-10-02
Memory: 11% (962M/8048M)
SD Card: 34% (20G/59G)
Temperature: 57.1ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (66fa477) 
zynthian-ui: oram (7b68279)
zynthian-sys: oram (105c12d)
zynthian-data: oram (305b301)
zynthian-webconf: oram (31f3f55)
```

**Comment by riban-bw** [comment]
Resolved in vangelis (testing) ready to be deployed to oram (stable) on next point release.

**Comment by jofemodo** [comment]
Restore options are per-zs3. It's important that this is like this. Be could apply last selected options to new zs3s, but they still have to be configurable by zs3.
