### ISSUE TITLE
ZynAddSubFx volume levels values

### ISSUE THREAD

**Issue by Ejdzi2** [zynthian/zynthian-issue-tracking#1289]
# Describe the issue
When there is at least two chains (same channel) of ZynAddSubFx saved in snapshot there ist problem with ZynAddSubFx engine volume levels. In example snapshot In the first chain engine volume level is set on 29 (quiet) and in the second chain engine volume level is set 114 (loud). After loading snapshot all chains has the same loudness. Changing level, for example to 30 or 28,  jumps the volume level. 
# To Reproduce
## Steps to reproduce the behaviour:
Making two different ZynAddSubFx chains on the same channel ( maybe also on different channels), setting different volumes levels (maybe others values too) and saving the snapshot. 
 ## Expected behaviour
Set values of engine should be maintained after loading snapshot.
## Actual behaviour
After loading snapshot levels showing different values but sound does not match the values.

# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-10-02
Memory: 12% (498M/4045M)
SD Card: 51% (14G/29G)
Temperature: 24.1ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (66fa477) 
zynthian-ui: oram (7b68279)
zynthian-sys: oram (105c12d)
zynthian-data: oram (305b301)
zynthian-webconf: oram (31f3f55)
```

**Comment by jofemodo** [comment]
It should be fixed now. Please, update and test (vangelis branch).
