### ISSUE TITLE
Issue: Outputs 1+2 in main menu cannot be disconnected

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#1291]
# Describe the issue
I have a multiple channels card (ES-9) connected with USB.
I'd like to connect Output 3+4 for main mixer channel, and disconnect Output 1+2.
The second is not working (see status images).
# To Reproduce
1. Take a clean setup, or any other setup with or without post-fading effect on the main mixer chain.
2. try to disconnect Output 1+2 does not work. 
3. Single channel connecting does not work correctly for channels 1 and 2.

It seems as if channel Output 1+2 is always connected automatically.
For example if I disconnect all jack connections manually and connect Output 7+8 for example, Output 1+2 are also automatically connected.

 ## Expected behaviour

Arbitrary choice of Output channels on the hardware.

## Actual behaviour

Channels 1+2 are automatically always connected after connecting or disconneting any channel to the main output.

# Screenshots
![image](https://github.com/user-attachments/assets/ebce024e-15d9-4d91-aabb-8d69d6404f3b)
![image](https://github.com/user-attachments/assets/dd573887-bf5b-4950-9980-260e79bf3aa3)

# Additional context
Other Output channel choices are working correctly.
Direct connection and disconnection from other chains is working correctly.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: Custom device
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21, ADS1115@0x4A
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-09-11
Memory: 39% (1508M/3791M)
SD Card: 54% (15G/29G)
Temperature: 37.9ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 0 minutes
Audio Levels on Snapshots: Off
```
## Software
```
zyncoder: vangelis (66fa477) 
zynthian-ui: vangelis (b897e56)
zynthian-sys: vangelis (2924766)
zynthian-data: vangelis (305b301)
zynthian-webconf: vangelis (6792f2c)
```

**Comment by riban-bw** [comment]
When we introduced hot-plug, it became evident that there was a bug in audio routing that did not account for more than 9 inputs or outputs. The mechanism for routing was changed and the default main output routing was updated but it seems that got regressed during a merge. I have reapplied this change to vangelis.

You need to "Remove All" to reset the output routing. There _may_ still be issues with snapshots. @gitnob please test and report success.

**Comment by gitnob** [comment]
It's working in vangelis now.
