### ISSUE TITLE
Issue: MIDI learning toggle (on/off) parameters doesn't work

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#1292]
# Describe the issue
Using the midi CC learning function of Zynthian, I set a lv2 parameter to be controlled by an external device. The lv2 parameter shows the correct midi channel and CC number of the external device on the zynthian screen.

But the lv2 parameter could only be controlled by the external device if CC number is <= 64.
If I choose a CC number higher than 64, the parameter could not be controlled by the external device.
Funny enough, with a continuous change on some CC channels (>64) it is working, but not if I use a value change from 0 to 127.

# To Reproduce
## Steps to reproduce the behavior:
1. Use external midi device with toggle button / or on/off connected to zynthian
2. Midi learn an on/off parameter with the external device (midi channel and number are visible now)
3. Toggle on/off button on external device
4. midi log shows values (0 -> 127 -> 0 -> 127 -> 0 ....)
5. no change of lv2 parameter
## Expected behaviour
Any CC channel on any midi channel to work after midi learning
## Actual behaviour
See attached video.
[CCexternal-bug.zip](https://github.com/user-attachments/files/18010385/CCexternal-bug.zip)

# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-10-02
Memory: 14% (1181M/8052M)
SD Card: 50% (14G/29G)
Temperature: 39.5ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 0 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: vangelis (36691b3) 
zynthian-ui: vangelis (01b3393)
zynthian-sys: vangelis (0176796)
zynthian-data: vangelis (305b301)
zynthian-webconf: vangelis (6d07476)
```

**Comment by jofemodo** [comment]
This should be fixed now (vangelis)
