### ISSUE TITLE
Implement per-loop MIDI binding of single pedal mode in sooperlooper

### ISSUE THREAD

**Issue by pft** [zynthian/zynthian-issue-tracking#1294]
**Is your feature request related to a problem? Please describe.**

The per-loop MIDI binding is only done for loop actions like record, overdub, etcetera. It saves a lot of buttons or pedals to be able to bind the single-pedal control per loop.

**Describe the solution you'd like**

Per-loop MIDI binding of single-pedal mode (alongside the 'selected loop binding').

**Describe alternatives you've considered**

Implementing a control driver.

**Comment by riban-bw** [comment]
Implemented in vangelis (testing). Ready to deploy to stable (oram) in next point release.
