### ISSUE TITLE
Some x42 plugins make mute/solo stop working from the touchscreen on audio tracks (consistent, replicable behavior)

### ISSUE THREAD

**Issue by TubularCorpration** [zynthian/zynthian-issue-tracking#1297]
**Describe the bug**
Mute and solo via touchscreen don't work on audio tracks that have an x42 plugin loaded. The behavior varies depending on which specific x42 plugin is being used. In all cases, both mute and solo function normally when using the encoders. 

Instrument tracks have been tested with x42 Dynamic Compressor and behave correctly.
I have been able to consistently replicate the behavior with all plugins listed below. I haven't been able to replicate it with any non-x42 plugins that I've tested. 

Here's a breakdown of the way the different x42 plugins available by default with a fresh Oram install behave:

Mute and solo can't be engaged from the touchscreen.  If they are engaged using encoder 1 and 2, they can't be disabled from the touchscreen:
- x42 Dynamic Compressor (mono and stereo)
- x42 Digital Peak Limiter (mono and stereo)
- x42 Whirl (simple version only)

Solo works correctly from the touchscreen, but mute can't be engaged or disengaged:
- x42 Preset Convolver Stereo

Both solo and mute function correctly:
- x42 Autotune (both variants)
- x42 Whirl (standard version)
- x42 Instrument Tuner

**To Reproduce**
1. Create a new audio track
2. From chain options, add one of the plugins listed above (either pre or post fader)
3. Return to the mixer page and use the touchscreen to mute or solo the track
4. Exact behavior will depend on which plugin was added in step 2, see list above.

**Setup:**
zyncoder: oram-2409 (71de6d2)
zynthian-ui: oram-2409.001 (df2facc)
zynthian-sys: oram-2409.002 (4c4ce51)
zynthian-data: oram-2409 (ddfa009)
zynthian-webconf: oram-2409.001 (88fc358)

Official v5.1 hardware
RPi 8gb

**Comment by riban-bw** [comment]
I suspect this is due to the length of the plugin name. It may be sufficiently long to overlap the mute/solo buttons in the fader strip and interfere with their behaviour. Touching the label will select the chain. The buttons _should_ be in front of the label in the z-order but maybe this is failing for touch. It works fine for mouse click so might relate specifically to the multitouch driver.

**Comment by TubularCorpration** [comment]
I actually noticed the overlap while I was testing and had a hunch it was something related to that, but didn't want to speculate in a bug report.

**Comment by riban-bw** [comment]
My bad! This regression occured in commit 7ad130a844b714da3b4798acc120f42b386a2d08. Only the first line of the title was being truncated based on the length of the longest line. Restored correct behaviour in vangelis. Ready to deploy in next point release.
