### ISSUE TITLE
Placing Overall zynthian output volume on the top left encoder during ADMIN & LAYER MODE.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#13]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when setting up to make a recording, I can't adjust the OVERALL volume of the zynthian using the top left encoder 

**Describe the solution you'd like**
I would like the top left decoder to default to OVERALL volume control when in ADMIN & LAYER mode.

**Describe alternatives you've considered**
Use of external MIDI mapping does address this issue, but requires to be configured before it can be used

**Additional context**
The whole area of Zynthian Layer volume control ( The output Mixer ) should ultimately be considered to allow balance between layers and effects to be easily modified.

**Comment by Baggypants** [comment]
Maybe have a volume circle around the menu select number at the bottom right.

**Comment by riban-bw** [comment]
This feels a bit inconsistent. Having a knob control volume (presumably master fader) on some screens but not others and there not being an indication doesn't feel right to me. I can see that having overal control at all times is advantageous but I would prefer that be a consistent method (ideally a dedicated knob but maybe too late for that!).

**Comment by riban-bw** [comment]
Pressing MIX/LEVEL button will access the mixer / audio levels screen alternately. This is the official way to access volume in a consistent and (fairly) quick manner so I will close this issue.
