### ISSUE TITLE
Preset options menu fails for some engines.

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1300]
# Describe the issue
Attempts to show the presets options menu for some engines results in an unrecoverable error. Example engine that suffers this issue is LinuxSampler.
# To Reproduce
## Steps to reproduce the behavior:
1. Add chain with LinuxSampler, Bass, BrightBass.
2. Access Presets menu.
3. Bold press on "SynthBass" preset.
 ## Expected behaviour
Preset options menu shows.
## Actual behaviour
Errors in log and no further action possible. UI locks up.
# Additional context
This doesn't happen for first entry, "BrightBass".

# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: Behringer UMC1820
Display: MIPI DSI 800x480
Wiring: DUMMIES
I2C: Not detected
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-10-02
Memory: 20% (1683M/8064M)
SD Card: NA (NA/NA)
Temperature: 48.8ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 15
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: vangelis (36691b3) 
zynthian-ui: vangelis (78a6b3c)
zynthian-sys: vangelis (4209dc0)
zynthian-data: vangelis (9875bb5)
zynthian-webconf: vangelis (d811ea6)
```

**Comment by riban-bw** [comment]
This is due to the options menu having ported to info display but not all uses being updated.

**Comment by riban-bw** [comment]
This was due to options menu now expecting info. Fixed in vangelis (testing). Ready for deploy to oram (stable).

**Comment by jofemodo** [comment]
But options menu should not be expecting info.This should be optional, not mandatory, right?
