### ISSUE TITLE
Indication of recording duration

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#135]
**Is your feature request related to a problem? Please describe.**
When reviewing a list of audio or MIDI recordings, it isn't obvious how long each one is, i.e. its duration. When playing a recording one doesn't know when the recording will end / loop.

**Describe the solution you'd like**
It would be advantageous to display the duration of each recording within the GUI and webconf. This could be appended to the name, e.g. SDC: jack_capture_01 [00:00:23].

**Additional context**
It would be further advantageous to display the current play time during playback but I will raise that as a separate ticket.

**Comment by wyleu** [comment]
Nice idea

**Comment by jofemodo** [comment]
It's already added.
