### ISSUE TITLE
Audio Injector Line Selector Input

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#14]
**Is your feature request related to a problem? Please describe.**
An Audio Injector equipped zynthian requires the Capture Input selected in alsamixer to enable audio input.

**Describe the solution you'd like**
The default state is Input enabled.

**Describe alternatives you've considered**
login in over ptty,
alsamixer 
tab to capture settings . . .
select Input to Line Capture from Line [off,off].

**Additional context**
![image](https://user-images.githubusercontent.com/79083/58396054-efbf4f80-8042-11e9-8f08-ad6f5fd0d40f.png)

**Comment by mheidt** [comment]
I added some code to the webconf already.
Maybe the command needs to be more generic though

**Comment by mheidt** [comment]
@wyleu  
could you provide the generic command?

**Comment by jofemodo** [comment]
Toc toc!! What about this? @wyleu?

**Comment by wyleu** [comment]
It wasn't so much a command as just adding or removing a space on the audio config string to make it update ...Which is a tip mheidt posted somewhere...

I'll set up an audio injector zynth from scratch and see how far I get.

**Comment by wyleu** [comment]
This seems to be a problem again.
Audio Injector zero on zynthian-pedal.local

Starts up but nothing works

**Comment by wyleu** [comment]
Was working before a software update. Now all Audio input has shut down.

**Comment by wyleu** [comment]
cleared down default mixer and that seemed to fix it.
