### ISSUE TITLE
Mixer Menue shows only PCM Poti

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#141]
Hi Jose,

if I call Hardware/audio/Mixer Controls ->(+)
I only see one PCM Controller
![grafik](https://user-images.githubusercontent.com/55761217/76311307-f3ba1680-62d0-11ea-9d27-23ca5e44a190.png)
I have read the wiki but I dont find nearer explanations.
How do I add another controller?

**Comment by jofemodo** [comment]
What sound card do you have? What version of zynthian SD image? etc.
Please, report the full context ...

**Comment by jofemodo** [comment]
A screenshot from the webconf's dashboard is normally enough ...

**Comment by Mickinator** [comment]
It's the same like before.
/home/micki/Downloads/Screenshot_2020-03-10 Zynthian Configuration.png

**Comment by Mickinator** [comment]
![Screenshot_2020-03-10 Zynthian Configuration](https://user-images.githubusercontent.com/55761217/76319048-ea37ab00-62de-11ea-99ce-366525d0f80b.png)

**Comment by jofemodo** [comment]
Send me the output of this command:
`amixer -c 0`
or 
`amixer -c 1`
or
`amixer -c 2`

;-)

**Comment by Mickinator** [comment]
amixer -c 0
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 80 [92%] [-5.25dB] [on]
Simple mixer control 'Headphone',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 87
  Mono:
  Front Left: Playback 87 [100%] [0.00dB] [on]
  Front Right: Playback 87 [100%] [0.00dB] [on]
Simple mixer control 'Speaker',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 87
  Mono:
  Front Left: Playback 0 [0%] [-65.25dB] [off]
  Front Right: Playback 0 [0%] [-65.25dB] [off]
Simple mixer control 'PCM',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 255
  Mono:
  Front Left: Playback 255 [100%] [0.00dB]
  Front Right: Playback 255 [100%] [0.00dB]
Simple mixer control 'Mic',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 31
  Mono:
  Front Left: Playback 0 [0%] [-34.50dB] [off]
  Front Right: Playback 0 [0%] [-34.50dB] [off]
Simple mixer control 'Mic Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 0 [0%] [0.00dB]
  Front Right: 0 [0%] [0.00dB]
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Beep',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 31
  Mono:
  Front Left: Playback 0 [0%] [-34.50dB] [off]
  Front Right: Playback 0 [0%] [-34.50dB] [off]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 63
  Front Left: Capture 39 [62%] [12.00dB] [on]
  Front Right: Capture 39 [62%] [12.00dB] [on]
Simple mixer control 'Auto-Mute Mode',0
  Capabilities: enum
  Items: 'Disabled' 'Enabled'
  Item0: 'Enabled'
Simple mixer control 'Digital',0
  Capabilities: cvolume
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 120
  Front Left: Capture 60 [50%] [0.00dB]
  Front Right: Capture 60 [50%] [0.00dB]
Simple mixer control 'Loopback Mixing',0
  Capabilities: enum
  Items: 'Disabled' 'Enabled'
  Item0: 'Disabled'

**Comment by jofemodo** [comment]
Is it the only soundcard connected to the zynthian?

**Comment by Mickinator** [comment]
Yes, the only soundcard is the behringer uca222. Works without probs.




Gesendet mit der Telekom Mail App
<https://www.telekom.de/unterwegs/apps-und-dienste/kommunikation/telekom-e-mail?wt_mc=alias_9998_unterwegs/apps-und-dienste/telekom-email#mail-app>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-issue-tracking] Mixer Menue shows only PCM 
Poti (#141)
Datum: 14.04.2020, 20:12 Uhr
An: zynthian/zynthian-issue-tracking <
zynthian-issue-tracking@noreply.github.com
<mailto:zynthian-issue-tracking@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Is it the only soundcard connected to the zynthian?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-issue-tracking/issues/141#issuecomment-613597754> 
, or unsubscribe
