### ISSUE TITLE
Can't route output to USB Controllers.

### ISSUE THREAD

**Issue by 1st-BrainStormer** [zynthian/zynthian-issue-tracking#145]
**Describe the bug**
Midi outputs cant be routed to USB devices

If I go to interface>Midi Options>Ports and attach the MIDI out/thru  to any USB device.
it doesn't actually connect it.

Checked with patchage and the a2j box has no connections

**Expected behavior**
If an output is connected in Midi Ports. It should actually be patched to the device.

**Setup:**
 - SD-image: 2020-03-20-zynthianos-buster-lite-1.0.0
 - Hardware Config: V3-Pro
 - Software Version:
zyncoder: master (8759b11)
zynthian-ui: master (4adc29a)
zynthian-sys: master (7869a0f)
zynthian-data: master (9cccef5)
zynthian-webconf: master (288a1a1)

**Comment by riban-bw** [comment]
@1st-BrainStormer Do your MIDI outputs have spaces in their names? There is a bug about this reported in #zynthian/zynthian-issue-tracking/issues/392 .

**Comment by riban-bw** [comment]
Please confirm this is still an issue as I believe the underlying cause is now resolved.

**Comment by jofemodo** [comment]
This should be solved, at less on testing.

**Comment by riban-bw** [comment]
MIDI routing in _oram_ seems to be broken.

Adding a MIDI chain listening on one input device and targetting another output device does not pass MIDI note messages.

**Comment by riban-bw** [comment]
This is now working as expected. You do not use webconf to route MIDI in Oram. Instead, use MIDI input and MIDI output routing in the chain options menu. I have tested routing one MIDI input to an emoty MIDI only chain and routing its output to another MIDI output. This works.
