### ISSUE TITLE
Audio routing not showing correctly after restart

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#148]
**Describe the bug**
Upon restarting a zynthian Audio routing crosses are not appearing in the GUI even thou' the growing is 'correct'

**To Reproduce**
1. Go to Audio Routing expecting to see a connction
2. Non present but routing is enabled as Audio can be heard ( this occurs with zynscope PD ) 

**Expected behavior**
The correct crosses are shown in audio Routing.

**Screenshots**
![image](https://user-images.githubusercontent.com/79083/77944109-47a79200-72b6-11ea-9702-296fdc76dd70.png)

![image](https://user-images.githubusercontent.com/79083/77944205-71f94f80-72b6-11ea-8b25-301bcd27085c.png)

![audio_routing](https://user-images.githubusercontent.com/79083/77944433-e7652000-72b6-11ea-9a04-044c9f46aee7.png)

**Comment by jofemodo** [comment]
Could you update and try again?
Thanks!

**Comment by jofemodo** [comment]
OK! I think this is closed ....
