### ISSUE TITLE
Don't find Audio & Midi Load

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#150]
**Describe the bug**
In Admin-Window is no Audio-& Midi Load function

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version

**Additional context**

**Comment by jofemodo** [comment]
Did you read this topic in the forum:

https://discourse.zynthian.org/t/new-apps-menu-auto-eq-app/3975

;-)

**Comment by Mickinator** [comment]
no, sry, thank you ! 🌈

von Norbert Schreiber gesendet

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-issue-tracking] Don't find Audio & Midi 
Load (#150)
Datum: 03.04.2020, 01:11 Uhr
An: zynthian/zynthian-issue-tracking <
zynthian-issue-tracking@noreply.github.com
<mailto:zynthian-issue-tracking@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Did you read this topic in the forum:

https://discourse.zynthian.org/t/new-apps-menu-auto-eq-app/3975
<https://discourse.zynthian.org/t/new-apps-menu-auto-eq-app/3975>

;-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-issue-tracking/issues/150#issuecomment-608138512> 
, or unsubscribe
