### ISSUE TITLE
Zynthian logo distorted on 2.8 inch V1 Kit

### ISSUE THREAD

**Issue by videobelu** [zynthian/zynthian-issue-tracking#153]
![IMG_20200407_093434](https://user-images.githubusercontent.com/33522308/78644906-f2234480-78b6-11ea-8477-69c7e9cc2031.jpg)

**Comment by jofemodo** [comment]
Try deleting this directory:

`rm -rf /zynthian/config/img`

and reboot.

Regards

**Comment by videobelu** [comment]
> Try deleting this directory:
> 
> `rm -rf /zynthian/config/img`
> 
> and reboot.
> 
> Regards

Ok thanks works fine!!!
