### ISSUE TITLE
Multiband EQ has no output

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#156]
**Describe the bug**
Adding "Multiband EQ to an engine results in silent output.

**To Reproduce**
1. Add a Fluidsynth engine layer
2. Add "Multiband EQ" effect to engine layer
3. Play keyboard

**Expected behaviour**
Sound plays.

**Actual behaviour**
No sound plays.

**Setup:**
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+GPIO 1024x600
Wiring: I2C_HWC
GPIO Expander: Not detected

Raspbian GNU/Linux 10 (buster)
Build Date: 2020-03-28
Memory: 19% (779M/3906M)
SD Card: 38% (9.9G/28G)
Temperature: 33.0ºC

yncoder: i2c_longpress (53d9536)
zynthian-ui: master (f2d6ea6)
zynthian-sys: master (a305ab9)
zynthian-data: master (9cccef5)
zynthian-webconf: master (d72a695)

**Additional context**
`jack_lsp -c` shows no connections to the effect plugin.
Removing the EQ plugin from the chain restores output.

**Comment by jofemodo** [comment]
It seems to take too much for starting ... i will remove it from the default list.
Could you verify if it works with MOD-UI?

Thanks!

**Comment by jofemodo** [comment]
It's removed from the default list.
