### ISSUE TITLE
No temperature indication in webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#160]
**Describe the bug**
Webconf home page does not show temperature reading.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to [webconf](http://zynthian.local)

**Expected behaviour**
Temperature indication is populated.

**Actual behaviour**
Temperature indication shows ???.

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/78948288-adb6c500-7abf-11ea-95ed-3c516c8b5fb9.png)

**Setup:**
See screenshot

**Comment by jofemodo** [comment]
Same here! I can't reproduce this issue. Perhaps this SD image have some hidden errors ...
Please, test a previous SD image updated to the last ... Mine is from 2020-03-05

**Comment by riban-bw** [comment]
I have started zynthian from command line and see the following message every second:
```
ERROR:zynthian_gui: [Errno 2] No such file or directory: 'vcgencmd': 'vcgencmd'
```
/usr/bin/vcgencmd is symbolic link to /opt/vc/bin/vcgencmd but /opt is missing. Was this omitted from the 2020-03-28 build? (I am pretty sure I haven't manually removed it.)

**Comment by riban-bw** [comment]
This issue is not present in 2020-04-09 build. I will close this issue but it may be worth checking if the 2020-03-28 build is broken.
