### ISSUE TITLE
Audio playback crashes Zynthian UI

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#161]
**Describe the bug**
Attempts to playback audio captures result in the UI becoming unresponsive and then the synth engines stopping.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to Audio Recorder
2. Select an audio capture to play

**Expected behaviour**
Audio plays. Zynthian continues to operate.

**Actual behaviour**
Audio does not play. Zynthian encoders stop working. Touch screen and sounds continues for a while but eventually seems to stop.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+GPIO 1024x600
Wiring: I2C_HWC
GPIO Expander: Not detected

 SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-03-28

SOFTWARE
zyncoder: master (11e32fa)
zynthian-ui: master (477ee17)
zynthian-sys: master (a305ab9)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
Zynthian audio recorder screen shows two recordings. Webconf shows three. This issue was first observed immediately after recording the third recording using Zynthian audio recorder. Third recording can be converted / downloaded using webconf.

**Comment by jofemodo** [comment]
Sorry, i can't reproduce here, a Buster from 2020-03-05, updated to the last.
Can anybody else confirm this issue?
Could you reproduce this behavior consistently?

**Comment by riban-bw** [comment]
This happens every time. I restarted Zynthian service about five times with same results. I powered off, left to rest for several hours and powered on with same results.

**Comment by riban-bw** [comment]
`/usr/bin/mplayer: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory`
I wonder if 2020-03-28 build image is bad (and maybe several images - don't know when these issues began). This is the first time I have used audio player since writing this image.

**Comment by riban-bw** [comment]
This is working in 2020-04-09 build. I will close issue but may be worth checking if 2020-02-28 build is broken.
