### ISSUE TITLE
start from new sd-image with buster os

### ISSUE THREAD

**Issue by spurkopf** [zynthian/zynthian-issue-tracking#174]
Using a zynthian V3 and 2020-04-14-zynthianos-buster-lite-1.0.0:
Zynthian won't boot with a new copied image of buster-os. 
In webconf Kit V3 Pro is pre-selected and has to be changed to V3.
Zynthian now boots, but encoders don´t work.
What helped was to change the kit to custom and then selection for wiring layout to Mcp23017 Extra - to make the encoders work.
![grafik](https://user-images.githubusercontent.com/5560755/79596222-b450c800-80cf-11ea-9f57-834c3e5077ed.png)

**Comment by jofemodo** [comment]
Latest images are pre-configured for latest kit version.
