### ISSUE TITLE
Strange screen appears on occasion after GUI event.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#176]
**Describe the bug**
The screen attached appears on occasion. Interface becomes un-responsive. (no GUI function)

**To Reproduce**
Difficult to be specific. Bak from admin has produced the effect

**Expected behaviour**
Normal GUI functionality

Reboot from webconf cures it...

**Screenshots**
![image](https://user-images.githubusercontent.com/79083/79684119-f04a7100-8226-11ea-9be9-a7f6215800db.png)
![image](https://user-images.githubusercontent.com/79083/79684126-fd676000-8226-11ea-92c4-3b94beaf0eca.png)
This is a vnc image but I've seen it on most GUI implemetations.

**Setup:**
![image](https://user-images.githubusercontent.com/79083/79684152-225bd300-8227-11ea-817d-32bda7ab948c.png)

**Comment by jofemodo** [comment]
Is your zynthian updated to the last version? This issue is already known and fixed:

https://github.com/zynthian/zynthian-ui/issues/228

I have not tested if riban's branch has included this fix ...
