### ISSUE TITLE
Exception caused by OSC

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#177]
**Describe the bug**
Starting Zynthian from the command line I see an exception:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./zynthian_gui.py", line 1049, in zyncoder_thread_task
    self.osc_receive()
  File "./zynthian_gui.py", line 261, in osc_receive
    while self.osc_server.recv(0):
AttributeError: 'zynthian_gui' object has no attribute 'osc_server'
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Access Zynthian command line
2. `systemctl stop zynthian`
3. `cd /zynthian/zynthian-ui`
4. `./zynthian_gui.py`

**Expected behaviour**
Application starts with no errors.

**Actual behaviour**
Exception message printed.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

SOFTWARE
zyncoder: master (3513de2)
zynthian-ui: feature/stepseq (ada7af1)
zynthian-sys: master (04e4dec)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
Enable TouchOSC MIDI Bridge is disabled.

**Comment by jofemodo** [comment]
This is not the right way of starting zynthian UI from the command line.
You have to call the "zynthian.sh·" script.

Regards,
