### ISSUE TITLE
capture assign to snapshot

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#180]
**Is your feature request related to a problem? Please describe.**
If you have a gig, you have less time to organice your epuipment. It would be good to need 1 command per song for sound and background-files.

**Describe the solution you'd like**
To assign one capture to one snapshot could be the solution.

**Describe alternatives you've considered**
In a first step it would be fine to recall captures via a midi-command.
E.g. a PC-command with special MSB and LSB

**Additional context**

**Comment by riban-bw** [comment]
It is not clear what is meant by "capture". Are you requesting that the audio inputs for chains be configurable per snapshot?  If so then this is implemented in _oram_ branch (next major release). Audio inputs are saved in ZS3 so can be recalled rapidly within a snapshot or between snapshots.

**Comment by riban-bw** [comment]
I think you are referring to audio player files. You can load an audio file into the audio player then save a ZS3, assigning it a MIDI program change. You can then load a different audio file and save as another ZS3 with a different MIDI program change. Sending MIDI program change will recall the ZS3 and hence the audio file.

I believe the required functionality is already implemented so I will close this ticket. Please reopen and add detail if this is not the case.
