### ISSUE TITLE
Bug after editing Snapshots in Web-UI

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-issue-tracking#182]
**Describe the bug**
Loading of presets is broken after changing the order inside Web-UI.

**To Reproduce**
1.Simply rename and reorder presets in your snapshots. Inbetween also store new snapshots.
2. Make a backup
3. Create a new SD image
4. Restore the data-backup

**Expected behavior**
Load snapshot as expected.

**Screenshots**
...

**Setup:**
```
SD: 2020-04-24-zynthianos-buster-lite-1.0.0.img
 
Hardware:
Raspberry Pi 4 Model B Rev 1.1
Soundcard: HifiBerry DAC+
Display: PiTFT 2.8 Resistive
Wiring: PROTOTYPE-3H
GPIO Expander: MCP23008

Software:
zyncoder: master (c9a395c)
zynthian-ui: master (926af8e)
zynthian-sys: master (cc93f7f)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)
```

**Additional context**
Apr 26 19:04:22 zynthian startx[464]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 836, in load_snapshot
Apr 26 19:04:22 zynthian startx[464]: self.layers[i].restore_snapshot_1(lss)
Apr 26 19:04:22 zynthian startx[464]: IndexError: list index out of range
Apr 26 19:04:29 zynthian startx[464]: ERROR:zynthian_autoconnect: Jack Audio XRUN!
Apr 26 19:04:30 zynthian startx[464]: ERROR:zynthian_autoconnect: Jack Audio XRUN!
Apr 26 19:04:31 zynthian startx[464]: ERROR:zynthian_gui_layer: Invalid snapshot: list index out of range
Apr 26 19:04:31 zynthian startx[464]: Traceback (most recent call last):
Apr 26 19:04:31 zynthian startx[464]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 836, in load_snapshot
Apr 26 19:04:31 zynthian startx[464]: self.layers[i].restore_snapshot_1(lss)
Apr 26 19:04:31 zynthian startx[464]: IndexError: list index out of range

**Comment by jofemodo** [comment]
Are restoring the snapshots on the same image version? If not, how different are both image versions? Have you tried to copy the snapshots by hand?
 
I don't see the relation with editing/renaming ... if you don't edit/rename, does backup/restore works OK?

Thanks!

**Comment by dcoredump** [comment]
I made my snapshots over the last three months and updated regularly, so I cannot say when exactly this happened. I can only say that this happened maybe since the last two or three updates.

I now have created new snapshots and will try the next days what happens...

But: is there a way to get check the consistency of my old snapshots? Or some more information what the problem is (logfiles?)?

**Comment by jofemodo** [comment]
Hi @dcoredump !

Could you tell me something about this issue? Have you reproduced the error again?

Regards

**Comment by dcoredump** [comment]
Hi @jofemodo,

no, currently not. Currently I have other problems found... :-/ But I am not sure if I am the problem or if it's a bug...

I think I will close this. Thanks for asking!

Regards, Holger
