### ISSUE TITLE
Webconf- and UI-Snapshots are not in sync

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-issue-tracking#184]
**Describe the bug**
When storing a snapsho from zynthian-ui and editing the name and the place inside the banks, the new bank/snaphsot layout is not in sync with the zynthian-ui

**To Reproduce**
1. Save s snapshot
2. Edit the name of the snapshot or put it into another bank
3. Take a look at the snapshots in zynthian-ui: No name, no new place

**Expected behavior**
I'd rather they were both in sync.

**Screenshots**
...

**Setup:**
 - 2020-04-23-zynthianos-buster-lite-1.0.0.img
 - Hardware Config:
Raspberry Pi 4 Model B Rev 1.1
Soundcard: HifiBerry DAC+
Display: PiTFT 2.8 Resistive
Wiring: PROTOTYPE-3H
GPIO Expander: MCP23008
 - Software Version:
zyncoder: master (0165831)
zynthian-ui: master (04cb642)
zynthian-sys: master (c6ea736)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**

**Comment by jofemodo** [comment]
Sorry Holger, i can't reproduce the problem.
I've been testing by renaming snapshots, creating new banks and moving presets. Everything works fine and Zynthian UI get changes.
Of course, if you are inside the UI's snapshot menu (load/save), you have to re-enter to get updated the list. Getting this kind of sync will require Zynthian-UI polls the snapshot dir contents all the time. I could do it easily, but i don't think this is really needed, or yes? ;-)

**Comment by dcoredump** [comment]
Ok, it seems to be a problem with my browser. Going back and entering again on the Zynthian works. The strange thing (with my browser) seems to be: It does not show updates when editing (names, bank-numbers, ...). Only "reloading" with selecting Snapshots from the menu seems to help.
(I am using the latest FF on Linux. I tried Chromium, but it seems that Chromium did not resolve *.local addresses).

**Comment by dcoredump** [comment]
Thanks @jofemodo !
