### ISSUE TITLE
Touchscreen calibration easy to launch process

### ISSUE THREAD

**Issue by MrDham** [zynthian/zynthian-issue-tracking#188]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the pointer position is not consistent with the stylus. Particularly when I am using the step sequencer or the admin menu and that I trigger wrong note or menu option. 

**Describe the solution you'd like**
As a standard kit user, I would like to be able to launch easilly a calibration process of the touchscreen so as I can increase consitency of pointer and stylus position. 
By "launch easilly" I mean from admin menu or with a simple command line described in the wiki.  

**Describe alternatives you've considered**
I look at the process described here: https://ozzmaker.com/enable-x-windows-on-piscreen/
but it is beyond non technical user's skill. 

**Additional context**
standard kit V2,V3,...

**Comment by jofemodo** [comment]
We have advanced with this issue. See this thread:

https://discourse.zynthian.org/t/could-this-be-the-end-of-all-touch-screen-calibration-issues/4167

**Comment by jofemodo** [comment]
This is implemented now ...
