### ISSUE TITLE
Zynthian without sound board fails to runable gui interface

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#19]
**Is your feature request related to a problem? Please describe.**
When A Zynthian can detect no sound card it fails to boot.

**Describe the solution you'd like**
Upon the lack of detection of a sound card the Interface should boot into a GUI only mode that displays this limited status in the Status area of the GUI. If the encoder board is still detected Jack should be raised to support the MIDI interfaces available.

MIDI or OSC can then be used to remotely control an other zynthian entity on the network.

**Describe alternatives you've considered**
Always provide an Audio infrastructure at all zynthian instances.

**Additional context**
This is an issue that exists outside the standard zynthian implementation but allows the base omponents of a distributed midi surface network.

Advantages: Sound rendering of both Zynthian generated and external contributed material can be routed conveniently whilst control surfaces & All in One boards can acquire and distribute MIDI data from the performance area and route control over Ethernet implementation.

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (4a1e025) 
zynthian-sys: master (09e8d3e) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (61986dc)

**Comment by jofemodo** [comment]
Have you tried to use the "dummy" device from the webconf audio config?

**Comment by mheidt** [comment]
Shouldn't we change the config to dummy, when it doesn't find a soundcard?

**Comment by jofemodo** [comment]
Detecting the soundcard is not "so easy" in a RBPi-like computer. There is no "plug&play" features, so configuration is normally done by hand. If someone knows how to do it, i will be very pleased of implementing this feature. Until then, if you want a Zynthian without soundcard, you have to configure the "dummy" device by hand. It's not so difficult!!! ;-)
