### ISSUE TITLE
ERROR:zynthian_gui: 'NoneType' object has no attribute 'getPeak'

### ISSUE THREAD

**Issue by pierre-girbon** [zynthian/zynthian-issue-tracking#190]
**Describe the bug**
ERROR:zynthian_gui: 'NoneType' object has no attribute 'getPeak'

**To Reproduce**
- update_zynthian.sh
- systemctl stop zynthian
- mv zynthian/zynthian-ui zynthian/zynthian-ui.origin
- git clone https://github.com/zynthian/zynthian-ui.git
- /zynthian/zynthian-sys/sbin/zynthian.sh

**Expected behavior**
No error should occur

**Screenshots**
Error Log
`ERROR:zynthian_gui: 'NoneType' object has no attribute 'getPeak'
Traceback (most recent call last):
  File "./zynthian_gui.py", line 1411, in refresh_status
    self.status_info['peakA'] = lib_jackpeak.getPeak(0)
AttributeError: 'NoneType' object has no attribute 'getPeak'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./zynthian_gui.py", line 1138, in zyncoder_thread_task
    self.osc_receive()
  File "./zynthian_gui.py", line 275, in osc_receive
    while self.osc_server.recv(0):
AttributeError: 'zynthian_gui' object has no attribute 'osc_server'
`

**Setup:**
 - Zynthian v3

**Additional context**

**Comment by le51** [comment]
Maybe jackpeak isn't working as it should or even is not installed at all.
You can try to build it again by running from command line
`/zynthian/zynthian-ui/jackpeak/build.sh`

**Comment by jofemodo** [comment]
Yes, @le51 is right. Your procedure is not complete. When cloning a new UI repository you have to build the jackpeak (and the zynseq, if it includes the new StepSequencer library)

```
/zynthian/zynthian-ui/jackpeak/build.sh
/zynthian/zynthian-ui/zynseq/build.sh

```
Thanks!

**Comment by pierre-girbon** [comment]
Thanks for your feedback!
I got my first sounds with Sfizz ;-)
