### ISSUE TITLE
Snapshot doesn't load

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#193]
**Describe the bug**
If i try to load a snapshot the load process stops without loading the snapshot.

I send BF 00 05, BF 20 05, CF 01 but it stops every time

**Expected behavior**
If I send a PC Command with MSB and LSB Zynthian should load the wanted Snapshot

 ##

**Screenshots**

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version

**Additional context**

**Comment by jofemodo** [comment]
Please, try to be more detailed when reporting an issue.
+ Did your snapshot load from the UI?
+ Could you show how your snapshot is configured from the webconf?
+ What about your image version?
+ Your hardware?
+ Is it updated to the last?
+ etc.

Thanks!

**Comment by Mickinator** [comment]
Ok, I will build the snapshots again, from the scratch.😥🌈
