### ISSUE TITLE
Pressing back button triggers error - effectively locking up device

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#194]
**Describe the bug**
Pressing the BACK button too many times can lead to Zynthian going to a blank screen and being unresponsive.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Zynthian from command line - Zynthain starts and shows engine control screen, e.g. setBfree
2. Press BACK button twice to reach Main screen
3. Press BACK button once more

**Expected behaviour**
Navigation to engine control screen.

**Actual behaviour**
Grey overlay of black screen without any controls or text. System unresponsive.

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/81260969-0fbd0880-9033-11ea-9827-061144c9c3cb.png)

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

SOFTWARE
zyncoder: master (3513de2)
zynthian-ui: feature/stepseq (ee83380)
zynthian-sys: master (04e4dec)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

(Same behaviour with current master zynthian-ui.)

**Additional context**
Output from command line:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 671, in cb_keybinding
    self.zyngui.callable_ui_action(action)
  File "./zynthian_gui.py", line 721, in callable_ui_action
    self.zynswitch_short(1)
  File "./zynthian_gui.py", line 998, in zynswitch_short
    self.show_screen(screen_back)
  File "./zynthian_gui.py", line 399, in show_screen
    self.screens[screen].show()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 73, in show
    super().show()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 220, in show
    self.fill_list()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 89, in fill_list
    if len(self.layers)==0:
TypeError: object of type 'NoneType' has no len()
```
I thought I had already reported this but can't find the ticket. This is really bugging me.

**Comment by jofemodo** [comment]
@riban-bw , this has been solved a few days ago. In master it works perfectly.
Please, check that you have correctly merged the changes from master ...

**Comment by jofemodo** [comment]
Check this:

https://github.com/zynthian/zynthian-ui/issues/228

And you already reported the bug (duplicated):

https://github.com/zynthian/zynthian-issue-tracking/issues/178

Thanks ...
