### ISSUE TITLE
WIFI doesn't work

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#195]
**Describe the bug**
If I try to start WIFI Zynthian says "Can+ t start WIFI network".
If I try to start WIFI via WebConf  it switches back to "off" after a while.

Screenshot doesn' t work
R4, B, Rev  1.1
Behringer UCA 222
WaveShare 5 HDMI + GPIO

**Comment by jofemodo** [comment]
Sorry, i can't reproduce your issue.
Have you configured some wifi network? What SSID are you using? 
Please,you have to be a lot more explicit when reporting issues.

Thanks!

**Comment by Mickinator** [comment]
That's the point: I do not know, what I can say.
Other Wifi-Components show their name if they are switched on.
But I Can't switch on zynthian. Zynthian says :"Can' t start Wifi network."
Ans so I do not find a SSID.

Is there a tutorial how to open a zynthian Wifi network?
This morning I tried to copy screenshots to the issue, but it was not possible ....

**Comment by Baggypants** [comment]
1. In the Web config on the WIFI page you need to click **Add Network**
2. On the next screen choose the SSID from the dropdown and enter the passord.
3. Click Add 
4. Enable wifi from the zynthian screen or in the Web Config set mode to **On**.

**Comment by Baggypants** [comment]
I've also updated the wiki https://wiki.zynthian.org/index.php/Configuration_Users_Guide#WIFI

**Comment by jofemodo** [comment]
Thanks a lot, @Baggypants !
