### ISSUE TITLE
Cannot load sf2-soundfonts

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#199]
**Describe the bug**
With Raspi 3B Soundfont upload doesn't work.

**To Reproduce**
In Webconf  Library/Preset & Soundfonts/Fluitsynth/Upload/click&Choose/"Name.sf2"/Return
After upload Zynthian Reboot 
in Zynthian Layers: Remove all Layers
New Synth Layer
FluidSynth - SF2 Player
Midi CH#1
Choose "My/Name".
        Normally now the wave runs and the soundfont will be loaded. But nothing happens. No sound.

**Expected behavior**
The sound should be hearable by playing the keys.

![Screenshot_2020-05-19 Zynthian Configuration](https://user-images.githubusercontent.com/55761217/82309406-60354e00-99c3-11ea-9a70-ebd5236c2103.png)

The system is updated. Iv'e tried some fonts. The upload of sf2-fonts works on raspi4.

**Comment by jofemodo** [comment]
Please, send me the soundfont giving the problems. If i can't reproduce the problem, i can't solve it.
I remember having said that in the past ...

**Comment by Mickinator** [comment]
No problem. I've said in the post, that I tried some fonts.
Please use "FluidR3_GM.sf2", because this chat doesn' t
transport files bigger than 10MB.

**Comment by jofemodo** [comment]
Please, try with a recent SD image. 

Thanks!

**Comment by Mickinator** [comment]
Ok, I' ve tried, it works. Thank you!
