### ISSUE TITLE
Add Yeti Microphone to Audio hardware options

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#203]
**Is your feature request related to a problem? Please describe.**
Add the Yeti Microphone as an Audio Hardware option

**Describe the solution you'd like**
I want the Yeti Microphone to be available as a zynthian standard device listed in webconf.

![image](https://user-images.githubusercontent.com/79083/83356754-05570b80-a360-11ea-97b0-0d358af17c38.png)

**Describe alternatives you've considered**
Configuring by hand. generally from info on the zynthian forum.

**Additional context**
One of many devices...
Set to 48000 do we have a default for this ?

**Comment by jofemodo** [comment]
I just merged your PR!! Thanks!
