### ISSUE TITLE
dropdown to choose between mounted usb sticks and sdcard

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#208]
**Is your feature request related to a problem? Please describe.**
As I use internal usb stick as music and record storage, I want to be able to just upload music/records without the struggle of usb stick dis-/connection.

**Describe the solution you'd like**
there is already a function to upload files in webconf, but if sd card is full, you cannot upload anything.

With just a little dropdown to choose between mounted usb stcks and sdcard, you would be able to upload more.

**Additional context**
I have a buildin usb sd card reader with 128GB sd, and just 16GB sd as boot.

**Comment by sehrgut** [comment]
I'd like this as well, since I would like to have separate USB drives for recording and for my soundfonts.

**Comment by riban-bw** [comment]
There are a couple of different but related features here.

- Target where presets are saved
- Target where recordings are made

These are both similar and work is in progress to implement this functionality. It is likely to use banks to identify file locations.
