### ISSUE TITLE
Fluidsynth shared outputs - adding effects gives unexpected behaviour

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#215]
**Describe the bug**
When using many fluidsynth layers the same fluidsynth engine is reused but with limited outputs which can result in limitations and unexpected behaviour when adding audio effects to layers.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add fluidsynth layers on channels 1 - 16 (fewer may also trigger issues)
2. Add effect to output of layer 1 - effect applied to layers 1 & 9
3. Add effect to output of layer 9 - effect has no input routed

**Expected behaviour**
Each layer may have own effects chain.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09
Memory: 9% (353M/3906M)

SOFTWARE
zyncoder: master (2703237)
zynthian-ui: master (964c746)
zynthian-sys: master (7f30365)
zynthian-data: zynseq (548d68a)
zynthian-webconf: master (9eb269b)

MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: off
Single Active Channel: off
ZS3 SubSnapShots: off

**Additional context**
Described behaviour is for a RPi4. Code review shows behaviour will differ for RPi3. A single fluidsynth engine is created with 8 (or 4) outputs and those outputs are reused as necessary. This is a reasonable resource saving approach but it should be evident to the user what limitations may occur. Also effects should not be created if they are not used. (Example above results in an orphaned effect which feeds main output but has no input.

I wonder if there is a workflow where shared outputs are identified within the user interface and effect chain sharing is explicit, e.g. editing the chain for any shared output shows the same effect chain?

Another alternative would be to not share outputs and create another instance of fluidsynth as required or replace existing instance with new instance with more outputs.

**Comment by jofemodo** [comment]
Fluidsynth has some basic internal effects (reverb and chorus) that have to be created on startup. I mean, when you start fluidsynth, you have to create as many audio channels & groups as you intend to use, and effect instances are created for every channel/group, consuming CPU, although you don't use all channels.
I've tried to create 16 channels/groups, but CPU usage is too high, so i decided to create only a few of them  (depending on the available CPU power: RBPi3 => 4 / RBPi4 => 8) and share them across layers.

I think we have 3 options to "improve" the current behaviour:

+ Limit the number of fluidsynth layers you can create to the number of available channels/groups => You are limited, but we would avoid inconsistent behaviour when creating more layers than avaialble channels/groups.
+ Disable internal effects on fluidsynth => You have to add your desired effects to the chain
+ Run per-layer fluidsynth instances => Soundfonts are not shared across instances and load time & memory consumption will increase, specially when using GM soundfonts like FluidR3 on several layers.

I prefer option 1 because it's the easier to implement and the other two options have their own drawbacks too.

Regards

Regards,

**Comment by riban-bw** [comment]
Fluidsynth internal effects are not great so I would not lament their loss but you are correct that they are convenient and some users may quite like that, especially if they only use Fluidsynth. I don't understand how the internal effects are routed. I observe that you create twice as many effects outputs as MIDI channels which I assume is one output for reverb and one for chorus for each channel. I would have guessed (but maybe incorrectly) that the default behaviour for Fluidsynth would be to mix the effects with the output if no specific effects outputs were defined. Anyway, I concur that we should probably leave the Fluidsynth effects intact but if these are adding significant CPU overhead yet seldom used then maybe we should disable. (The first thing I do when I create a Fluidsynth layer is turn down the effects and am reminded how silly it is that chorus defaults to 2!!!)

I am not particularly pleased with limiting the Fluidsynth layers to 8 (4 on RPi3). I have use cases where I use all 16 channels, e.g. playing a .mid file expecting GM sounds, it is simple to just load up a full compliment of Fluidsynth layers with a GM soundfont.

I don't think we should run an instance of Fluidsynth per layer. This is very wasteful and I believe Zynthian will struggle with a full compliment of 16 instances, each with its own copy of a soundfont. It feels like that solution would be reducing the ability to implement the workflow it was supposed to enable.

Some suggestions for consideration:

- Create an instance with current configuration (4/8 outputs) for each set of layers, e.g. one instance for 1-8 layers, 2 instances for 9-16 layers (or RPi3, one for 1-4, two for 5-8, three for 9-12, four for 13-16).
- Create an instance with current configuration (4/8 outputs) for first set of layers then recreate instance for further layers with appropriate outputs, e.g. create an instance with 8 outputs for 1-8 layers then when ninth layer is requested, create a new Fluidsynth instance with 9 outputs, etc. The behaviour of this would need to be considered by performance artist as a switch of snapshot may be more intrusive but for most use cases (few Fluidsynth layers) it may not impact.
- Have a parameter within engine editor to enable effects which would re-instantiate the engine so not for live performance change but allows configuration of layer to suit user's requirements at design time whilst scaling resource usage gracefully.
- Document the limitation of output sharing. This may prove irksome as users seldom read documentation and the pairing may appear inconsistent, e.g. a user who has a piano on channel 2 and percussion on channel 10 may find they share an effects chain under some configurations. This could become rather difficult to understand for the user.
- Provide a method of driving one Fluidsynth instance from multiple MIDI channels, all sending to same audio output. (Maybe MIDI channel cloning or rules does similar.) This does not resolve the issue in hand but if a user understands that they have a limited quantity of audio output chains but can control different instruments on some of the same outputs it may provide sufficient flexibility, e.g. MIDI channels 1 & 2 driving piano and organ on output (layer) 1 which may have a reverb inserted and MIDI channel 10 driving drums on output 2 which might have a compressor inserted. This would give some flexibility with some constraints. It might prove tricky to maintain (and does not resolve my underlying issue that I have not yet mentioned - how to control each audio from zynmixer) but is an option worth considering.
- Some indication within the layer management of how outputs are shared, e.g. two instruments sharing an output might be indicated as sublayers of the same layer. This adds additional hierarchy to the layers which may prove challenging to code and present in the UI.

I believe we need to provide a method of having 16 channels of Fluidsynth, ideally each with its own output but if not, some indication or explanation of the rules of how layers map to outputs.

**Comment by jofemodo** [comment]
This has been solved recently by removing the internal FXs on fluidsynth. No more "shared" audio channels ;-)
