### ISSUE TITLE
No captures listed in webconf if no sdcard used

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-issue-tracking#219]
**Describe the bug**
If you boot from usb without an sd card and record audio then the webconf doesn't show the wav file

**To Reproduce**
1. Set p boot from usb
2. record audio for Wylieu
3. go to captures in webconf

**Expected behavior**
Should list recording in webconf.

**Comment by Baggypants** [comment]
Also it mount's root and boot partitions under /media which results in recordings ending up in the root of the filesystem :smile:

**Comment by Baggypants** [comment]
```
root@zynthian:/media/usb0# mount | grep sda
/dev/sda2 on / type ext4 (rw,noatime)
/dev/sda2 on /media/usb0 type ext4 (rw,nodev,noexec,noatime,nodiratime)
/dev/sda1 on /media/usb1 type vfat (rw,nodev,noexec,noatime,nodiratime,sync,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
/dev/sda1 on /boot type vfat (rw,relatime,sync,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
```

**Comment by jofemodo** [comment]
I think this is solved!
