### ISSUE TITLE
Unable to load fluidsynth

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#226]
**Describe the bug**
Attempting to load fluidsynth layer fails.

**To Reproduce**
1. Go to Layers
2. Click on Engine FluidSynth
3. Select MIDI channel 
4. See list of files
5. Select either and press
6. List is still displayed but you see no Instruments.

**Expected behavior**
No layer loaded ...

UI give.s
![image](https://user-images.githubusercontent.com/79083/87950181-dd9e3d00-ca9e-11ea-9f65-1f3ab687f81f.png)

![image](https://user-images.githubusercontent.com/79083/87950537-52717700-ca9f-11ea-9a15-1ba311c9945f.png)

**Screenshots**

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
![image](https://user-images.githubusercontent.com/79083/87950614-72089f80-ca9f-11ea-9052-64040897ac75.png)

**Additional context**
I'm hoping to demo this machine later today :-D

**Comment by jofemodo** [comment]
This Buster SD-image has a known and already fixed bug on fluidsynth, More recent buster SD-images work OK!
