### ISSUE TITLE
Unable to hide cursor

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#227]
**Describe the bug**
Using HDMI output the mouse cursor is constantly displayed. Attempts to hide using webconf fail.

**To Reproduce**
1. Boot Zynthian
2. From webconf navigate to Iterface->UI Options
3. Deselect, "Enable cursor"
4. Save settings

**Expected behaviour**
Mouse cursor is hidden.

**Actual behaviour**
Mouse cursor is displayed.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: Behringer UMC404HD
Display: WaveShare 7 HDMI+USB
Wiring: DUMMIES
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 4% (189M/3906M)
SD Card: 36% (9.5G/28G)
Temperature: 39.0ºC

SOFTWARE
zyncoder: master (2703237)
zynthian-ui: master (8a46ae2)
zynthian-sys: master (7e38436)
zynthian-data: master (8b13619)
zynthian-webconf: master (e20d5b8)

**Additional context**
This follows a fresh install of [ZynthianOS "Aruk Buster" RC-2](https://os.zynthian.org/2020-05-27-zynthianos-buster-lite-1.0.0-RC2.zip) and continues to occur after a full update and several reboots.

**Comment by riban-bw** [comment]
@riban-bw please retest with current stable release.

**Comment by jofemodo** [comment]
It works, right?
