### ISSUE TITLE
Zynthian webconf truncates JALV URL

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#23]
The URL is truncated in Zynthian webconf even on screens with sufficient horizontal resolution to display the whole URL.

**To Reproduce**
1. Within web browser (e.g. Chrome) navigate to http://zynthian.local/api/sw-jalv-lv2

**Expected behaviour**
Table of JALV plugins displayed

**Actual behaviour**
Table of JALV plugins has _URL_ column truncated, e.g. http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidBass...

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/59155740-3ae85200-8a88-11e9-9a8e-0dcc0c2bef9c.png)

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (4a1e025) 
zynthian-sys: master (09e8d3e) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (61986dc)

**Comment by mheidt** [comment]
this is on purpose and realized with css.
I would suggest or tooltip that shows the complete string

**Comment by mheidt** [comment]
What about making it a link? Although most of them won't work.
