### ISSUE TITLE
Nightly build failures since 2020/07/20

### ISSUE THREAD

**Issue by smiths73v3** [zynthian/zynthian-issue-tracking#231]
**Describe the bug**
Jenkins nightly build failure: 
/bin/mv: cannot stat 'Pianoteq*': No such file or directory
or
losetup: 2020-05-27-raspios-buster-lite-armhf.img: failed to set up loop device: No such file or directory

**To Reproduce**
1. Go to https://jenkins.zynthian.org/job/ZynthianOS/#build#/parsed_console/
2. Click on Error(1)
3. See error /bin/mv: cannot stat 'Pianoteq*': No such file or directory
  or
  losetup: 2020-05-27-raspios-buster-lite-armhf.img: failed to set up loop device: No such file or directory

**Expected behavior**
Successful nightly build

**Screenshots**
N/A

**Setup:**
N/A

**Additional context**

**Comment by jofemodo** [comment]
This is not strange. Sometimes some change in some package breaks automatic builds and we lost some days of nightly builds.It can take some days to detect and fix the problems. It's not always a priority to have a working nightly build every day.
