### ISSUE TITLE
Subsnapshot takes seconds to change when in single channel mode

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#235]
**Describe the bug**
A workflow may be to have a single keyboard feeding Zynthian on a single MIDI channel and to select subsnapshots using that keyboard's MIDI program selector. This works to some extent, selecting the right engine and preset but it takes more than a second before the changes occur.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure Zynthian for "Single Channel Mode" and "Program Change ZS3"
2. Add two synth layers
3. Add subsnapshot for a preset on each synth layer
4. From external MIDI controller send program changes to select each of the subsnapshots

**Expected behaviour**
Selection of each preset is instant.

**Actual behaviour**
Selection of each preset takes over a second with previous instrument continuing to be playable until change occurs.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: Behringer UMC404HD
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09
Memory: 4% (178M/3906M)
SD Card: 38% (10G/28G)
Temperature: 52.0ºC

SOFTWARE
zyncoder: master (9b8de4f)
zynthian-ui: master (bb888fc)
zynthian-sys: master (f398d09)
zynthian-data: master (8b13619)
zynthian-webconf: master (e671cad)

**Additional context**
The wiki describes subsnapshots as a method to instantly change preset without the overhead and delay of loading a new snapshot. This delay occurs even if the layer already has the preset selected and user expectation is to change the active layer.

**Comment by jofemodo** [comment]
For me it's working like a charm. ZS3 changes are almost instant. Could you give me details about engines and presets?
Also, could you verify that your controller is sending the PC message wihout delay? Check the MIDI log ...

**Comment by riban-bw** [comment]
I have monitored MIDI and observe:

```
CH#02 PITCHWHEEL 0
CH#02 CONTROL_CHANGE 1 => 0
CH#02 CONTROL_CHANGE 12 => 0
CH#02 AFTERTOUCH 0
CH#02 CONTROL_CHANGE 4 => 127
CH#02 CONTROL_CHANGE 7 => 96
CH#02 CONTROL_CHANGE 91 => 4
CH#02 CONTROL_CHANGE 94 => 64
CH#02 CONTROL_CHANGE 64 => 0
CH#02 CONTROL_CHANGE 1 => 0
CH#02 CONTROL_CHANGE 67 => 0
CH#02 CONTROL_CHANGE 70 => 0
CH#02 CONTROL_CHANGE 71 => 0
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 CONTROL_CHANGE 22 => 64
CH#02 NOTE_ON 60, Vel: 88
CH#02 PITCHWHEEL 0
CH#02 NOTE_OFF 60, Vel: 64
CH#02 NOTE_ON 60, Vel: 104
CH#02 PITCHWHEEL 0
CH#02 NOTE_OFF 60, Vel: 64
```

The first few messages are printed quite quickly (probably resulting from the initial program change message) then about a second later the rest of the messages (probably triggered by content of the subsnapshot). Playing a single note at half second intervals I hear two or three more instances of previous instrument before new instrument sounds.

I observe lots of duplicate content in the MIDI log.

Layers:
- 1#FS > TimGM6mb/Piano 1 (switching to Piano 2 on program change)
- 2#BF/Sin > Upper/Blues 1 (switching to Blues 2 on program change)

ZS3 configured for program change for two presets for each of two layers.

I tried with VZ-1 direct MIDI and python command via RTP-MIDI and both gave similar results. I notice that changes from program 1 to program 2 doesn't seem to have such a large effect but changing between programs 64 and 65 does. (That might be relevant or might be different preset configurations causing issue.)

**Comment by jofemodo** [comment]
Sorry @riban-bw, I can't reproduce the issue. I've replicated exactly the same layer/ZS3 structure, but it works perfectly for me, with ZS3 changing almost instantly in all cases. Please, consider other possibilities and try monitoring the MIDI stream before the zynmidirouter (use the select on top-left of MIDI log)

Regards,

**Comment by jofemodo** [comment]
Hi @riban-bw !
Please, could you re-check this issue? I can't reproduce ...

**Comment by riban-bw** [comment]
I think this might be due to some patches taking longer to load than others. The effect is clearly evident when changing between patches in ZynAddSubFX with low number patches (1,2,3,etc.) changing quickly whilst high number patches (63,64,65) taking longer. It is not evident for small soundfonts within Fluidsynth. I will close the issue and work around the issue somehow.

**Comment by jofemodo** [comment]
Some ZynAddSubFX presets takes several seconds to load. We have no control over this. ZynAddSubFX is a really complex beast and loading some presets implies pre-calculating lots of data.
