### ISSUE TITLE
Wrong preset title displayed when ZS3 selected

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#236]
**Describe the bug**
When switching between subsnapshots the sound changes but the preset name does not.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure Zynthian for "Single Channel Mode" and "Program Change ZS3"
2. Add two subsnapshots for the same layer
3. Send program change from external MIDI controller to select each subsnapshot

**Expected behaviour**
The preset changes and displays the correct preset name

**Actual behaviour**
The preset changes and but displays the same preset name

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: Behringer UMC404HD
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09
Memory: 4% (178M/3906M)
SD Card: 38% (10G/28G)
Temperature: 52.0ºC

SOFTWARE
zyncoder: master (9b8de4f)
zynthian-ui: master (bb888fc)
zynthian-sys: master (f398d09)
zynthian-data: master (8b13619)
zynthian-webconf: master (e671cad)

**Additional context**
I assume the correct preset parameters are selected. I did not test - I just noticed the sound changed but not the display name.

**Comment by jofemodo** [comment]
This work perfectly for me. Could you give me details about engines and presets?

**Comment by jofemodo** [comment]
BTW, are you using the master branch?

**Comment by riban-bw** [comment]
Although I can reproduce this with the previously saved snapshot, I cannot reproduce from scratch. I have added the snapshot to this ticket. It has two layers. Sending program change 64 initially selects "2#BF/Sin > Upper/Blues 2" but if you send program change 66 to select "2#BF/Sin > Upper/ELP (Keith Emerson)" subsequent program change 64 will change the sound but not the title.

[017-ZSS TEST.zip](https://github.com/zynthian/zynthian-issue-tracking/files/5027630/017-ZSS.TEST.zip)

I am using master branch as detailed in the issue report.

**Comment by jofemodo** [comment]
I suppose you saved this snapshot before i fixed the "favorites" bugs, what could be related with this issue, specially if some of the ZS3 used a preset marked as favorite. If you can't replicate the problem in a fresh snapshot, i would close the issue.
