### ISSUE TITLE
Common automagic method to build zyngui libraries

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#237]
**Is your feature request related to a problem? Please describe.**
Each time a new library is added to zynthian-ui, e.g. zynstep, the `update_zynthian_code.sh` needs to be updated in the zynthian-sys repository. This makes it difficult to create and test feature branches.

**Describe the solution you'd like**
It would be advantageous to have a build step in `update_zynthian_code.sh` which builds **all** zyngui libraries.

**Describe alternatives you've considered**
Developers create branches in both zynthian-ui and zynthian-sys repositories for a single feature which is suboptimal.

**Additional context**
I will create branches and PRs to implement this feature.

**Comment by riban-bw** [comment]
I have implemented this in https://github.com/zynthian/zynthian-sys/pull/173 and https://github.com/zynthian/zynthian-ui/pull/281. If lib source code is placed in own directory within `/zynthian/zynthian-ui/zynlibs` and has `build.sh` file then it will be found and built by `/zynthian/zynthian-sys/scripts/update_zynthian_code.sh`.

I believe this will improve testing, e.g. users have recently been unable to test zynmixer because the library is not being built.

**Comment by jofemodo** [comment]
Hi @riban-bw !
I don't forget this, including the 2 PRs. I tool a look and it seems OK, so ... give me some days for testing and i will merge, OK?

**Comment by jofemodo** [comment]
Tested and merged! ;-)

Thanks a lot!
