### ISSUE TITLE
Webconf: Select Kit=custom gives 500 internal error

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#24]
Selecting custom kit in the webconf gives an error.

**To Reproduce**
1. Within web browser (e.g. Chrome) navigate to http://zynthian.local/api/hw-kit
2. Select "Custom" from "Kit" selector
3. Click "Save£

**Expected behaviour**
Kit selection is saved

**Actual behaviour**
500: Internal Server Error

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (4a1e025) 
zynthian-sys: master (09e8d3e) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (61986dc)

**Comment by mheidt** [comment]
solved

**Comment by mheidt** [comment]
i cannot close issues

**Comment by riban-bw** [comment]
Thanks for prompt fix. Closing as now resolved.
