### ISSUE TITLE
midifilter/passthru ("MIDI Thru") LV2 plugin only functions as a MIDI FX layer when in foreground

### ISSUE THREAD

**Issue by sehrgut** [zynthian/zynthian-issue-tracking#243]
**Describe the bug**
When I create a MIDI FX layer with the "MIDI Thru" LV2 plugin (midifilter/passthru), it only routes MIDI messages to hardware MIDI OUT when in the foreground.

**To Reproduce**
1. Create a MIDI FX layer using "MIDI Thru" on ch1 and set it to clone to ch2.
2. Create a synth layer on ch2.
3. Connect an external MIDI synth to hardware MIDI OUT, listening on ch1.
3. Bring MIDI Thru layer to foreground
4. Play MIDI on ch1 through hardware MIDI IN.
5. Press "Layer" to bring synth layer to foreground.
6. Play MIDI on ch1 through hardware MIDI IN.

**Expected behavior**
Both the synth layer on ch2 and the external synth on ch1 should play whatever notes are played at MIDI IN.

**Observed behavior**
The synth layer plays whether or not it is in foreground, but the external synth only plays when the MIDI Thru layer is in foreground.

**Setup:**
 - Buster RC2
 - Kit v4
 - updated as of 7 aug 2020

**Comment by jofemodo** [comment]
Is enabled the Single Active Channel mode?
Try disabling It ;-)

**Comment by jofemodo** [comment]
I would like to find a better name for this, but I don't like the "omni on/off", because most of people don't insertando this. But the current name is not clear enough.

**Comment by sehrgut** [comment]
Oh! Okay, that was it. I couldn't find anything in the wiki explaining what "single channel mode" was, so I left it at its default. Another page I could create, I suppose, when I figure it out.

And ya, I wouldn't call it omni either, because omni means responding to all channels already in midi-land, but doesn't mean anything about how the target device interprets it. I would seriously suggest "Single-Layer Mode" though, since that expresses what it is, while "single channel" is kinda a side-effect of a single layer reading from a single midi channel, and made me think it was simply reading a s
