### ISSUE TITLE
Cannot set any hardware parameters in webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#25]
The parameters for Audio, Display and Wiring cannot be adjusted.

**To Reproduce**
1. Within web browser (e.g. Chrome) navigate to http://zynthian.local/api/hw-audio (or http://zynthian.local/api/hw-display or http://zynthian.local/api/hw-wiring)
2. Attempt to adjust any parameter, e.g. Soundcard (select custom kit for enable):

**Expected behaviour**
Selection may be adjusted

**Actual behaviour**
Selection is read-only

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (4a1e025) 
zynthian-sys: master (09e8d3e) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (61986dc) 

**Additional context**
This is related to issue #24. It seems that a recent modification to webconf constrains entry of hardware parameters if a "Kit" is configured but it is not currently possible to select "Custom" kit which makes it impossible to configure a custom Zynthian.
**This renders the Zynthian unusable.**

**Comment by mheidt** [comment]
Is this still valid after I fixed the other issues?

**Comment by riban-bw** [comment]
Thanks for prompt fix. Closing as now resolved.
