### ISSUE TITLE
vcgencmd missing from Buster-RC2

### ISSUE THREAD

**Issue by sehrgut** [zynthian/zynthian-issue-tracking#250]
**Describe the bug**
zynthian_gui.refresh_status tries running vcgencmd every couple of seconds and fails to find vcgencmd

**To Reproduce**
1. Boot from a Buster-RC2 SD card
2. run `journalctl -f`
3. Observe the `ERROR:zynthian_gui.refresh_status: [Errno 2] No such file or directory: 'vcgencmd': 'vcgencmd'` errors

**Expected behavior**
I expect vcgencmd to be found.

**Setup:**
 - Buster-RC2
 - Raspberry Pi 4 8GB
 - Software Version:
    - zyncoder: master (9b8de4f)
    - zynthian-ui: master (529760c)
    - zynthian-sys: master (ed1f8b8)
    - zynthian-data: master (20e7da0)
    - zynthian-webconf: master (4b49125)

**Comment by jofemodo** [comment]
Curious ...
Could you check if the error is also present in a fresh-burned (not updated) RC-2 image?

Regards,

**Comment by sehrgut** [comment]
I have a spare SD card coming, but it's delayed because of postal issues in my country. I'll revisit this as soon as I get it! I don't want to disrupt my live image now that I have a pianoteq activation on it.

**Comment by sehrgut** [comment]
I installed ext4fuse so I could mount the Buster-RC2 image on my desktop, and can confirm vcgencmd is preset on the image.

```
Tue Aug 11 12:03:40 tmp keithbeckman>sudo find mnt/ -iname vcgencmd
Password:
mnt//opt/vc/bin/vcgencmd
mnt//usr/bin/vcgencmd
```

The entire `/opt` tree is not present on my updated filesystem.

```
root@zynthian:~# ls /opt
ls: cannot access '/opt': No such file or directory
```

**Comment by jofemodo** [comment]
BTW, you can activate Pianoteq in all the SDs you want. While using the same RBPi board, it will count as 1 device.
And you can remove active devices from the list from the Pianoteq's control panel.

Regards,

**Comment by sehrgut** [comment]
That's useful to know about pianoteq. The "if deactivated, can never be activated on this device again" in my modartt account scared me. 😅

**Comment by jofemodo** [comment]
Regarding the issue, that's quite strange ... how "/opt" has been deleted? Could you try:

```
apt-get update
apt-get upgrade

```
on the fresh image and see if the "/opt"  and "vcgencmd" still exist?

Thanks!

**Comment by sehrgut** [comment]
I actually found a suitable SD card in an old phone, so I'll be able to try this today.

**Comment by sehrgut** [comment]
Okay, so doing that right now leaves /opt/vc in place. I'm going to go back to my main SD and see if I can reinstall libraspberrypi-bin and bring /opt back.

**Comment by sehrgut** [comment]
Okay, reinstalling libraspberrypi-bin fixed it. I ran updates a couple times since building this box, so it's likely whatever package file was in Buster that caused this has been fixed. Oddly, madison doesn't show any other versions, so I'm not sure what could've happened to wipe out vc.

```
root@zynthian:~# apt-get --reinstall install libraspberrypi-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
Need to get 339 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi-bin armhf 1.20200212-1 [339 kB]
Fetched 339 kB in 1s (431 kB/s)            
(Reading database ... 102661 files and directories currently installed.)
Preparing to unpack .../libraspberrypi-bin_1.20200212-1_armhf.deb ...
Unpacking libraspberrypi-bin (1.20200212-1) over (1.20200212-1) ...
Setting up libraspberrypi-bin (1.20200212-1) ...
Error: GDBus.Error:org.freedesktop.systemd1.UnitMasked: Unit packagekit.service is masked.
root@zynthian:~# ls /opt/vc/bin/
containers_check_frame_int    containers_stream_server      dtoverlay                     raspistill                    vcgencmd
containers_datagram_receiver  containers_test               dtoverlay-post                raspivid                      vchiq_test
containers_datagram_sender    containers_test_bits          dtoverlay-pre                 raspividyuv                   vcmailbox
containers_dump_pktfile       containers_test_uri           dtparam                       raspiyuv                      vcsmem
containers_rtp_decoder        containers_uri_pipe           edidparser                    tvservice                     
containers_stream_client      dtmerge                       mmal_vc_diag                  vcdbg                         
```

**Comment by jofemodo** [comment]
The problem seems to be related with a kernel update.
Kernel updates have been disabled on RC3.
