### ISSUE TITLE
Allocate all sounds off to Long Back Press.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#254]
**Is your feature request related to a problem? Please describe.**
The long press on the back button sends all notes off, it would be more useful if it sent all Sounds off.

**Describe the solution you'd like**
When starting a zynth if it comes up in a mode that generates an horrible noise of any sort you should be able to kill it with one long back press.

**Describe alternatives you've considered**
Allocating a valuable i/o button to this function.
or frantically menu hop to find all sounds off. which on many guis is a menu option that's not in screen view when first entering the menu...
**Additional context**
Ultimately you want to be able to kill all sounds as fast as possible if MIDI locks up but killing all sound seems a more useful response. All notes off might go somewhere else?

**Comment by jofemodo** [comment]
This has changed and currently this action opens the Admin menu. I think a long action is too long and you don't want to wait 1-2 seconds for stopping the sound when things get funny. I prefer to leave the user assign this action to a dedicated push button.

Regarding this request, there are CUIA actions for satisfying all user preferences:

+ 10    ALL_NOTES_OFF              A#-1
+ 11    ALL_SOUNDS_OFF           B-1
+ 12    ALL_OFF                            C0

Regards
