### ISSUE TITLE
Add run & enable button options so zynthians can be restarted without pulling power line.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#255]
**Is your feature request related to a problem? Please describe.**
A zynthian that has been powered off requires PSU interuption to restart it. There are available pads for RUN & ENABLE that would allow this to be done without the electronic chaose that unplug/plug can generate ( audio clunks in mixers and such like )
**Describe the solution you'd like**
A cable with switches able to provide this feature.

**Describe alternatives you've considered**
All kinds of nasty mechanisms that involve cutting type C leads and such. The problem really shows itself in the battery pack powered zynth where repeated unplug/plug cycling is far from ideal. I would like to be able to leave my battery powered zynth safely inside a case (pedalboard) and restart from a simple switch.

**Comment by jofemodo** [comment]
But this is a hardware problem with a hardware solution, my friend!! ;-D
I found several options on the market:

A fast one:
https://www.amazon.co.uk/Adafruit-USB-Cable-with-Switch/dp/B00KAE3F58/

A very cheap one:

https://es.aliexpress.com/item/32982665717.html

Regards!
