### ISSUE TITLE
Avoid immediate reboot in webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#26]
When one makes some changes in the webconf that require a reboot to be applied, the reboot occurs as soon as the save button is pressed. This makes it quite irksome to make several changes which each require a reboot.

It may be advantageous to flag that a reboot is required but allow the user to manually reboot once all changes are applied. Maybe an indication in the header of webconf could show that changes require reboot and maybe clicking on this indication takes the user to the reboot option.

I have considered the fact that the procedure of configuring a Zynthian with parameters that require a reboot is quite infrequent, usually only during initial build and hence have avoided making this feature request in the past. I am suffering this issue quite frequently whilst testing various hardware configurations and also recent issues have caused configuration to be corrupt (e.g. #24, #25).

**Comment by wyleu** [comment]
Yep, I'm in for this one. 
Five reboots generally required to anoint a new zynth in my world...

Also the password section, perhaps, should require an extra password re-enter to allow you to change it.

A malicious passerby could lock you out very easily.

**Comment by riban-bw** [comment]
Thanks for the prompt fix. That is much better. Users may be confused by being asked to confirm reboot after clicking save but this feels better than previous solution.
