### ISSUE TITLE
Cannot route to each MIDI output individually

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#263]
**Describe the bug**
A MIDI FX layer can be routed to "Hardware MIDI Out" and/or "Network MIDI Out". It cannot be routed to any other physically attached MIDI interfaces, e.g. USB MIDI.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add MIDI-FX layer, e.g. MIDI Clock Generator
2. Bold press on layer to show context menu
3. Select "MIDI Routing"

**Expected behaviour**
Each and all MIDI outputs are listed.

**Actual behaviour**
"Hardware MIDI Out" and "Network MIDI Out" are listed.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: Behringer UMC1820
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

 SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09
Memory: 5% (202M/3906M)
SD Card: 39% (11G/28G)
Temperature: 51.0ºC

SOFTWARE
zyncoder: master (a1cf317)
zynthian-ui: master (9c8970b)
zynthian-sys: master (466236e)
zynthian-data: master (20e7da0)
zynthian-webconf: master (90015f4)

**Additional context**
There may need some consideration of what MIDI outputs are routed to by default. It probably makes sense to leave this as the one physical output (ttyMIDI) allowing user to change routing as required. This routing should be saved in snapshot.

**Comment by jofemodo** [comment]
Currently, you have to select what hardware "MIDI ports" are enabled for "MIDI Out". It's done from "MIDI Options->Ports".

**More in detail:** The current paradigm is that zynthian has 1 MIDI-input and 1 MIDI-output. Zynthian autoconnector is device-agnostic, being the MIDI channel mechanism the only way for targeting a device. Nevertheless, there is a mechanism for selecting whitch hardware MIDI ports will be used for MIDI-output and MIDI input.

I close this issue, but if you like, we could open a thread for discussing "How to improve routing (audio + MIDI)" ;-)
