### ISSUE TITLE
Some synth plugins appear in Audio-FX layer list

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#268]
**Describe the bug**
The list of available plugins for an Audio-FX layer includes some synths, e.g. synthv1. This makes no sense as these synths do not have audio inputs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Within webconf, enable synthv1 in LV2-Plugins Audio Effects list.
2. Select "New Audio-FX Layer
3. Observe synthv1 in Audio-FX Layer list

**Expected behaviour**
Synths should not appear in webconf audio effects list of UI Audio -FX Layer list.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: RBPi Headphones
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-12
Memory: 22% (206M/926M)
SD Card: 35% (9.5G/29G)
Temperature: 54.8ºC

SOFTWARE
zyncoder: master (ec1f6cb)
zynthian-ui: master (8ba25fb)
zynthian-sys: master (b84239e)
zynthian-data: master (20e7da0)
zynthian-webconf: master (27672ca)

**Comment by jofemodo** [comment]
I can't reproduce on latest RC3 image.
Please, click the "Search for new Plugins & Presets" button on the webconf's LV2 panel.
If it doesn't work, try updating to RC-3.

**Comment by riban-bw** [comment]
Sorry, I saw this behaviour on an old RPi 3 which I had not been using for a while. Performing a "search for new Plugins.." fixed this.
