### ISSUE TITLE
The Password on Webconf should not be altered without entering the existing password.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#27]
**Is your feature request related to a problem? Please describe.**
The Password on Webconf should not be reset without entering the existing password.

**Describe the solution you'd like**
The password section, should require an extra password re-enter to allow you to change it.

A malicious passerby could lock you out very easily.

**Describe alternatives you've considered**
Logging out at every opportunity.

**Additional context**

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (4a1e025) 
zynthian-sys: master (09e8d3e) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (61986dc)

**Comment by mheidt** [comment]
Please test and close

**Comment by wyleu** [comment]
Tested

1.1. Changed password on machine using new interface
1.2. Cleared cookies in browser
1.3. Logged in with new set password.

2.1 Attempted to change password with wrong password
2.2 Confronted.... 
![image](https://user-images.githubusercontent.com/79083/59223545-17c2bd00-8bc4-11e9-8e7e-68635fc2becf.png)
