### ISSUE TITLE
Transpose on an encoder for MIDI Player

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#270]
**Is your feature request related to a problem? Please describe.**
The ability to transpose a MIDI playback makes the zynthian an excellent practice and learning tool when combined with the bpm facility

**Describe the solution you'd like**
An encoder that allows the current sequence to be transposed up and down when playing a MIDI file. possibly with press to return to initil pitch of the file

**Describe alternatives you've considered**
External modification of the MIDI file

**Additional context**
![image](https://user-images.githubusercontent.com/79083/94994073-3a34d280-058d-11eb-9048-69dbcf4e9695.png)

**Comment by jofemodo** [comment]
A workaround would be transposing the layer(s) receiving the MIDI stream. A step forward would be implementing a MIDI routing menu, similar to the recently implemented audio player's output routing.
Ideally we should implement a MIDI-FX chain for the MIDI player and an Audio-FX chain for the Audio player.
@riban, this should be considered when refactoring the layers subsystem.

**Comment by jofemodo** [comment]
This is being addressed on:

https://github.com/zynthian/zynthian-issue-tracking/issues/491
