### ISSUE TITLE
Add remote layer

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#271]
**Is your feature request related to a problem? Please describe.**
Add a layer option that allows control of a remote zynthian over an OSC channel

**Describe the solution you'd like**
Operating remote zynthians requres access to the controlled GUI to configure and modify settings.
If a zynthian remote layer is available then the remote machines controls can be presented on the local display and modify the remote machine.

**Describe alternatives you've considered**
VNC modification, or xwindows GUI connection

**Comment by jofemodo** [comment]
I implemented this partially here:

https://github.com/zynthian/zynthian-ui/issues/68

I call this concept "zynthian cluster" and i'm pretty sure it will be fully implemented in the future.
Regarding the OSC API, i would implement full management of layers, including local & remote layers.

I close this ticket as it's addressed by #68.

Regards,
