### ISSUE TITLE
'install: cannot stat 'mod-host': No such file or directory' when updating

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-issue-tracking#274]
**Describe the bug**
Update (via webconf) from my Disco-Zynthian (last update was several weeks ago!)

**To Reproduce**
Simply update from webconf and than there occured this error inside the log text:

...
cc -I/usr/local/include -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0 -DHAVE_FFTW335 -DHAVE_NEW_LILV -DHAVE_JACK2 -I/usr/local/include -DHAVE_HYLIA -mcpu=cortex-a53 -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mlittle-endian -munaligned-access -mvectorize-with-neon-quad -ftree-vectorize -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -pthread -Wno-deprecated-declarations -Werror=implicit-function-declaration -Werror=return-type -fvisibility=hidden -o src/monitor.o src/monitor.c
make: *** [Makefile:113: src/effects.o] Error 1
make: *** Waiting for unfinished jobs....
install -d /usr/local/share/man/man1/
install -m 644 doc/*.1 /usr/local/share/man/man1/
install -d /usr/local/bin
install -m 755 mod-host /usr/local/bin
install: cannot stat 'mod-host': No such file or directory
make: *** [Makefile:125: install] Error 1
make: Nothing to be done for 'all'. 
...

**Expected behavior**
No error?

**Screenshots**
Not available.

**Setup:**
 - Hardware Config: Disco-Zynthian pre-v1
 - Software Version: before? I cannot say anymore, sorry. After update:

```
 ##########################       ----------------------------------------
#                          #      ZynthianOS: Built on os.zynthian.org
#            ##            #      Timestamp: 2020-04-23
#      ##   #  #   ##      #      Optimized: Raspberry Pi 3 Model B Plus
#     #  #  #  #  #  #     #      ----------------------------------------
###   #  #  #  #  #  #   ###      Kit:           Custom
#  #  #  #  #  #  #  #  #  #      Display:       PiTFT 2.8 Resistive
#   ##   #  #  #  #   ##   #      Soundcard:     HifiBerry DAC+
#         ##    ##         #      Wiring Layout: PROTOTYPE-3H
#                          #      ----------------------------------------
 ##########################
                                  zynthian-ui: master (d37e5d)
                                  zynthian-webconf: master (3bb219)
                                  zyncoder: master (0d4f15)
                                  zynthian-sys: master (0415dc)
                                  zynthian-data: master (ee9a22)
                                  ---------------------------------------

```
 

**Additional context**

**Comment by dcoredump** [comment]
The problem was that for `/zynthian/zynthian-sw/mod-host/src/effects.c`  `HAVE_LV2_STATE_FREE_PATH` (in line 100) was not defined but the `typedef struct LV2_State_Free_Path` already exists (maybe due to newer lv2-libraries). Defining manually `HAVE_LV2_STATE_FREE_PATH` for compilation fixed this problem.

**Comment by jofemodo** [comment]
Updating SD images older than the last official one is "dangerous". I only test updates on last SD image, in this case Buster RC-2 ...
