### ISSUE TITLE
Software update does not appear to complete from webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#28]
Performing a software update using webconf shows a log of progress. This stops at
> Updating zynthian-webconf ... 
although the update does complete.

**To Reproduce**
1. Within web browser (e.g. Chrome) navigate to http://zynthian.local/api/sw-update
2. Click "Update Software

**Expected behaviour**
Software is updated and progress is shown ending with successful completion message.

**Actual behaviour**
Software is updated and progress is shown ending with "Updating zynthian-webconf ...".

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (4a1e025) 
zynthian-sys: master (09e8d3e) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (8598e0a)

**Comment by mheidt** [comment]
https://github.com/zynthian/zynthian-sys/issues/107

**Comment by jofemodo** [comment]
Note: Issues can be transfered from a repository to another ;-)

**Comment by mheidt** [comment]
107 existed already when I worked on it.

**Comment by mheidt** [comment]
And i don't think, that I can...
