### ISSUE TITLE
alsa_out crashes (affects headphones.service)

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#284]
**Describe the bug**
I cannot use the Raspberry 4s headphone output. The service crashes and restarts every few seconds. This is related to the alsa_out application.

**To Reproduce**
Enable "Headphones" in the Zynthian admin section.
Check the jackd ports (with QJackCtl or another tool): The "Headphones" connections appears and disappears.

Extended test:
Run the services command manually in a terminal (SSH):
/usr/local/bin/alsa_out -q 0 -j Headphones -d hw:Headphones
OUTPUT:
selected sample format: 16bit
delay = 1817
delay = 1794
THEN AFTER A FEW SECONDS
err = -11
Write error: Resource temporarily unavailable

**Setup:**
Latest SD image and updated running on a Raspberry 4b

**Additional context**
The problem is clearly related to the alsa_out program because I can use the hw:Headphones output from other applications without problem. For example aplay -D hw:Headphones somefile.wav works without any problems.

**Comment by jofemodo** [comment]
Have you tried to disable/enable again?

**Comment by mark-orion** [comment]
> Have you tried to disable/enable again?

Many times. And as I said, the problem even happens when I use alsa_out in a plain command line and not the systemd service.
Just to add about my setup:
It's a non-standard setup with an external HDMI / USB touchscreen and a Behringer UCA202 as sound interface. The Behringer is sampling at 48 KHz what should not be a problem as this is the standard RPi output samplerate.

**Comment by jofemodo** [comment]
I can't reproduce the problem. It seems related with the specific hardware setup. We need more info.
