### ISSUE TITLE
set_select_path should be in base class

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#289]
**Describe the bug**
Some GUI screens do not use selector. A recent change added the method: set_select_path() to zynthian_gui_selector.py but this should be in zynthian_gui_base.py. This function is called by zynthian_gui_base.py hence making a circular dependency.

**Comment by riban-bw** [comment]
I have supplied a fix in https://github.com/zynthian/zynthian-ui/pull/306.

**Comment by jofemodo** [comment]
OK! It's merged just now ...
