### ISSUE TITLE
Update results in black screen and unusable Zynthian

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#291]
**Describe the bug**
Performing a normal update from the admin menu of the Zynthian resulted in the screen going black and the Zynthian being unresponsive.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to Admin menu
2. Select, "Software Update"

**Expected behaviour**
Software is updated and Zynthian returns to normal operating state.

**Actual behaviour**
Software is updated but Zynthian shows black screen and does not appear to respond to encoders

**Setup:**

HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 7% (138M/1939M)
SD Card: 35% (9.1G/28G)
Temperature: 46.0ºC

SOFTWARE (after update)
zyncoder: master (aa91afe)
zynthian-ui: master (8e99583)
zynthian-sys: master (dcf8d8a)
zynthian-data: master (74ceb35)
zynthian-webconf: master (17b44ff)

**Additional context**
This was probably the second update after a fresh build / install.

**Comment by riban-bw** [comment]
Reboot returns normal operation but this should not happen with a simple update of an official build Zynthian. Bad user experience.

**Comment by jofemodo** [comment]
The expected behaviour is what i get when updating my 2 zynthians ... I would need the logs for finding what is the problem with your update.

**Comment by riban-bw** [comment]
I _think_ others have experienced similar behaviour recently. What logs would be useful? There wasn't anything in service journal.

**Comment by jofemodo** [comment]
The UI's update code simply run's the update script _update_zynthian.sh_ from _zynthian-sys/scripts_. This script will restart zynthian or zynthian-webconf services when some of this repositories have been modified.
I will try to reproduce the error, but without logs it's difficult to know where the problem is ....

**Comment by riban-bw** [comment]
I built the Zynthian with the current stable image https://os.zynthian.org/zynthianos-last-stable.zip on 15th December. Today I noticed that keyboard split was not implemented so I must not have updated before today. Today I did the first update and got this behaviour. Are you testing by starting with a newly installed image and updating for the first time?

**Comment by jofemodo** [comment]
Hi @riban-bw !
The last stable is not the last build but the last RC.

**Comment by riban-bw** [comment]
Imminent changes to stable and testing should render this issue irrelevant.
