### ISSUE TITLE
500 Error in selecting backup/restore menu...

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#293]
**Describe the bug**
Upon selecting backup and restore from the Webconf System menu a 500 error is returned

![image](https://user-images.githubusercontent.com/79083/103154903-e9e79e00-4792-11eb-803f-a7e02a866a94.png)

**To Reproduce**
1. Slect Backup/Restore

**Expected behavior**
The Backup Menu

**Setup:**
![image](https://user-images.githubusercontent.com/79083/103154921-14d1f200-4793-11eb-92de-69b611c35c50.png)

**Additional context**

**Comment by jofemodo** [comment]
Sorry @wyleu !
I can't reproduce the error. It works for me (staging-2109)
