### ISSUE TITLE
Large MIDI files make MIDI recorder screen unresponsive

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#294]
**Describe the bug**
If there are large MIDI files in the capture folder then the MIDI Recorder screen becomes slow and unresponsive. Each change of view including starting / stopping player, toggle loop, etc. will take many seconds to respond.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a large MIDI file, e.g. 1200 minutes long
2. Navigate to MIDI Recorder view

**Expected behaviour**
Interface remains responsive.

**Actual behaviour**
Interface becomes slow and unresponsive. Web interface also becomes slow / unresponsive on the http://zynthian.local/lib-captures page.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 19% (371M/1939M)
SD Card: 36% (9.3G/28G)
Temperature: 46.0ºC

zyncoder: master (aa91afe)
zynthian-ui: master (94854cb)
zynthian-sys: master (dcf8d8a)
zynthian-data: master (336eadc)
zynthian-webconf: master (17b44ff)

**Additional context**
The large MIDI file causing the problem was created accidentally by inadvertently leaving the machine in record mode but it is plausible that someone may want many / large MIDI files which may trigger this issue and it is certainly possible for the issue to occur by accident as in my case. A normal user may not have the diagnostics skills to identify the cause of the issue.

Work-around is to remove large files.

**Comment by jofemodo** [comment]
The problem seems to be located on the library that calculates the time duration. Long files shouldn't be a problem, so perhaps we should open an issue and try to solve the issue there:

https://github.com/quodlibet/mutagen

Regards,

**Comment by riban-bw** [comment]
Raised issue https://github.com/quodlibet/mutagen/issues/509. It is plausible they may not be able or willing to resolve this so any optimisation in Zynthian would be useful, e.g. populating file duration as a background talk or not updating if nothing changed, e.g. starting playback or toggling loop mode should not trigger reparsing files.

**Comment by jofemodo** [comment]
If they don't solve it, we will do it ;-)

**Comment by riban-bw** [comment]
Mutagen said this was challenging to resolve and needed help, i.e. they won't fix. Subsequently Zynthian SMF player has been written and provides this function so no longer using mutagen.
