### ISSUE TITLE
ZynMidiRouter routes clock even with all routing disabled

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#299]
**Describe the bug**
Although I have all MIDI routing disabled, ZynMidiRouter still routes clock messages between inputs and outputs. This causes a lot of trouble (double clock messages etc.). I am considering this as a bug as it happends even with "Enable System Messages (Transport)" disabled in the MIDI configuration

**To Reproduce**
1. Disable all routing options in the MIDI configuration, but enable the MIDI inputs and outputs you want to connect to Zynthian
2. Load an MOD layer and log into the MOD web ui.
3. Set sync mode to "MIDI". The displayed clock rate is **twice** the one in the setup.
4. With Qjackctl remove the ZynMIDIRouter -> mod-host Jack MIDI link
5. MOD UI is now showing the correct clock rate.

**Expected behavior**
Clock realtime messages should not be routed when MIDI routing is disabled.

Just in case this is by design: Then please add a feature (checkbox) to suppress clock routing.

**Comment by jofemodo** [comment]
Have you tried to disable these 2 options from the UI's admin menu?

+ MIDI System Messages
+ MIDI Clock Internal

Regards,

**Comment by mark-orion** [comment]
> Have you tried to disable these 2 options from the UI's admin menu?
> 
>     * MIDI System Messages
> 
>     * MIDI Clock Internal
> 
> 
> Regards,

Yes, both options are disabled. And what I am talking about is clock coming in from an external source (Roland synthesizer) that is connected to Zynthian via a MIDI-USB interface. The doubled clock messages do come from the synth because when I change the BPM rate on the device, the doubled BPM rate that is shown in MOD changes accordingly.

**Comment by jofemodo** [comment]
Perhaps it's MOD-UI related. If you have disabled "MIDI System Messages" from admin menu, zynthian shouldn't route any clock message. MOD-UI, although integrated on zynthian-ui, is an independent beast, and he routes as he wants. Try tweaking with MOD-UI clock options ...

Anyway, for confirming this hypothesis, try without MOD-UI ;-)

Regards,

**Comment by mark-orion** [comment]
I am closing this now as it looks as I had some corrupted configuration on my system. The problem with unwanted clock routing was gone after a fresh Zynthian install. However, MOD-UI still reports a clock speed twice that of the one provided by my synth.
