### ISSUE TITLE
touchosc2midi consuming 10% CPU when idle

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#30]
The touchosc2midi process is consuming excessive (~10%) CPU when idle.

**To Reproduce**
1. Enable touchosc2midi (TouchOSC Bridge)
2. Observe process CPU usage ~ 1%
3. Make OSC connection to port 12101
4. Observe process CPU usage

**Expected behaviour**
CPU usage remains low whilst idle

**Actual behaviour**
CPU usage increase to 10% whilst idle

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (4a1e025) 
zynthian-sys: master (3db6429) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (588c830) 

I have reported this upstream as [issu 20](https://github.com/velolala/touchosc2midi/issues/20). There is a simple fix which is to change the sleep time within the main function to 0.1s. I am not sure where this would be applied within Zynthian (else I would have submitted a patch). I have made the change to /usr/local/lib/python2.7/dist-packages/touchosc2midi/touchosc2midi.py on my local Zynthian and this resolves the issue.

**Comment by jofemodo** [comment]
I sent a pull request to TouchOSC repo:

https://github.com/velolala/touchosc2midi/pull/21

**Comment by jofemodo** [comment]
I already forked the touchOSC repo. If maintainers take too long to merge, we could start using our repository until the fix is accepted.

**Comment by jofemodo** [comment]
We should use our fork until the patch is merged upstream.
