### ISSUE TITLE
Nightly build - PI 4 with 4GB RAM - USB MIDI keyboard not recognized

### ISSUE THREAD

**Issue by mszulen** [zynthian/zynthian-issue-tracking#302]
I've noticed, that when switching the RPI3 to RPI4 (same sd card) my usb midi keyboards are not being recognized.
aconnect -i shows nothing.
After searching over the net, I've found information about the USB problems on PI 4 with more than 3GB ram.
I've put total_mem=3072 command into the config.txt and everything works without the issues.

I've tried different Zynthian images up to nightly 19.1.2021

I've found my solution here:
https://github.com/raspberrypi/linux/issues/3093#issuecomment-520269280

In such a situation - using PI4 with more than 2GB RAM for Zynthian doesn't make sense, unless you don't plan to use USB midi.

![pi3](https://user-images.githubusercontent.com/6932464/105514141-72def000-5cd3-11eb-8b16-0af8209354eb.jpg)
![pi4](https://user-images.githubusercontent.com/6932464/105514147-74101d00-5cd3-11eb-9066-79f2768f7b24.jpg)

**Comment by mszulen** [comment]
hmm.. Looks like it was only the nightly build issue (different kernel?). When Installed the official stable image - usb works without need to limit the memory.

**Comment by riban-bw** [comment]
Is this still an issue with current stable build?

**Comment by jofemodo** [comment]
Not a problem in the current stable version. We can close it.

Regarding future, i think this is solved if we can update the kernel and firmware. I already have located the problem and a solution is on the way.

Regards,
