### ISSUE TITLE
Update from admin menu appears to succeed when no network available

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#309]
**Describe the bug**
Performing an update from the UI admin menu shows apparent success even if the network is not available for an update.

**To Reproduce**
1. Disconnect / disable network
2. Navigate to Admin menu3. Select Update Software

**Expected behaviour**
Update fails. Indication of failure with reason, e.g. no network available.
**Actual behaviour**
Update fails. No failure indication. Success shown.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 17% (343M/1939M)
SD Card: 36% (9.3G/28G)
Temperature: 44.0ºC

OFTWARE
zyncoder: master (3bb3969)
zynthian-ui: feature/stepseq (58d7a9f)
zynthian-sys: master (4ee88ca)
zynthian-data: master (336eadc)
zynthian-webconf: master (0587018)

**Additional context**
Update should check for network connectivity and then maybe each stage should be counted for success with summary of success / failure shown at end.

**Comment by jofemodo** [comment]
I should refactorize the update script and the UI/Webconf update tools for better detecting problems ;-)

**Comment by riban-bw** [comment]
This issue is substantially reduced because update is not available in the admin menu if there is no Internet access but can be further improved by testing for access to github, e.g. ping. This would catch when the network becomes unavailable whilst the admin menu is shown.
