### ISSUE TITLE
Inconsistent reference to MIDI Network protocol

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#32]
Within the admin menu and webconf there are various configuration elements relating to network protocols:

- TouchOSC
- MIDI Network
- QMidiNet

These are not consistently referenced in documentation or the application.

There should be a common naming convention for each type of interface with each documented to describe what it provides and how to use it.

I believe "MIDI Network" refers to "QmidiNet".

I recommend using QmidiNet (note lowercase 'm') throughout to reduce confusion. This will hopefully also make it clear that QmidiNet and TouchOSC are different protocols. (It may further assist understanding if these two configurations were adjacent in the admin menu and both present in webconf (TouchOSC is missing in webconf).

I do now understand what each means but I had to resort to source code review to understand. This is not a user friendly methodology!

So - I suggest the following actions:

- Change admin menu text from "MIDI Network" to "QmidiNet
- Move QmidiNet admin entry to immediately before TouchOSC
- Change dashboard reference of "QMidiNet" to "QmidiNet"
- Add dashboard indication of TouchOSC
- Change webconf MIDI Config page from "Enable MIDI over Network" to "Enable QmidiNet (MIDI over Network)
- Add to webconf MIDI Config Page "Enable TouchOSC" option
- Change reference of QMidiNet on http://zynthian.org to QmidiNet

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (ac000fb) 
zynthian-sys: master (3597e65) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (2904617)

**Comment by jofemodo** [comment]
+10. Absolutely OK for me. I will do it ASAP.
Thanks a lot for your accurate analysis ;-)

**Comment by jofemodo** [comment]
Or perhaps you want to do it ... these changes are mostly trivial.

**Comment by riban-bw** [comment]
Sure, I will make the changes. I don't think I have permission on webconf repo so may need to submit a PR for that bit

**Comment by jofemodo** [comment]
I will give you write access to webconf repo ;-)

**Comment by riban-bw** [comment]
I have created branch in my local repo to fix the zynthian-ui part but github is refusing to let me push that.
I have created a branch in my local repo to fix zynthian-webconf but found that webconf doesn't actually work for the existing service so there is more work to do there to make it work. I have it looking right but don't yet know how to make it work.

**Comment by jofemodo** [comment]
Testing the UI gh32 branch, but ... I don't understand your second paragraph:

>  but found that webconf doesn't actually work for the existing service so there is more work to do there to make it work

Anyway, this branch naming convention don't fit very well with our current "issue flow". It should be improved....

**Comment by riban-bw** [comment]
Actually, stop testing this. I have realised why some bits are not working. QmidiNet is managed by MIDI Profile whilst TouchOSC is managed by global config. The current implementation of TouchOSC only provides MIDI interface so I will move TouchOSC configuration into MIDI profile.

I was not able to get webconf to enable / disable QmidiNet. I will try again today. The good news is that the indication on the dashboard works!

I agree (and previously voiced my concern) about moving issues between issue trackers. I observed there are now two gh32... branches in webconf repo. I still don't see the benefit of separate issue trackers but that is a discussion for another forum.

**Comment by riban-bw** [comment]
Okay - I that should be better. I have committed changes to both repos.
TouchOSC is now part of the MIDI profile.
TouchOSC and QmidiNet are stopped / started when MIDI profile is loaded.
Note: ZYNTHIAN_MIDI_TOUCHOSC is now the configuration element to enable TouchOSC. ZYNTHIAN_TOUCHOSC is obsolete and may be removed from zynthian_envars.sh.
Note: ZYNTHIAN_MIDI_TOUCHOSC should ideally be added to zynthian-sys repo : config/default_midi_profile.sh.
Note: TouchOSC and QmidiNet services are not controlled from webconf and there is no request to restart Zynthian after changing these config elements. This is by design because you are actually configuring MIDI Profiles and may wish to do many which are then loaded in the Zynthian. This may want some documentation / notification in webconf or further consideration.

This should now work - please test and merge as appropriate.

**Comment by jofemodo** [comment]
I've added AubioNotes (Audio2MIDI) to MIDI profiles.

**Comment by jofemodo** [comment]
It's merged with master now.
