### ISSUE TITLE
No captures made yet displayed after restore.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#321]
**Describe the bug**
After a restore including captures is restored the webconf displays 
"No captures have been made yet."

![image](https://user-images.githubusercontent.com/79083/108606480-31189680-73b2-11eb-8252-60b11c34a1be.png)

**To Reproduce**
1. Restore a seperate zynthian  restore file to a 'clean' zynthian
2. Click on Captures
3. "No captures have been made yet."
 displayed beside list of restored capture files.

**Expected behavior**
After a restore the message should not be displayed.

**Comment by jofemodo** [comment]
This should be solved on testing.
