### ISSUE TITLE
ZynSeq: Tap to set tempo

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#325]
**Is your feature request related to a problem? Please describe.**
Sometimes you just want to feel the beat...

**Describe the solution you'd like**
Ability to set the tempo by tapping a button or screen or external MIDI controller.

**Additional context**
Currently tempo is set with a rotary encoder. There may be challenges in getting an input device that works well for recording the tapping.

**Comment by gr0k-net** [comment]
Not knowing anything about the codebase, or most of the technologies being utilised within it, I have no idea if this is feasible, but many MIDI controllers already have an internal clock with tempo tap. 

Could the tap to set tempo option simply show a screen that reads from and displays the current external MIDI clock BPM, then reverts to the internal clock when affirmed or canceled?

P.S - Also woah, I imagine creating and following all these separate issues is as much work as the coding itself. If this kind of suggestion isn't useful, I'm happy to keep comments to the forum or elsewhere (or myself haha)

**Comment by riban-bw** [comment]
I have added CUIA action TAP_TEMPO. This can be assigned to a GPI or button or could be triggered by OSC, e.g. a phone app. Sending this CUIA twice within 3s will change the internal clock tempo. The last two taps are always used (within the range 20..420 BPM). This is in the feature/slave_to_midi_clock dev branch. I will close this ticket because this should be merged to testing soon
