### ISSUE TITLE
ZynSeq: Move notes off the beat (unquantize)

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#328]
**Is your feature request related to a problem? Please describe.**
ZynSeq is tightly quantised. It can improve the feel of a track if notes are slightly unquantised and it can provide greater artistic freedom to move notes around.

**Describe the solution you'd like**
Ability to shift notes off the quantised steps. Maybe use a modifier to allow finer control of note positioning.

**Additional context**
Probably have to quantise to clock which is currently 24 ppqn.

**Comment by jofemodo** [comment]
Implemented as "note offset"
