### ISSUE TITLE
ZynSeq: Ability to play long notes live into pattern editor from external MIDI controller

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#330]
**Is your feature request related to a problem? Please describe.**
ZynSeq currently adds notes with duration of one step when triggered from external MIDI controller. It would be advantageous to record the duration the key is held.

**Describe the solution you'd like**
When playing live to pattern editor whilst looping the duration the key is held should be the duration of the added note in the pattern.

**Additional context**
Must consider what happens if the note is longer than the pattern. Should probably use current rule that maximum duration is the duration of the pattern.

**Comment by riban-bw** [comment]
This is implemented. Press and hold sustain pedal then press a note to add to pattern then repeat pressing note to extend length. Release sustain pedal to complete the action. Each different note added whilst sustain is pressed will be added at the same start position. Alternating between notes whilst sustain is pressed will continue to extend duration of each note. Play cursor is advanced only one step when sustain is released.

TODO: Limit duration of note to duration of pattern (as is done when manually editing note duration).

**Comment by CarloCattano** [comment]
> 

> This is implemented. Press and hold sustain pedal ....

Hi there ! I kindly disagree. In an usual playing scenario , where you want to just replicate what you played acuratedly in a "looping" manner , then no . This sustain pedal technique isnt ideal , and its a whole different concept/workflow. In fact , this tiny missing feature can be decisive when trying to choose a midi sequencer of this kind . It is awesome and runs very well on the zynthian , but its impractical at the moment

**Comment by riban-bw** [comment]
I see this as two different features. The hold pedal option is for manual step input, i.e. adding notes to a sequence one step at a time. The feature @CarloCattano describes relates to recording a pattern in loop mode. You are right that this functionality is not implemented and _should_ be. I also see that the feature request relates to the latter but the implemented fix relates to the former so I will leave this issue open until live, looping input is improved.

**Comment by riban-bw** [comment]
Live recording of patterns is now implemented.
