### ISSUE TITLE
ZynSeq: Add metronome

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#339]
**Is your feature request related to a problem? Please describe.**
It would be advantageous to add a metronome feature.

**Describe the solution you'd like**
Ability to enable a metronome which triggers a click ever beat with different sound at start of bar.

**Describe alternatives you've considered**
Can use a spare pattern in a spare sequence targetted at a percusion instrument.

**Additional context**
It would be useful to not have to load a percussion layer for this purpose. Maybe automatically load an instrument or add a builtin click sound, e.g. playing a sample or similar from within libzynseq.

**Comment by riban-bw** [comment]
I've been thinking about this and think it would be beneficial to add metronome click as sample played by zynseq library. I measured a metronome spend too be about 8ms which is about 350 samples. I may add this in a future sprint. It would mean adding an audio output from zynstep and routing it to main output.

**Comment by jofemodo** [comment]
It's implemented!
