### ISSUE TITLE
ZynSeq: Indication of transport state

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#341]
**Is your feature request related to a problem? Please describe.**
It may be advantageous to be able to see the state of the JACK transport.

**Describe the solution you'd like**
Icon in the status area indicating transport status. This could be an animation, e.g. dots progressing or integrated with other transport displays like the MIDI / audio player / recorder.

**Additional context**
This may demand a redesign of the status area with more consistent and integrated icons.

**Comment by jofemodo** [comment]
Currently this is shown with the different play symbols. Perhaps can be improved, but it kind of works.
