### ISSUE TITLE
ZynSeq: Add ability to undo previous action

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#347]
**Is your feature request related to a problem? Please describe.**
Sometimes a user makes a mistake and wants to revert to a previous state. Sometime a user may feel more empowered to try new ideas if they can restore to a previous state.

**Describe the solution you'd like**
The ability to roll back to previous states after each action.

**Additional context**
This would be advantageous for various elements within Zynthian and maybe a global / common undo mechansim would be beneficial. It may prove challenging to identify which actions warrent undo option and design a mechanism that is not intrusive to workflow or resource hungry.

**Comment by jofemodo** [comment]
This could be really challenging. Implementing a reliable and consistent "undo" mechanism is difficult. I would spend time and effort on this:

https://github.com/zynthian/zynthian-issue-tracking/issues/320

before considering implementing "undo".

**Comment by riban-bw** [comment]
Need to review to see if this has sufficient benefit now that destructive changes are confirmed.

I think there are many operations in sequencer that do not trigger confirmation, e.g. adding / removing notes in pattern. This can be undesirable and difficult to undo. I have experienced notes added and removed when not intended and difficulty recovering to previous state.

I think this feature is still desirable.

**Comment by jofemodo** [comment]
It's already implemented in pattern editor: ALT mode in V5
We would need a V4 workflow.

**Comment by riban-bw** [comment]
The batch undo (based on time - now 1s) is not intuitive. I expect the undo to perform per-note undo after manually adding individual notes. This does not happen when you add notes rapidly which is more liekly when undo would be required. I agree that batch undo makes sense in live record although even there you may prefer per-note undo, e.g. you are adding notes to a long, slow sequence and only the last few are bad. (You could manually remove them but that might involve stopping transport, scrollng, etc.)

**Comment by riban-bw** [comment]
Batch undo is now fixed. So we just need a V4 workflow. I think this has to be menu driven.

**Comment by jofemodo** [comment]
From pattern editor, bold-back to enter undo/redo with select knob. Custom buttonbar with undo/redo actions.
