### ISSUE TITLE
ZynSeq: Option to show short or long black notes on pianoroll

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#351]
**Is your feature request related to a problem? Please describe.**
It was requested (I can't find who by) that the pianoroll be presented with short black keys representative of a real piano.

**Describe the solution you'd like**
Option to toggle between short and long black keys. This could be done in the scales menu.

**Additional context**
Original keyboard had short black keys but it had issues with parallax so I used long black keys.

**Comment by jofemodo** [comment]
-1. I don't see any advantage on having this implemented, apart from satisfying the aesthetical preferences of somebody else.

**Comment by riban-bw** [comment]
Having considered this feature request I think it provides little tangible benefit whislt having some disadvantage, e.g. the row lines won't meet making it less obvious what notes correspond to what rows and some keys on the keyboard becomes smaller. It is also technically challenging.

Rejected!
