### ISSUE TITLE
VNC Server seems to stop hdmi output.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#357]
**Describe the bug**
Selecting VNC Server prevents hdmi output from starting.

**To Reproduce**
1. Turn on VNC Server 
2. Restart zynthian
3. HDMI output does not appear

**Expected behavior**
You can see the hdmi start up, but the GUI never appears.

![image](https://user-images.githubusercontent.com/79083/108750011-6e0e9580-7538-11eb-863f-143787b837d5.png)

**Comment by jofemodo** [comment]
Could you check the UI's log?

Thanks

**Comment by wyleu** [comment]
Can't duplicate. Closed.
