### ISSUE TITLE
Deleting current MIDI Profile in web conf does not actually delete profile

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#36]
Deleting the currently active MIDI Profile results in Zynthian thinking it still has that profile available.

**To Reproduce**
1. Within webconf navigate to http://zynthian.local/api/ui-midi-options
2. Select the MIDI Profile and click "Delete MIDI profile"
3. Within Zynthian click "MIDI Profile"
4. Navigate away and back to http://zynthian.local/api/ui-midi-options

**Expected behaviour**
The deleted profile is absent

**Actual behaviour**
The deleted profile is present

***SOFTWARE***
zyncoder: master (80862b6) 
zynthian-ui: master (d664827) 
zynthian-sys: master (c2e285c) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (950c16b)

**Comment by riban-bw** [comment]
Sometimes get errors :
> ERROR parsing MIDI filter rule: Invalid RULE type (\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n)

**Comment by riban-bw** [comment]
Ignore last comment - that seems to be an unrelated issue which I will investigate and report separately.

The currently selected profile (within Zynthian) cannot be deleted by webconf. There are no warnings and I can't yet see why this is the case. The file does seem to be deleted and recreated at this time. Webconf removes it from its list so maybe webconf removes the file then something recreates it.

**Comment by jofemodo** [comment]
The "default" template is recreated if deleted. In fact, deleting the "default" MIDI profile act as a kind of "MIDI Options Factory reset" ;-)

I just tested with some MIDI profiles (not the default) and it works for me ...

**Comment by riban-bw** [comment]
Not working for me... If I create a MIDI profile and select it on the Zynthian then delete it in the webconf, it _appears_ to delete from webconf but persists in Zynthian and will show in webconf if navigating away and back to MIDI Profiles page. This is reliably reproducible.

**Comment by jofemodo** [comment]
OK! You are right ... I will solve it ASAP.

**Comment by jofemodo** [comment]
It should be solved in  74ba664. Please, test it!
