### ISSUE TITLE
Differentiate between audio and MIDI recording state

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#362]
**Is your feature request related to a problem? Please describe.**
There is an indication of recording state in the topbar but this is the same for MIDI or audio recording. It would be advantageous to differentiate between these two different states.

**Describe the solution you'd like**
Different icons for MIDI and audo record. These icons may be separated or overlayed, whichever is appropriate.

**Additional context**
The icons should indicate unambiguously their meaning. The record and play state of each recorder should be indicated individually.

**Comment by jofemodo** [comment]
This has been discussed but not solved in the past ...

https://github.com/zynthian/zynthian-ui/issues/148

This time we will find a good solution ;-)

**Comment by wyleu** [comment]
From my investigations of using a single RGB LED as a status display, Could we restrict each status indicator to a specif unique colour even if the effect is marginal?
