### ISSUE TITLE
Port based MIDI routing

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#367]
**Is your feature request related to a problem? Please describe.**
I cannot assign certain soft synths or effects to specific external (USB) MIDI hardware.

**Describe the solution you'd like**
The MIDI routing option in the Zynthian UI should offer exactly the same functionality as the audio routing option or the options that other Jackd control software like QJackCtl is offering. This would mean to list all MIDI ports individually rather than the (for me too) generic "Hardware", "Network" etc. groups.

**Describe alternatives you've considered**
An option to completely  disable Zynthians MIDI router so that all MIDI routing can be done by an alternative system (e.g. QJackCtl).

**Comment by jofemodo** [comment]
It's been implemented on https://github.com/zynthian/zyncoder/issues/26
Please, before creating a new issue, check that it's not duplicated.

Thanks!
