### ISSUE TITLE
MIDI Profile gets '\n' in config

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#37]
Some MIDI Profiles have '\n' in the "Midi filter rules" and / or "MIDI Ports".

**To Reproduce**
1. Within web browser, e.g. Chrome, navigate to http://zynthian.local/api/ui-midi-options
2. Add some MIDI Profiles
3. Swap between profiles

**Expected behaviour**
Each profile contains newlines in "Midi filter rules" and "MIDI Ports" fields

**Actual behaviour**
Some profiles contains '\n' in "Midi filter rules" and "MIDI Ports" fields

**SOFTWARE**
zyncoder: master (80862b6) 
zynthian-ui: master (d664827) 
zynthian-sys: master (c2e285c) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (950c16b)

**Comment by riban-bw** [comment]
I note that the webpage has:
```
<textarea id="ZYNTHIAN_MIDI_PORTS" name="ZYNTHIAN_MIDI_PORTS" cols="50" rows="2" class="">DISABLED_IN=
ENABLED_OUT=ttymidi:MIDI_out
ENABLED_FB=
</textarea>
```
Should that be `rows="3"`?

**Comment by riban-bw** [comment]
It looks like the page loads correctly but if you subsequently change the selection of the "MIDI profile" drop-down then the text boxes are populated with 'n' characters, even if you reselect the profile that appeared okay when first loaded. Maybe something needs escaping?

**Comment by riban-bw** [comment]
Issue is that javascript function to replace newlines only acted on first one. [this branch](https://github.com/zynthian/zynthian-webconf/tree/ghz37-newlines) fixes this.

**Comment by jofemodo** [comment]
But ... how this "problem" affect to the functionality?

**Comment by riban-bw** [comment]
This results in MIDI profiles becoming corrupt.

**Comment by jofemodo** [comment]
OK! This is a good reason to fix it ;-)

**Comment by mheidt** [comment]
why did I get assigned? @riban-bw  has a fix branch already?!

**Comment by jofemodo** [comment]
Ups, sorry ;-)

**Comment by jofemodo** [comment]
Hi @riban-bw !

Could you push again the ghz37-newlines branch? I think i deleted by error when cleaning old branches ...

**Comment by riban-bw** [comment]
I have pushed ghz37-newlines.

**Comment by jofemodo** [comment]
Tested and closed ;-)
