### ISSUE TITLE
Save Snapshot; where is "New Snapshot"

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#371]
If I try to save a snapshot the Zynthian user guide says i have to push bold snapshot and find a window with the entry "New snapshot". But I don see it now.

**To Reproduce**
push bold snapshot

**Expected behavior**
I find the entry "new snapshot and use it

**Screenshots**
![IMG_3051](https://user-images.githubusercontent.com/55761217/109954053-211d8280-7ce1-11eb-8e69-6cb65168f9d3.JPG)

**Setup:**
![grafik](https://user-images.githubusercontent.com/55761217/109954180-4f02c700-7ce1-11eb-8978-a25f57a962c3.png)

**Comment by jofemodo** [comment]
I can't reproduce this issue.
BTW ... Build Date???
What SD image are you using? You should be using the latest stable SD image.
