### ISSUE TITLE
Vitalium fails if external GUI enabled

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#372]
**Describe the bug**
If vitalium is stared with jalv.gtk it immediately fails.

**To Reproduce**
1. Enable VNC Server
2. Add Vitalium layer
3. Play a some notes

**Expected behaviour**
Viltalium engine plays.

**Actual behaviour**
Viltalium engine plays one note then stops working.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 26% (513M/1939M)
SD Card: 37% (9.7G/28G)
Temperature: 44.0ºC

SOFTWARE
zyncoder: master (ef24e0e)
zynthian-ui: master (45257ae)
zynthian-sys: master (cdbb0e9)
zynthian-data: master (67e3636)
zynthian-webconf: master (25b1ace)

**Additional context**
Log shows jalv.gtk failing.

**Comment by riban-bw** [comment]
If the external UI is disabled then default LV2 UI shows which allows plugin to run. I suggest we use this workaround until this bug is fixed upstream. I have reported the bug upstream.

**Comment by jofemodo** [comment]
As vitalium has now a nice GUI, i will close this.
