### ISSUE TITLE
if a Recording is made make that the default play file for play commands

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#378]
**Is your feature request related to a problem? Please describe.**
I record with toggle record on one foot pedal ans have play toggle located next to it 
IF I wish to play back a recording I have just made I have to navigate to the audio recorder to access the file which might not be immediately obvious if you have a lot of recordings ...
If the last recording was a default unless overridden by a audio recorder play selection

**Describe alternatives you've considered**
Boils down to a navigation dance.

**Comment by jofemodo** [comment]
Already implemented!
