### ISSUE TITLE
Remember favourites state

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#382]
**Is your feature request related to a problem? Please describe.**
It is possible to add engine presets to a list of favourites but one must toggle the display of these favourites each time one enters the engine's preset selection screen.

**Describe the solution you'd like**
It may be advantageous to store the current state of showing all / favourite presets. This would mean storing the state (persistently) and not cancelling favourite display when BACK pressed, instead exit preset list.

**Describe alternatives you've considered**
None.

**Additional context**
If I have a list of favourites it is probably because they are the only presets I want to see in a scenario, e.g. during live performance. Having to change view on every entry to the screen can be irksome and impact workflow adversely.

**Comment by jofemodo** [comment]
Currently, favorites are managed like a bank by the UI. As selected bank is saved with state, i think we can close this issue.
