### ISSUE TITLE
Pressing LAYER changes view unexpectedly

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#383]
**Describe the bug**
When showing an engine's control screen the LAYER button switches between layers but will then drop back to the "Layers" list screen.

**To Reproduce**
1. Add several layers, e.g. 1#FS, 2#JV/Dexed, 3#JV/ZynChorus
2. Navigate to 1#FS control screen
3. Press LAYER switch several times

**Expected behaviour**
Control screen changes between FS->Dexed->ZynChorus->FS....

**Actual behaviour**
Control screen changes between FS->Dexed->ZynChorus->Layer

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 16% (150M/926M)
SD Card: 40% (11G/29G)
Temperature: 54.8ºC

SOFTWARE
zyncoder: code_review (dcb627e)
zynthian-ui: sprint_2021.02.27 (ac7e976)
zynthian-sys: master (6d93662)
zynthian-data: master (194fd59)
zynthian-webconf: master (45bcb08)

**Additional context**
This only seems to happen with a mix of layers, e.g. synth and effects. With all synths or all effects it behaves as expected.

**Comment by jofemodo** [comment]
You probably bold-push layer, that jumps to layers screen. From control screen:

+ short-layer => rotate layers
+ bold-layer => layers screen

Cheers,

**Comment by riban-bw** [comment]
Really odd! This was completely reproducable and consistent behaviour yesterday but today it behaves correctly. I will close this ticket and if I figure out the workflow that leads to this issue, reopen.
