### ISSUE TITLE
Master Tuning (cents) and BPM - Double instead Integer

### ISSUE THREAD

**Issue by kosmasolarius** [zynthian/zynthian-issue-tracking#384]
I am producing and performing so-called cosmic octave (planetary tunings) tracks.
Each planet tuning has a very specific set of data. I gonna add an example screenshot of the Earth Year tuning.

So, for each case, I need to set the BPM and Master Tuning in Hz or cent at a very precise range (Double) and It would be amazing to be able to, first of all, get those settings in the Zynthian at all, which is not the case right now and of course, saving it with the track. I am thinking of templates, which I can quickly recall. Of course, the Snapshots are just that.

I would like to be quickly able to switch between planet tunings, so I could use the Zynthian for my live performances and just click on the planet snapshot, and all are tuned in the right way and in the correct BPM.

I have mentioned this issue with Zynthian only offering Integer numbers for Tuning and Tempo, which makes it useless for me.
![Screenshot 2021-03-12 at 15 41 53](https://user-images.githubusercontent.com/14310696/110958442-fc628400-834c-11eb-8ff5-8c43b6b4a884.png)

**Comment by jofemodo** [comment]
Regarding tuning, it's not too complex to implement.
Simply update, reboot and test ;-)

Anyway, you have to realize that Zynthian uses the MIDI "pitch bending" for fine tuning most of engines, and this impose some limitations:

+ The frequency resolution is about 1/41 cents (1 tone=100 cents)
+ You can not fine tune more than +/-1 tone over 440.0. If you want more, you have to transpose (coarse tune).

Regarding the Tempo, Mr. @riban is the man ;-)

Cheers,

**Comment by kosmasolarius** [comment]
Thank's @jofemodo for the quick action. 
Tuning is my specialty, I know well about the usual limitations in DAWs and instruments. 
I did the update and saw, that I have now the option to type in Master Tuning I need. 
As I can see this, the tuning is also stored in the Snapshot, which is great.
The tuning range of a1 is of course within the key of a1 (100 cents).
To catch any possible wrong inputs from people, who don't know about the exact tuning range for a1, ArrowUP/ArrowDown and Cent changes would be maybe a safe solution to do this setting. Now I seem to be able to type in any number, but Master Tuning has a clear range. 

So, if the Setting would say Master Tuning a1 440Hz and then a field where I can dial up and down the cent might be the most secure way to avoid errors. 
Any other changes (semitones) need to be done in the synth settings. That's normal. 
I am just thinking of user-friendly ways of changing the setting. 

For me, this works as it is right now. I am happy.
I have my own tuning calculator and a table of all planetary tunings, so I will prepare a MIDI setting for each planet and then I can just quickly switch between tunings if I need to. 

Mr. @riban mentioned already, that the BPM in floating numbers will be his part. 
Thanks for the great work.

**Comment by riban-bw** [comment]
Note on tuning: This sets MIDI pitchbend so the actual frequency offset depends on the pitchbend range of each engine.

I have started work on tempo. Tempo is already calculated with double accuracy but exposed to user as integer. I need to change this in a few places which _should_ be trivial but how to present this to the user? Most users don't want to rotate the encoder hundreds of times to change tempo by a few BPM. Also what resolution? 0.1? 0.01? 0.001?

**Comment by riban-bw** [comment]
I have added the functionality to the development branch by using the tempo (SNAPSHOT) encoder to adjust in whole BPM. If you select Tempo from the menu then the SELECT or LAYER encoders adjust in whole BPM but the SNAPSHOT encoder becomes a fine control, adjusting in 0.1 BPM. This may still be too large a step for you. Please advise @kosmasolarius.

**Comment by kosmasolarius** [comment]
> Note on tuning: This sets MIDI pitchbend so the actual frequency offset depends on the pitchbend range of each engine.
> 
> I have started work on tempo. Tempo is already calculated with double accuracy but exposed to user as integer. I need to change this in a few places which _should_ be trivial but how to present this to the user? Most users don't want to rotate the encoder hundreds of times to change tempo by a few BPM. Also what resolution? 0.1? 0.01? 0.001?

2 decimal points is perfect. 0.01 BPM - That is precise enough for any case.

**Comment by kosmasolarius** [comment]
> I have added the functionality to the development branch by using the tempo (SNAPSHOT) encoder to adjust in whole BPM. If you select Tempo from the menu then the SELECT or LAYER encoders adjust in the whole BPM but the SNAPSHOT encoder becomes a fine control, adjusting in 0.1 BPM. This may still be too large a step for you. Please advise @kosmasolarius.

If a number block would show up to type in the actual bpm, it would be perfect. selecting only straight BPM might do for the most to play around with, but it would slow down the workflow a lot to have to go in the snapshot setting to get the BPM I need.
I already used the MIDI present option to set up all planet tunings I need, so I can now quickly select any tuning, by switching between the MIDI presets. 
I wish I could have something like a template, where I can define what parameters I want to have for my track. 
Why not adding the BPM also into the MIDI preset? The tempo is part of the MIDI specs too.
If you add it there and let me type in the BPM I need, like I, can now freely type in the tuning in Hz, I would be able to add this to the presets I already created. Should be the easiest solution to add Tempo to the Midi section too.

**Comment by riban-bw** [comment]
@kosmasolarius There isn't a MIDI command for tempo.

The current tempo is currently stored with the snapshot but I think it would be inapproriate to store it with sub-snapshots. The sub-snapshot mechanism allows fast recall of presets and configuration for performance but this may be used at arbitrary times, e.g. during performance when you don't want running sequences to change tempo. It is planned to add tempo change events to sequences (partially implemented but needs more work) which may provide some of your required functionality. Tempo changes could be added at required time during sequenced playback or added to _dummy_ sequences whose prime purpose is to change tempo. These could be fired off from ZynPad or using MIDI triggers as required during live performance.

Regarding keyboard entry of tempo, this requires some development which may not be imminent.

**Comment by kosmasolarius** [comment]
@riban-bw  MIDI Beat clock...
Timecode is sent by MIDI to other devices. You can not only send a Sync signal but also the timecode, so the tempo is transmitted as well.

[](https://en.wikipedia.org/wiki/MIDI_beat_clock)

It should be possible to make Zynthian the Master and other devices Slave and that requires not only a Sync signal but also Tempo and in some cases Song-Position as well. 
It would be very limiting if I had to make a sequence, so I can define an overall Tempo. 
The tempo is also important for Delay Time for example, so Tempo is something required also without having a sequence going. 


**MIDI Clock**

**Purpose:**
Some master device that controls sequence playback sends this timing message to keep a slave device in sync with the master. A MIDI Clock message is sent at regular intervals (based upon the master's Tempo) in order to accomplish this.

**Status**
0xF8


**Errata**
There are 24 MIDI Clocks in every quarter note. (12 MIDI Clocks in an eighth note, 6 MIDI Clocks in a 16th, etc). Therefore, when a slave device counts down the receipt of 24 MIDI Clock messages, it knows that one quarter note has passed. When the slave counts off another 24 MIDI Clock messages, it knows that another quarter note has passed. Etc. Of course, the rate that the master sends these messages is based upon the master's tempo. For example, for a tempo of 120 BPM (ie, there are 120 quarter notes in every minute), the master sends a MIDI clock every 20833 microseconds. (ie, There are 1,000,000 microseconds in a second. Therefore, there are 60,000,000 microseconds in a minute. At a tempo of 120 BPM, there are 120 quarter notes per minute. There are 24 MIDI clocks in each quarter note. Therefore, there should be 24 * 120 MIDI Clocks per minute. So, each MIDI Clock is sent at a rate of 60,000,000/(24 * 120) microseconds).

A slave device might receive (from a master device) a Song Select message to cue a specific song to play (out of several songs), a Song Position Pointer message to cue that song to start on a particular beat, a MIDI Continue in order to start playback from that beat, periodic MIDI Clocks in order to keep the playback in sync with the master, and eventually a MIDI Stop to halt playback.

**Comment by riban-bw** [comment]
MIDI clock can be sent from Zynthian by adding a MIDI Clock plugin. That is not the same as storing the current tempo. Tempo can be derived over time from a clock signal but the instantaneous tempo is not sent and is not part of the MIDI 1.0 standard.
