### ISSUE TITLE
Clear All Button in LV2 selection menu

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#385]
**Is your feature request related to a problem? Please describe.**
We have A LOT of LV2 items by default and the selection of an engine or component if building a layer can be quite involved in the GUI.
The enabled feature certainly makes this useful, but increasingly users are clearing down the list to aid GUI interaction.

**Describe the solution you'd like**
A clear and default button which allow all lv2's to be cleared & the default restored.

**Describe alternatives you've considered**
Going throu' them individually and dis enabling them

**Additional context**
![image](https://user-images.githubusercontent.com/79083/110961785-164d9800-8348-11eb-8e48-e182aa6141c6.png)

![image](https://user-images.githubusercontent.com/79083/110962514-fcf91b80-8348-11eb-969c-90fa02bde00d.png)

**Comment by riban-bw** [comment]
Rleated to #138.
