### ISSUE TITLE
MIDI port names with spaces are not handled by webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#392]
**Describe the bug**
You cannot disable any MIDI port with a space in its name.

**To Reproduce**
1. Go to webconf Interface->MIDI Options
2. Click on 'MIDI Ports +' button
3. Disable a MIDI INput port which has a space in its title
4. Check routing, e.g. with patchage

**Expected behaviour**
MIDI port is unrouted from ZynMidiRouter.

**Actual behaviour**
MIDI port is remains routed to ZynMidiRouter.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 21% (425M/1939M)
SD Card: 38% (10G/28G)
Temperature: 45.0ºC

SOFTWARE
zyncoder: master (3c914fe)
zynthian-ui: master (84a7f25)
zynthian-sys: master (348f40c)
zynthian-data: master (194fd59)
zynthian-webconf: master (c8cd1a6)

**Additional context**
Initial investigation shows that webconf uses the midi_port['id'] from configuration but displays the midi_port['alias']. The id seems to have spaces replaces with underscores hence attempts to unroute this fail due to wrong jack name.

**Comment by riban-bw** [comment]
Looks like there is a double assumption where spaces are replaced by underscores then later underscores are replaced by spaces with the assumption that you end up with the original name but this fails to handle names that have spaces / underscores to start with.

**Comment by riban-bw** [comment]
Closed prematurely. This issue persists.

**Comment by riban-bw** [comment]
Actually - the fix / work-around does remain valid. There may need to be some work done to handle other MIDI issues but I will close this ticket and await reports of specific issues.

**Comment by jofemodo** [comment]
But where is the fix? There is no commit associated to this issue ...

**Comment by riban-bw** [comment]
https://github.com/zynthian/zynthian-sys/pull/194 mitigates this issue.

**Comment by jofemodo** [comment]
OK! Now I remember this strange issue...
