### ISSUE TITLE
Discourse activation email not sent

### ISSUE THREAD

**Issue by duncanbeevers** [zynthian/zynthian-issue-tracking#394]
**Describe the bug**
It is not possible to sign up for the Zynthian Discourse forums.
No activation email is sent.

**To Reproduce**
1. Go to https://discourse.zynthian.org
2. Click on `Sign Up`
3. Sign up with a new email address, or attempt to send a new activation email to an unactivated account
4. No email arrives

![Image of unactivated account message](https://user-images.githubusercontent.com/7367/111081148-1e7c1380-84bf-11eb-9838-44cd0dd16a22.png)

**Comment by jofemodo** [comment]
Of course it sends emails, but your email domain is probably rejecting our email server. Some email servers are too paranoids. Our email server is not listed in any black list and we have a quite decent configuration for the domain and also the server, but still we have problems with some of them. Could you tell me what email domain did you use? Could you try with gmail or something like that?

Thanks

**Comment by duncanbeevers** [comment]
When I try to sign up with Google as an oauth provider, I get this error;

![2021-03-14 at 7 44 PM](https://user-images.githubusercontent.com/7367/111097071-0d062c00-84fe-11eb-90f3-a3ebc4a2f8ce.png)

**Comment by duncanbeevers** [comment]
Email(s) arrived after 17 hour flight time.

| GHI Opened | Email Received |
|-|-|
| 2021-03-14T19:17:18Z | Mon, 15 Mar 2021 04:52:35 -0700 (PDT) |
