### ISSUE TITLE
Third party repositories are uncontrolled in stable branch

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#403]
**Describe the bug**

Updating stable branch may update third party software to an unstable (or untested) versoin.
Zynthian uses several third party repositories, e.g.  https://github.com/dcoredump/dexed.lv2. The update mechanism pulls from directly from these repositories. A user performing an update on stable will expect their device to remain stable and for any updates to be tested for valid integration with Zynthian. This is not currently the case.

**To Reproduce**
Steps to reproduce the behaviour:
1. Perform software update from UI or webconf

**Expected behaviour**
Software and plugins are updated from Zynthian repository - testing or stable as appropriate.

**Actual behaviour**
Software and plugins are updated directly from third party sources.

**Hardware**
- Raspberry Pi 3 Model B Plus Rev 1.3
- Soundcard: HifiBerry DAC+ ADC PRO
- Display: ZynScreen 3.5 (v1)
- Wiring: MCP23017_ZynScreen
- GPIO Expander: MCP23017

**System**
- Raspbian GNU/Linux 10 (buster)

- Build Date: 2020-05-27
- Memory: 12% (113M/926M)
- SD Card: 40% (11G/29G)

**Software**
- zyncoder: stable (d852c8f)
- zynthian-ui: stable (6cdb0ad)
- zynthian-sys: stable (140eac7)
- zynthian-data: stable (194fd59)
- zynthian-webconf: stable (b64c737)

**Additional context**
It is important that the Zynthian stable release does not change unexpectedly. Its purpose is to ensure a known working system. This is not possible if software is updated without warning or test from other sources.

I suggest cloning third party sources into the Zynthian GitHub project and adjusting update scripts to update from there. We should monitor all third party sources for updates and process them like any other development thought the pull request - test - merge to testing process.

**Comment by riban-bw** [comment]
Some projects affected:

- setBfree
- preset2lv2 (@jofemodo)
- mod-host
- dexed.lv2

**Comment by jofemodo** [comment]
Not only third party repositories. When running update recipes from testing zynthian-sys, software from official and third party repositories can be installed/updated, and "irreversible" modifications can be done to the system, rendering it unusable if returning to the stable version. What i mean is that we have not a robust mechanism for undoing system changes that can be made by the update recipes.

Anyway, i could block third party software updates **while being on stable**.Once stable is left, yet temporary, irreversible changes can be produced that avoid returning to stable easily. This would improve a little bit the issue.

**Comment by riban-bw** [comment]
A fix for the third party repos would be to fork them into Zynthian project and point Zynthian at the forks. Then we have control over when the fork is updated and tested. We can create testing and stable branches in our fork and merge upstream changes to testing, then during a stable release merge these changes to stable. That way we have total control over the version we have in Zynthian. I feel this is better to have control over what hits testing rather than letting upstream change Zynthian behaviour without our knowledge.

Regarding other irreversable changes - I would suggest breaking out to a seperate issue and detailing examples so that we can consider solutions.

**Comment by riban-bw** [comment]
An alternative to forking the third party projects is to modify the update scripts to check for a specific git revision. I have done this in the zynthian-sys add_riban_lv2_plugins branch. We can define the _stable_ revision in the update file and update it when we want to test / deploy a new version.

**Comment by jofemodo** [comment]
Yes. Some package's install scripts use stable versions. 

If we want to have a really stable version, certainly we should  have control over the software versions installed by the update system. In stable, every update script should define a "stable" version/branch for the updated package. Other branches could use different versions/branches. So, for having smooth transitions when changing from testing to stable, update recipes should test the installed version and and re-install if it's different to the defined one.

Regards,

**Comment by riban-bw** [comment]
This could / should be resolved when https://github.com/zynthian/zynthian-sys/issues/202 is complete.

**Comment by riban-bw** [comment]
Closing as now tracking in  zynthian/zynthian-sys#202.
