### ISSUE TITLE
Zyncoder rebuilding on every update

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#405]
**Describe the bug**
Part of the software update is to check libraries and rebuild then if required. It seems that zyncoder is rebuilt on every update.

**To Reproduce**
1. Run `update_zynthian_code.sh` twice

**Expected behaviour**
First run may rebuild libraries. Second run should not rebuild any libraries.

**Actual behaviour**
Zyncoder rebuilt on every run.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 19% (178M/926M)
SD Card: 40% (11G/29G)

SOFTWARE
zyncoder: stable (d852c8f)
zynthian-ui: testing (6cdb0ad)
zynthian-sys: testing (8705d1c)
zynthian-data: stable (194fd59)
zynthian-webconf: stable (b64c737)

**Additional context**
```
./update_zynthian_code.sh
Updating zyncoder ...
/zynthian/zyncoder /zynthian/zyncoder
/zynthian/zyncoder/build /zynthian/zyncoder /zynthian/zyncoder
++ Defined HAVE_WIRINGPI_LIB
++ Defined MCP23017_ENCODERS
++ Defined MCP23017 INTA PIN
++ Defined MCP23017 INTB PIN
++ Using wiringPI
-- Configuring done
-- Generating done
-- Build files have been written to: /zynthian/zyncoder/build
[ 60%] Built target zyncoder
[100%] Built target zyncoder_test
/zynthian/zyncoder /zynthian/zyncoder
/zynthian/zyncoder
Updating zynthian-ui ...
/zynthian/zynthian-ui/zynlibs/jackpeak /zynthian/zynthian-ui
/zynthian/zynthian-ui/zynlibs/jackpeak/build /zynthian/zynthian-ui/zynlibs/jackpeak /zynthian/zynthian-ui
-- Configuring done
-- Generating done
-- Build files have been written to: /zynthian/zynthian-ui/zynlibs/jackpeak/build
[100%] Built target jackpeak
/zynthian/zynthian-ui/zynlibs/jackpeak /zynthian/zynthian-ui
/zynthian/zynthian-ui
/zynthian/zynthian-ui/zynlibs/zynsmf /zynthian/zynthian-ui
/zynthian/zynthian-ui/zynlibs/zynsmf/build /zynthian/zynthian-ui/zynlibs/zynsmf /zynthian/zynthian-ui
-- Configuring done
-- Generating done
-- Build files have been written to: /zynthian/zynthian-ui/zynlibs/zynsmf/build
[100%] Built target zynsmf
/zynthian/zynthian-ui/zynlibs/zynsmf /zynthian/zynthian-ui
/zynthian/zynthian-ui
/zynthian/zynthian-ui/zynlibs/zynseq /zynthian/zynthian-ui
/zynthian/zynthian-ui/zynlibs/zynseq/build /zynthian/zynthian-ui/zynlibs/zynseq /zynthian/zynthian-ui
-- Configuring done
-- Generating done
-- Build files have been written to: /zynthian/zynthian-ui/zynlibs/zynseq/build
[100%] Built target zynseq
/zynthian/zynthian-ui/zynlibs/zynseq /zynthian/zynthian-ui
/zynthian/zynthian-ui
Updating zynthian-webconf ...
Update Complete.
```

**Comment by riban-bw** [comment]
There are plans to review zyncoder implementation during which I recommend considering creating a more robust / less intrusive update mechanism. Maybe it becomes a deb package or there is a different method of checking for rebuild. It would make sense for this library to be delivered as a binary package rather than compiling on target systems.

**Comment by jofemodo** [comment]
OK to review it, but ... there are no real issues regarding this! The zyncoder library builds perfectly OK on every zynthian, and  time consumed by this is negligible. Sometimes, building from code are the easier and safer way of installing software. Languages like python "compile" the code when needed and cache the "binary". I prefer this approach for zynthian especific libraries, as it integrates nicely with our "git-based update" system. I don't think using deb packages is a good idea for this, unless we use deb packages for everything, including zynthian-ui, zynthian-webconf, etc.

Regards,
