### ISSUE TITLE
zynthian-sys repository not cloning to Windows

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#406]
**Describe the bug**
Attempts to clone zynthian-sys repository to a Windows machine using Tortoise-Git fail.

**To Reproduce**
1. Within File Explorer right click on a folder and select Git clone...
2. Enter URL: https://github.com/zynthian/zynthian-sys.git
3. Click OK

**Expected behaviour**
Repository clones to local directory.

**Actual behaviour**
Repository clones but fails to checkout with error / log:
```
git.exe clone --progress -v "https://github.com/zynthian/zynthian-sys.git" "C:\Users\brian\Documents\Zynthian\zynthian-sys"
Cloning into 'C:\Users\brian\Documents\Zynthian\zynthian-sys'...
POST git-upload-pack (625 bytes)
remote: Enumerating objects: 158, done.
remote: Counting objects: 100% (158/158), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 5464 (delta 91), reused 103 (delta 45), pack-reused 5306
Receiving objects: 100% (5464/5464), 4.39 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (3827/3827), done.
error: invalid path 'etc/systemd/vncserver@:1.service'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

git did not exit cleanly (exit code 128) (3531 ms @ 20/03/2021 09:58:59)
```

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 19% (178M/926M)
SD Card: 40% (11G/29G)

SOFTWARE
zyncoder: stable (d852c8f)
zynthian-ui: testing (6cdb0ad)
zynthian-sys: testing (8705d1c)
zynthian-data: stable (194fd59)
zynthian-webconf: stable (b64c737)

**Additional context**
It looks like Windows does not like the filename `etc/systemd/vncserver@:1.service`.

I find Tortoise tools on my Windows laptop useful for some awkward git analysis hence occasionally checkout the Zynthian project for development and testing purposes.

Windows 10 Pro
20H2

TortoiseGit 2.11.0.0
git version 2.28.0.windows.1

**Comment by jofemodo** [comment]
This kind of filenames are not strange on Linux systems, and it's reasonable we can have these files on our repository.
Of course, we could add complexity to the config system and rename the files when installing, but i don't like.Why not using Linux for zynthian development?

Regards,

**Comment by riban-bw** [comment]
I am constrained by the operating systems that I must use on the only available PCs I have. (Well... I have some Linux netbooks but they are small and less suitable for dev.) Also the Tortoise tool is excellent for some tasks. I only use this when I need to do something that I can't do (or is significantly more irksome to do) on the Linux (Zynthian) command line (where I feel most at home). I agree this is very low priority and can be rejected but wanted to highlight the issue that affected me.

Whilst here though... why is this called this? It is an odd name that serves little purpose. I had to use this, including an escape backslash in the Python code recently and it just felt wrong to have a name that isn't very descriptive and is awkward to read. I would prefer this service be renamed to vncserver or vncserver1. the `@:` isn't very nice to have in the servic name.
