### ISSUE TITLE
Toggle VNC does not restart all engines

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#407]
**Describe the bug**
When VNC is toggled in the admin menu the engines with GUIs are restarted to ensure the continue to operate. This fails for some engines.

**To Reproduce**
1. Enable VNC
2. Add Pianoteq LV2 to layer 1
3. Add Helm LV2 to layer 2
4. Observe both GUIs in NoVNC viewer
5. Observe both engines operate as expected
6. Disable VNC
7. After approx. 10s check both engines are operational
8. Enable VNC
9. After approx. 10s check both engines are operational

**Expected behaviour**
Within 10s both engines are operational.

**Actual behaviour**
Within 10s of **disabling** VNC Helm is operational but Pianoteq has failed to start.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 19% (178M/926M)
SD Card: 40% (11G/29G)

SOFTWARE
zyncoder: stable (d852c8f)
zynthian-ui: testing (6cdb0ad)
zynthian-sys: testing (8705d1c)
zynthian-data: stable (194fd59)
zynthian-webconf: stable (b64c737)

**Additional context**
Extract from journal in reverse order (newest at top)
```
Mar 20 10:24:12 zynthian startx[495]:     0: re.compile(b'\n> ')
Mar 20 10:24:12 zynthian startx[495]: searcher: searcher_re:
Mar 20 10:24:12 zynthian startx[495]: delayafterterminate: 0.1
Mar 20 10:24:12 zynthian startx[495]: delayafterclose: 0.1
Mar 20 10:24:12 zynthian startx[495]: delaybeforesend: 0
Mar 20 10:24:12 zynthian startx[495]: searchwindowsize: None
Mar 20 10:24:12 zynthian startx[495]: ignorecase: False
Mar 20 10:24:12 zynthian startx[495]: maxread: 2000
Mar 20 10:24:12 zynthian startx[495]: logfile_send: None
Mar 20 10:24:12 zynthian startx[495]: logfile_read: None
Mar 20 10:24:12 zynthian startx[495]: logfile: None
Mar 20 10:24:12 zynthian startx[495]: delimiter: <class 'pexpect.exceptions.EOF'>
Mar 20 10:24:12 zynthian startx[495]: timeout: 20
Mar 20 10:24:12 zynthian startx[495]: closed: False
Mar 20 10:24:12 zynthian startx[495]: child_fd: 32
Mar 20 10:24:12 zynthian startx[495]: pid: 5186
Mar 20 10:24:12 zynthian startx[495]: flag_eof: True
Mar 20 10:24:12 zynthian startx[495]: exitstatus: 1
Mar 20 10:24:12 zynthian startx[495]: match_index: None
Mar 20 10:24:12 zynthian startx[495]: match: None
Mar 20 10:24:12 zynthian startx[495]: after: <class 'pexpect.exceptions.EOF'>
Mar 20 10:24:12 zynthian startx[495]: before (last 100 chars): b'set 81 0.583333\r\n'
Mar 20 10:24:12 zynthian startx[495]: buffer (last 100 chars): b''
Mar 20 10:24:12 zynthian startx[495]: args: ['/usr/local/bin/jalv', '-n', 'Pianoteq_7_STAGE-00', 'http://pianoteq.com/lv2/Pianoteq7STAGE']
Mar 20 10:24:12 zynthian startx[495]: command: /usr/local/bin/jalv
Mar 20 10:24:12 zynthian startx[495]: <pexpect.pty_spawn.spawn object at 0xaa351bb0>
Mar 20 10:24:12 zynthian startx[495]: ERROR:zynthian_engine.proc_cmd: Can't exec engine command: set 81 0.583333 => End Of File (EOF). Exception
```

**Comment by riban-bw** [comment]
Any further attempt to load Pianoteq LV2 failes until either reboot or restart VNC, e.g. remove all layers then add Pianoteq LV2 layer fails. It seems that Zynthian is upset with running jalv pianoteq after this change until a reboot.

**Comment by riban-bw** [comment]
This does not occur when running zynthian manually from a ssh command line but always fails when running from startup scripts and disabling VNC.

Helm seems to behave the opposite to Pianoteq. Helm will only run with VNC disabled whilst PT only runs with VNC enabled.

**Comment by riban-bw** [comment]
I have found that there is a check if remote display is enabled which checks for `DISPLAY` in `/root/.remote_display_env`. This works during boot but at some point after that `/root/.remote_display_env` gets overwritten and the `DISPLAY` entry is removed. I see this `/etc/profile.zynthian` seems to perform this operation, writing a new file. This means that subsequent attempts to launch engines result in headless versions running.

**Comment by riban-bw** [comment]
`/zynthian/zynthian-sys/etc/profile.zynthian` is sourced by `/root/.profile` so this gets called when logging in as root user. It looks like there is a conflict here. I suggest we lose the ability to implicitly forward display over X and require user to explicitly do so if they need it. I will add some changes to the branch I am working on.

@jofemodo are you happy to lose default X-forwarding of display over ssh? (It doesn't work now anyway!)

**Comment by riban-bw** [comment]
This is fixed by PR https://github.com/zynthian/zynthian-ui/pull/366. I was able to retain the ability to forward over ssh but it is now explicit, i.e. you need to set the env var `ZYNTHIAN_X11_SSH` before starting zynthian manually but this is better (more functional) than it is in _stable_ and _testing_.

This implementation is quite simple but I think I have caught everything. Please test.

**Comment by jofemodo** [comment]
I fixed some details on jalv and now i can't reproduce the issue from the description. Of course, probably there are other cases that cause problem. Could you test?
