### ISSUE TITLE
unwanted cmdline.txt overwrite

### ISSUE THREAD

**Issue by jpnielsen** [zynthian/zynthian-issue-tracking#409]
Hello, I'm new to zynthian, and thought i would try it on a PI400 with a focusrite2i2 usb audio device + USB midi keyboards.

It presumably works as intended, but i have moved my boot and root to a USB device, that i boot from with the PI400
so, i have changed the /boot/cmdline.txt to have root=/dev/sda2 instead of root=/dev/mmblk0p2

every time i go to the webinterface, and change something, this get s overwritten...
so, i changed /zynthian/zynthian-sys/boot/cmdline.txt too to the new root location.
but when i do a software update, this gets overwritten.

Can you please make the change of root device a configurable persistent option ?

Thank you

**Comment by jofemodo** [comment]
Avoiding the overwriting is not easy, but auto-restoring your changes on it is trivial. Please, read this:

https://discourse.zynthian.org/t/no-sound-after-update-warning-zynthian-autoconnect-cb-jack-xrun/5274/32

It would show you a reasonable way of solving the problem.

Regards,
