### ISSUE TITLE
wlan0 network interface missing

### ISSUE THREAD

**Issue by ukch** [zynthian/zynthian-issue-tracking#41]
**Describe the bug**
On the Zynthian pre-built image `zynthian_gorgona_omega_rbpi3_kitv2-2018-04-03.zip`, there appears to be no wireless network interface. Although I have set up wifi through the web UI, there is no `wlan0` network interface, or any network interface other than `lo` and `eth0`.

Here's some debugging info:
```
# ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:6c:c5:83  
          inet addr:192.168.1.241  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::1f39:f1ca:e54f:cab6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:27214 errors:0 dropped:13 overruns:0 frame:0
          TX packets:9401 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:34642138 (33.0 MiB)  TX bytes:1482419 (1.4 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1216 (1.1 KiB)  TX bytes:1216 (1.1 KiB)

# iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

# iwlist wlan0 scan
wlan0     Interface doesn't support scanning.
```

**To Reproduce**
1. Flash the image onto an SD card
2. Boot the RPi with ethernet connected
3. SSH into the RPi
4. `iwlist wlan0 scan`

**Expected behavior**
The command should scan for wireless networks in range and show their SSIDs.

**Setup:**
 - SD-image: `zynthian_gorgona_omega_rbpi3_kitv2-2018-04-03.zip`
 - Hardware Config: RPi3, hand-soldered Zynthian main board, USB sound card, PiScreen2
 - Software Version: Default based on the SD-image

**Comment by jofemodo** [comment]
Gorgona is at the end of its life cycle now and It's not recommended to use it. You should be using the new Aruk image .
