### ISSUE TITLE
Attempt to set engine note range goes to wrong screen.

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#412]
**Describe the bug**
If you try to adjust the Note Range then try again you end up in the wrong screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add synth engine layer
2. Bold press to access layer's context menu
3. Select "Note Range & Transpose"
4. Click Back
5. Select "Note Range & Transpose"

**Expected behaviour**
Note Range & Transpose screen displayed.

**Actual behaviour**
Layer's control screen displayed.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 48% (446M/926M)
SD Card: 41% (11G/29G)
Temperature: 56.4ºC

SOFTWARE
zyncoder: testing (d852c8f)
zynthian-ui: issue_352_lv2_gui_broken (0064356)
zynthian-sys: testing (c7648a4)
zynthian-data: testing (194fd59)
zynthian-webconf: testing (b64c737)

**Additional context**
That's all!

**Comment by jofemodo** [comment]
It's fixed now, at less on testing.
