### ISSUE TITLE
TEMPO doesn't show up anymore.

### ISSUE THREAD

**Issue by kosmasolarius** [zynthian/zynthian-issue-tracking#413]
Tempo is still visible in the sequencer menu, but when I click on it nothing happens.
So, it doesn't show up anymore.

I updated today from the UI first and then again from the webconfig because after the update in the UI installation it told me installed with 17 errors, so I did the webconfig software update.

**Comment by jofemodo** [comment]
This has been fixed urgently on testing & stable versions:

https://github.com/zynthian/zynthian-ui/issues/370

Simply update and test.
