### ISSUE TITLE
Selecting tempo from menu causes lockup

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#414]
**Describe the bug**
Selecting tempo from the stepsequencer menu will stop zynthian from operating.

**To Reproduce**
1. Open step sequencer
2. Open menu and selecte "Tempo"
3. Try to adjust tempo

**Expected behaviour**
Tempo changes with associated indication.

**Actual behaviour**
Application locks up requiring repowering.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 40% (372M/926M)
SD Card: 41% (11G/29G)
Temperature: 58.0ºC

SOFTWARE
zyncoder: stable (d852c8f)
zynthian-ui: stable (6cdb0ad)
zynthian-sys: stable (140eac7)
zynthian-data: stable (194fd59)
zynthian-webconf: stable (b64c737)

**Additional context**
This is affecting the stable builld. It is due to a function result being passed as the get_value argument rather than the function itself. A fix is ready to push.

**Comment by riban-bw** [comment]
Fix applied in branch hotfix/414_tempo_menu. This should be tested ASAP and deployed as a hotfix to stable.

I observed that adjustment of the menu selected tempo uses the coarse adjustment on select encoder and fine adjustment on learn.shot encoder. I don't know if we want to retain this or implement encoder acceleration (which was previously removed)? I suggest that be considered as a separate issue and this fix be tested and deployed to allow this bug to be resolved rapidly as it has substantial impact on users.

**Comment by jofemodo** [comment]
It works. Tested and merged.

The "dynamic step" feature is only implemented in the "snapshot" encoder. The rest of rotaries work step by step.But it seems coherent to conserve the "select" rotary action, and ideally it should implement "dynamic step". I also would like to enable the "dynamic step" when it's convenient:

+ Pattern Editor Cursors, specially X, when N steps is big.
+ Parameter Editor, when "num of allowed values" is great

Thanks!
