### ISSUE TITLE
Sequencer stops playing out of no obvious reason and restarts by itself

### ISSUE THREAD

**Issue by kosmasolarius** [zynthian/zynthian-issue-tracking#415]
**Describe the bug**
I just updated, due to the tempo-menu bug in the sequencer.
Now I programmed a simple sequencer with 3 layers.
I pressed play on all pads and out of the blue it just stops by itself, just to restart a few moments later, and keeps doing this.
All the play arrows stay green - basically the audio stops and no audio levels are shown on the top right and also the 'm' symbol disappears for the period of no sound - just to come back by itself. 

**To Reproduce**
created 2 synths (ZY Fantasy/Space Choir and ZY Arpeggios/Soft Arpeggio1) and 1 drum layer (FS/AVL Drmkits Perc)
programmed simple patterns in the sequencer
pressed play on all 3 pads
music runs for some time and then stops. 
simple 4 bar loop

**Expected behavior**
...well, it should keep playing

**Screenshots**
VNC Viewer won't let me connect to the Zynthian (error msg: 

**Setup:**
 - Hardware Config: Raspberry Pi 4 8GB, TRAKTOR AUDIO2, 7'' Pi Touchscreen
 - Software Version: Just updated to the newest version of Zynthian.

**Comment by kosmasolarius** [comment]
After the shutdown of the Pi and reboot, it seems to run stable now. 
No idea how to recreate the issue.

**Comment by kosmasolarius** [comment]
Just changed Tempo during play mode and then the error appeared again.

**Comment by kosmasolarius** [comment]
left the sequencer to save the snapshot and the error appeared as well.

**Comment by riban-bw** [comment]
Please provide a screenshot of webconf so we can see the hardware and software versions.

**Comment by riban-bw** [comment]
I have followed the instructions and cannot reproduce this on Testing branch. I have three sequences with the detailed instruments running and they continue to run. Adjusting tempo and navigating around the menus, etc. does not stop playback. If it reoccurs please capture the snapshot and if possible look at logs (visble in webconf INTERFACE->UI Log).
