### ISSUE TITLE
Reboot from Zynthian Admin ends up with black screen

### ISSUE THREAD

**Issue by kosmasolarius** [zynthian/zynthian-issue-tracking#416]
**Describe the bug**
Rebooting from the Zynthian Admin ends up with a black screen.
Only switching off and on again does bring back the UI.

**To Reproduce**
Go in the Admin, click Reboot

**Expected behavior**
A reboot of the system.

**Screenshots**
black screen

**Setup:**
 - Hardware Config: Pi4 8GB, Traktor Audio2, Pi 7'' touchscreen
 - Software Version: updated today

**Comment by riban-bw** [comment]
This is not reproducible with standard Zynthian. Please provide a screenshot of webconf so we can see all the hardware and software.

**Comment by jofemodo** [comment]
Too old!
