### ISSUE TITLE
Starting an entire Pad row in the ZynSeq at once

### ISSUE THREAD

**Issue by kosmasolarius** [zynthian/zynthian-issue-tracking#417]
**Is your feature request related to a problem? Please describe.**
The problem is, that I can only start one Pad after the other.

**Describe the solution you'd like**
let's say I programmed all 4x4 Pads of the sequencer and I would like to start the entire row at the same time.
Or maybe I want to start A + C simultaneously. The touchscreen doesn't seem to allow me to press multiple Pads, so they would start at the same time. 

**Additional context**
Like in Bitwig Studio or Ableton Live the sessions work this way. I can fire off an entire row at once. 
This would be a great functionality in a live situation to be able to fire off an entire row, so multiple Pads start synchronously.

**Comment by Mickinator** [comment]
Hi,
As long as it's not integrated you can start a row of pads using an app like "Midi Makros" to send all the wished Master-Note-on-Midi-Commands with one fingertip.

Or you build a small Contoller with an arduino nano to do that 👍😂🌈

**Comment by riban-bw** [comment]
Sequences will start to play at the beginning of the next bar so you can tap each pad in rapid succession to prime them to start together. If you want this before any sequences are already running then you can use an empty (or click) sequence as a count-in.

This is the workflow designed for this function and I would prefer not to add an extra macro layer which will add complexity to the UI.
