### ISSUE TITLE
Multiple USB midi issue

### ISSUE THREAD

**Issue by Ejdzi2** [zynthian/zynthian-issue-tracking#420]
**Describe the bug**
There is a problem with usb midi controlers if there is more than four attached to Zynthian (with usb hub). Four working properly but the 5th seems to be not recognising by ALSA.

**To Reproduce**
1. Start Zynthian without any usb midi controler
2. Connect usb midi keyboards one by one (no matter if straight or through hub) 
3. ALSA is recognising all the interfaces if it is less than 5. 
4. The 5th not appear in midi ports window.

**Expected behavior**
All connected usb keyboards works properly with Build Date: 2020-04-11 but with updated Build Date:  2020-09-05 or the newest works only with up to 4 usb midi keyboards.

**Setup**
HARDWARE
Raspberry Pi 4 Model B Rev 1.1
Soundcard: HifiBerry DAC+
Display: PiTFT 2.8 Resistive
Wiring: MCP23017_EXTRA
GPIO Expander: MCP23017
SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 6% (131M/1939M)
SD Card: 34% (9.3G/30G)
Temperature: 60.0ºC
SOFTWARE
zyncoder: stable (d852c8f)
zynthian-ui: stable (6cdb0ad)
zynthian-sys: stable (140eac7)
zynthian-data: stable (194fd59)
zynthian-webconf: stable (b64c737)

**Comment by jofemodo** [comment]
Could this issue:

https://github.com/zynthian/zynthian-issue-tracking/issues/421

be related with yours, @Ejdzi2?

Could you try disabling some of the "extra" USB audio devices, like the Pi's headphones or the OTG?
You have to edit the "/boot/config.txt" and reboot.

**Comment by Ejdzi2** [comment]
Yes, this is related (according to this [discourse topic](https://discourse.zynthian.org/t/multiple-usb-midi-issue-edit/5605/31) . After disabling headphones in config.txt all 5 usb keyboards are working.

**Comment by jofemodo** [comment]
I added 2 options for disabling RBPi audio & OTC from the webconf. The new options are located in the Hardware->Audio menu.
This should solve partially the problem of connecting more than 4 midi controllers to zynthian, increasing the limit to 7. It's not perfect, but it's a good improvement ;-)
