### ISSUE TITLE
a2jmidid capturing physical MIDI ports instead of jack

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#422]
**Describe the bug**
Service a2jmidid looks like it should be avoiding grabbing physical MIDI ports but it is.

**To Reproduce**
1. Check a2jmidid ports

**Expected behaviour**
Only grabbing software ports.

**Actual behaviour**
Grabbing physical ports.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 8% (157M/1939M)
SD Card: 72% (9.4G/14G)
Temperature: 47.0ºC

SOFTWARE
zyncoder: testing (d852c8f)
zynthian-ui: testing (cb456cc)
zynthian-sys: testing (0985b47)
zynthian-data: testing (194fd59)
zynthian-webconf: testing (b64c737)

**Additional context**
The service file for a2jmidid has --export-hw commented out but this option seems to be interpreted anyway. This is having adverse effect because alias is not define and attempts to route to the port fail.

**Comment by riban-bw** [comment]
Created dev branch for this fix but need to figure out how to force update to rewrite service file. Looks like something to do with NO_ZYNTHIAN_UPDATE. Maybe @jofemodo can advise.

**Comment by jofemodo** [comment]
It's merged on testing.

Thanks!
