### ISSUE TITLE
Saving a snapshot when parameters not displayed saves as default snapshot for Engine.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#427]
**Describe the bug**
Saving a snapshot ( specifically default) when the parameter page has not been entered stores the location None in the name.
Even thou' the select list may have had a specific preset selected.

Thus 
![image](https://user-images.githubusercontent.com/79083/113282708-333e1100-92df-11eb-888a-24d5df6fab18.png)

**To Reproduce**
1. Go to Load an Engine
2. Scroll up and down in list of presets playing MIDI keyboard to preview sounds
3. Long Press on Snapshot & short press to get to save snapshot page
4. Load the saved snapshot 
5. The default or initial preset will be presented instead of the sound that was playing when the save was performed.

**Expected behavior**
I would expect snapshots to be as selected when the snapshot was saved

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
![image](https://user-images.githubusercontent.com/79083/113283114-bfe8cf00-92df-11eb-99fb-fc50ea691856.png)

**Additional context**
Doesn't inspire confidence

**Comment by jofemodo** [comment]
@wyleu, a preset is not fully loaded until it's "clicked". The preset preview status is not currently saved on snapshots. Of course, you can try to convince developers to change this behaviour, but we need a good reason for making things more complex.
