### ISSUE TITLE
webconf reboot/halt does not work with 2019-06-25-zynthianos-stretch-lite-1.0.0.

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-issue-tracking#43]
**Describe the bug**
- Install 2019-06-25-zynthianos-stretch-lite-1.0.0.
- Boot
- Wait until webconf is up and login to webconf
- Choose System/Reboot and wait 20 seconds
=> If you are logged in via ssh you can determine that nothing happens. Also when beeing not logged in and pinging: no reboot. The same for "Halt"

**To Reproduce**
see above.

**Expected behavior**
Reboot or Halt

**Screenshots**
-

**Setup:**
 - 2019-06-25-zynthianos-stretch-lite-1.0.0.img
 - Raspberry Pi 3 Model B Plus Rev 1.3
 zyncoder: master (80862b6)
zynthian-ui: master (e461d86)
zynthian-sys: master (1723f7b)
zynthian-data: master (676c32a)
zynthian-webconf: master (78c4ac3)

**Additional context**
-

**Comment by jofemodo** [comment]
Sorry Holger, i can't reproduce the bug:
+  I just burned an image from today night build (2019-06-25-zynthianos-stretch-lite-1.0.0.img)
+ Booted and awaited until everything is "stable" ...
+ From webconf, tried the boot / poweroff functionality

Everything worked as expected for me ... please, could your repeat the process?

Regards,

**Comment by dcoredump** [comment]
Ok, thanks Fernando... that's really strange. Why do "I" have all those mystic trouble? @:-) I tried three times... will do this again later.

**Comment by jofemodo** [comment]
It's really curious .... Could it be browser- related?

**Comment by riban-bw** [comment]
The steps to reproduce do not include the step to click the "Reboot" button on the reboot page. Is this step in your procedure? (This was added to a recent update to webconf.)

**Comment by dcoredump** [comment]
Yes, forgot to mention that I pressed "Reboot".

**Comment by dcoredump** [comment]
Hm, ok... I don't know what the problem exactly was. If I am using my hardware Zynthian it works. If I am using a bare Raspi (without display, audio card, ...) and perhaps a slightl underdesigned power supply, it seems not to work.
