### ISSUE TITLE
Pianoteq: Can't load

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#436]
**Describe the bug**
If I try to build a snapshot using pianotec the process stops at choosing Midi Channel. It doesn' t load pianotec-parameters.
In webconf (Software/Pianotec) I get an error (500: Internal Server Error)

**To Reproduce**
1. Layers/Remove all Layers
2. Layers/New Synth Layer
3. Pianoteq 7.2 Stage
4. Midi Channel#1 / Return
4. See error/ Process stopps

**Expected behavior**
I can finish the snapshot building

**Screenshots**
![grafik](https://user-images.githubusercontent.com/55761217/114173098-e2f62d00-9936-11eb-91a0-2a33d4344b82.png)

**Setup:**
![grafik](https://user-images.githubusercontent.com/55761217/114172759-619e9a80-9936-11eb-835c-5ad47a9e8213.png)

**Additional context:**
I can build snapshots using other engines

**Comment by Mickinator** [comment]
Hi everybody,

what am I doing wrong?
Nobody reads my post, nobody answers....
What can I do?

**Comment by jofemodo** [comment]
Hi @Mickinator !

It seems that your PIanoteq installation is not OK You can try to re-install it. 

If it doesn't work, Burn a fresh SD image with the latest stable. The demo works perfectly out the box. Once you check the demo is working OK, you can install the licensed version from the webconf tool. Follow the instructions and it should work with both v6 & v7 binaries.

Regards,

**Comment by Mickinator** [comment]
Hi Jose,

Thanx for the tip to burn a new SD. I made it, and now I can play the pianoteq again. So I will close the issue.
