### ISSUE TITLE
Disable Auto Mute by default

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#437]
**Is your feature request related to a problem? Please describe.**
Hifiberry has a feature to mute the output below a threshold. This gating feature is called auto mute but works really poorly. As the mute starts to operate it crackles with digital distrortion. It is possible to disable auto mute in webconf.

**Describe the solution you'd like**
Auto mute should be disabled by default in the stable image. Other ALSA parameters should also be considered and defaults set, e.g. PGA Gain is set to -0.5dB but should probably be 0dB. Also ADC Left Input should be VIN2[SE] + VIN1[SE] (and similar for ADC Right Input).

**Additional context**
I haven't been able to change auto mute via alsamixer and changes made with webconf do not persist after reboot.

**Comment by jofemodo** [comment]
Hi @riban-bw !

Any of my zynthians with HB DAC+ADC PRO/STAGE have this problem. I don't hear any "gate cut", but anyway, i will do extra testing and will consider adjusting ALSA defaults.

Regards,

**Comment by riban-bw** [comment]
The effect can be exaggerated by playing a piano note then turning volume up for the tail of the note.

**Comment by riban-bw** [comment]
This is still an issue. I just flashed 2104 image and have been tracing a click in various plugins for an hour then just realised it is the automute. I don't see why we wouldn't just disable this by default. If it has no effect for you but is interferring with others' workflows (mine) then it seems like the best thing is to disable. No ill effect for all but big boon for some.

**Comment by jofemodo** [comment]
Sorry! I totally forgot it. I will take a look for disabling this on the ALSA mixer when configuring PRO/STAGE audio cards.
