### ISSUE TITLE
Apt upgrade (disables input devices)

### ISSUE THREAD

**Issue by kanaida2** [zynthian/zynthian-issue-tracking#438]
**Describe the bug**
If I upgrade packages with APT
 Input no longer works. Such as keyboard or mouse.

**To Reproduce**
Apt update
Apt upgrade
Reboot

**Expected behavior**
For input to keep working

**Screenshots**

**Setup:**
 Latest image. Custom kit. Plain raspberry pi 4 with touch screen plus keyboard and mouse.

**Additional context**
Is it safe to upgrade this way usually?

**Comment by jofemodo** [comment]
You shouldn't update with apt. By doing so you will broke things for sure. You should burn a new SD using the latest stable image and don't use "apt upgrade" on it.

**Comment by kanaida2** [comment]
Got it. I recreated my box after that.
