### ISSUE TITLE
OSC CUIA implementation not working

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#441]
**Describe the bug**
Zynthian is not reacting to OSC CUIA control messages sent to port 1370

**To Reproduce**
Send OSC CUIA messages to localhost:1370
Zynthian won't react, but the following type of traceback is found in the UI debug log:

Apr 23 10:11:02 zynthian startx[4497]: INFO:zynthian_gui.osc_cb_all: OSC MESSAGE ‘/CUIA’ from ‘osc.udp://127.0.0.1:42220/’
Apr 23 10:11:02 zynthian startx[4497]: Traceback (most recent call last):
Apr 23 10:11:02 zynthian startx[4497]: File “src/liblo.pyx”, line 56, in liblo._weakref_method.call
Apr 23 10:11:02 zynthian startx[4497]: File “./zynthian_gui.py”, line 304, in osc_cb_all
Apr 23 10:11:02 zynthian startx[4497]: self.callable_ui_action(parts[2].upper(), args)
Apr 23 10:11:02 zynthian startx[4497]: IndexError: list index out of range
Apr 23 10:11:02 zynthian startx[4497]: Exception ignored in: ‘liblo._msg_callback’
Apr 23 10:11:02 zynthian startx[4497]: Traceback (most recent call last):
Apr 23 10:11:02 zynthian startx[4497]: File “src/liblo.pyx”, line 56, in liblo._weakref_method.call
Apr 23 10:11:02 zynthian startx[4497]: File “./zynthian_gui.py”, line 304, in osc_cb_all
Apr 23 10:11:02 zynthian startx[4497]: self.callable_ui_action(parts[2].upper(), args)
Apr 23 10:11:02 zynthian startx[4497]: IndexError: list index out of range

A wireshark capture log of the test messages sent can be found here (warning, not a 'log' file, but a pcap capture)

[capture.log](https://github.com/zynthian/zynthian-issue-tracking/files/6364321/capture.log)

**Comment by jofemodo** [comment]
Hi @mark-orion!

AFAIK, the OSC CUIA is working OK. It's actively used to communicate webconf and update system with the UI, so if it were broken, everybody would note it.

Take a look to the code used by webconf:

https://github.com/zynthian/zynthian-webconf/blob/153a0206fc0e28f566c0ed2888dd80bfb36928a8/lib/zynthian_config_handler.py#L142

Regards,

**Comment by mark-orion** [comment]
Thanks @jofemodo. The problem was that the callable action belongs to the path, not the parameter. I am closing this now.
