### ISSUE TITLE
Audio levels reset after reboot

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#453]
**Describe the bug**
Each time I reboot the Zynthian the audio level settings are lost.

**To Reproduce**
1. Go to Main Menu->Audio Levels
2. Adjust ADC Left, ADC Right, ADC Left Input, ADC Right Input
3. Save snapshot (just in case it has an effect - it doesn't)
4. Reboot

**Expected behaviour**
Audio levels are restored to those set during previous session.

**Actual behaviour**
Audio levels are reset to defaults.

**Setup:**
* HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
* SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 25% (496M/1939M)
SD Card: 71% (9.4G/14G)
Temperature: 49.0ºC
* SOFTWARE
zyncoder: stable (d852c8f)
zynthian-ui: stable (b2f6a7c)
zynthian-sys: stable (e8fe7ce)
zynthian-data: stable (f71259d)
zynthian-webconf: stable (153a020)

**Additional context**
This is a standard official V4.1 kit with freshly flashed 2104 firmware. I have tried reboot from webconf and also shutdown from UI. All level settings are lost after restart. I have tried saving and restoring snapshot. 

Mixer controls:
`ADC Left,ADC Right,ADC Left Input,ADC Right Input,Auto Mute,Digital Left,Digital Right`

I have tried restoring Mixer controls to default:
`ADC Left,ADC Right,ADC Left Input,ADC Right Input,Digital Left,Digital Right`

**Comment by riban-bw** [comment]
I set the parameter values in webconf, saved and rebooted and still reset to defaults.

**Comment by riban-bw** [comment]
Systemd journal shows:
```
May 17 08:28:27 zynthian systemd[1]: Started Manage Sound Card State (restore and store).
May 17 08:28:27 zynthian systemd[1]: Starting Save/Restore Sound Card State...
May 17 08:28:27 zynthian systemd[1]: Condition check resulted in getty on tty2-tty6 if dbus and logind are not available being skipped.
May 17 08:28:27 zynthian alsactl[396]: alsactl 1.1.8 daemon started
May 17 08:28:27 zynthian alsactl[396]: /usr/sbin/alsactl: load_state:1674snd_config_load error: Invalid argument
May 17 08:28:27 zynthian alsactl[396]: ALSA lib conf.c:1887:(_snd_config_load_with_include) _toplevel_:359:40:Unexpected char
May 17 08:28:27 zynthian systemd[1]: Started D-Bus System Message Bus.
May 17 08:28:27 zynthian alsactl[398]: ALSA lib conf.c:1887:(_snd_config_load_with_include) _toplevel_:359:40:Unexpected char
May 17 08:28:27 zynthian alsactl[398]: /usr/sbin/alsactl: load_state:1674: snd_config_load error: Invalid argument
```

**Comment by riban-bw** [comment]
Apparently a bug in alsactl reported [here](https://github.com/raspberrypi/linux/issues/4003).

We need to get alsa-utils 1.2.4 or later.

**Comment by riban-bw** [comment]
It is actually alsa-lib 1.2.4 that has the fix. I was able to compile this by:

```
git clone https://github.com/alsa-project/alsa-lib.git
cd alsa-lib
git checkout v1.2.4
libtoolize --force --copy --automake
aclocal
autoheader
automake --foreign --copy --add-missing
autoconf
./configure --libdir=/usr/lib/arm-linux-gnueabihf
make
make install
```

This updates many files so worth checking it hasn't overwritten something we customise in Zynthian:

```
/usr/share/alsa/cards/*.conf
/usr/share/alsa/pcm/*.conf
/usr/share/alsa/alsa.conf
/usr/lib/arm-linux-gnueabihf/libasound.la
/usr/lib/arm-linux-gnueabihf/libasound.so.2.0.0
/usr/lib/arm-linux-gnueabihf/libasound.so
/usr/lib/arm-linux-gnueabihf/libasound.la
/usr/bin/aserver 
/usr/lib/arm-linux-gnueabihf/pkgconfig/alsa.pc
/usr/lib/arm-linux-gnueabihf/pkgconfig/alsa-topology.pc
```
(I think that is it.)

We should add this to the base build and maybe just provide compiled lib in an update.

**Comment by riban-bw** [comment]
I am flashing another image so will try copying just the lib and see how it works.

**Comment by riban-bw** [comment]
Replacing /usr/lib/arm-linux-gnueabihf/libasound.so.2.0.0 with the recompiled v1.2.4 version (attached) solves this issue. I am yet to observe any adverse effects.
[libasound.so.2.0.0.zip](https://github.com/zynthian/zynthian-issue-tracking/files/6496429/libasound.so.2.0.0.zip)

**Comment by riban-bw** [comment]
Although this is a significant issue with the official device, I suggest not merging this issue to stable until we have a better implementation, e.g. deb package. I will take the official dep package for libasound and update it with v1.2.4 and repackage so that it is a similar as possible. Once the deb repo is configured we can also look at how to configure ZynthianOS to allow apt upgrade without breaking it. This could (should?) be the _right_ way to update (stable), reducing the direct access to github. Let me know when we are ready to test the dep repo... actually - we should create a new ticket to track it rather than here!

**Comment by jofemodo** [comment]
I'm working on the repo infrastructure. It's working more or less, but i'm facing problems with the gpg signing procedure. Also, i've build the deb packages for alsa-lib from the debian src package.

Regarding the apt upgrade, i just tested and i couldn't find any problem. It simply worked for me on the latest stable. I will repeat the test this morning.

Regards,

**Comment by riban-bw** [comment]
Let's close this issue and track improvment to implementation in https://github.com/zynthian/zynthian-sys/issues/202.
