### ISSUE TITLE
Riban's plugins recipes generate errors  when updating

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#458]
**Describe the bug**
When updating zynthian, riban plugin logs errors.

**Screenshots**
Executing /zynthian/zynthian-sys/scripts/recipes.update/update_riban_lv2.sh ...
warning: unable to rmdir 'DPF': Directory not empty
sed: can't read Makefile: No such file or directory
sed: can't read Makefile: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
/zynthian/zynthian-sw/plugins/riban
sed: can't read Makefile: No such file or directory
sed: can't read Makefile: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
/zynthian/zynthian-sw/plugins/riban
make -C dgl
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/dgl'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/dgl'
make all -C examples/Info
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Info'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Info'
make all -C examples/Latency
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Latency'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Latency'
make all -C examples/Meters
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Meters'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Meters'
make all -C examples/MidiThrough
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/MidiThrough'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/MidiThrough'
make all -C examples/Parameters
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Parameters'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/Parameters'
make all -C examples/States
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/States'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/States'
make all -C examples/CairoUI
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/CairoUI'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/CairoUI'
# ExternalUI is WIP
make all -C examples/ExternalUI
make[1]: Entering directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/ExternalUI'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/zynthian-sw/plugins/riban/DPF/examples/ExternalUI'
install -d bin/d_extui-dssi
install -d bin/d_extui.lv2
install -m 755 examples/ExternalUI/ExternalLauncher.sh bin/d_extui.sh
install -m 755 examples/ExternalUI/ExternalLauncher.sh bin/d_extui-dssi/d_extui.sh
install -m 755 examples/ExternalUI/ExternalLauncher.sh bin/d_extui.lv2/d_extui.sh
Generate ttl data for './d_extui_dsp.so', basename: 'd_extui_dsp'
Writing manifest.ttl... done!
Writing d_extui_dsp.ttl... done!
Writing d_extui_ui.ttl... done!
Generate ttl data for './d_midiThrough_dsp.so', basename: 'd_midiThrough_dsp'
Writing manifest.ttl... done!
Writing d_midiThrough_dsp.ttl... done!
Generate ttl data for './d_parameters_dsp.so', basename: 'd_parameters_dsp'
Writing manifest.ttl... done!
Writing d_parameters_dsp.ttl... done!
Writing d_parameters_ui.ttl... done!
Writing presets.ttl... done!
Generate ttl data for './d_cairoui_dsp.so', basename: 'd_cairoui_dsp'
Writing manifest.ttl... done!
Writing d_cairoui_dsp.ttl... done!
Writing d_cairoui_ui.ttl... done!
Generate ttl data for './d_states_dsp.so', basename: 'd_states_dsp'
Writing manifest.ttl... done!
Writing d_states_dsp.ttl... done!
Writing d_states_ui.ttl... done!
Writing presets.ttl... done!
Generate ttl data for './d_meters_dsp.so', basename: 'd_meters_dsp'
Writing manifest.ttl... done!
Writing d_meters_dsp.ttl... done!
Writing d_meters_ui.ttl... done!
Generate ttl data for './d_info_dsp.so', basename: 'd_info_dsp'
Writing manifest.ttl... done!
Writing d_info_dsp.ttl... done!
Writing d_info_ui.ttl... done!
Generate ttl data for './d_latency_dsp.so', basename: 'd_latency_dsp'
Writing manifest.ttl... done!
Writing d_latency_dsp.ttl... done!
make: *** No rule to make target 'install'.  Stop.
/zynthian/zynthian-sw/plugins/riban

**Setup:**
 - SD-image: Fresh burned SD with latest stable image
 - Hardware Config: v4

**Comment by riban-bw** [comment]
Odd! I am looking at creating a debian package for this so maybe we can resolve this after we merge the debian repo into testing?

**Comment by jofemodo** [comment]
Please, do it!! ;-)

**Comment by jofemodo** [comment]
Awaiting for the next deb package ... riban-lv2-plugins_0.1.0.deb?? ;-)

**Comment by riban-bw** [comment]
I have started work on this but there is a dependency on DISTRHO framework. I would like to package that up as a separate deb package but it adds delay in delivering this. Stay tuned...

**Comment by jofemodo** [comment]
Closing this because it's now installed/updated as a deb package.
