### ISSUE TITLE
Cannot connect to open wifi networks

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#465]
**Describe the bug**
Attempt to add an open WiFi will fail because webconf asks for a password.

**To Reproduce**
1. Start WiFi Hotspot and connect computer
2. Target web browser at webconf
3. Add WiFi Network
4. Select an open SSID
5. Click "ADD"

**Expected behaviour**
Open network is added as the Zynthian network.

**Actual behaviour**
No network is added.

**Setup:**
Testing

**Additional context**
If a password is added then the network is added but will not connect.

**Comment by riban-bw** [comment]
I have created a branch in git to fix this. I can't currently test the fix because I can't access the Zynthian due to the bug.

**Comment by jofemodo** [comment]
Hi @riban-bw !!

I would like to test your development branch for this. 
We should close this issue and move forward to release the staging_2108 ;-)

**Comment by jofemodo** [comment]
Hi @riban!

Do you think we could include this on the next stable-2109?

**Comment by riban-bw** [comment]
I need to configure a WiFi access point and test it. I suggest we leave it out until that is done. I will attempt to do the test soon but if not then it will have to wait.

**Comment by riban-bw** [comment]
Just tested and this does not work.

**Comment by jofemodo** [comment]
This should be fixed in Oram Bookworm. Closing!
