### ISSUE TITLE
Gui based audio cut down tool. 

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#466]
**Is your feature request related to a problem? Please describe.**
The audio recorder is a useful tool but simple editing capability would enhance it considerably. 
1/ display of a complete audio recording (scaled suitably) 
2/ in point display controlled by left top encoder
3/ out point display controlled by right top encoder
4/ scale of display set by bottom left encoder
5/ window into display bottom right encoder. 
6/ top left press goto first sound 
7/ bold press top left end of last sound
8/ back press quit app
9/ save selected sample as new audio file. 

Don't try scrub or such. This is just a simple slicing tool

**Additional context**

**Comment by jofemodo** [comment]
All this can be done with current audio player.
