### ISSUE TITLE
Omni mode in MIDI channel selector for layers

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#469]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to easily create a global (meaning working on all layers and all channels) MIDI FX layer. The core problem is that a single MIDI channel has to be assigned what in most cases is a show stopper. Specially for MIDI FX layers the channel assignment is not needed as most MIDI plugins have a buit-in option to set one or all MIDI channels.

**Describe the solution you'd like**
Add an "Omni" option to the MIDI channel selector for layers. This Omni option would then attach the layer to the Zynrouters Main output instead of one of the channels. Another very useful option would be in my opinion to allow several layers to be attached to the same channel.

**Comment by mark-orion** [comment]
As I am just facing the problem again, here is the solution I would suggest:

- Use the same interface style as for the "Clone MIDI to...". This page allows one to select as many channels as one wants to select.
- Add an OMNI option that bypasses channel selection and attaches the layer to Zynrouters main MIDI output.
- Do not hide "used" MIDI channels any more. I would propose to drop the whole concept of "using up" MIDI channels in favour of more flexibility.

**Comment by jofemodo** [comment]
It's implemented in Oram (chain_manager)
