### ISSUE TITLE
Cloning channels doesn’t send cc messages

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-issue-tracking#47]
**Describe the bug**
Cloning a channel doesn’t clone cc message. E.g. sustain, or whatever cc control I’ve mapped to sustain in the engine this week.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup:**
 - SD-image Aruk
 - Hardware Config:

HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC
Display: PiScreen 3.5 (v2)
Wiring: MCP23017_EXTRA 

 - Software Version

SOFTWARE
zyncoder: master (80862b6)
zynthian-ui: master (3688c73)
zynthian-sys: master (26f86d2)
zynthian-data: master (676c32a)
zynthian-webconf: master (0094c99)

**Comment by jofemodo** [comment]
"Clone" was introduced to allow having several instruments layered while allowing to control each one separately, so this is not a bug, but a feature. In fact it's **the feature** because "clone" exist at all ;-)

From the wiki Zynthian User's Guide :

> Clone MIDI to... => clone the layer's MIDI channel messages to other MIDI channels. Note that only note on/off, pitch-bending, and key-press messages are cloned, while the rest are kept independent (CC, channel-pressure, program change, ...)

Kind Regards,

**Comment by Baggypants** [comment]
But there is no alternative way of controlling layers simultaneously. Like a virtual MIDI Through.

From the wiki Zynthian User's Guide :

> Having several layers in the same MIDI channel is not allowed.
