### ISSUE TITLE
Webconf: Upload Pianoteq binaries and audio captures doesn't work

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#470]
**Describe the bug**
Since i have the new Zynthian V4/4 Kit im glad with the sound and new possibilities. Great work.

But I cannot upload the pianoteq and some songs to the captures.

**To Reproduce*
Go to pianoteq
go to your *.7z file, mark it,
try to download

**Expected behavior**
Upload should work

**Screenshots**
![grafik](https://user-images.githubusercontent.com/55761217/123429606-6b47ae00-d5c7-11eb-96f3-b13ab2bc2c7a.png)

**Setup:**
 - SD-image: 2020-09-05
 - Hardware Config: v4-kit
 - Software Version:2021-05-18-zynthianos-stable-2104.img

**Additional context**
Upload Songs is the same prob

**Comment by riban-bw** [comment]
What browser and operating system are you using on the computer connecting to Zynthian?

**Comment by jofemodo** [comment]
I just tested the last Pianoteq 7.4 in a fresh SD (testing branch). It works like a charm, including the license setup.
I also tested the audio captures and they work nicely.
So, since @Mickinator doesn't added more to this issue, i will close it.
