### ISSUE TITLE
Indicate whether zynpad has any content

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#474]
**Is your feature request related to a problem? Please describe.**
It is not evident whether a sequence behind a zynpad has any content. It may be advantageous to indicate to the user if a sequence is empty.

**Describe the solution you'd like**
An indication, e.g. icon on each zynpad to show whether the pad will trigger a populated or empty sequence. This could be the play state icon which is currently blank when stopped.

**Additional context**
Requested by @harrytuttle in [Zynthian Discourse forum](https://discourse.zynthian.org/t/zynseq-pads/5980/8).

**Comment by riban-bw** [comment]
Implemented in branch /feature/747_indicate_empty_sequence. Need to test and validate changes.

**Comment by jofemodo** [comment]
It works nicely here. Merged on testing. You can close.

Thanks!

**Comment by riban-bw** [comment]
Excellent!
