### ISSUE TITLE
Lack of encoders makes Learn in accessible.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#478]
**Describe the bug**
If the zynthian doesnt have encoders there appears to be no way of performing learn Ctrl MIDI-Learn

**Comment by jofemodo** [comment]
Did you try this?

https://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#MIDI-CC_Learning_with_a_touch_interface

Also, you can use the "standard" workflow. From the Instrument Control screen:

1. Click on the top-right controller-area
2. Move the controller you want to assign (vertical swipe on the controller area)
3. Move a knob/fade on your MIDI controller

Regards,

**Comment by wyleu** [comment]
OK closed
