### ISSUE TITLE
Snapshot long press goes to Layer Options

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#481]
**Describe the bug**
Snapshot Long Press goes to Layers options no snapshot menu.

**To Reproduce**
1. Go to Any screen ( Not sequencer) 
2. Long Press on Snapshot Icon
3. See Layer Option NOT snapshot menu. (Error)

**Expected behavior**
Long Press should go to Snapshot Menu

**Screenshots**
![image](https://user-images.githubusercontent.com/79083/124600908-24777500-de5f-11eb-8b10-83bcc2ced19c.png)

**Additional context**
Applies to both GUI & Touchscreen interface

**Comment by jofemodo** [comment]
This is the new workflow, that has not been documented yet:

+ From Instrument Contriol => bold-press on "learn/snapshot" open layer options

For getting the snapshot menu, you must navigate to "main menu=> snapshots", or assign "CUIA snapshots" to an extra switch. A mechanism for emulating the 4 extra switches S1-S4 as touch widgets is on the way ...

Regards,
