### ISSUE TITLE
Action appears to run after update complete

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#486]
**Describe the bug**
Updating software from webconf shows the output from the update process, ending with, "Update Complete" but there is a subsequent message, "Running Flag Actions from '/zynthian/zynthian-sys/scripts/update_zynthian.sh'...". The indication of the update being complete should occur after... it is complete.

**To Reproduce**
1. Go to webconf
2. Click on 'Update Software'
3. Wait for update to complete
4. See extra message at end of update

**Expected behaviour**
The last message should be "Update Complete".. It would be advantageous if this were highlighted, e.g. colour coded but that is a feature request beyond this bug report.

**Setup:**
Testing branch

**Additional context**
Minor issue but it should be sorted.

**Comment by jofemodo** [comment]
Hi @riban! 

The "Flag Actions" are post-update actions, like restarting services or reboot.
Let me think about it ... ;-)

**Comment by jofemodo** [comment]
OK! It's changed. Anyway, the update system needs a refact too ;-D

**Comment by riban-bw** [comment]
There does not seem to be any message at the end now showing "Update complete". Maybe that only occurs on first update after the change. Will try again...

Working okay now!
