### ISSUE TITLE
Zynseq tries to restart and segfaults on UI exit

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#487]
**Describe the bug**

**To Reproduce**
1. Boot zynthian
2. From command line, try to restart zynthian UI with:

`    send_osc 1370 /CUIA/RESTART_UI`

3. See UI logs using:

`      journalctl -u zynthian -f`

```
Aug 03 23:28:07 zynthian startx[12933]: New instance of zynseq
Aug 03 23:28:07 zynthian startx[12933]: **zynseq initialising as zynthstep**
Aug 03 23:28:09 zynthian startx[12933]: ./zynthian.sh: line 144: 13636 Segmentation fault      ./zynthian_gui.py

```
**Expected behavior**
Zynseq shouldn't try to re-initialize when exiting the UI.

**Setup:**
 - testing branch update to the last
 - v4 kit

**Comment by riban-bw** [comment]
I cannot reproduce this issue. I have added a setBfree on layer 1 and added a simple sequence. Restarting the UI via admin menu or OSC CUIA works fine with Zynthain UI restarting and sequencer able to play the sequence. What configuration do you have that triggers this?

**Comment by jofemodo** [comment]
OK! I can't reproduce this anymore. I will close it.
