### ISSUE TITLE
ttyMIDI appears to ignore streams of MIDI data bytes.

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-issue-tracking#49]
**Describe the bug**
Hanging notes when using ttyMIDI on certain brands of keyboard.

**To Reproduce**

Using a MIDI DIN keyboard that sends note off as "MIDI note ON velocity 0" and uses the one Status Byte for proceeding a stream of data byte velocity messages as outlined [here](https://www.sweetwater.com/insync/status-byte/) 

Example keyboards **evolution / M-Audio MK-449C** (and possibly **Technics sx-PX55(M)**)

**Expected behavior**
Notes shouldn't hang.

**Setup:**
 - SD-image Aruk
 - Hardware Config
 - Software Version

**Additional context**

**Comment by jofemodo** [comment]
Could you try with the recently fixed mod-ttymidi? Simply use ssh to login into your zynthian and run these commands:

```
update_zynthian.sh
$ZYNTHIAN_RECIPE_DIR/install_mod-ttymidi.sh
reboot

```

Thanks!

**Comment by jofemodo** [comment]
Eooo! Could you confirm if it's solved with the udpated ttymidi?
You also can test it in the latest Buster images (nightly builds):

https://os.zynthian.org/2019-10-08-zynthianos-buster-lite-1.0.0.zip

**Comment by Baggypants** [comment]
Works fine on a recent buster image.
