### ISSUE TITLE
Alternate SFZ engine using sfizz

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#490]
Implement an alternate SFZ engine using sfizz: 

https://github.com/sfztools/sfizz

Sfizz is a much alive project than LinuxSampler and it's developing blasting fast. Also, it doesn't have the "license" problems associated with LinuxSampler. So everthing points to be a good idea.

Anyway, first we should asses if it's it's worth it and test the sfizz core on zynthian with several SFZs, comparing with LinuxSampler (supported SFZ operators, CPU usage, stability, etc.)

**Comment by riban-bw** [comment]
It will be worth testing standalone (encapsulated as zynthian engine) and LV2 for functionality, usability, overhead, etc.
