### ISSUE TITLE
Changes to Raspbian repositories throwing errors and warnings

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#493]
**Describe the bug**
During updates there are various errors and warnings thrown which look like something has changed with the upstream Raspbian repositories.

**To Reproduce**
Run Update from webconf.

**Expected behaviour**
Update occurs without warning or error.

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version

**Additional context**
During update I saw these messages:
```
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/a/aspell/libaspell15_0.60.7~20110707-6_armhf.deb 404 Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/a/aspell/aspell_0.60.7~20110707-6_armhf.deb 404 Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.32.1-1~deb10u1+rpi1_armhf.deb 404 Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.32.1-1~deb10u1+rpi1_armhf.deb 404 Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Performing `apt update` this warning was shown:
```
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
```
I wonder if Raspbian has moved to bullseye. I don't see any news but this looks likely from this message.

**Comment by riban-bw** [comment]
Everything at http://raspbian.raspberrypi.org/raspbian/dists/ has been modified today so looks like changes have happened. I have not seen any announcements about this.

**Comment by riban-bw** [comment]
I just confirmed that stable now points to bullseye. Zynthian updates may fail.

**Comment by jofemodo** [comment]
Adding the "--allow-releaseinfo-change" solves the problem:

`# apt-get -y update --allow-releaseinfo-change`

I just updated the needed scripts on zynthian-sys.
