### ISSUE TITLE
Changing wiring config restarts UI without saving snapshot

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#496]
**Describe the bug**
Changes to wiring from webconf, e.g. Customizable Switches require to be asserted by pressing _Save_ button_ which restarts the UI then loads the previously saved snapshot which loses any work done since last restart.

**To Reproduce**
1. In webconf navigate to HARDWARD->Wiring
2. Change a Customizable Switches setting
3. Press _Save_ button

**Expected behaviour**
Changes are saved and Zynthian retains its current settings.

**Actual behaviour**
Changes are saved but Zynthian UI restarts and previous snapshot is restored.

**Setup:**
* HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
* SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 10% (202M/1872M)
SD Card: 50% (14G/29G)
Temperature: 50.6ºC
* MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
* SOFTWARE
zyncoder: testing (7b58d8c)
zynthian-ui: sfizz (6c7912d)
zynthian-sys: sfizz (18d2a12)
zynthian-data: testing (f6a7b36)
zynthian-webconf: bug/494_wiring_error_500 (547978a)

**Additional context**
Snapshot should be saved before UI restarts. This has occurred previously for different restart reason. Maybe the restart options should default to saving snapshot.

**Comment by jofemodo** [comment]
It works for me. I can't reproduce. Please, test again with all repos updated on "testing".

**Comment by riban-bw** [comment]
I did the following:

- Set all repositories to _Testing_
- Update Software
- Reboot
- Zynthian loaded previous snapshot: 1: Pianoteq, 2: ALO
- REMOVE All Layers
- Add Calf Mono Synth on Channel 1 with preset Barkline
- Set _Extra Switch-3 Action:_ to _Midi Prog Change_ MIDI channel 1, MIDI Number 2
- Clicked _Save_ in webconf

Zynthian UI restarted and showed Pianoteq on layer 1 and ALO on layer 2.

**Comment by jofemodo** [comment]
I follow your steps but i can't reproduce the behaviour. In my case, the latest layer configuration is restored.
Could you verify that your zynthian is really updated to the last "testing" on all the repositories?

Regards,

**Comment by riban-bw** [comment]
Hmmm.... very odd! I ssh to Zynthian and manually `git pull` on each of the four repositories then run SOFTWARE UPDATE from UI and now it works. Previously I just ran software update from webconf. I wonder if it didn't complete the update (I left it for a long time so if it did not complete it is likely to to a failure) or maybe there is an issue with updating from webconf... or maybe something else went wrong. Let's hope it was just an oddity due to my specific workflows and repro jumping / development.

**Comment by jofemodo** [comment]
My development zynthians sometimes have "rare" states due to continuous jumping from one branch to another, copying source files by hand, etc. Sometimes, these "rare" states cause problems with updates. I don't worry too much about while the update work on a fresh "not-tweaked" SD image. In fact, currently i'm testing the updates with the automated script, that also generates an updated image, what is nice to have.
