### ISSUE TITLE
Add Bollie Delay to Zynthian

### ISSUE THREAD

**Issue by kingcaleb216** [zynthian/zynthian-issue-tracking#497]
I would like to be able to use the Bollie Delay in the MOD-UI layer

**Comment by jofemodo** [comment]
Hi @kingcaleb216 !

I just added this nice plugin to the collection. It's on testing branch. Simply change to testing, update and test.
After updating, remember to click "Search for new plugins and presets" from webconf's plugin list.

Regards,

**Comment by kingcaleb216** [comment]
Wow! Now THAT was fast! I just have to say thank you, what an amazing turnaround. I pulled the testing branch and it worked like a charm! Thank you again.

**Comment by jofemodo** [comment]
It was an old request from long time ago.
Thanks for creating the request and bringing this to my mind!! ;-)
