### ISSUE TITLE
Cloned Layers cannot allocate MIDI CC from original channel

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#499]
**Is your feature request related to a problem? Please describe.**
I have a roland A-88 MIDI keyboard and I wish to control the volume of  two layers (piano & strings)  from the C1 & C2 Midi CC controllers.

I can clone the strings (fluidsynth) (Midi Channel 2 c2) from the Piano (fluidsynth) (C1 Midi Channel 1) and both play. I can select and allocate the CC1 control to the volume parameter (fluidsynth) snf it functions but the CC2 control CANNOT operate the volume layer of the cloned layer. 

**Describe the solution you'd like**
In a cloned environment I would CC controls to be transmitted to all coned voices on their defined MIDI channel.

**Describe alternatives you've considered**
Lot's of mucking around in MIDI Mapper.

**Additional context**
This produces a simple to understand highly flexible control structure, and requires little knowledge of the GUI.

**Comment by jofemodo** [comment]
Follow these steps:

+ From the layer 1 options, click clone
+ Bold click "Channel 2" to access CC-clone selection (do anybody knows this menu exists?)
+ Select/Unselect the CC you want to clone

Enjoy!

**Comment by jofemodo** [comment]
**Rationale:** Clone was implemented because having several instruments in the same MIDI channel doesn't allow to send separated CC to each instrument. So clone allows to choose which CC you want to clone. By default a few only are cloned.

Regards,

**Comment by wyleu** [comment]
I had to say I did wonder if this functionality was available as I saw the CC listing in the interface.
