### ISSUE TITLE
Sainsmart 18 display does not honour configuration

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#5]
Configuration elements added to the webconf display configuration are not influencing the display driver, e.g. rotate=270 does nothing.

**To Reproduce**
1. Navigate web browser to zynthian.local/api/hw-display
2. Select "Sainsmart 18" display
3. Add "rotate=270" to the configuration
4. Save changes

**Expected behaviour**
Zynthian restarts with display rotated by 270°.

**Actual behaviour**
Display rotation does not change.

**Setup:**
 - Aruk RC1 zynthianos-stretch-lite-1.0.0
 - 1.8 inch LCD Display 128x160 TFT SPI ST7735

**Additional context**
The device tree does not expose settings via overrides. Update to device tree source and blob required. (I am working on this.)

**Comment by jofemodo** [comment]
Anyway, currently there is no standarized  way of rotating the display from webconf. You can add an option for the overlay configuration, but not all displays support, or do it in the same way.

Probably you can rotate the framebuffer using some X11 trick. It should be done modifying the custom device files, in zynthian-sys.

**Comment by riban-bw** [comment]
Indeed - it is the overlay configuration that is currently not working for which I have a fix. I will apply a patch to the gh98_st7735r branch to fix this.

**Comment by riban-bw** [comment]
Will track this change in [#98](https://github.com/zynthian/zynthian-sys/issues/98).
