### ISSUE TITLE
2109 pre-stable release - MIDI FX kills FS sound

### ISSUE THREAD

**Issue by gonzob** [zynthian/zynthian-issue-tracking#503]
**Describe the bug**
Adding a MIDI FX to Fluidsynth layer on Ch1 kills sound

**To Reproduce**
Add a new Fluidsynth layer on channel 1
Select soundfont and preset
Test - works OK
Short-Click Layer
Bold-Click Select
Choose Add MIDI FX
Choose MIDI map
Test - no sound
Adjusting setting on MIDI map makes no difference
removing the MIDIFX returns the sound

**Expected behavior**
Sound

**Screenshots**

**Setup:**
Raspberry Pi 4 Model B Rev 1.4 - 8GB
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

zyncoder: staging-2109 (6ca2847)
zynthian-ui: staging-2109 (229f751)
zynthian-sys: staging-2109 (74d959b)
zynthian-data: staging-2109 (006a071)
zynthian-webconf: staging-2109 (87ac0e6)

**Comment by jofemodo** [comment]
Fixed! Please, update and test. You should rebuild your recent snapshots.
