### ISSUE TITLE
Pre-stable 2109 - snapshots not shown in web interface

### ISSUE THREAD

**Issue by gonzob** [zynthian/zynthian-issue-tracking#504]
**Describe the bug**
I have a number of snapshots - they are shown on the UI, but not on the web interface

**To Reproduce**
- load Zynthian web interface
- select Library>Snapshots
- only "New bank" is shown - see screenshot below 

**Expected behavior**
List of snapshots and directories
**Screenshots**
![Screenshot at 2021-09-13 12-44-01](https://user-images.githubusercontent.com/19601586/133016660-c3921a88-f07c-4190-b60f-6c622f8bfa3a.png)

**Setup:**
![Screenshot at 2021-09-13 12-50-15](https://user-images.githubusercontent.com/19601586/133016732-872d37c6-693f-40ec-b5c8-bec98006d9b6.png)

**Comment by jofemodo** [comment]
Sorry, i can't reproduce the problem.  Please try updating.
Also, could you send your snapshot folder/files structure? From command line:

# tree /zynthian/zynthian-my-data/snapshots

Thanks

**Comment by gonzob** [comment]
I've updated twice yesterday with no change.
The tree looks like this:
/zynthian/zynthian-my-data/snapshots
├── 000
│   ├── 001-House In RTP.zss
│   ├── 002-FluidR3 GM.zss
│   └── 003-ThreeOnThree.zss
├── Favourites
│   ├── 001-C-Tenor Recorder.zss
│   ├── 002-C-WARBL Whistle.zss
│   ├── 003-C-Flute.zss
│   ├── 004-Eb-Flute.zss
│   ├── 010-Bb-Clarinet.zss
│   ├── 012-C-Oboe.zss
│   ├── 014-C-English Horn.zss
│   ├── 016-C-Bassoon.zss
│   ├── 020-Bb-Soprano Sax.zss
│   ├── 022-Eb-Alto Sax.zss
│   ├── 024-Bb-Tenor Sax.zss
│   ├── 030-Bb-Trumpet.zss
│   ├── 032-Bb-Trombone.zss
│   ├── 034-F-French Horns.zss
│   ├── 036-Bb-Tuba.zss
│   ├── 050-C-Violin.zss
│   └── 052-C-Cello.zss
└── last_state.zss

Gonzo

**Comment by jofemodo** [comment]
Try renaming favorites to 001-Favourites  ;-)

**Comment by gonzob** [comment]
Done.

A small change resulted:

![Screenshot at 2021-09-16 21-15-01](https://user-images.githubusercontent.com/19601586/133602842-a7a7d8f0-cea6-4af5-8c26-bb1c7b05f9e9.png)

**Comment by jofemodo** [comment]
Could you check the webconf logs? From command line:

`journalctl -u zynthian-webconf -f`

and then reload the webconf's snapshot page and send the output.

Thanks

**Comment by gonzob** [comment]
I dumped it to a file. The resulting file has very long lines - they don't fit in the screen. How do I mount a drive to transfer the file so I can send it?

PS: It won't let me mount a memory stick

**Comment by gonzob** [comment]
Of course, the answer was simple - just remove the SD card. Doh!
The weblog file is here:
https://gonzos.net/zynthian/weblog.txt
Hope that sheds some light.

Gonzo

**Comment by gonzob** [comment]
OK, I gave up on trying to find out what was wrong. Pulled the SD card, saved the snapshots, deleted the contents of the snapshots directory, reinstalled the SD, powered up, and uploaded the saved snaps.
Seems to be working.
Closing the issue.

Gonzo
