### ISSUE TITLE
 Pre-stable 2109 - "Select" action not consistent in Control screen 

### ISSUE THREAD

**Issue by gonzob** [zynthian/zynthian-issue-tracking#505]
**Describe the bug**
The action of the Select knob in the Control screen with Fluidsynth differs when you don't have a Audio FX loaded

**To Reproduce**
Load a new layer with FS
Select a soundfont and a preset
The control screen is shown
To switch between  portamento, sustain, or main you have to click the knob (as per previous stable release)
Add a AudioFX - eg 3Band mixer
Now you have to click Select, then twist to choose the item you want to adjust, then click. The behaviour is different

**Expected behavior**
Click then twist then click on all control screens

**Setup:**
![Screenshot at 2021-09-13 12-50-15](https://user-images.githubusercontent.com/19601586/133019216-580bdd9b-270a-4dbd-b711-ebefdde02bef.png)

**Comment by jofemodo** [comment]
Currently, this is the expected behaviour.
Please, read this:

https://discourse.zynthian.org/t/proposal-for-changing-engine-control-screen-workflow/6228/29

Regards,

**Comment by gonzob** [comment]
Ah. This has been thought about and discussed. I thought it was a bug. Sorry. Will close the ticket
