### ISSUE TITLE
MIDI CC Control of Audio level settings

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#506]
**Is your feature request related to a problem? Please describe.**
I would like to be able to allocate the Audio Levels controls to MIDI CC control

**Describe the solution you'd like**
USing the MIDI learn features I would like the audio level controls to be controllable by external MIDI CC messages as with engine parameters

**Describe alternatives you've considered**
At present this requires access to some GUI implementation and is even more frustrating as outside of an offical zynthian i2c implementation connected locally these controls cannot be remotely controlled at all. 
IT seems an obvious need to be able to present an overall volume control somewhere away from the zynthian unit.

**Comment by jofemodo** [comment]
MIDI learning is already implemented on Audio Levels. Simply follow the normal workflow. If you want to save this settings on snapshots, you have to check the "Audio Levels on Snapshots" option from Admin or Webconf.

Regards,

**Comment by wyleu** [comment]
AAah right. It's probably the considerable difficulty on activating MIDI learning on a mouse driven screen.

**Comment by wyleu** [comment]
No matter how hard I try I can't get this to work with a mouse . Audio levels to snapshot is enabled in admin
