### ISSUE TITLE
MIDI Control change one on MIDI #1 controls select 

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#507]
**Describe the bug**
Altering MDI channel 1 control change 1 seems to alter the select parameter in the GUI meaning that altering a control ( second fader on a Korg NanoController 2) moves the GUI highlighted cursor in the GUI.

**To Reproduce**
1. Plug in Korg NanoController 2 to USB.
2. Move second fader
3. GUI selected element responds to slider 

**Expected behavior**
This shouldn't happen as it's responding on MIDI channel one and my understanding is control is restricted to the selected channel ( normally 16)

**Comment by jofemodo** [comment]
Sorry @wyleu!
I can't reproduce this behaviour with any of my controllers. 
Perhaps i don't fully understand what you are trying to describe. Could you give a more detailed description?

Thanks!

**Comment by wyleu** [comment]
https://user-images.githubusercontent.com/79083/133649399-6846e5be-a906-4d66-9ec3-f0ed65745662.mp4

https://user-images.githubusercontent.com/79083/133649412-105fe63d-f67a-4a9f-98df-719ceb82ce14.mp4

These are cloned from MIDI channel one to 3 other MIDI channels 2,3,4

**Comment by wyleu** [comment]
Not been able to duplicate this myself. Can we close but leave the lid slightly open?

**Comment by wyleu** [comment]
No this is for real.

built a stable zynthian (zynthian-1820.local). The nanoKontrol2 sending on it's default settings for level control 01 operates the GUI as seen in the above video.

**Comment by wyleu** [comment]
Re-opening.

**Comment by jofemodo** [comment]
It's solved now??
