### ISSUE TITLE
Snapshot title in Control Screen

### ISSUE THREAD

**Issue by gonzob** [zynthian/zynthian-issue-tracking#508]
**Is your feature request related to a problem? Please describe.**
Currently, using FluidSynth, when you load a snapshot the only indication which snapshot is loaded is the title bar that shows the soundfont and the preset. I have multiple snapshots of the same preset but with different configurations. I can't tell which one I have loaded because they all show the same preset.

**Describe the solution you'd like**
If a snapshot is loaded, the title bar should show the snapshot name. If a snapshot is not loaded(simply a preset), then the current situation with the soundfont/preset should be shown

**Describe alternatives you've considered**
None

**Additional context**
No.

**Comment by jofemodo** [comment]
The control screen "title" is already too long for adding more info, like the snapshot title.
Anyway, i'm open to discusse this subject in the forum and see what other community members think about it.

**Comment by jofemodo** [comment]
Adding more info to the Control Screen title is not a good idea, but we could add the snapshot info into the layers screen, and also improve the snapshot menu so it remember current snapshot, etc.

**Comment by riban-bw** [comment]
We discussed this a Zynth Club tonight and there was consensus that the snapshot title would be best displayed in the mixer title area. I have added this to ZynMixer development branch but it exposes the fact that there isn't really a concept of the current snapshot, e.g. on first boot the device always thinks it has the "last_snapshot" loaded.

**Comment by jofemodo** [comment]
We already added this to the Audio Mixer screen. I think it's enough.
