### ISSUE TITLE
What do I do if I forget my password?

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#51]
**Describe the bug**
If I have forgotten my password (or the system ultimately refuses me access) There is no equivalent of the createsuperuser command available to respawn a root user password reset. 

**To Reproduce**
1/ Forgot password   :-D
2/ Loss of access to resources via webconf.

**Assumption**
Access to the GUI panel grants you implied superuser rights. 
  
**Expected behaviour**
A GUI reset on Admin screen to trigger a root user reset. 
All kinds of security implications but in a pre - performance/performance environment, a distinct possibility.
What do you mean you can't access the GUI... ? 
Maybe the default setting of some environmental variable? 

I might have lost my line up tones ... ! :-D and I got bold. Overwrite the image and treat it as research.

**Things the audience said**
He did nothing! I 'm not even sure he logged in...

**Comment by naught101** [comment]
Somehow I managed to change the password, and then forget it. Is there a way from the UI to change it again? Or if I remove the SD card can I change the password directly from my laptop?

**Comment by jofemodo** [comment]
The only way of changing the password is accessing the SD from a computer and editing the /etc/shadow file. Replace the root line by this:

    root:$6$lzzP87mA20ap.J2j$hyB8BXcNHy/w9Kp55UrxMzyM/o50yY.bvEVE.pBPLVzA6iSJPBaReegcw0X9BkKWGbk7Q2D/fUGLgJuCgWzIC0:18327:0:99999:7:::

This should restore the original password: raspberry

Regards
