### ISSUE TITLE
Bug: web-conf UI main page hangs for 120 seconds after configuring custom wiring extra switches

### ISSUE THREAD

**Issue by jp8** [zynthian/zynthian-issue-tracking#511]
**Describe the bug**
After adding extra switch configurations to the custom wiring, the configuration works but strangely it has added a 120 second delay to rendering the web-conf UI main page.

**To Reproduce**
1. flash latest-stable or recent staging
2. boot, update, reboot
3. webconf -> hardware -> kit -> custom -> reboot
4. webconf -> audio -> Behringer Uca222 -> reboot
5. webconf -> display -> generic HDMI -> reboot
6. webconf -> wiring -> dummies -> save
7. webconf -> wiring -> custom -> switches: 0,0,0,0,9
8. webconf -> navigate to any other page
9. click on zynthian logo at top left and wait 120 seconds

**Expected behavior**
Render page without delay

**Screenshots**

**Setup:**
zyncoder: testing (7c09738)
zynthian-ui: testing (5f3414a)
zynthian-sys: testing (061cae8)
zynthian-data: testing (006a071)
zynthian-webconf: testing (87ac0e6)

**Additional context**
 The main page displays a ‘status’ of various components and configurations. It feels like one of those status checks is taking 120 seconds, and it also feels like the web-conf UI is single-threaded.

**Comment by jofemodo** [comment]
Please, update (staging or test), reboot and and try again. The reboot is important this time !! ;-)

The commit that solves the issue is this:

https://github.com/zynthian/zynthian-ui/commit/9efaa7f53afb1ef9c51ba39f8a0a214a3312a5df

Regards,

**Comment by jp8** [comment]
Doesn't solve it, but why would it ?  I already did the update and reboot in step 2 above

**Comment by jofemodo** [comment]
Sorry ... i forgot to explain you have to configure the switches like this:

`-1,-1,-1,-1,9`

Regards,

**Comment by jp8** [comment]
even using just -1,-1,-1,9 (4 switches only) the problem persists.

**Comment by jp8** [comment]
on staging, update, then reboot

-1,-1,-1,-1 -> reboot -> OK
-1,-1,-1,9 -> reboot -> Not OK
0,0,0,0 -> reboot -> OK
0,0,0,9 -> reboot -> not OK

I'm sorry for the misleading title on this issue.  It seems I was wrong and the web-conf UI hanging is not related to extra switches.

**Comment by jp8** [comment]
0,0,9,0 -> reboot -> also not OK
