### ISSUE TITLE
Webconf Data backup failure

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#513]
**Describe the bug**
Attempting to back up data fails with a 500 error.

**To Reproduce**
1. Go to backup in webconf
2. Click on data backup
3. Press Backup button

**Expected behavior**
A Backup file should be downloaded to the browser host of the data files defined in the backup details

**Screenshots**
500 display

**Setup:**
![image](https://user-images.githubusercontent.com/79083/134356173-01a8f2fd-2837-433b-9fac-5e3cd5116dd3.png)

**Additional context**
![image](https://user-images.githubusercontent.com/79083/134356083-a9154269-a3d8-40d7-b862-b456e8d1053e.png)

**Comment by jofemodo** [comment]
Sorry @wyleu!

I can't reproduce the issue. It's working for me, on testing & staging-2109.
Anyway, it seems that the zip process fails due to lack of memory. Could you calculate how much is the size of your soundfonts? Try excluding user soundfonts from backup.

Regards,

**Comment by wyleu** [comment]
Ok excluding soundfonts allowed a backup to be taken.

There was some quite largish captures in the backup so that's reassuring.

![image](https://user-images.githubusercontent.com/79083/134368626-681d49c9-a1a0-4b85-8530-e013e92b770c.png)
