### ISSUE TITLE
Ability to start multiple sequences simultaneously

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#514]
**Is your feature request related to a problem? Please describe.**
In arranger view the step sequencer is similar to a track based DAW. It would be advantageous to be able to start all sequences playing with a single command / operation.

In pad view the step sequencer is similar to a sequence launcher. It would be advantageous to be able to start a group of tracks playing with a single command / operation.

**Describe the solution you'd like**
Ability to start / pause / recue a group of tracks playing. Ability to define that group to be all tracks.

**Describe alternatives you've considered**
Use one track as an intro then start each other track so that they all begin on next bar. This is awkward.

**Additional context**
One might consider starting all tracks simultaneously as a song mode. It may be okay to define all tracks to be in appropriate group/s so that the group start method works for this _song mode_ too.

It may be appropriate to implicitly use the physical location of a sequence to define its launch group. Novation call these _scenes_.

There needs to be a method of launching different _scenes_, either with onscreen buttons / operation and/or using external triggers like MIDI note on message.

**Comment by wyleu** [comment]
What elements of MIDI transport should/would/could operate this...?

**Comment by riban-bw** [comment]
I am not convinced this is a required feature. As described in the example workflows in the [documentation](https://wiki.zynthian.org/index.php/Using_ZynSeq) it is already possible to have a sequence with multiple tracks. All tracks will play simultaeously when the sequence is started. There may be some sublte workflows that are not possible with Zynseq but I want to hear what they are and consider how best to implement them within the ZynSeq framework (which is not the same as many other sequencers - some may say it is better...).
