### ISSUE TITLE
2109 stable - Snapshots web interface doesn't show snapshots

### ISSUE THREAD

**Issue by gonzob** [zynthian/zynthian-issue-tracking#515]
**Describe the bug**
The Snapshots web interface doesn't show snapshots, it only offers the ability to add a directory

**To Reproduce**
Have a blank list of snapshots like this
![Screenshot at 2021-09-24 10-56-26](https://user-images.githubusercontent.com/19601586/134603088-8586e010-3a4c-4522-9942-38a2495acfc5.png)

add a new directory (001)
![Screenshot at 2021-09-24 10-57-22](https://user-images.githubusercontent.com/19601586/134603143-3be08e81-e6f2-48ee-a6df-360185e8ee26.png)

refresh the browser
![Screenshot at 2021-09-24 10-57-40](https://user-images.githubusercontent.com/19601586/134603211-d74f2f85-4be0-41ac-88d4-11a344fdc74d.png)

The same happens if you add screenshots

**Expected behavior**
Show the directories and screenshots

**Screenshots**
see above

**Setup:**
![Screenshot at 2021-09-24 11-10-53](https://user-images.githubusercontent.com/19601586/134603387-bf34de87-b16b-4baa-8849-7d16d8708850.png)

**Additional context**
Latest 2109 stable. Same issue was raised (zynthian-issue-tracking#501) in testing pre-release on a DIFFERENT SD card. Was found to be "can't reproduce"

**Comment by jofemodo** [comment]
Have you tried to open the bank 000 folder? Simply click the folder icon.

**Comment by gonzob** [comment]
Not sure what you mean - I can't see the 000 folder - see the screenshot above after "refresh the browser". That's the problem - no directories or screenshots are shown unless I've just added a new directory. Then they are shown until I refresh the browser. 

Here is a screenshot of how it looks after I've added a folder and some snapshots
![Screenshot at 2021-09-24 18-06-49](https://user-images.githubusercontent.com/19601586/134640722-e136614f-429c-4732-b5cb-2636afcdbc5c.png)

And now after a browser refresh
![Screenshot at 2021-09-24 18-07-14](https://user-images.githubusercontent.com/19601586/134640768-1915d297-5c98-4108-b85b-5356f0ac871a.png)

**Comment by jofemodo** [comment]
Sorry, i can’t reproducce the issue. Could you send the output of this command:

tree /zynthian/zynthian-my-data/snapshots

Thanks!

**Comment by jofemodo** [comment]
Also, the "Favorites" directory should be renamed to something like  "001-Favorites".
Did you change the name by hand (from command line or sftp?)

**Comment by gonzob** [comment]
Refer latest comments on forum:
https://discourse.zynthian.org/t/webconf-snapshot-screen/6314/10

**Comment by jofemodo** [comment]
I just pushed a workaround to testing. Please, switch to testing and test.

Thanks!
