### ISSUE TITLE
Red Zeppelin Drum Kit LV2 crashes Zynthian

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#523]
**Describe the bug**
Attempt to load Red Zeppelin LV2 instrument will cause Zynthian screen to blank and become unresponsive.

**To Reproduce**
Steps to reproduce the behaviour:
1. Layers->Remove All Layers
2. Layers->NEW Synth Layer
3. Select Red Zeppelin Drumkit
4. Select MIDI CH#1

**Expected behaviour**
Red Zeppelin Drumkit is added as a synth layer.

**Actual behaviour**
Screen becomes unresponsive. Sometimes it blanks to grey.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 20% (387M/1872M)
SD Card: 47% (13G/29G)
Temperature: 51.1ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: on
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (09580ef)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (94a42a5)

**Additional context**
The GUI for the plugin shows in VNC.
Log shows:
```
zynthian1 startx[4883]: ERROR:zynthian_gui_layer.add_layer_midich: list index out of range
```

**Comment by jofemodo** [comment]
I can confirm the problem
