### ISSUE TITLE
Touch interface broken - does not select the touched / clicked item 

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#524]
**Describe the bug**
Touching or clicking with a mouse on the screen selects the currently highlighted menu item, not the item that was touched or clicked.

**To Reproduce**
1. Go to any screen, e.g. main menu
2. Touch or click on any menu item other than the currently highligted item

**Expected behaviour**
The clicked item is selected.

**Actual behaviour**
The highlighted item is selected.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 11% (212M/1872M)
SD Card: 48% (13G/29G)
Temperature: 49.6ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: on
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (09580ef)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (94a42a5)

**Additional context**

**Comment by jofemodo** [comment]
It's been merged to stable as HotFix.
