### ISSUE TITLE
Cannot disable Headphones from webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#525]
**Describe the bug**
When Headphones is enabled, it cannot be disabled from the webconf.

**To Reproduce**
1. Admin menu: Enable headphones
2. Webconf: hw-audio
3. Disable Headphones
4. Reboot

**Expected behaviour**
Headphones are disabled after rebbot.

**Actual behaviour**
Headphones remain enabled after rebbot.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 10% (200M/1872M)
SD Card: 48% (13G/29G)
Temperature: 49.6ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: on
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (09580ef)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (94a42a5)

**Additional context**

**Comment by jofemodo** [comment]
Solved! Anyway, webconf must be improved a lot. For instance, it has no sense to reboot the zynthian for enabling headphones from webconf!!
