### ISSUE TITLE
Keep audio input and output settings from first and last audio fx plugin in chain

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#527]
**Is your feature request related to a problem? Please describe.**
I use a multichannel audio interface. Whenever I replace, add or move an audio FX plugin that is part of a chain, the audio inputs revert to system1+2 input or output. This is annoying as it creates nasty feedback effects. Unhealthy wearing headphones and a show stopper during a jam.

**Describe the solution you'd like**
In the case an audio effects chain gets modified, the audio capture / playback settings should not change or revert to default.

**Comment by jofemodo** [comment]
We will take this into account on next code revisions but ... multichannel audio is not a priority, so don't expect this to be solved in the short term.

Regards,

**Comment by jofemodo** [comment]
It should be working in Oram
