### ISSUE TITLE
ZynPad disabled pads stop other pads in same group

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#533]
**Describe the bug**
It is possible to configure a ZynPad pad with play mode _Disabled_ but the pad will still act on its mutually exclusive group when pressed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ZynPad
2. Start a sequence playing
3. Select the play mode for another pad in the same group to _Disabled_
4. Press the disabled pad

**Expected behaviour**
Nothing happens.

**Actual behaviour**
Sequence stops playing.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 29% (268M/923M)
SD Card: 40% (11G/29G)
Temperature: 57.5ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: feature/516_launchkey (cb2ecd2)
zynthian-sys: testing (b49f8e8)
zynthian-data: testing (006a071)
zynthian-webconf: testing (39b61bb)

**Additional context**
Also happens if triggered by external MIDI controller. Also happens with current testing and stable release.

**Comment by riban-bw** [comment]
Very simple fix - check if pad is disabled when asked to toggle play state. PR submitted.

**Comment by jofemodo** [comment]
Nice fix! It seems OK.

**Comment by riban-bw** [comment]
Cool! Yes - the simple fixes are the nice ones :-). Sometimes a touch embarrassing that one missed it initially but to be expected.
