### ISSUE TITLE
New lv2 OS-251

### ISSUE THREAD

**Issue by Crush-Steelpunch** [zynthian/zynthian-issue-tracking#538]
**Is your feature request related to a problem? Please describe.**
https://github.com/utokusa/OS-251

**Additional context**

I've built it on my pi but it won't build in 1G ram unless you have swap enabled (I installed and used zram). The workflow _should_ be pretty much as follows but this is build retrospectivly from my history.

```bash
apt update
apt install npm cmake gcc-c++
cd ~
git clone --recursive https://github.com/utokusa/OS-251
cd OS-251/src/jsui/
npm ci
npm run build
cd ../../
mkdir build
cd build
cmake ..
make
cp -r src/Os251_artefacts/LV2/OS-251.lv2 /zynthian/zynthian-plugins/lv2/
```

**Comment by riban-bw** [comment]
`apt install npm` installs a stack load of dependencies! I guess this won't matter if this plugin is built and delivered as a deb package.

I assume this a request to add this plugin to Zynthian. Please provide some justification for why this plugin should be added. This will be used to decide whether to add it and how much support might be provided, e.g. will it be part of the official Zynthian release or a community supported or other available plugin. We want to avoid adding plugins which do not give significant benefit to the project to avoid disappointment for users, e.g. if plugin is suboptimal and to reduce support overhead, e.g. investigating and responding to bug reports.

**Comment by Baggypants** [comment]
Sure, npm and the compile memory limit is why I've documented this as an issue rather than a pull request. I think it would have to be packaged before it can be distributed. I'll see if it's going to be added to the kxstudio repos.

I have had issues with xruns using a high number of voices i.e. settings past 0.4, much the same with helm, zynaddsubfx and obxd back on the pi3. Once some presets become available we can filter out the problematic ones, or reduce the voice count like we did for obxd.

It provides a unique sound which is currently pursued by contemporary popular musicians, and simple 'analogue' style controls.

**Comment by Baggypants** [comment]
KXStudio package request: https://github.com/KXStudio/Repository/issues/269

**Comment by riban-bw** [comment]
KXStudio rejected request to package with some critism of the software and citing challenges in packaging. I tried to build on a RPi3 work 1GB RAM and it failed to build juceaide. I might try again when I have access to a RPi4 with more memory. We should validate FXTalk's critism in case there is some improvement that can be reported upstream.

**Comment by jofemodo** [comment]
I was listening the demos and i think the sound is quite good and authentic. But yes, compiling it is heavy and it installs a lot of "shit". Anyway it can be done in the image builder without problem, and perhaps someone could make a deb package for the zynthian deb-repo.

**Comment by jofemodo** [comment]
The GUI works OK in VNC and it include 16 factory presets that i've saved to LV2. I think it's a good addition to zynthian's collection.

**Comment by jofemodo** [comment]
It would need some TTL refactorization for grouping parameters and adding scale points, etc. Perhaps somebody could help with this.

**Comment by jofemodo** [comment]
This is ready for testing:

https://github.com/zynthian/lv2-plugins-prebuilt-rbpi3/commit/b926d97697aa33841676f158b68cec90f129c16a

https://github.com/zynthian/zynthian-sys/commit/6d8898dacc3b500d8d70dd1170637e5e6ce789cb

Simply update and click "Search new plugins & presets" in webconf.
