### ISSUE TITLE
GPIO wired encoders don't start with Pi3 on stable

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#539]
**Describe the bug**
Upon selecting GPIO encoders via the webconf wiring settings the zynth would not boot failing with.

Oct 15 11:20:33 zynthian-amp startx[489]: gpio: Unable to open GPIO direction interface for pin 7: No such file or directory
Oct 15 11:20:33 zynthian-amp startx[489]: wiringPiISR: unable to open /sys/class/gpio/gpio7/value: No such file or directory

Occurs on both machine update 
& clean build from stable 

Selecting wiring dummies clears fault but encoders no longer functional .

**To Reproduce**
1. Enable Custom wiring
2. enter appropriate values ( that have previously worked) 
3. Reboot zynth
4. Zynth errors

**Expected behavior**
Zynth to start with working encoders

**Screenshots**
![image](https://user-images.githubusercontent.com/79083/137488582-360a4b1a-9726-4ece-8d53-64467c54e4b7.png)

**Additional context**
Previously worked, failed on update.

**Comment by jofemodo** [comment]
Hi @wyleu, I just tested with an old v1, that uses RBPi GPIO and it works perfectly for me.
Also, this message is normally due to the pin being used (already opened or configured for a other function).

Regards,

**Comment by wyleu** [comment]
This is an effect when using pin 7 (BCM) pin 11 GPIO.  Back button in my case ...

**Comment by wyleu** [comment]
The complete story and a fix.. . .

https://discourse.zynthian.org/t/gpio-encoder-wont-start-on-pi3-solved/6346/6

hifiberry settings seem to enable SPI interface which is used by pin 26 (GPIO7, BCM 11)

**Comment by jofemodo** [comment]
Closing this ;-)
