### ISSUE TITLE
Engine parameter values appear to change when changing parameter page

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#540]
**Describe the bug**
Using the touchscreen to change between parameter screens results in the value of some parameters being incorrectly displayed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add an engine, e.g. Fluidsynth
2. Within engine parameter screen, select different pages by touching the list in the middle of the screen

**Expected behaviour**
Pages of parameters change as appropriate and show the correct values.

**Actual behaviour**
Pages of parameters change as appropriate but show the wrong values.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 11% (217M/1872M)
SD Card: 50% (14G/29G)
Temperature: 46.7ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (478b6ab)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (39b61bb)

**Additional context**
This occurs for many (all?) engines. I have observed volume changing to zero for Fluidsynth whilst output remained at normal volume.

**Comment by riban-bw** [comment]
This is not just cosmetic. Parameters change although it is not clear what they change to!!! I was using GX-Guitar amp simulator and touched the screen to change parameter page and the whole guitar sound changed. The work I had been doing to craft a sound was lost. This is a significant bug!

**Comment by jofemodo** [comment]
I was debugging this problem and discovered it's an old concurrence (a "mutex" scenario) problem that was supposedly solved but in some point, probably when implementing the new controller screen workflow, it was revived. Fortunately, some lost neurons in my brain recalled the old crussade and i could re-enable the original solution (lock/unlock the right code fragments).

Anyway, stay alert with this, as i'm not 100% sure of not creating side effects. Concurrence is a slippery snake.

Regards,

**Comment by jofemodo** [comment]
This is not working well. The change breaks control screen navigation. I reverted it.

**Comment by polluxsynth** [comment]
@riban-bw : have you confirmed that it is only when using the touchscreen to navigate that this happens, not when scrolling through the parameters by clicking select and turning the select knob?

**Comment by riban-bw** [comment]
No, I cannot confirm this is touch only. It may occur when using business. I can't test now because my Zynthian is broken.

**Comment by riban-bw** [comment]
I have tried to trigger this issue with touch and encoder and failed so will close the issue.
