### ISSUE TITLE
Stage Mode++

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#541]
**Is your feature request related to a problem? Please describe.**
I have never really seen the benefit of _Stage Mode_ which routes all MIDI input to the currently selected layer / engine / instrument. Recently I have found it useful for testing and composing by letting me switch my controller between different instruments rapidly which is of course its purpose but it does this at the expense of multitimbrality and does so for __all__ input. Whilst working on something today I realised I wanted the best of both - stage mode and multitimbral mode but how?

**Describe the solution you'd like**
I wanted to be able to control specific instruments from specific controllers whilst switching one of those controllers between instruments. Maybe we could have another mode which used one MIDI channel for stage mode whilst leaving all other MIDI channels multitimbral.

**Describe alternatives you've considered**
I haven't thought of another way to do this.

**Additional context**
This would allow Zynthian to provide sequenced backing tracks whilst a performer uses it leveraging the benefit of stage mode.

**Comment by jofemodo** [comment]
Hi @riban!

>Recently I have found it useful for testing and composing by letting me switch my controller between different instruments >rapidly which is of course its purpose but it does this at the expense of multitimbrality and does so for all input

That's not true. Multitimbrality is still there on stage mode. In fact, you can use the sequencer with several tracks and layers while stage mode is enabled. It's not "all MIDI" what is routed, it's just "external MIDI input".

Anyway, i agree that would be very useful to enable "stage mode" for selected devices only. But first we have to implement "device-filtering" capabilities into the router. Current router implementation is quite "MIDI-centric", where there are no devices, only channels. Messages does not have "device info" associated, so no way of filtering until this info is added on every message.

Thanks!

**Comment by jofemodo** [comment]
It's already implemented in testing:

+ https://github.com/zynthian/zynthian-ui/commit/210617e30823a7459367c7b0ad9d9130e0f51471
+ https://github.com/zynthian/zynthian-ui/commit/2279a8e8ec508ca26d19750a7fee54e3974d2bee
+ https://github.com/zynthian/zynthian-ui/commit/6b8e360e77008e4308001feaa1a3c20c45cd6e50
+ https://github.com/zynthian/zynthian-ui/commit/d29586ec3b1a7ea0d0041f83c59dd81ed2de6d24
+ https://github.com/zynthian/zynthian-ui/commit/eef1a117a8eb77d60c7df34c944d0d95aad3688c
