### ISSUE TITLE
SMF player tempo changing incorrectly

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#543]
**Describe the bug**
Playing take5.mid the tempo slows to 10bpm after a few bars.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load GM snapshot
2. Navigate to MIDI Recorder screen
3. Play take5.mid

**Expected behaviour**
Take 5 plays.

**Actual behaviour**
Take 5 starts then slows to 10bpm.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 29% (272M/923M)
SD Card: 44% (12G/29G)
Temperature: 54.2ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: testing (b214a0f)
zynthian-sys: testing (b49f8e8)
zynthian-data: testing (006a071)
zynthian-webconf: testing (39b61bb)

**Additional context**
This SMF file used:
[take5.zip](https://github.com/zynthian/zynthian-issue-tracking/files/7376720/take5.zip)

**Comment by jofemodo** [comment]
I can't reproduce it now. You probably fix it. Please confirm.
