### ISSUE TITLE
InnoMaker DAC HAT Plays at double speed

### ISSUE THREAD

**Issue by JonathanZeppa** [zynthian/zynthian-issue-tracking#544]
When using packages like setBfree and Obxd, the playback was at double speed.

Specific model: InnoMaker Raspberry Pi HiFi DAC HAT PCM5122

**To Reproduce**
Steps to reproduce the behavior: (from a working PI)
1. NEW Synth Layer
2. Select setBfree
3. Select MIDI Channel 1
4. Select Preset / Upper / Sine / Blues 1 (no change in behavior testing multiple presets)
5. Perform a chord, then adjust the rotary speaker effect 

**Expected behavior**
I expected less latency using the DAC hat, as I've experienced some latency with using the Pi headphone jack.
The rotary function in particular is the most noticeable, playing double speed 

**Screenshots**
Not applicable

**Setup:**
SD-image
 - 2021-05-18-zynthianos-stable-2104

 - Hardware Config
Raspberry Pi 3 Model A Plus Rev 1.0
Soundcard: HifiBerry DAC+
Display: WaveShare 4 HDMI+GPIO
Wiring: MCP23017_EXTRA
GPIO Expander: MCP23017

 - Software Version
zyncoder: stable (7c09738)
zynthian-ui: stable (478b6ab)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (39b61bb)

- System
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 33% (143M/427M)
SD Card: 19% (11G/59G)
Temperature: 30.6ºC

**Comment by jofemodo** [comment]
This card is not in the list of supported cards. We can add it, but first you should find the right configuration for it. This kind of support is better managed from the forum.

Thanks!

**Comment by jofemodo** [comment]
I keep open this issue. When you have the right configuration, please, send it here ;-)

**Comment by JonathanZeppa** [comment]
Will do!

Looks like as a new user I can't make too many replies in the same day.

Here's the output from journalctl -u jack2,
using dtoverlay=allo-boss-dac-pcm512x-audio in the custom device webconf:

-- Logs begin at Wed 2021-10-20 19:14:37 BST, end at Wed 2021-10-20
19:15:34 BST. --
Oct 20 19:14:39 zynthian systemd[1]: Started JACK2 Audio Server.
Oct 20 19:14:39 zynthian jackd[467]: jackdmp 1.9.14
Oct 20 19:14:39 zynthian jackd[467]: Copyright 2001-2005 Paul Davis and
others.
Oct 20 19:14:39 zynthian jackd[467]: Copyright 2004-2016 Grame.
Oct 20 19:14:39 zynthian jackd[467]: Copyright 2016-2019 Filipe Coelho.
Oct 20 19:14:39 zynthian jackd[467]: jackdmp comes with ABSOLUTELY NO
WARRANTY
Oct 20 19:14:39 zynthian jackd[467]: This is free software, and you are
welcome to redistribute it
Oct 20 19:14:39 zynthian jackd[467]: under certain conditions; see the file
COPYING for details
Oct 20 19:14:39 zynthian jackd[467]: JACK server starting in realtime mode
with priority 70
Oct 20 19:14:39 zynthian jackd[467]: self-connect-mode is "Don't restrict
self connect requests"
Oct 20 19:14:40 zynthian jackd[467]: creating alsa driver ...
hw:0|hw:0|256|2|48000|0|0|nomon|swmeter|-|32bit
Oct 20 19:14:40 zynthian jackd[467]: Failed to open server
Oct 20 19:14:40 zynthian systemd[1]: jack2.service: Main process exited,
code=exited, status=255/EXCEPTION
Oct 20 19:14:40 zynthian systemd[1]: jack2.service: Failed with result
'exit-code'.
Oct 20 19:14:41 zynthian systemd[1]: jack2.service: Service RestartSec=1s
expired, scheduling restart.
Oct 20 19:14:41 zynthian systemd[1]: jack2.service: Scheduled restart job,
restart counter is at 1.
Oct 20 19:14:42 zynthian systemd[1]: Stopped JACK2 Audio Server.
Oct 20 19:14:42 zynthian systemd[1]: Started JACK2 Audio Server.
Oct 20 19:14:42 zynthian jackd[557]: jackdmp 1.9.14
Oct 20 19:14:42 zynthian jackd[557]: Copyright 2001-2005 Paul Davis and
others.
Oct 20 19:14:42 zynthian jackd[557]: Copyright 2004-2016 Grame.
Oct 20 19:14:42 zynthian jackd[557]: Copyright 2016-2019 Filipe Coelho.
Oct 20 19:14:42 zynthian jackd[557]: jackdmp comes with ABSOLUTELY NO
WARRANTY
Oct 20 19:14:42 zynthian jackd[557]: This is free software, and you are
welcome to redistribute it
Oct 20 19:14:42 zynthian jackd[557]: under certain conditions; see the file
COPYING for details
Oct 20 19:14:42 zynthian jackd[557]: JACK server starting in realtime mode
with priority 70
Oct 20 19:14:42 zynthian jackd[557]: self-connect-mode is "Don't restrict
self connect requests"
Oct 20 19:14:43 zynthian jackd[557]: creating alsa driver ...
hw:0|hw:0|256|2|48000|0|0|nomon|swmeter|-|32bit
Oct 20 19:14:43 zynthian jackd[557]: Failed to open server
Oct 20 19:14:43 zynthian systemd[1]: jack2.service: Main process exited,
code=exited, status=255/EXCEPTION
Oct 20 19:14:43 zynthian systemd[1]: jack2.service: Failed with result
'exit-code'.
Oct 20 19:14:44 zynthian systemd[1]: jack2.service: Service RestartSec=1s
expired, scheduling restart.
Oct 20 19:14:44 zynthian systemd[1]: jack2.service: Scheduled restart job,
restart counter is at 2.
Oct 20 19:14:46 zynthian systemd[1]: Stopped JACK2 Audio Server.
Oct 20 19:14:46 zynthian systemd[1]: Started JACK2 Audio Server.
Oct 20 19:14:46 zynthian jackd[654]: jackdmp 1.9.14
Oct 20 19:14:46 zynthian jackd[654]: Copyright 2001-2005 Paul Davis and
others.
Oct 20 19:14:46 zynthian jackd[654]: Copyright 2004-2016 Grame.
Oct 20 19:14:46 zynthian jackd[654]: Copyright 2016-2019 Filipe Coelho.
Oct 20 19:14:46 zynthian jackd[654]: jackdmp comes with ABSOLUTELY NO
WARRANTY
Oct 20 19:14:46 zynthian jackd[654]: This is free software, and you are
welcome to redistribute it
Oct 20 19:14:46 zynthian jackd[654]: under certain conditions; see the file
COPYING for details
Oct 20 19:14:46 zynthian jackd[654]: JACK server starting in realtime mode
with priority 70
Oct 20 19:14:46 zynthian jackd[654]: self-connect-mode is "Don't restrict
self connect requests"
Oct 20 19:14:46 zynthian jackd[654]: creating alsa driver ...
hw:0|hw:0|256|2|48000|0|0|nomon|swmeter|-|32bit
Oct 20 19:14:46 zynthian jackd[654]: Failed to open server
Oct 20 19:14:46 zynthian systemd[1]: jack2.service: Main process exited,
code=exited, status=255/EXCEPTION
Oct 20 19:14:46 zynthian systemd[1]: jack2.service: Failed with result
'exit-code'.
Oct 20 19:14:48 zynthian systemd[1]: jack2.service: Service RestartSec=1s
expired, scheduling restart.
Oct 20 19:14:48 zynthian systemd[1]: jack2.service: Scheduled restart job,
restart counter is at 3.
Oct 20 19:14:49 zynthian systemd[1]: Stopped JACK2 Audio Server.
Oct 20 19:14:49 zynthian systemd[1]: Started JACK2 Audio Server.
Oct 20 19:14:49 zynthian jackd[759]: jackdmp 1.9.14
Oct 20 19:14:49 zynthian jackd[759]: Copyright 2001-2005 Paul Davis and
others.
Oct 20 19:14:49 zynthian jackd[759]: Copyright 2004-2016 Grame.
Oct 20 19:14:49 zynthian jackd[759]: Copyright 2016-2019 Filipe Coelho.
Oct 20 19:14:49 zynthian jackd[759]: jackdmp comes with ABSOLUTELY NO
WARRANTY
Oct 20 19:14:49 zynthian jackd[759]: This is free software, and you are
welcome to redistribute it
Oct 20 19:14:49 zynthian jackd[759]: under certain conditions; see the file
COPYING for details
Oct 20 19:14:49 zynthian jackd[759]: JACK server starting in realtime mode
with priority 70
Oct 20 19:14:49 zynthian jackd[759]: self-connect-mode is "Don't restrict
self connect requests"
Oct 20 19:14:50 zynthian jackd[759]: creating alsa driver ...
hw:0|hw:0|256|2|48000|0|0|nomon|swmeter|-|32bit
Oct 20 19:14:50 zynthian jackd[759]: Failed to open server
Oct 20 19:14:50 zynthian systemd[1]: jack2.service: Main process exited,
code=exited, status=255/EXCEPTION


I took a closer look at the dmesg output, and found these lines:
[    0.000000] Kernel parameter elevator= does not have any effect anymore.
               Please use sysfs to set IO scheduler for individual devices.

[    0.490466] brcm-pcie fd500000.pcie:   No bus range found for
***@***.***, using [bus 00-ff]

[    0.569091] bcm2835-aux-uart fe215040.serial: there is not valid maps
for state default

[    2.704632] snd-allo-boss-dac soc:sound: snd_soc_register_card() failed:
-517
[    2.706466] snd-allo-boss-dac soc:sound: snd_soc_register_card() failed:
-517
[    2.737858] snd-allo-boss-dac soc:sound: snd_soc_register_card() failed:
-517
[    2.779006] vc_sm_cma: module is from the staging directory, the quality
is unknown, you have been warned.

[    2.787629] snd-allo-boss-dac soc:sound: snd_soc_register_card() failed:
-517

[    3.099875] ads7846 spi0.1: supply vcc not found, using dummy regulator

[    3.132808] pcm512x 1-004d: supply AVDD not found, using dummy regulator
[    3.132916] pcm512x 1-004d: supply DVDD not found, using dummy regulator
[    3.132959] pcm512x 1-004d: supply CPVDD not found, using dummy regulator

Is it possible the allo configuration doesn't provide the correct voltage
or correct pin out to power the soundcard?

**Comment by JonathanZeppa** [comment]
The correct answer was found on the forum.

1. Select Hardware / Audio
2. Select Custom
3. This card is allo-BossDAC compatible
Under Jackd Options:
-P 70 -t 2000 -s -d alsa -d hw:BossDAC -r 44100 -p 256 -n 2 -X raw
