### ISSUE TITLE
Cannot add 16 layers

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#545]
**Describe the bug**
I can only add 15 layers. Attempt to add 16th will show an empty MIDI Channel list.

**To Reproduce**
Steps to reproduce the behaviour:
1. Disable _Master Channel_
2. Load "FluidR3 GM" snapshot or add 15 layers manually
3. Add a layer

**Expected behaviour**
Channel 16 is available to assign to the new layer.

**Actual behaviour**
There are no channels available to assign to the new layer.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: RBPi Headphones
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 40% (377M/923M)
SD Card: 44% (12G/29G)
Temperature: 55.8ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: off
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: testing (e186abb)
zynthian-sys: testing (b49f8e8)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (39b61bb)

**Additional context**
Master Channel was previously set to 16.

**Comment by riban-bw** [comment]
zynthian_gui_midi_chan.py checks for available channels excluding the master channel. Despite setting master channel to _None_ in webconf, it is still being detected as 15 (16). This means it continues to be ignored.

**Comment by riban-bw** [comment]
I can't reproduce this today. It defo happened but I will close this (to avoid the wrath of the almighty @jofemodo.

**Comment by jofemodo** [comment]
Perhaps you didn't restart UI after disabling Master Channel from webconf?

**Comment by riban-bw** [comment]
I rebooted and saw the problem. I don't have time to investigate further and it seems to be working so let's leave it to sleep until someone else pokes the angry dog!
