### ISSUE TITLE
Audio recorder produces audio splashes on tracks with short leaders

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#546]
**Describe the bug**
When the audio recorder is used to playback audio tracks with short audio silences loud splashes are produced.

**To Reproduce**
1. Load track with very short lead in silence into audio recorder
2. Play track
4. Track can produce loud audio splash before playing track.

**Expected behavior**
Clean audio starts

**Screenshots**
![image](https://user-images.githubusercontent.com/79083/138638205-06b2b176-aa0f-4014-8d0c-c1ac5d80011f.png)

The above is an zynthian audio recording of the start of the attached audio file. IT doesn't always occur but is rather disconcerting in backing track playing.

**Setup:**
![image](https://user-images.githubusercontent.com/79083/138638348-9fa42159-6139-4da5-939d-4773657b8ba3.png)

**Additional context**
This occurs on both Pi3 AND Pi4's I have tried at different sample rates but increasing the audio silence at the start of the track alleviates the problem.

The attached file is a wav renamed to txt to demonstrate.
[splash.txt](https://github.com/zynthian/zynthian-issue-tracking/files/7407413/splash.txt)

It seems any wav with a loud intro ripped from a CD and uploaded via webconf exhibits the effect . Restarts of the zynth sometimes reduce the effect but it's guarenteed to happen at the worst possible moment of course.

**Comment by riban-bw** [comment]
A new audio player is under development. I suggest we put this ticket on hold until that is delivered to avoid effort being spent on something that may be replaced soon.

**Comment by wyleu** [comment]
Agreed

**Comment by riban-bw** [comment]
@wyleu please validate if new audio player has fixed this issue. Also consider that auto-mute was previously enabled by default which could cause clicks when muting/unmuting.

**Comment by wyleu** [comment]
Fixed
