### ISSUE TITLE
Disable Master Channel by default on next SD images.

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#548]
Master channel can cause confusion to most users that doesn't need it nor use it.

**Comment by riban-bw** [comment]
@jofemodo will you please implement this? Disable _master channel_ on the image build system?

**Comment by jofemodo** [comment]
Done!
+ https://github.com/zynthian/zynthian-sys/commit/36315069f799b78923747ed89bfef87868ab5172
+ https://github.com/zynthian/zynthian-webconf/commit/b60b5292d056a3966ddf105a6399ef3bd85bdba7
+ https://github.com/zynthian/zynthian-ui/commit/108d7b1547c40b5702389b6b801416eb84ed090f
