### ISSUE TITLE
Stopping MIDI player does not reset controllers

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#549]
**Describe the bug**
Playing a sequence with the SMF player that adjusts parameters, e.g. pitch-bend does not reset them after stopping.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use SMF player to play Take5
2. Stop part way through
3. Play keyboard or other SMF

**Expected behaviour**
Notes play with correct pitch.

**Actual behaviour**
Notes play with incorrect pitch.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: Behringer UMC1820
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 6% (124M/1872M)
SD Card: 59% (16G/29G)
Temperature: 55.0ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: bug/535_smf_slow_file_read (f8175f4)
zynthian-sys: testing (d81148d)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (39b61bb)

**Additional context**
Probably only pitch bend we should fix. Maybe also after touch. Other controls may not have known starting state.

**Comment by jofemodo** [comment]
For correctly resetting all controllers, it should save the state of all the controllers before starting to play.

**Comment by riban-bw** [comment]
That is a lot of data (all the controllers for all the channels) and may not be desirable as you may be tweaking things manually as you go. I think the most appropriate compromise is to just reset the controllers that traditionally have a bias, e.g. pitch bend bias to centre and after touch bias to zero.

**Comment by jofemodo** [comment]
OK. Totally agree ;-)
