### ISSUE TITLE
Random issues at boot with engines not starting ( no gui )

### ISSUE THREAD

**Issue by smiths73v3** [zynthian/zynthian-issue-tracking#55]
**Describe the bug**
An engine failure at boot will cause the GUI not to start.

**To Reproduce**
Boot System, observe black screen (no gui)

**Expected behavior**
Normal system startup with gui

**Setup:**
 - SD-image
2019-06-20-zynthianos
 - Hardware Config
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+
Display: Generic HDMI Display
Wiring: MCP23017_EXTRA
 - Software Version
zyncoder: master (80862b6)
zynthian-ui: master (3688c73)
zynthian-sys: master (b289ae9)
zynthian-data: master (676c32a)
zynthian-webconf: master (0094c99)

**Additional context**
From the logs, it appears that bFree did not load for some reason.

`Jul 19 19:15:06 zynthian startx[414]: ERROR:root:Can't start engine setBfree => <pexpect.pty_spawn.spawn object at 0x6d5caf90>
`
Everything else seems to be good. I can play the other mapped midi channels just fine despite not having any screen. I currently have about 5 engines loaded. Removing power and rebooting seems to clear it up. I have not been able to figure out a correlation to any actions at the moment. Perhaps some of the "once per day" tasks getting in the way? I tend to power up in the evening, play for a bit, and shut down for the night.

**Comment by jofemodo** [comment]
I think this is solved in latest Buster builds ...
