### ISSUE TITLE
Duplicate entries in MIDI recorder screen

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#550]
**Describe the bug**
Sometimes there are ghost duplicate entries in the MIDI recorder screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to MIDI Recorder screen
2. Start and stop playback a few times

**Expected behaviour**
List of available SMF files is displayed.

**Actual behaviour**
List of available SMF files is duplicated in display.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: Behringer UMC1820
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 6% (124M/1872M)
SD Card: 59% (16G/29G)
Temperature: 55.0ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: bug/535_smf_slow_file_read (f8175f4)
zynthian-sys: testing (d81148d)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (39b61bb)

**Additional context**
This has happened a couple of times but I am finding it difficult to reproduce on demand.

**Comment by wyleu** [comment]
Seen something similar in Audio recorder as well. Might or might not be same effect.

**Comment by riban-bw** [comment]
@wyleu good - less likely to be my code that introduced it!

**Comment by jofemodo** [comment]
I can't reproduce this issue. I think it's gone now!
