### ISSUE TITLE
MIDI Recorder screen selecting "Record" when playing last SMF

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#551]
**Describe the bug**
When I play each SMF file in the MIDI recordings list the file remains highlighted allowing toggle playback except when the last one is selected in which case the highlight jumps to the top - Toggle Record.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add several MIDI recordings
2. Play last recording in list

**Expected behaviour**
Selected recording remains highlighted.

**Actual behaviour**
"Start Recording"  becomes highlighted.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: Behringer UMC1820
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 6% (124M/1872M)
SD Card: 59% (16G/29G)
Temperature: 55.0ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: bug/535_smf_slow_file_read (f8175f4)
zynthian-sys: testing (d81148d)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (39b61bb)

**Additional context**
I have 5 recordings in my list, all on internal storage.

**Comment by jofemodo** [comment]
This seems to be fixed now. Please confirm.
