### ISSUE TITLE
Zynthian slows (and stops) after restarts

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#555]
**Describe the bug**
When restarting the Zynthian UI there are often increasing quantity of xruns and the UI becomes slower. This may be due to memory leaks.

**To Reproduce**
Steps to reproduce the behaviour:
1. From Admin menu, select RestartUI
2. Repeat step 1 until issue observed

**Expected behaviour**
Zynthian works as well the 100th time as it does the 1st.

**Actual behaviour**
Zynthian gets increasing bad until it eventually stops working.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: Behringer UMC1820
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 9% (186M/1872M)
SD Card: 59% (16G/29G)
Temperature: 55.0ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: zynmixer (0584d94)
zynthian-sys: testing (d81148d)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (39b61bb)

**Additional context**
I suspect this is one or more of the C++ libraries not unloading properly or freeing all its resources.

**Comment by riban-bw** [comment]
This is likely to be my fault! I suspect some of the libraries I have created may not behave well when closed or maybe they are not being closed properly.

**Comment by jofemodo** [comment]
Could you determine what library is causing the issue?

**Comment by riban-bw** [comment]
Duplicated by #718 so closing this ticket.
