### ISSUE TITLE
Mouse wheel activates zynmixer volume faders

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#556]
**Is your feature request related to a problem? Please describe.**
Scroll wheel control of selected fader seems natural.

**Describe the solution you'd like**
With a selected fader ( volume control, what's the term?) increasing and decreasing the mouse wheel should alter the current setting and this should be displayed correctly.

**Describe alternatives you've considered**
Dragging the mouse pressed :-D

**Comment by riban-bw** [comment]
I have implemented this in development branch. If cursor (pointer) is hidden then the selected channel's fader is adjusted by 2% for each mouse wheel pulse. If cursor is shown then the fader under the cursor is adjusted.

I don't have a mouse with where here (will grab one later) so only tested with laptop two finger drag.

**Comment by riban-bw** [comment]
I already know what you will ask next and I am working on it...

**Comment by riban-bw** [comment]
Also allows mouse wheel to adjust balance when pointer over channel balance or legend strip.
