### ISSUE TITLE
ZynMixer main effects

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#558]
**Is your feature request related to a problem? Please describe.**
It should be possible to add audio effects to the main output of ZynMixer.

**Describe the solution you'd like**
The context menu for the main mix bus should be similar to the context menu for an input channel strip, i.e. allow manipulation of the chain including adding, modifying and removing effects. (Currently this behaviour is undefined which is a bug.) This chain should be before the main output audio meters and probably pre-fader, i.e. the main fader should operate on the final output.

**Describe alternatives you've considered**
This is my design and I stand by it!

**Additional context**
This may require modification to the mixer library to add an insert point in the main output so that the main mix can be fed out to effects and return to the mixer to allow fader / metering then appear again on the main output. This is directly analogous to analogue mixing desks that may have inserts on the main output.

**Comment by jofemodo** [comment]
Already done!!
