### ISSUE TITLE
Favourite presets not working

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#559]
**Describe the bug**
If I save a favourite preset I get odd behaviour and locked up UI.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add setBFree engine
2. Add favourite preset
3. Select favourite preset

**Expected behaviour**
Can select from list of favourite presets.

**Actual behaviour**
Selecting from list of favourite presets results in UI lockup.
**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: Behringer UMC1820
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 29% (551M/1872M)
SD Card: 59% (16G/29G)
Temperature: 54.5ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: zynmixer (2b43da1)
zynthian-sys: testing (d81148d)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (39b61bb)

**Additional context**
Error message:
```
ERROR:zynthian_engine_setbfree.load_program_list: Getting program info from *FAVS* => [Errno 2] No such file or directory: '*FAVS*'
```
Similar errors when trying to load snapshots when favourite engines exist.

**Comment by riban-bw** [comment]
This is pretty bad. If you add favourites to an instrument you can no longer use Zynthian with that instrument because any attempt to do so locks up Zynthian requiring power restart.

**Comment by jofemodo** [comment]
I can't reproduce the issue following your steps. It works OK for me. Using zynmixer branch.

**Comment by riban-bw** [comment]
It has been happening a lot but interfering with my efforts so I have not had time to detail the exact steps to reproduce. I will try to do so an update this ticket.

**Comment by riban-bw** [comment]
It's a bit tricky because my setBFree is broken. Where is the config that defines favs? I will need to manually fix this to get back to a state where I can start to fault find.

[Edit] Found it in /zynthian/zynthian-my-data/preset-favorites/BF.json. I have deleted and trying again...

Here is that file:
[BF.zip](https://github.com/zynthian/zynthian-issue-tracking/files/7442909/BF.zip)

**Comment by riban-bw** [comment]
- Clean All
- Add New Synth Layer, setBFree
- MIDI CH#1
- Upper
- Sine
- Highlight "Blues 1"
- Bold press SELECT - Added to favourites
- Short press SELECT to load the preset
- Save snapshot
- Load different snapshot
- Load SetBFree snapshot
- Go to Layers screen and see "1#BF/Sin > *** Favorites ***"
- Short press SELECT to select this entry
- Zynthian hangs

Errror message:
```
Oct 29 16:07:52 zynthian1 startx[31779]: ERROR:zynthian_engine_setbfree.load_program_list: Getting program info from *FAVS* => [Errno 2] No such file or directory: '*FAVS*'
Oct 29 16:07:52 zynthian1 startx[31779]: WARNING:zynthian_layer.restore_snapshot_1: Invalid Preset on layer 1#BF/Sin: 'NoneType' object is not iterable
Oct 29 16:07:52 zynthian1 startx[31779]: ERROR:zynthian_gui_layer.load_snapshot: Invalid snapshot: 'NoneType' object is not iterable
Oct 29 16:07:52 zynthian1 startx[31779]: Traceback (most recent call last):
Oct 29 16:07:52 zynthian1 startx[31779]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 1257, in load_snapshot
Oct 29 16:07:52 zynthian1 startx[31779]:     self._load_snapshot_layers(snapshot)
Oct 29 16:07:52 zynthian1 startx[31779]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 1386, in _load_snapshot_layers
Oct 29 16:07:52 zynthian1 startx[31779]:     self.zyngui.set_curlayer(self.layers[self.index])
Oct 29 16:07:52 zynthian1 startx[31779]:   File "./zynthian_gui.py", line 658, in set_curlayer
Oct 29 16:07:52 zynthian1 startx[31779]:     self.screens['bank'].fill_list()
Oct 29 16:07:52 zynthian1 startx[31779]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_bank.py", line 47, in fill_list
Oct 29 16:07:52 zynthian1 startx[31779]:     self.zyngui.curlayer.load_bank_list()
Oct 29 16:07:52 zynthian1 startx[31779]:   File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 152, in load_bank_list
Oct 29 16:07:52 zynthian1 startx[31779]:     for bank in self.bank_list:
Oct 29 16:07:52 zynthian1 startx[31779]: TypeError: 'NoneType' object is not iterable
```

**Comment by jofemodo** [comment]
OK! I think i have fixed this. setBfree needs a deep revision because of the way it re-uses the bank selector for selecting things that are not a bank. We need a mechanism for selecting engine specific options.
