### ISSUE TITLE
Enable QmidiNet (MIDI over IP) Not working properly.

### ISSUE THREAD

**Issue by 1st-BrainStormer** [zynthian/zynthian-issue-tracking#56]
**Describe the bug**
Enable QmidiNet (MIDI over IP Not working correctly

**To Reproduce**
1. Go to 'Interface->MIDI Options'
2 Check  'Advanced'
3. Check  
4. Click 'Save'
5. Go into "+" on Midi Ports
6. Note that "QmidiNet:out 1,QmidiNet:in 1,QmidiNet:in 1" Do not appear
7. Back-out and uncheck  'Enable QmidiNet (MIDI over IP)'
8. Click 'Save'
9. Go into "+" on Midi Ports
10. Note that "QmidiNet:out 1,QmidiNet:in 1,QmidiNet:in 1" DO appear.

**Expected behavior**
When enabling Qmidinet the ports should appear when its enabled
and not when it is disabled.

**Setup:**
 - SD-image
        Aruk RC3
 - Hardware Config
        Raspberry Pi 3 Model B Plus Rev 1.3 
        Soundcard: Behringer UMC404HD (USB) 
        Display: WaveShare 5 HDMI+GPIO 
        Wiring: MCP23017_EXTRA 
 - Software Version
        zyncoder: master (4651ea0) 
        zynthian-ui: master (ec8be3e) 
        zynthian-sys: master (1888cd0) 
        zynthian-data: master (7feff4d) 
        zynthian-webconf: master (0094c99) 

**Additional context**
I am trying to use Midi over IP to connect to RTPMidi on my windows machine.

**Comment by jofemodo** [comment]
Could you try from the Zynthian UI's Admin menu?

Thanks!

**Comment by 1st-BrainStormer** [comment]
It seems to be only in the advanced-> ports settings that are mismatched.
Also I'm testing with VMPK. I can send notes to zynthian but not from.

**Comment by jofemodo** [comment]
It's only a "refresh" problem. If you reload the MIDI options page the ports will appear. I leave the issue open i will correct the refresh problem anyway ;-)

Regarding the "send" problem, i will try to reproduce, but, could you try with another Linux machine with QMidiNet?

**Comment by jofemodo** [comment]
Hi! I just tested with my desktop fedora 23 + qmidinet (last version) and it works perfectly for me. Sending and receiving works like a charm ;-)

**Comment by 1st-BrainStormer** [comment]
Ok Thanks,   oh BTW have you checked out https://github.com/ravelox/pimidi
its a implementation of RTP-Midi (AppleMidi)  it can go past a router or VLAN.
