### ISSUE TITLE
Set BPM of zynthian clock / sequencer as a UI action

### ISSUE THREAD

**Issue by julesdg6** [zynthian/zynthian-issue-tracking#563]
Currently, the only way I can find to set BPM for the zynthian is from the sequencer menu. I would like to be able to assign BPM speed as a UI-Action just as we can with the sequencer start/stop/pause controls. I hope this would allow us to control BPM as both a realtime control (via the wiring page), and also as a sequenced event to alter the speed during a sequenced song.

**Comment by riban-bw** [comment]
Do you want to be able to bump the tempo up/down by 1/0.1 BPM and/or set the absolute value?

**Comment by julesdg6** [comment]
up/down by 1bpm would be great. I assume that would actually require 2 actions (i hadn't thought of that). One action to move up 1bpm and another action to move down 1bpm. 

I think if you went to 0.1 bpm it would be too granular and you would end up turning and turning to get results.

**Comment by riban-bw** [comment]
I have added CUIA commands to:

- TEMPO set absolute tempo to first CUIA parameter
- TEMPO_UP nudge up by first CUIA parameter or by 1 BPM if no parameter provided
- TEMPO_DOWN nudge down by first CUIA parameter or by 1 BPM if no parameter provided

This is in the feature/slave_to_midi_clock dev branch. I will close this issue as I expect this to be merged into testing soon.
