### ISSUE TITLE
Partially adding new layer leaves in inconsistent state

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#566]
**Describe the bug**
Adding a layer but not completing all steps can leave the layer partially configured and not useable or easily accessible.

**To Reproduce**
Steps to reproduce the behaviour:
1. New Synth Layer
2. setBfree
3. MIDI CH#2
4.  Short-Back

**Expected behaviour**
Layer is not added.

**Actual behaviour**
Layer is added but not fully configured.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: Behringer UMC1820
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 12% (240M/1872M)
SD Card: 59% (16G/29G)
Temperature: 50.6ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: on
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: zynmixer (aa69929)
zynthian-sys: testing (d81148d)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (3b5c0d7)

**Additional context**
Adding a layer should be atomic. The operation should complete or cancel and layer removed. If the user cancels part way through the wizard, i.e. does not complete all steps, the layer should be removed. With ZynMixer branch we end up with a layer that is not easily accessible. It does not appear in the mixer. You must go to the control screen, press LAYER button until you select the partially configured layer then complete the wizard which is suboptimal.

**Comment by riban-bw** [comment]
I think the main issue here is that you can cancel out of the bank or preset selection. Maybe the creation of the engine (at the MIDI channel step) should configure with the default / first bank/preset before progressing to the bank selection page. This may allow the bank and preset selection page navigation to be consistent, e.g. allow short-back to close whilst ensuring the engine has sufficient configuration if this occurs during creation.

**Comment by riban-bw** [comment]
The current codebase does not lend itself to an easy fix. I tried to load a preset when the engine is first loaded but this results in skipping the bank/preset selection. I tried to clear unconfigured engines but some engines don't use presets, e.g. many audio plugins.

This will best be solved by implementing an atomic process to add a layer (chain). I suggest this be deferred until we separate the GUI from the core which will likely be in the next development cycle. Removing Release milestone.

**Comment by jofemodo** [comment]
With the latest fix this issue should be mitigated, if not totally solved.
setBfree is a different animal and perhaps the issue is not totally solved for it. After refactorization, all "multi-layer" engines will be "single" nodes in a chain that listen several MIDI channels, what will allow to easily fix this,

**Comment by jofemodo** [comment]
I don't think the "state" described here is inconsistent. It's incomplete and the created chain must be configured, choosing the model, keyboard layout, ban & preset. But it's not broken at all. In fact, when you try accessing chain control, you will be prompted for the needed options and the engine is then correctly started.
So, i don't see this as a "bug", but a "workflow feature", and although it could be discussed if it's the best workflow, it's not wrong.
