### ISSUE TITLE
Remove "*** Favorites ***" from top of bank list

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#567]
**Is your feature request related to a problem? Please describe.**
The first entry in the bank selection list is "*** Favorites ***" if any favourites have been configured. I think this was added recently as a simple way to access favourites. The proposed navigation schema for ZynMixer branch allows fast toggle of favourites which renders this entry redundant.

**Describe the solution you'd like**
Remove "*** Favorites ***" from bank list.

**Additional context**
Need to consider if there are any workflows that still benefit from this, e.g. are favourites accessible from touchscreens?

**Comment by jofemodo** [comment]
This was added for touch-screen users. I think is not a bad mechanism, as you can see banks as a kind of "virtual bank".
