### ISSUE TITLE
setBfree & Zynmixer: only last layer is shown

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#568]
**Describe the bug**
When using setBfree with multi-manual setup only the last layer is shown on the mixer screen.

**To Reproduce**
1. New Synth Layer => setBfree
2. Lower + Upper
3. Sine (it doesn't matter)

**Expected behavior**
The 2 setBfree layers are shown in the mixer view

**Setup:**
 - Zynmixer branch
 - Officlal v4.5 kit

**Comment by riban-bw** [comment]
ZynMixer currently shows a strip for each channel that has audio routed to it. This configuration results in a single setBfree engine with stereo output routed to just one channel of the mixer.

We should probably move away from using audio routing as an indication of a channel and instead use the root layers.

ssetBfree acts oddly in that it seems to have multiple layers but just one engine. Could @jofemodo please describe how the engine operates?

**Comment by jofemodo** [comment]
setBfree, same as Aeolus, are special beasts in the Zynthian world. They use several MIDI channels (one per manual), but have a common audio output. This fits the real device but challenges software architecture.

Currently you can add audio FXs to the common audio output. This is done adding FX to any setBfree layer. You can also add MIDI FX on the different layers (manuals). It's not clean, but it works and you can do most things in such a way.

We have to think about it and zynmixer must evolve to support this cases, and also chains with no audio output at all (MIDI FX chains, for instance).

Regards,

**Comment by riban-bw** [comment]
Recent change to mixer view now shows all layers, not just the ones with audio routed to mixer. This resolves this issue. setBfree and Aeolus now show all layers but only the highest numbered channel has actual audio, e.g. with setBfree configured with "Pedals + Lower + Upper" there are three channel strips, one each for Upper, Lower and Pedal but audio is controlled and monitored on the third (Pedal) channel. This may seem counter-intuitive but is much improved on previous behaviour.

There are still issues presenting these _special_ engines but I will close this ticket as this specific issue is resolved. Each layer can be accessed and controlled. Audio level for the whole engine can be controlled and monitored. Removing any of the layers will remove the whole synth engine.
