### ISSUE TITLE
Non-audio layers not accessible in zynmixer branch

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#569]
**Describe the bug**
ZynMixer branch presents layers as chains feeding channel strips in an audio mixer. Access to each channel is from the mixer but non-audio channels such as MIDI effects chains can not be easily accessed after they are created.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add MIDI effects layer
2. Try to access the MIDI effects layer

**Expected behaviour**
Ability to access MIDI effects layer.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 20% (192M/923M)
SD Card: 44% (12G/29G)
Temperature: 55.8ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: off
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (7c09738)
zynthian-ui: zynmixer (643aaa2)
zynthian-sys: testing (b49f8e8)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (39b61bb)

**Additional context**
It may be advantageous to present MIDI chains as empty channels, i.e. just the channel number in the legend strip to allow it to be accessed.

It is possible to access MIDI layers by pressing the LAYER button within the control screen to page through the layers.

**Comment by jofemodo** [comment]
This can be also useful for engines using multiple MIDI channels and a single audio output (setBfree, Aeolus). We could find a way of "grouping chains" (logic and visually) sharing a common audio output.

**Comment by riban-bw** [comment]
Fixed by presenting all layers in mixer view.
