### ISSUE TITLE
Pressing Learn makes zynthian unresponsive

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#570]
**Describe the bug**
Pressing Learn touch button makes zynthian unresponsive 
generates 

Nov 12 18:01:38 zynthian-1820 startx[472]: ERROR:zynthian_gui.plot_zctrls: 'snapshots'
Nov 12 18:01:39 zynthian-1820 startx[472]: ERROR:zynthian_gui.zyncoder_read: 'snapshots'
Nov 12 18:01:39 zynthian-1820 startx[472]: Traceback (most recent call last):
Nov 12 18:01:39 zynthian-1820 startx[472]: File "./zynthian_gui.py", line 1285, in zyncoder_read
Nov 12 18:01:39 zynthian-1820 startx[472]: free_zyncoders = self.screens[self.modal_screen].zyncoder_read()
Nov 12 18:01:39 zynthian-1820 startx[472]: KeyError: 'snapshots'

![image](https://user-images.githubusercontent.com/79083/141514552-61a7b9d7-e6ab-4ca4-85c9-b25d60addd88.png)

And could we have some indication of what buttons are meant to do what? Nothing seems to do what it says now.

**Comment by jofemodo** [comment]
Sorry, i can't reproduce.

**Comment by jofemodo** [comment]
Regarding the UI documentation, yes, it needs some update ;-)
