### ISSUE TITLE
Addition of Current Value on a zynmixer fader.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#571]
**Is your feature request related to a problem? Please describe.**
Whilst modifying a parameter in the zynthian parameter screen small movements can be discerned by the c hange of the value.

**Describe the solution you'd like**
A current overall gain multiplier string displayed at current fader top edge interface

**Describe alternatives you've considered**
No alternative.

**Additional context**
It would help unify the overall zynthian object modification model.

**Comment by riban-bw** [comment]
Are you asking for a temporary display of fader value as the fader is adjusted? Would this timeout after some period like a "toast"? Would we want the same for any parameter changed? Could this be shown in the top strap, similar to how tempo is shown when adjusted in the sequencer?

**Comment by riban-bw** [comment]
The title of this issue refers to mixer whilst the content refers to parameter screen. I am could to (conveniently) assume you mean mixer which is now implemented.
