### ISSUE TITLE
Merging of snapshots

### ISSUE THREAD

**Issue by gonzob** [zynthian/zynthian-issue-tracking#575]
**Is your feature request related to a problem? Please describe.**
No problem, just an opportunity created by the new mixer

**Describe the solution you'd like**
I have a number of FluidSynth snapshots of single instruments tuned the way I like (i.e with audioFX in the chain). Sometimes there is need to have two or three of these available for quick change. A sub-snapshot approach will achieve this, but it takes quite a while to set up. It would be nicer with the new mixer arrangement to be able to load multiple pre-configured single-layer snapshots

**Describe alternatives you've considered**
None

**Additional context**
Original discussion here: https://discourse.zynthian.org/t/merging-snapshots/6454?u=gonzob

Once this item is completed, I will probably raise tickets for the following features, so keep them in mind:
- the ability to name the layers (preferably from the snapshot title, but could be a separate mechanism)
- the ability to quickly select a layer (i.e. from a stomp box via MIDI or maybe HMI device)
- a way to adjust the order of layers, or determine where each new layer gets inserted

**Comment by riban-bw** [comment]
I have implemented this feature in vangelis (testing) branch. I tracked its progress in a duplicat issue #1273 so read there for details. To avoid confusion, I will close this issue as a duplicate (despite me creating the other issue later).
