### ISSUE TITLE
Problem with loading complex snapshots

### ISSUE THREAD

**Issue by multim0** [zynthian/zynthian-issue-tracking#577]
**Describe the bug**
I’ve tried to prepare some 10 layer snapshot using multiple Linux Sampler and Fluid Synth instuments. Also I’ve applied some audio FX for guitar and noise maker. It seems that everything works fine during inital configuration but after I reload snapshot two layers go mute and audio effects doesn’t work.
This occurs every time for similiar scenario when I use TAL reverb and Gain FXs (one, serial for each channel) and multiple engines.
I’m sure it is connected to audio fx chain restoring or saving, because this happens for different engines with different setups.
In logs I can see Xruns when fx plugins are resetting, but no errors or warnings during loading.
When I look into layer options, audio output, then no output is set for corrupted layers.

**To Reproduce**
(At least) on my device:
1. Configure new snapshot with at least few layers (SFZ player, SF2 player and other).
Add at least one reverb (eg. TAL II) and Gain audio fx-es for each layer.
2. Store snapshot with this configuration.
3. All works well until device is not restarted.
4. Restart Zynthian.
5. Some audio chains do not load properly, some audio routes are "unchecked" and layers do not produce the sound.

On any other devices:
1. Load snaphot 05-Gig Basic.zss or 007-LS;SFZ;Pianos;SalamanderGrandPianoV3.zss
2. Some audio chains do not load properly, some audio routes are "unchecked" and layers do not produce the sound.
In first snaphot affected layers are 1st Fluid Synth (Full Grand) and 7th Noize Mak3r
In second that are: 

**Expected behavior**
Layers and audio chains should be restored to the same state, that they were configured.

**Setup:**
 - SD-image: 
2021-09-25-zynthianos-stable
 - Hardware Config: 
 Zynthian Kit v4.3 (HifiBerry DAC+ ADC PRO
 - Software Version:
zyncoder: stable (7c09738)
zynthian-ui: stable (478b6ab)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (39b61bb)

Snapshots that are not loaded correctly:
[corrupted-snapshots.zip](https://github.com/zynthian/zynthian-issue-tracking/files/7653779/corrupted-snapshots.zip)

**Comment by riban-bw** [comment]
This seems to work well with the latest testing branch. I did not experience the described issues when creating and restoring similar snapshots and the "005-Gig Basic" snapshot seems to load without issue. It is quite large but all routes seemed to be made. I will leave the ticket open until we release to stable so that you can retest.

**Comment by riban-bw** [comment]
No issues in staging so closing.
