### ISSUE TITLE
Add "Trigger out" as a Customizable Switch option under Wiring

### ISSUE THREAD

**Issue by julesdg6** [zynthian/zynthian-issue-tracking#578]
Add "Trigger out" as an option on the 16 digital i/o's on the zynface

On the "wiring" page of the web config, you would just need to add "midi channel" and "midi note" as parameters. For instance, if you wanted to trigger a kick drum, you would set it as midi channel 10, note 36. This would allow the sequencer to trigger drum synths and other outboard gear.

I can use the gate on a CV/Gate pair, but that is limited to only 4 of the I/O's

**Comment by jofemodo** [comment]
Hi @julesdg6 !!

It's implemented. Please, update on testing and try.

Enjoy!

**Comment by jofemodo** [comment]
Hi @julesdg6 !

Finally i could test and after fixing a few bugs, everything is working for me, including the recently added gate-out option for the custom switches. I hope you can test it very soon. 

Regards!
