### ISSUE TITLE
Missing dependancy for z2rf branch

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#579]
**Describe the bug**
Zynthian does not start when using z2rf branch.

**To Reproduce**
1. Update to z2rf branch for zyncoder and zynthian-ui
2. Reboot

**Expected behavior**
Zynthian starts.

**Actual behavior**
Zynthian does not start. Error: `ModuleNotFoundError: No module named 'rpi_ws281x'`.

**Setup:**
* HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: Behringer UMC1820
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
* SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 4% (91M/1872M)
SD Card: 61% (17G/29G)
Temperature: 51.1ºC
* MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
* SOFTWARE
zyncoder: z2rf (b4116ec)
zynthian-ui: z2rf (d8af92e)
zynthian-sys: testing (d81148d)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (f998b4a)

**Additional context**
Looks like rpi_ws281x python module needs to be added which may require a development branch for zynthian-sys. Can reslove with `pip3 install rpi_ws281x`.

**Comment by jofemodo** [comment]
Update scripts are updated on zynthian-sys for installing rpi_ws281x package:

https://github.com/zynthian/zynthian-sys/commit/52d000d073b84af7fe7753cca5401cbde263cdc0

How did you update to z2rf? Could you check the logs?

Thanks

**Comment by jofemodo** [comment]
I just tested again and i can't find any problem. Please, reconfirm or close.

**Comment by riban-bw** [comment]
I ran update from webconf. I just did this again and saw the error:
`fatal: refusing to merge unrelated histories`
so there is something odd with git. Not sure if it is on my or your side. I don't remember changing the sys folder. More investigation required...

[Edit] My zynthian-sys working copy has been linked with remote zynthian-data. I can't think how that happened. I am checking webconf history to see if there may have been an error. The last log entry in my zynthian-sys is for 21 Aug so will look around then.

I fixed my local working copy thus:
```
cd /zynthian/zynthian-sys
git remote remove origin
git remote add origin git@github.com:zynthian/zynthian-sys.git
git branch --set-upstream-to=origin/testing testing
```

Let's close this ticket as it is plausible I buggered things up myself. If someone else has an issue we can revisit.

**Comment by jofemodo** [comment]
Nice! BTW, i just merged z2rf on testing, before you commit more changes to testing ;-)
FYI, with this merge, the testing branch is ready to work on the Z2 prototypes we are finishing. I hope you will have your Z2 proto by the first weeks of 2022.
