### ISSUE TITLE
Encoders erratic

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#582]
**Describe the bug**
The SELECT encoder is moving random quantity of steps when selecting mixer channel strip.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add several layers
2. Rotate SELECT encoder whilst on mixer page

**Expected behaviour**
Cursor moves one channel per detent.

**Actual behaviour**
Cursor moves several channels per detent.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 17% (336M/1872M)
SD Card: 59% (16G/29G)
Temperature: 53.5ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (20837dd)
zynthian-ui: testing (a1c0e18)
zynthian-sys: testing (446e665)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (f998b4a)

**Additional context**
This seems to have occurred since z2rf was merged to testing. It looks like there are several steps being triggered per detent. Partially turning encoder selects next channel but resting at next detent jumps forward.

**Comment by jofemodo** [comment]
Fixed in https://github.com/zynthian/zynthian-ui/commit/5a3c76db6643000a7d92626f6bfdac9da4fe17fa
