### ISSUE TITLE
Cannot add sub-snapshot

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#584]
**Describe the bug**
There does not seem to be a way to assign a sub-snapshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to engine control screen
2. Press snapshot twice

**Expected behaviour**
Listen for program change.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 17% (336M/1872M)
SD Card: 59% (16G/29G)
Temperature: 53.5ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (20837dd)
zynthian-ui: testing (a1c0e18)
zynthian-sys: testing (446e665)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (f998b4a)

**Additional context**
This seems to be a casualty of workflow and navigation changes. Maybe this should be added to the layer/chain context menu.

**Comment by jofemodo** [comment]
Documentation is not updated to the testing branch (in fact it's not updated to current stable!!)
After the recent workflow changes, MIDI learn is accessed by "bold-clicking" the "learn/snapshot" button, so you have to make:

+ bold learn + short learn 

for accessing subsnapshot learning. It's far from intuitive. MIDI learning workflow needs some attention ;-)
