### ISSUE TITLE
Encoder does not step between enumerated values consistently

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#585]
**Describe the bug**
When a control has a list of values with associated labels, the encoder often requres several detents to be passed before the value changes.

**To Reproduce**
1. Add Pianoteq layer
2. Adjust SELECT encoder

**Expected behaviour**
Sustain pedal changes value on each detent of encoder rotation.

**Actual behaviour**
Sustain pedal changes value on each second or third detent of encoder rotation.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 21% (403M/1872M)
SD Card: 59% (16G/29G)
Temperature: 53.0ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (14e0a2b)
zynthian-ui: testing (0ddb0e1)
zynthian-sys: testing (446e665)
zynthian-data: testing (7ca0778)
zynthian-webconf: testing (f998b4a)

**Additional context**
Current implementation assumes all enumeration steps are equally spaced and has integer rounding error. It would be better for the controller to know this is an enumerated list and associate the encoder value with the index of the step, i.e. set encoder range to span quantity of enumerations and look up each value from emuneration list. This hits lots of the code and may be best updated in a refactor of this bit of the code, e.g. new_zyncoder_algorithm development branch. (I started but got lost in the warren.)

**Comment by jofemodo** [comment]
I've made some improvements to the zynthian_gui_controller class and the behaviour now seems to be a lot better:

https://github.com/zynthian/zynthian-ui/commit/e8cd3676071a17ee5fa6a1a4739d15f83d790ce8

Could you update and test?

**Comment by riban-bw** [comment]
This is much better but the limits are wrong. The first and last steps do nothing, e.g. Pianoteq rotate SELECT encoder:

- off
- off
- 1/4
- 1/2
- 3/4
- full
- full

Removing 2205 milestone as current behaviour is much improved and won't block stable release (although it would be nice if it fully worked properly!).

**Comment by jofemodo** [comment]
Most of people could use Zynthian all his life and wouldn't be conscious about this detail. In spain we use to say that you are a "tikis-mikis" ... jajaja! Same as me, but different. Good for Zynthian, anyway!! Tikis-mikismo is always good for improving things ,-DD I will take a look to this when feel inspired.

**Comment by riban-bw** [comment]
> The word tiquismiquis means fussy or nitpicker in English. It's used to describe someone's character. This is someone who is hard to please and demanding about his requirements and needs.

Some say I am pedantic whilst others say I have a high attention to detail :-) This kind of detail is the difference between a user feeling great about a product or feeling there is something wrong that they can't quite pinpoint. We must indeed fix the big issues first but should also record the small ones so they don't go unfixed forever. I like the software development term, "papercuts" for small issues that don't stop the core workflow but are irksome. Some development teams have a short push of fixing paper cuts. I tend to use this kind of bug as a distraction when the tough stuff is proving challenging. Pick of something simple then get back to the big stuff.

Priority - low.

**Comment by riban-bw** [comment]
This is now fixed by encoder library moving to relative steps rather than absolute steps and moving value to Python zyncoder object.
