### ISSUE TITLE
Can't disable VNC in webconf

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#589]
**Description**
When VNC is enabled, navigating to webconf: Interface -> UI-options and unciicking Enable VNC server and clicking Save should result in the VNC server being disabled. Instead, the box remains clicked. It's necessary to manually edit zynthian_envars.sh and rebooting to disable it.

**To Reproduce**
1. Enable VNC in webconf (navigate to Interface -> UI-options, and check Enable VNC Server)
2. Click Save
2. Reboot
3. Disable VNC in webconf (navigate to Interface -> UI-options, and uncheck Enable VNC Server)
4. Click Save
5. Note how Enable VNC Server is still checked

**Expected behavior**
When VNC is disabled in webconf by unchecking Enable VNC Server, it should remain checked after clicking Save, and the VNC links should disappear from the Interface menu.

**Setup:**
- SD image
2021-09-25-zynthianos-stable.img 
- HARDWARE: Zynthian kit v4.4 (4 GB)
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-25
Memory: 3% (121M/3839M)
SD Card: 44% (13G/29G)
Temperature: 48.2ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (478b6ab)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (39b61bb)

**Comment by jofemodo** [comment]
Please, update and test (on testing!).

**Comment by polluxsynth** [comment]
Tested by applying patch to my local stable branch, works fine now. Thanks!
