### ISSUE TITLE
Add Midi port selection to Midi filter rules

### ISSUE THREAD

**Issue by 1st-BrainStormer** [zynthian/zynthian-issue-tracking#59]
I'm trying to get rid of a midi feedback loop.  I have 2 Keyboards. One physical one and one I built in VR. The real one plays zynthian and is passed through to the VR one which lights up the keys.  The when playing the VR Keyboard it ouputs back to Zynthian to be played but then Zynthian sends it back to the VR Keyboard causing a loop.

I would like to be able to filter/route the signals so they don't cause feedback. 

![BrainStormerKeyboard](https://user-images.githubusercontent.com/21322924/63737968-09885280-c83d-11e9-89d7-50aeb1c13314.jpg)

**Comment by jofemodo** [comment]
Ohh! Nice use-case!! ;-) Please, could you give some details in the forum? I think the community will find really interesting your use-case ... ;-)

Regarding the issue ... could you give details about your exact MIDI routing? MIDI-USB, MIDI-IN, MIDI-OUT, MIDI-THRU ...
+ Did you use QMidiNet to send the VR MIDI to zynthian?
+ Did you take a look to the MIDI ports configuration, in the webconf tool?

Also, i think that this question is better suited for the forum ... ;-)

**Comment by 1st-BrainStormer** [comment]
I'll have to do a write up for the forum.  I added a bunch of Midi code to High Fidelity for the windows version last year so it supports Midi directly. So currently I have hardware midi ports between my windows machine and zynthian for both in and out.  For now I just changed the output midi channel to 2 which avoids the feedback loop.  Qmidinet doesn't work for me as it can't cross my VLANs.
I did play with the webconf tool.  I'm still trying to understand what caused the feedback loop.  It gets interesting when you connect multiple instruments across the world. Surprised a friend when I brought in my VR keyboard  and Casio started playing by itself cause it was connected at the time..

**Comment by jofemodo** [comment]
Zynthian sends ALL MIDI input (MIDI-USB + QMidiNet + MIDI-IN) to the MIDI output ports selected in the webconf tool (MIDI options -> MIDI ports), so the feedback loop is the expected behaviour with the MIDI routing described in your first post. As you figured, using a different channel avoids the problem. Congrats!

We will be waiting your report in the zynthian forum!! ;-)
