### ISSUE TITLE
Unxpected interaction between key range and layer transpose

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#590]
**Describe the bug**
When setting up splits using Clone MIDI, transposing a layer can lead to unexpected/unwanted overlaps.

**To Reproduce**
This is an example:
1. Set up two layers, 1 and 2, on MIDI channels 1 and 2
2. For layer 2, set up Clone MIDI to ch 1
2. Set the key range of layer 1 to C-2 .. B2
3. Set the key range of layer 2 to C3 .. G8
4. Play on a keyboard using ch 2, and note how the keyboard is now split as expected.
5. Set the 'octave transpose' for layer 2 to -1.
6. Note that from C3 to B3, layer 1 will be heard overlapping layer 2, but shifted up an octave

**Expected behavior**
When setting octave transpose for a layer, it should only apply an octave offset to the MIDI notes emitted from the engine associated with the layer, and not affect the key range of any MIDI-cloned layers (or indeed the layer itself).

**Screenshots**
![split-overview](https://user-images.githubusercontent.com/6740739/148575275-64d2bca9-138d-45c9-a92b-142d3af920db.png)
![layer-1-range+xpose](https://user-images.githubusercontent.com/6740739/148575299-1e8e63d2-4132-4b22-a035-b2aa44208d7e.png)
![layer-2-range+xpose](https://user-images.githubusercontent.com/6740739/148575335-cc627bf2-2b46-4bc8-83f8-f91ed162d642.png)

**Setup:**
- SD image
2021-09-25-zynthianos-stable.img 
- HARDWARE: Zynthian kit v4.4 (4 GB)
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-25
Memory: 3% (121M/3839M)
SD Card: 44% (13G/29G)
Temperature: 48.2ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (478b6ab)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)
zynthian-webconf: stable (39b61bb)

**Additional context**
This seems to happen regardless of which synth engine is used.

**Comment by jofemodo** [comment]
This should be solved with the ZynMidiRouter refactorization done by @riban-bw
