### ISSUE TITLE
Replace deprecated ZynAddSubFX Ppolymode and Plegatomode parameters with new polyType

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#591]
**Is your feature request related to a problem? Please describe.**
Key assign modes for ZynAddSubFX set in Zynthian UI do not correspond to ZynAddSubFX GUI. In the Zynthian UI, there are separate Ppolymode and Plegatomode parameters, but in ZynAddSubFX these have been deprecated and replaced by a single polyType parameter, which is the one seen in the ZynAddSubFX GUI (see screenshot below). This is confusing for the user.

Furthermore, in the next version of ZynAddSubFX currently being worked on, an additional key assign mode will be introduced, introducing a new 'hidden' boolean, Platchmode, and increasing the number of assign modes from 3 to 4 (poly,mono,legato -> poly,mono,legato,latch).

![zyn-polytype-ui](https://user-images.githubusercontent.com/6740739/148579183-2071a9b4-a606-452b-9cc3-1036ed37e5db.png)

**Describe the solution you'd like**
Replace Ppolymode and Plegatomode parameters in Zynthian GUI with single polyType parameter. The now-spare slot in the screen can be used for the Pkeylimit parameter which limits the number of simultaneously played keys. Or it can simply be left empty, and used for the Pvoicelimit parameter which limits the number of simultaneously played voices, which will be introduced in the next ZynAddSubFX release.

**Risks**
If this is implemented, I'm not sure if there would be backwards compatibility issues when old snapshots are loaded with a new Zynthian UI where Plegatomode and Ppolymode have been replaced with polyType. The snapshots will contain references to the old parameters, but will these be ignored, or sent to ZynAddSubFX anyway? On the other hand, sooner or later something will be need to be done on account of the new latch mode introduced, which will further augment the confusion.

**Additional context**
While attempting to implement this, I came across two bugs in the Zynthian UI. Since they are bugs discovered while implementing a new feature which has not even been approved yet, it would make for rather convoluted bug reports, so I've not created any. See the following zynthian-ui branch for details:
https://github.com/polluxsynth/zynthian-ui/tree/zyn-polytype-voicelimit-saved

**Comment by jofemodo** [comment]
Hi @polluxsynth! Could you send a PR with these changes?

Thanks!

**Comment by jofemodo** [comment]
Hi @polluxsynth !

Don't need the PR, as i copied your changes by hand to test them. I can merge on testing if you don't care "authoring".

Anyway, i don't get ZynFusion to refresh values changed from zynthian UI. For instance, i change "assign mode" from zynthian UI, i can hear how sound changes, but i can't see the selector value changing on ZynFusion.
Same with other OSC controlled parameters. No syncing at all. Finally i noted volume (CC7) is not working anymore.

And of course, ZynFusion is extremely irresponsive on VNC, so i ask myself if shouldn't we comeback to the old fltk GUI, unless is totally unmaintained and outdated. Do you know something about this? Any chance that ZynFusion becomes more responsive under VNC?

Thanks!

**Comment by polluxsynth** [comment]
Perhaps it's a ZynAddSubFX 3.0.5 issue? On my Zynthian, I'm running HEAD from the master branch, and for OSC parameters such as assign mode (when using polyType at least and not the old style individual boolean parameters; I haven't tried these) and portamento threshold Zyn-Fusion echos the values set in the Zynthian UI with no problem. However, CC controlled parameters such as portamento on/off or volume don't get echoed the same way.

Volume works in my setup, although I can't turn the volume down all the way to 0, i.e. when the Volume parameter in the Zynthian UI is set to 0, there's still some residual volume. But this is the same when adjusting the part volume in Zyn-Fusion, so I guess that's just the way it's designed.

(One thing I did notice is that the panning goes in the wrong direction, both when changing in the Zynthian UI and in Zyn-Fusion (Part settings). The voice panning in OBXd is fine, so I guess it's some ZynAddSubFX thing. There is a 'swap stereo' parameter in .zynaddsubfxXML.cfg, which is set to 0 though, so it should be correct. I'll have to check how this behaves on the PC version. It's easy enough to fix in .zynaddsubfxXML.cfg though of course.)

The old fltk GUI, is that the one with separate windows for each function, similar to the way Yoshimi works? I've just come into contact with ZynAddSubFX fairly recently, so I've never used the old UI, but I must say I really like Zyn-Fusion, although I agree it is painfully slow in VNC on Zynthian, and on my machine I keep having to scroll around to reach everything. I don't know why it is so slow, my guess is that there is quite a lot of polling going on in order to get information from Zyn, i.e. the volume meter and envelope states. But I honestly don't know. I don't think the old GUI is maintained at all since the birth of Zyn-Fusion, but that's just my guess.

I haven't worred to much about VNC for ZynAddSubFX personally, because for me it's easy enough to start up Zyn-Fusion on a PC and connect to Zynthian via OSC, and then it's fast enough, and doesn't load the Zynthian CPU, and I don't have to contend with scrolling around the Zynthian VNC window and can set Zyn-Fusion to use the whole screen easily. But I can understand that it's an unnecessarily complex step for the average Zynthian user.

**Comment by jofemodo** [comment]
I will try to upgrade ZynAddSubFX and let's see ...
Did you compile the latest ZynAddSubFX on your zynthian? Please, share the recipe, or better, package a ".deb" for our deb-repo.

BTW, i also noted the inverted pan control. We could do something if needed ...

Thanks!

**Comment by polluxsynth** [comment]
I basically just checked out the zyn-fusion-build repo from github (https://github.com/zynaddsubfx/zyn-fusion-build) and followed the instructions in README.md . I was expecting there to be issues when building in a non-PC (or non-Intel) environment, but the build went smoothly without any manual intervention needed.

Note the 'make MODE=release -f ...'  thing at the end of the file to avoid building zynaddsubfx in demo mode.

As suggested in https://discourse.zynthian.org/t/updating-synth-engine-zynaddsubfx/6545, I removed the upstream installation before installing the new one, using `apt remove zynaddsubfx-data` which removes the factory banks and then the application itself.

I'm not really comfortable generating a package, I guess one could start with an existing package and modify it?

**Comment by polluxsynth** [comment]
> BTW, i also noted the inverted pan control. We could do something if needed ...

I tested this on a PC. It seems that the part outputs from zynaddsubfx are swapped. The zynaddsubfx mixer displays the channels correctly, and the mix output is correct (although of course unused in Zynthian).

I created an issue for zynaddsubfx:
https://github.com/zynaddsubfx/zyn-fusion-issues/issues/330

**Comment by polluxsynth** [comment]
Fixed the swap issue in zynaddsubfx: https://github.com/zynaddsubfx/zynaddsubfx/pull/169

**Comment by jofemodo** [comment]
I think this can be closed. 
If there is another issue with ZynAddSubFX, we should address it on a separated ticket.
BTW, i updated the ZynAddSubFX zynthian engine implementation, fixing/improving some controllers, adding some new controller screen, etc. I think you could be interested on taking a look and testing (testing branch!) ;-)

**Comment by polluxsynth** [comment]
Agreed, no need to keep this ticket open as the change to use polyType has been implemented (at least on testing).

BTW, I was actually wrong when I said the old Ppolymode and Plegatomode were deprecated; they are no longer used in the Zyn-Fusion UI, but it is still possible to set them, the reason I thought they were deprecated was because of the bug in the Zynthian UI that precluded sending parameter changes for binary (T/F) OSC parameters. But of course using polyType is preferable because that's what Zyn-Fusion uses.

Yes, I noticed the new Zynthian Zynaddsubfx screens; I've brought them into my working branch on my Zynthian. They are a good improvement over the previous set of screens, although there are a few things which I think need further adjustment. I suppose the best would be to raise an issue, or should I just submit a PR?

BTW, I asked Mark (Zynaddsubfx maintainer) about fltk vs Zyn-Fusion, and it turns out that while fltk isn't deprecated, new features do not necessarily get added to it, so it will fall behind more and more as changes are made to Zyn-Fusion. Regarding responsiveness, there are apparently runtime configurable options which govern the screen update rate, so experimenting with lowering the update rate may increase responsiveness if the sluggishness is due to high CPU load. I'm planning on experimenting a bit with this. (https://github.com/zynaddsubfx/zyn-fusion-issues/issues/331#issuecomment-1035847730).

**Comment by polluxsynth** [comment]
> Yes, I noticed the new Zynthian Zynaddsubfx screens; I've brought them into my working branch on my Zynthian. They are a good improvement over the previous set of screens, although there are a few things which I think need further adjustment. I suppose the best would be to raise an issue, or should I just submit a PR?

For instance, the bend range adjustment doesn't really work properly, because the OSC parameter has the value specified in cents, but the Zynthian ui parameters are 0..127, so the maximum bend range that can be set is just over a semitone.

**Comment by jofemodo** [comment]
So, what is the right range for that parameter? I will fix it ASAP.
And please, check is there is more OSC parameters with bad ranges, o i can fix them too ;-)

**Comment by polluxsynth** [comment]
The actual range of the OSC parameter is -6400 to +6400, but I don't think it would be useful to set it up or even display it like that, as in practice what one would not want to set it up in cents, as it wouldn't be practical to reach every value from the Zynthian UI, and having that resolution seems crazy to me. I think setting it in semitones so that it's displayed as -64 to +64 (which is the largest pitchbend range I've ever seen on a synthesizer...) on the Zynthian ui, but sent as x100 (i.e. -6400 to 6400) when sending the OSC parameter would be the most useful, or what do you think?

I can't remember any other parameter with a bad range, but I'll have closer look at them and report back. 

One thing that is upcoming on Zynaddsubfx master is a new `portamento_auto` parameter, which is a boolean which controls if portamento requires legato playing or not. Previously, legato and mono modes required legato playing to engage portamento, and poly mode did not, but that control is now in a separate parameter, rather than being implicit based on the mode. It causes a minor problem for Zynthian though, because it means there are 5, not 4 portamento parameters, so portamento now needs to be split across two screens, in as practical a way as possible.

**Comment by jofemodo** [comment]
I fixed the bendrange scale and re-work the portamento parameters & screens, adding the new "automode" parameter although it's not available on the current zynaddsubfx binary. I also added the portamento.receive toggle, so the first portamento screen doesn't feel so empty.

Please, update and test.

Thanks!

**Comment by polluxsynth** [comment]
Thanks for looking into this!

The bendrange parameter works as expected now. However, bendrange down should behave in the same way.

I'm also wondering if 'pitchwheel split' should be called 'bendrange split' to be consistent with 'bendrange down'. The screen can still be called 'pitchwheel'.

I think the portamento screens are well laid out. The portamento automode parameter works as expected, although I think it should just be called 'portamento auto', or even just 'auto'. (The reason the OSC parameter is called 'automode' is because the corresponding variable is called 'automode', in turn because 'auto' is a reserved word in C++.)

Some of the portamento parameters have very long names and the text becomes really small (and doesn't fit properly, although perhaps there have been layout fixes that I haven't brought in; I just cherry-picked the portamento screen commit).
- Portamento thresh type: I think it should be called 'Portamento >= thresh' or something like that, or just '>= thresh', because that's how it works: when the parameter is on, portamento is applied only when the note played is >= thresh notes away from the previous note. Or is '>= thresh' too technical? 'Equal to or larger than thresh' is too  long...but 'thresh type' doesn't really convey any information.
- Portamento updown time: This is also too long. Perhaps just 'Portamento up/down' ? Or 'Up/down ratio' ? I know it is a good idea to retain 'portamento' in the parameter names, but when the parameter name gets too long the font gets too small and it sortof defeats the purpose.

**Comment by jofemodo** [comment]
Try now. I've implemented most of your suggestions ;-)
Also, i've improved the controller's title render algorithm and now it should work better with long titles, avoiding "too-small" font sizes.

**Comment by polluxsynth** [comment]
Yes, the fonts look better with long parameters. And bend range down now works fine! Thanks!

I still think though that there is an advantage to shortening the parameter names if possible, because the shorter the name, the quicker it is to read, both because of the resulting larger font size but also because it's simply fewer characters. This is perhaps something for wider discussion. I know I mentioned I think regarding the NoiseMaker screens that it's a good idea to have the name of the module in the parameter in order to aid orientation when scrolling through parameters, so that filter envelope attack would have the name "filter attack" and not just "attack". But I'm not so sure about it when it comes to screens which are completely different how important it is to have, say, "portamento" as part of all the parameter name.

I see you didn't go for the ">= thresh" idea. :-) Perhaps something like "thresh or larger" or "larger than thresh" or "above thresh" or something that indicates what the ON value actually means. Having a parameter called "threshold type" have the values on and off doesn't really make sense.

Alternatively, if the parameter has the name "threshold type", but the values are "larger" and "smaller" (although technically that's not correct as it should be "larger or equal" or "smaller or equal", which of course could be written as ">=" and "<=", respectively). Although the parameter name should really then be something like "portamento when threshold is ...".

**Comment by jofemodo** [comment]
OK! Try now. I shorted the threshold controllers titles and replaced the on/off ticks by <=/>=.

**Comment by polluxsynth** [comment]
I think the T/F vs numeric OSC issue bit us again. The parameters is now in the ON (T) state, regardless of the value set.

Also, hard to test at this point, but the values are swapped, it should be >= when the value is T / on, and <= when the value is F / off.

**Comment by jofemodo** [comment]
OK! I think it's fixed now. Update & test, please.

Thanks!

**Comment by polluxsynth** [comment]
Yep, thanks, it works fine now! 

One thing I've got to penetrate are the modulation, resonance, bandwidth and veflocity screens. I don't really understand all the parameters and I can't find them all in the Fusion UI, and I think some of them might be buggy in Zynaddsubfx. I've got to do some more testing and get back. The screens themselves look fine though.

This may be related to the fact that some patches just don't really sound right in Zynthian. For instance Strings/Morph Strings1 requires the Filter Cutoff to be pulled up to 127, but normally it should be at 64 for the filter frequency to be unchanged from the preset itself, IIUC.

**Comment by polluxsynth** [comment]
Ok, I figured out Morph Strings1, and it comes down to the same thing as the other 'part' parameters which are exposed in Zynthian. In order for a patch to sound as programmed, i.e. all control values such as filter frequency, filter resonance etc, either the depth parameter needs to be set to 0 (so that no offset can be supplied via for instance the filter cutoff parameter in the main screen in Zynthian), or, with the depth set to any other value, the cutoff parameter needs to be set to 64. I.e. 64 means "no change from the preset value".

There is also a bug in Zynaddsubfx (which I'll be addressing) where changing the 'depth' parameter has no effect until the corresponding CC parameter is changed, which results in confusing behavior when setting parameter values.

But back to the CC parameters. In a way, it would be nice if these were displayed as "-64 .. 0 .. +63" rather than "0 .. 64 .. 127", but then they wouldn't correspond to the MIDI CC values. 

Similarily with the depth parameters, 64 represents a "normal amount of influence on the parameter by the modulation value", with 0 meaning "no influence on the parameter" and 127 meaning "lots of influence". So using "-64 .. 0 .. +64" would not b a good idea here, but perhaps the values 0 and 64 could be replaced by the texts "OFF" and "NORM".

Velocity sens is yet another special case. "64" means "as programmed in the patch", with 0 meaning "very low sensitivity" (meaning "you have to bang like mad on the keyboard to get a high velocity response") and 126 meaning "very high sensitivity" (meaning "you don't have to play very hard to get high velocity values", but 127 is a special case and means "always emit max velocity  no matter hard the keys are played". In the latter case, the actual velocity value can be controlled by the velocity offs parameter. So the value range I think really should be "-64 .. NORM .. +62 FIXED-MAX".

The velocity offset again as 64 as it's "no offset" value, but the offset applied is actually twice the amount shown; for instance, when setting velocity sensitivity to 127 (= FIXED-MAX), it's possible to pull down the velocity value to 0 (or 1) by setting the velocity offset to 0, and in this case, setting it to 64 yields maximum velocity, so that any value above 64 yields the same result. Thus I think the value range for this parameter should be "-128.. 0 .. +127", in steps of 2.

The key issue here at any rate is that displaying the modulation and depth parameters in the range 0..127 with 64 being the "normal" value is confusing unless one is very familiar with the underlying mechanisms in Zynaddsubfx.
