### ISSUE TITLE
Wrong path names in ZynAddSubFX configuration file

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#593]
**Describe the bug**
When using the UI for ZynAddSubFX, the browser window shows no banks or patches. This is due to the bank paths being incorrectly specified in the /root/.zynaddsubfxXML.cfg file. 

**To Reproduce**
1. Start the ZynAddSubFX UI, either as standalone or using VNC.
2. Note how the bank/preset browser window is completely empty.

**Expected behavior**
The bank/preset window should show all available original and user banks and presets.

**Setup:**
- SD image
2021-09-25-zynthianos-stable.img 
- HARDWARE: Zynthian kit v4.4 (4 GB)
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-25
Memory: 3% (121M/3839M)
SD Card: 44% (13G/29G)
Temperature: 48.2�C
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (478b6ab)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (006a071)

**Additional context**

The problem is that in the configuration file ~/.zynaddsubfxXML.cfg, the path names are specified without being prefixed by "/zynthian/zynthian", i.e. as

```
<BANKROOT id="0">
<string name="bank_root">data/zynbanks</string>
</BANKROOT>
<BANKROOT id="1">
<string name="bank_root">my-data/presets/zynaddsubfx</string>
</BANKROOT>
```

rather than

```
<BANKROOT id="0">
<string name="bank_root">/zynthian/zynthian-data/zynbanks</string>
</BANKROOT>
<BANKROOT id="1">
<string name="bank_root">/zynthian/zynthian-my-data/presets/zynaddsubfx</string>
</BANKROOT>
```

A similar problem exists for the PRESETROOT (which is not actually the root to presets in the ordinary sense, but rather portions of patches that can be reused in other patches).

The change is easy enough to make on a running system, but I'm not sure how to go about this in a future consistent way, i.e. affecting future Zynthian SD images.

**Comment by jofemodo** [comment]
I just fixed this on https://github.com/zynthian/zynthian-sys/commit/fa010c90bb4f23e4121e42e08a77c5e50f6d47f0
