### ISSUE TITLE
After Touch Calibration, touch axis are reversed and need restarting UI

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#594]
**Describe the bug**
After Touch Calibration, touch axis are reversed. Restarting the UI seems to solve the problem.

**To Reproduce**
1. Go to 'Admin->Touch Calibration'
2. Calibrate the screen by touching the crosses
3. Test the touchscreen
4. Axis are reversed

**Expected behavior**
Axis are not reversed

**Setup:**
 - 2109 Stable SD-image
 - Official v4.5 kit with ZynScreen display
 - Testing branch updated to the last

**Comment by riban-bw** [comment]
I cannot reproduce this on Testing. I am unaware of any updates to this code since last stable release.

**Comment by jofemodo** [comment]
I can't reproduce on testing. Closing!
