### ISSUE TITLE
Errors switching to testing branch

### ISSUE THREAD

**Issue by somervid111** [zynthian/zynthian-issue-tracking#597]
**Describe the bug**
Zynthian box which was working on the testing branch up until approx.2 mos. ago. The box works fine on the stable release. When I select testing branch and update, I receive a Cmake error on building zyncoder but it continues and completes update. After update I receive Zynthian IP error screen.

**To Reproduce**
In web configuration with a working stable release, switch to testing repos and update. After update Zynthian error screen with IP error appears. Reboot Zynthian and same issue on restart.

**Expected behavior**
Approx. 2 months ago I had the testing branch working fine on this Zynthian.

**Screenshots**

**Here is the update build errors:**

/zynthian/zyncoder /zynthian/zyncoder
/zynthian/zyncoder/build /zynthian/zyncoder /zynthian/zyncoder
++ Defined HAVE_WIRINGPI_LIB
++ Defined MCP23008_ENCODERS
++ Building for Wiring Layout CUSTOM
++ Using wiringPi
– Configuring done
– Generating done
– Build files have been written to: /zynthian/zyncoder/build
[ 9%] Building C object CMakeFiles/zyncore.dir/zyncoder.c.o
/zynthian/zyncoder/zyncoder.c: In function ‘update_expanded_zynswitches’:
/zynthian/zyncoder/zyncoder.c:608:23: error: ‘zynswitch’ undeclared (first use in this function); did you mean ‘zynswitches’?
send_zynswitch_midi(zynswitch, status);
^~~~~~~~~
zynswitches
/zynthian/zyncoder/zyncoder.c:608:23: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/zyncore.dir/build.make:128: CMakeFiles/zyncore.dir/zyncoder.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/zyncore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
/zynthian/zyncoder /zynthian/zyncoder
/zynthian/zyncoder

**The UI log after update has these errors:**

Jan 23 15:58:04 zynthian startx[2857]: Building XImage…done
Jan 23 15:58:08 zynthian startx[2857]: ERROR:zynthian_gui_config.: ERROR configuring control I/O subsytem: ‘NoneType’ object has no attribute ‘get_num_zynswitches’
Jan 23 15:58:08 zynthian startx[2857]: libzynmixer: Registering as ‘zynmixer’.
Jan 23 15:58:08 zynthian startx[2857]: libzynmixer: Created input ports
Jan 23 15:58:08 zynthian startx[2857]: libzynmixer: Registered output ports
Jan 23 15:58:08 zynthian startx[2857]: libzynmixer: Activated client
Jan 23 15:58:11 zynthian startx[2857]: ERROR:zynthian_gui.init_midi: ERROR initializing MIDI : ‘NoneType’ object has no attribute ‘set_midi_filter_tuning_freq’
Jan 23 15:58:13 zynthian startx[2857]: Can’t init zyncore library: /home/pi/zyncoder/build/libzyncore.so: cannot open shared object file: No such file or directory
Jan 23 15:58:13 zynthian startx[2857]: New instance of zynseq
Jan 23 15:58:13 zynthian startx[2857]: zynseq initialising as zynthstep
Jan 23 15:58:13 zynthian startx[2857]: Traceback (most recent call last):
Jan 23 15:58:13 zynthian startx[2857]: File “./zynthian_gui.py”, line 2095, in
Jan 23 15:58:13 zynthian startx[2857]: zyngui.start()
Jan 23 15:58:13 zynthian startx[2857]: File “./zynthian_gui.py”, line 584, in start
Jan 23 15:58:13 zynthian startx[2857]: self.show_screen(‘main’)
Jan 23 15:58:13 zynthian startx[2857]: File “./zynthian_gui.py”, line 638, in show_screen
Jan 23 15:58:13 zynthian startx[2857]: self.hide_screens(exclude=screen)
Jan 23 15:58:13 zynthian startx[2857]: File “./zynthian_gui.py”, line 617, in hide_screens
Jan 23 15:58:13 zynthian startx[2857]: screen_obj.hide()
Jan 23 15:58:13 zynthian startx[2857]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_midi_key_range.py”, line 275, in hide
Jan 23 15:58:13 zynthian startx[2857]: lib_zyncore.set_midi_learning_mode(0)
Jan 23 15:58:13 zynthian startx[2857]: AttributeError: ‘NoneType’ object has no attribute ‘set_midi_learning_mode’
Jan 23 15:58:15 zynthian startx[2857]: /zynthian/config/img/fb_zynthian_error_ip.png is 1280x720 PNG image, color type RGB_ALPHA, 8 bit
Jan 23 15:58:15 zynthian startx[2857]: Zooming image by 50%…done
Jan 23 15:58:15 zynthian startx[2857]: Merging…done
Jan 23 15:58:15 zynthian startx[2857]: Building XImage…done

**Setup:**
 Zynthian Custom Kit, direct encoder to GPIO wiring set to A=25,26,4,0, B=27,21,3,7 and SW=23,6,2,22. Midi tty circuit used on GPIO. Generic HDMI display, DAC is HiFiberry DAC+ADC pro, RPI 4B model Rev 1.2
Buster build date 2020-09-05, also confirm to occur with 21-09 build

**Additional context**
*UPDATE* I can confirm this also occurs when I start with a fresh 09-21 Stable image(latest). Stable works but testing has build errors on "zyncoder" and "zyncore"
I have another Zynthian with the same wiring, generic HDMI display but a generic PiFi DAC and different midi cct(still on tty from GPIO). The same behaviour exists on this box as well however I currently do not have the second box with me to check that the errors are the same.

**Comment by jofemodo** [comment]
Hi @somervid111 !

I think i solved the problem. Please update and test.

Regards,

**Comment by somervid111** [comment]
Hi,
Sorry, same thing is happening.
