### ISSUE TITLE
Custom Wiring Profile switch functions fail after some use.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#598]
**Describe the bug**
The testing branch Custom Wiring Profiles stop functioning after  some use.

**To Reproduce**
1. Load up v4_studio touch wiring profile.
2. repeatably select functions. 
3. Pressing a button twice sometimes seems to toggle back to provious screen
4. Button function stops functionin. No debug log messages

**Expected behavior**
Buttons consistently function.

**Setup:**
![image](https://user-images.githubusercontent.com/79083/151196969-135df7e2-5c72-411f-96a7-28ac2a8d99b3.png)

**Comment by jofemodo** [comment]
Sorry, i can't reproduce this behaviour. Are your hardware buttons "debounced" in some way?

Regards,
