### ISSUE TITLE
UI Options / "Enable VNC Server" cannot be disabled

### ISSUE THREAD

**Issue by eykh** [zynthian/zynthian-issue-tracking#600]
**Describe the bug**
The VNC server cannot be disabled in the UI options.

**To Reproduce**
- Open the UI options in webconf. 
- Remove the check at "Enable VNC Server". 
- Click "Save". 
- After a few seconds, the page reloads and the check is set again.
- VNC is still enabled and can be used

**Expected behavior**
The checkbox stays unchecked and VNC is disabled

**Setup:**
zyncoder: stable (7c09738)
zynthian-ui: stable (4a08200)
zynthian-sys: stable (a0e01eb)
zynthian-data: stable (076a23d)
zynthian-webconf: stable (39b61bb)

**Additional context**
It's a headless system (in a rack) without any display attached. Usually controlled by VNC or MIDI.

**Comment by jofemodo** [comment]
This should be fixed. Please update and test.

**Comment by eykh** [comment]
Yes, it works. Thank you!
