### ISSUE TITLE
Removing engine gives error

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#603]
**Describe the bug**
Removing an engine (possibly the last engine) gives an error in the log and shows empty control screen.

**To Reproduce**
1. Add 2 engines, e.g. ZynAddSubFx & setBfree
2. Open context menu for each engine and select Remove Layer

**Expected behaviour**
Engines are removed and empty mixer is shown.

**Actual behaviour**
Engines are removed but empty control screen is shown.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: [HifiBerry DAC+ ADC PRO](http://10.42.0.60/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://10.42.0.60/hw-display)
Wiring: [MCP23017_ZynScreen](http://10.42.0.60/hw-wiring)
GPIO Expander: [MCP23017](http://10.42.0.60/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 26% (242M/923M)
SD Card: 46% (13G/29G)
Temperature: 52.6ºC
- SOFTWARE
zyncoder: [testing (558fd12)](https://github.com/zynthian/zyncoder/commit/558fd12b7ebbddafa13a174c0822243c64eb85d6)
zynthian-ui: [testing (5f46d3a)](https://github.com/zynthian/zynthian-ui/commit/5f46d3a85f8ccb5c053c58741d8848e90f6e0301)
zynthian-sys: [testing (b49f8e8)](https://github.com/zynthian/zynthian-sys/commit/b49f8e8411a541a3f732c5c85b1d2902ebfd0802)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (9a79565)](https://github.com/zynthian/zynthian-webconf/commit/9a795651fe9b6593845eb1be209298874274aa01)

**Additional context**
Log shows:
```
Feb 07 20:11:03 zynthian startx[483]: ERROR:zynthian_gui_control.fill_list: Can't fill control screen list for None layer!
Feb 07 20:11:09 zynthian startx[483]: ERROR:zynthian_gui_preset.show: Can't show preset list for None layer!

![image](https://user-images.githubusercontent.com/3158323/152865075-4b2a67cd-b31b-491e-969e-0fca9508414c.png)
```

**Comment by jofemodo** [comment]
This should be fixed now. Please update and test.
