### ISSUE TITLE
Error on exit - wsleds not defined

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#604]
**Describe the bug**
During shutdown Zynthian throws an error complaining that 'NoneType' object has no attribute 'setPixelColor'.

**To Reproduce**
1. Close Zynthian

**Expected behaviour**
Closes without error.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: [HifiBerry DAC+ ADC PRO](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
GPIO Expander: [MCP23017](http://zynthian1.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 46% (864M/1872M)
SD Card: 61% (17G/29G)
Temperature: 48.2ºC
- SOFTWARE
zyncoder: [testing (558fd12)](https://github.com/zynthian/zyncoder/commit/558fd12b7ebbddafa13a174c0822243c64eb85d6)
zynthian-ui: [testing (5f46d3a)](https://github.com/zynthian/zynthian-ui/commit/5f46d3a85f8ccb5c053c58741d8848e90f6e0301)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (9a79565)](https://github.com/zynthian/zynthian-webconf/commit/9a795651fe9b6593845eb1be209298874274aa01)

**Additional context**
The error occurs in zynthian_gui.py, end_wsleds (line 286) when an attempt to set the LEDs fails because none are configured for this device (V4 Zynthian). There should be a check that the object exists. Also it assumes 25 LEDs. The quantity of LEDs should probably be defined somewhere.

I also see a subsequent error at line 2249: exit(zyngui.exit_code). But that may be because of the earlier error.

**Comment by riban-bw** [comment]
https://github.com/zynthian/zynthian-ui/pull/419 submitted to fix this.

(The exit error I wsa seeing is simply a reporting thing within VSCode that shows any exit code as an uncaught exception. Zynthian uses exit codes to signal actions to its BASH wrapper so that observation is not a fault.)

**Comment by jofemodo** [comment]
Merged! Thanks @riban-bw.

Regarding the LEDs code, it's currently "hardcoded" on the main class, but the idea is to split it on a separated file, so you can have different LED's logic depending on the hardware model. These are the functions to split:

```
	def init_wsleds(self)
	def end_wsleds(self)
	def update_wsleds(self)

```

I will do it ASAP.

Regards,
