### ISSUE TITLE
Error reported during startup setting up encoders

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#605]
**Describe the bug**
During startup Zynthian reports an error, "ZynCore->setup_rangescale_zyncoder(3, 0, 0, ...): Invalid range!".

**To Reproduce**
1. Start Zynthian
2. 
**Expected behaviour**
Zynthian starts without reporting errors.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: [HifiBerry DAC+ ADC PRO](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
GPIO Expander: [MCP23017](http://zynthian1.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 46% (864M/1872M)
SD Card: 61% (17G/29G)
Temperature: 48.2ºC
- SOFTWARE
zyncoder: [testing (558fd12)](https://github.com/zynthian/zyncoder/commit/558fd12b7ebbddafa13a174c0822243c64eb85d6)
zynthian-ui: [testing (5f46d3a)](https://github.com/zynthian/zynthian-ui/commit/5f46d3a85f8ccb5c053c58741d8848e90f6e0301)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (9a79565)](https://github.com/zynthian/zynthian-webconf/commit/9a795651fe9b6593845eb1be209298874274aa01)

**Additional context**
The error occurs within zynthian_gui_mixer.py within function setyp_zyncoders() at line 1078:

`lib_zyncore.setup_rangescale_zynpot(ENC_SELECT, 0, 4 * self.number_layers, 4 * self.selected_channel, 1)`

Are the x4 multipliers required?

**Comment by jofemodo** [comment]
This should be fixed now, although it could be side effects. 
I checked the code to be sure there is no 0 division anywhere, but if you find some new encoder-related bug, it could be this change.
