### ISSUE TITLE
Errors logged trying to start VNC server at startup

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#606]
**Describe the bug**
During startup of Zynthian it may attempt to start VNC which can log errors if VNC is already running.

**To Reproduce**
1. Start or restart Zynthian whilst VNC server is already running.

**Expected behaviour**
Zynthian starts without error.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: [HifiBerry DAC+ ADC PRO](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
GPIO Expander: [MCP23017](http://zynthian1.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 43% (817M/1872M)
SD Card: 61% (17G/29G)
Temperature: 50.6ºC
- SOFTWARE
zyncoder: [testing (558fd12)](https://github.com/zynthian/zyncoder/commit/558fd12b7ebbddafa13a174c0822243c64eb85d6)
zynthian-ui: [testing (5f46d3a)](https://github.com/zynthian/zynthian-ui/commit/5f46d3a85f8ccb5c053c58741d8848e90f6e0301)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (9a79565)](https://github.com/zynthian/zynthian-webconf/commit/9a795651fe9b6593845eb1be209298874274aa01)

**Additional context**
Within file zyn_gui_admin.py the function `start_vncserver()` calls:

`check_output("systemctl start novnc0", shell=True)`

This fails if VNC is already running. The attempt to launch VNC server issues a warning: "A dependency job for novnc0.service failed. See 'journalctl -xe' for details."

This is caught within Python as exception then printed as an error: "ERROR:zynthian_gui_admin.start_vncserver: Command 'systemctl start novnc0' returned non-zero exit status 1.".

So an expected behaviour produces two error messages.

**Comment by jofemodo** [comment]
Fixed! please update and test.

**Comment by riban-bw** [comment]
I am still seeing the error. The check is made for vncserver0 which returns 'failed'. On my system there are services:

vncserver0 - failed
vncserver1 - active
vncserver2 - inactive

I am not certain that this isn't related to other changes I may have made. Please validate which vncserver systemd services should be configured.

**Comment by jofemodo** [comment]
AFAIK, only vncserver0 & vncserver1 are "officially" managed. The vncserver2 must be something yours??
Now every service is managed separatelly and status is checked before trying to start the service, so no error should be logged for this cause. Please, could you verify that you are running the last code i patched?

**Comment by riban-bw** [comment]
I am running the latest code. The issue I am seeing is because I do not have the UI running on fb0 hence attempts to start x11vnc fail. The `systemctl is-active vncserver0` command then returns `failed` which in turn results in Python reporting:
```
A dependency job for novnc0.service failed. See 'journalctl -xe' for details.
ERROR:zynthian_gui_admin.start_vncserver: Command 'systemctl start novnc0' returned non-zero exit status 1.
```

I know this is not standard workflow (debugging) but we should capture such a state gracefully, i.e. when vncserver0 fails because UI is not running on its normal display. (FYI: During debug I run zyn_gui on vnc1 desktop.)

[Edit] BTW this is very low priority - debug warnings in off-normal test conditions is not something we should be chasing our tails over but worth recording and resolving if possible as a background task.
