### ISSUE TITLE
Stopping MIDI (SMF) playback does not silence notes

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#608]
**Describe the bug**
Playing a standard midi format file (SMF) with Zynthian MIDI player can leave notes hanging when playback stops.

**To Reproduce**
Steps to reproduce the behaviour:
1. Play a (complex) MIDI file
2. Stop playback

**Expected behaviour**
Playback stops and all notes are silenced.

**Actual behaviour**
Playback stops and but some notes are not silenced.

**Setup:**
Assume testing - recorded issue some time ago and just found in a note.

**Additional context**
Have not validated this issue recently but want to record here to avoid loss of info.

**Comment by jofemodo** [comment]
I think this can be closed for sure.

**Comment by riban-bw** [comment]
Nope! Still broken :-(
