### ISSUE TITLE
Pitchbend not reset when MIDI playback stops

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#609]
**Describe the bug**
Starting playback of a Standard Midi Format (SMF) file does not clear any existing pitch bends, e.g. roland_take5.mid seems to pitch bend the sax at the end of the track so restarting results in out of tune sax.

**To Reproduce**
Steps to reproduce the behaviour:
1. Play a MIDI file with pitchbend
2. Stop playback whilst pitchbend applied
3. Play Zynthian instrument on which bend was applied (or start SMF playback)

**Expected behaviour**
Pitchbend is reset after stopping playback

**Actual behaviour**
Pitchbend is reset after stopping playback

**Setup:**
Assume testing - recorded issue some time ago and just found in a note.

**Additional context**
Have not validated this issue recently but want to record here to avoid loss of info.
We need to consider the situation where playback is paused then resumed but that seems less of an issue than the core one reported here.

**Comment by jofemodo** [comment]
What about this one? Can be close it?

**Comment by riban-bw** [comment]
Yep! I just fixed it. MIDI player now resets _some_ controllers when playback stops. It uses the rule that if the controller was set by SMF then it gets reset when playback stops. This is only true for a subset of controllers including:

- Pitchbend
- Poly pressure / aftertouch
- Channel pressure / aftertouch
- Sustain (various CC64 - CC69)
- Note on

This _should_ allow live playback to accompany SMF playback with reduced interferrence.
