### ISSUE TITLE
x42 Instrument Tuner UI eating 75% CPU

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#610]
**Describe the bug**
When running x42 Instrument Tuner with VNC enabled the corresonding jalv.gtk instance uses 75% CPU. Disabling VNC results in jalv using 17%. The UI is very busy!

**To Reproduce**
Steps to reproduce the behaviour:
1. Add an audio effect layer with x42 Instrument Tuner

**Expected behaviour**
CPU usage is not excessive.

**Actual behaviour**
CPU usage is excessive.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: [ZynADAC](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
GPIO Expander: [MCP23017](http://zynthian1.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 7% (144M/1872M)
SD Card: 63% (17G/29G)
Temperature: 54.5ºC
- SOFTWARE
zyncoder: [testing (1609f8d)](https://github.com/zynthian/zyncoder/commit/1609f8dc2c134e9e879bd29334f53513db1ff295)
zynthian-ui: [testing (f561029)](https://github.com/zynthian/zynthian-ui/commit/f56102902a3f27fb1cba7ce815078c161e284ea0)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
Until the root cause is resolved it may be worth adding this plugin to the blocked list.

**Comment by jofemodo** [comment]
It's solved with https://github.com/zynthian/zynthian-ui/pull/420
