### ISSUE TITLE
Keyboard binding for mixer view not working

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#611]
**Describe the bug**
Since change to using zynpot the (QWERTY) keyboard binding is not working properly in the mixer view.

**To Reproduce**
1. Add one or more layers
2. Navigate to audio mixer
3. Press up / down arrow keys on (QWERTY) computer keyboard 

**Expected behaviour**
Layer selection changes

**Actual behaviour**
Nothing happens.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: [ZynADAC](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
GPIO Expander: [MCP23017](http://zynthian1.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 50% (937M/1872M)
SD Card: 63% (17G/29G)
Temperature: 52.5ºC
- SOFTWARE
zyncoder: [testing (1609f8d)](https://github.com/zynthian/zyncoder/commit/1609f8dc2c134e9e879bd29334f53513db1ff295)
zynthian-ui: [testing (f561029)](https://github.com/zynthian/zynthian-ui/commit/f56102902a3f27fb1cba7ce815078c161e284ea0)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
CUIA SELECT_UP is called which triggers zynthian_gui_mixer::select_up. This calls zyncoder_up which sets value in zynpot but does not then trigger the actual action within mixer view.

**Comment by jofemodo** [comment]
It should be fixed now. Please update & test.

**Comment by riban-bw** [comment]
Great! Thanks for fixing so quickly.
