### ISSUE TITLE
Remember you are within favourites preset list

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#613]
**Is your feature request related to a problem? Please describe.**
It would be advantageous to be able to select from favourites list quickly rather than have to navigate back to the list each time.

**Describe the solution you'd like**
After selecting a preset from the favourites list, subsequent access to preset list should start in the favourites list. Currently it takes you to the bank the preset is in requiring you to navigate back to the favourites. The point of favourites is to provide fast access to the most used presets hence this extra navigation undermines the feature.

**Additional context**
I guess there would need to be a flag that says the last selection was from the favourites to provide consistent behaviour, i.e. if you select from a bank then you should be shown that bank next time.

**Comment by riban-bw** [comment]
This is more subtle.
 - Select a favourite preset
 - Short press BACK shows list of favourites
 - Short press BACK shows list of banks with the bank (not FAVOURITES) highlighted
 - Short press BACK shows control view
 - Short press BACK shows list of presets within the bank, not favourites

**Comment by jofemodo** [comment]
"Shown Favorites" status is already remembered. If you access favorites and select a presets, next time you click "back" for accessing preset list, you sill see favorites. I think something strange is happening with your zynthian. Perhaps some kind of gremlin ;-D

**Comment by riban-bw** [comment]
No gremlins. This is behaving as described in my comment. If you press BACK twice so you end up in the bank list the concept of having navigated from the favourties list is lost. This feels quite irksome.

**Comment by jofemodo** [comment]
OK! I understand. I think it's the same bug (or very related to) than https://github.com/zynthian/zynthian-issue-tracking/issues/612

**Comment by jofemodo** [comment]
It should be fixed now. Please update & test!
