### ISSUE TITLE
Restart after update to  ea511f6 on testing fails with multiple None type errors..

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#617]
**Describe the bug**
Updating to version 
ea511f6 of testing generates Zynthian error on reboot.

This is a highly configured open source machine using an Audio Injector card.

**To Reproduce**
1. Update zynthian-pedal.local to ea511f6
2. reboot
3. See error

**Expected behavior**
Zynthian should start with no reported errors.

**Screenshots**
Feb 26 13:04:23 zynthian-pedal startx[511]: ERROR:zynthian_gui_config.<module>: ERROR configuring control I/O subsytem: 'NoneType' object has no attribute 'get_num_zynswitches'
Feb 26 13:04:25 zynthian-pedal startx[511]: libzynmixer: Registering as 'zynmixer'.
Feb 26 13:04:25 zynthian-pedal startx[511]: libzynmixer: Created input ports
Feb 26 13:04:25 zynthian-pedal startx[511]: libzynmixer: Registered output ports
Feb 26 13:04:25 zynthian-pedal startx[511]: libzynmixer: Activated client
Feb 26 13:04:29 zynthian-pedal startx[511]: ERROR:zynthian_gui.init_midi: ERROR initializing MIDI : 'NoneType' object has no attribute 'set_midi_filter_tuning_freq'
Feb 26 13:04:31 zynthian-pedal startx[511]: ERROR:zynthian_gui_layer.load_snapshot: Invalid snapshot: 'NoneType' object has no attribute 'set_midi_active_chan'

**Setup:**
![image](https://user-images.githubusercontent.com/79083/155844522-f01005d3-ef48-49a9-80b9-893bdee992c8.png)

Repeatable problem.

**Comment by wyleu** [comment]
When audio injector removed and replaced with Dummy

zynthian-pedal.local starts.

**Comment by wyleu** [comment]
changing audio device in webconf generates 500 error.

attempting to update an old machine.

![image](https://user-images.githubusercontent.com/79083/155998589-2d06f89b-90d1-458c-ad0a-df55cda81750.png)
Feb 28 14:20:01 zynthian-amp4 startx[508]: from zyncoder.zyncoder import lib_zyncoder, lib_zyncoder_init
Feb 28 14:20:01 zynthian-amp4 startx[508]: ModuleNotFoundError: No module named 'zyncoder.zyncoder'

**Comment by wyleu** [comment]
]: ModuleNotFoundError: No module named 'rpi_ws281x'

**Comment by wyleu** [comment]
From a cean download.
Added the described package and setup.py install...

Mar 01 12:52:19 zynthian-steel startx[512]: ERROR:zynthian_gui_config.<module>: ERROR configuring control I/O subsytem: 'NoneType' object has no attribute 'get_num_zynswitches'
Mar 01 12:52:20 zynthian-steel startx[512]: lilv_world_load_bundle(): warning: Replacing version 2071.7 of <http://gareus.org/oss/lv2/b_whirl#extended> from <file:///zynthian/zynthian-plugins/lv2/b_whirl.lv2/>
Mar 01 12:52:20 zynthian-steel startx[512]: lilv_world_load_bundle(): note: New version 2071.11 found in <file:///zynthian/zynthian-plugins/lv2/b_whirl/>
Mar 01 12:52:20 zynthian-steel startx[512]: lilv_world_load_bundle(): warning: Replacing version 2071.7 of <http://gareus.org/oss/lv2/b_whirl#simple> from <file:///zynthian/zynthian-plugins/lv2/b_whirl.lv2/>
Mar 01 12:52:20 zynthian-steel startx[512]: lilv_world_load_bundle(): note: New version 2071.11 found in <file:///zynthian/zynthian-plugins/lv2/b_whirl/>
Mar 01 12:52:20 zynthian-steel startx[512]: lilv_world_load_bundle(): warning: Ignoring bundle <file:///zynthian/zynthian-plugins/lv2/b_synth.lv2/>
Mar 01 12:52:20 zynthian-steel startx[512]: lilv_world_load_bundle(): note: Newer version of <http://gareus.org/oss/lv2/b_synth> loaded from <file:///zynthian/zynthian-plugins/lv2/b_synth/>
Mar 01 12:52:21 zynthian-steel startx[512]: Can't init zyncore library: /home/pi/zyncoder/build/libzyncore.so: cannot open shared object file: No such file or directory
Mar 01 12:52:21 zynthian-steel startx[512]: Can't init zynmixer library: /home/pi/zynthian-ui/zynlibs/zynmixer/build/libzynmixer.so: cannot open shared object file: No such file or directory
Mar 01 12:52:21 zynthian-steel startx[512]: Can't initialise zynseq library: /home/pi/zynthian-ui/zynlibs/zynseq/build/libzynseq.so: undefined symbol: changeDurationAll
Mar 01 12:52:21 zynthian-steel startx[512]: New instance of zynseq

![image](https://user-images.githubusercontent.com/79083/156172764-39d5c0f6-a844-4cbc-bff8-7e76cc8799a7.png)

**Comment by wyleu** [comment]
After several updates....

Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->set_value_zyncoder(2, ...): Invalid index!
Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->set_value_zyncoder(3, ...): Invalid index!
Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->setup_rangescale_zyncoder(0, ...): Invalid index!
Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->setup_rangescale_zyncoder(1, ...): Invalid index!
Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->setup_rangescale_zyncoder(2, ...): Invalid index!
Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->setup_rangescale_zyncoder(3, ...): Invalid index!
Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->set_value_zyncoder(0, ...): Invalid index!
Mar 01 18:56:31 zynthian-amp4 startx[514]: ZynCore->set_value_zyncoder(1, ...): Invalid index!

**Comment by riban-bw** [comment]
Please do an update via UI / webconf on _Testing_ branch and retest. If issue persists then upload the snapshot. I am removing this from next stable release cycle due to inability to reproduce.
