### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#620]
**Describe the bug**
Zynthian log shows divide by zero error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start an engine that has logarithmic control

**Expected behaviour**
Errors are not shown under normal operation.

**Setup:**
Not near device but manifests in current testing branch.

**Additional context**
Occurs at /home/pi/zynthian-ui/zyngine/zynthian_controller.py:156
```
		if self.is_logarithmic:
			self.powbase = self.value_max/self.value_min
			self.log_powbase = math.log(self.powbase)
```

**Comment by jofemodo** [comment]
When "is_logarithmic" is enabled, value_min shouldn't be 0. Never!
Anyway, i will add a "fix" for that. What about something like this?

```
		if self.is_logarithmic:
			try:
				self.powbase = self.value_max/self.value_min
				self.log_powbase = math.log(self.powbase)
			except:
				self.is_logarithmic = False

```

Or do you prefer something like this:

```
		if self.is_logarithmic:
			if self.value_min==0:
				self.powbase = 10000
				self.value_min = self.value_max/self.powbase
			else:
				self.powbase = self.value_max/self.value_min
			self.log_powbase = math.log(self.powbase)
```
I like more the first solution, but the second is probably more "pragmatic".

Thanks!

**Comment by riban-bw** [comment]
I'm seeing it for a couple of engines. I will try to identify a specific example.

**Comment by riban-bw** [comment]
This occurs when loading MDA DX10 plugin which has these two control settings:
```
    [
        a lv2:InputPort ,
            lv2:ControlPort ;
        lv2:index 3 ;
        lv2:name "Coarse" ;
        lv2:symbol "coarse" ;
        lv2:portProperty epp:logarithmic;
        lv2:default 33.68 ;
        lv2:minimum 0.0 ;
        lv2:maximum 40.0 ;
        units:unit [
            rdfs:label   "ratio" ;
            units:symbol "ratio" ;
            units:render "%f" ;
        ]
    ] , [
        a lv2:InputPort ,
            lv2:ControlPort ;
        lv2:index 4 ;
        lv2:name "Fine" ;
        lv2:symbol "fine" ;
        lv2:portProperty epp:logarithmic;
        lv2:default 0.247 ;
        lv2:minimum 0.000 ;
        lv2:maximum 0.750 ;
        units:unit [
            rdfs:label   "ratio" ;
            units:symbol "ratio" ;
            units:render "%f" ;
        ]
    ]
```
It looks like this plugin has bad configuration. If run with jalv.gtk the following warnings are issued:
```
(jalv.gtk:10907): GLib-GObject-WARNING **: 16:34:54.403: value "-inf" of type 'gdouble' is invalid or out of range for property 'lower' of type 'gdouble'
(jalv.gtk:10907): GLib-GObject-WARNING **: 16:34:54.403: value "-inf" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
(jalv.gtk:10907): GLib-GObject-WARNING **: 16:34:54.451: value "-inf" of type 'gdouble' is invalid or out of range for property 'lower' of type 'gdouble'
(jalv.gtk:10907): GLib-GObject-WARNING **: 16:34:54.451: value "-inf" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
```
JALV seems to limit the minimum to 1. Maybe we should limit to a value close to zero with same sign as maximum, e.g. +/- 0.1.

Could use code like:
```
if self.is_logarithmic:
	if self.value_min == 0:
		self.value_min = 0.1
	if self.value_max == 0:
		self.value_max = -0.1
	self.powbase = self.value_max/self.value_min
	self.log_powbase = math.log(self.powbase)
```
Maybe a more elegant solution would be to add an offset so that the control works across the range logarithmically but min/max remains its configured zero. (The above code does give better behaviour in that the control is no longer hidden and has log control.)

**Comment by jofemodo** [comment]
I implemented and tested this solution, that calculates a reasonable value_min using value_max:

```
                   if self.is_logarithmic:
			if self.value_min==0:
				self.powbase = 10000
				self.value_min = self.value_max/self.powbase
			else:
				self.powbase = self.value_max/self.value_min
			self.log_powbase = math.log(self.powbase)
```
I think it's better than using a fixed value for value_min ;-)

Regards,
