### ISSUE TITLE
Cannot access presets of cascaded engines

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#622]
**Describe the bug**
If a layer has multiple engines, only the _root_ engine's presets are accessible.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a layer with multiple engines
2. Try to access the list of presets for each engine

**Expected behaviour**
Preset view should show list of presets for the engine that was selected in the control screen.

**Setup:**
Not near device but manifests in current testing branch.

**Additional context**
There may be a better method of selecting which engine's presets to show. Maybe show the full list of banks of all engines in the chain with divider title showing the name of the engine.

**Comment by riban-bw** [comment]
This does not seem to be resolved.

- Add Synth layer, e.g. Fluidsynth
- Open "Layer Options" for the synth layer
- Add Audio-FX, e.g. ZynChorus
- Access Layer control screen
- Cannot access presets of ZynChorus

**Comment by jofemodo** [comment]
This is not the right workflow. You have to access layer options and click the FX for accessing its presets.

**Comment by riban-bw** [comment]
Layer Options-> ZynChorus shows:
- Replace
- Remove

![zynthain_screen_capture2](https://user-images.githubusercontent.com/3158323/158395771-ccc685d3-53ce-4c98-8596-4ce887c1cff3.gif)

**Comment by jofemodo** [comment]
It works for me. Is your software updated to the last? Please re-check it ...

**Comment by riban-bw** [comment]
Doh! I updated a Zynthian then tested on a different unit! Stoopid cold giving me brain fog! But I found how to make a cool 25s GIF of screencapture: `byzanz-record --display :0 -d 25 filename.gif`

**Comment by jofemodo** [comment]
The trick for capturing animation is supernice!!! I will use it for mini tutorials!!
We should do it!! In fact, we could add a feature on the UI, so everybody can do it super-easy and share tricks ...
Thanks!
