### ISSUE TITLE
Cannot access high numbered layers in the mixer view

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#623]
**Describe the bug**
If there are more layers / channels / chains than can be displayed within the mixer view, navigating to higher indices fails.

**To Reproduce**
1. Add multiple layers until there are more than can be displayed within mixer view
2. Use SELECT encoder to move highlight to right

**Expected behaviour**
Faders scroll left and right to allow access to all chains.

**Actual behaviour**
Faders stop scrolling when reaching right hand end of screen then jump 2 back when scrolling left.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: [HifiBerry DAC+ ADC PRO](http://192.168.1.53/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.1.53/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.1.53/hw-wiring)
GPIO Expander: [MCP23017](http://192.168.1.53/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 58% (542M/923M)
SD Card: 49% (14G/29G)
Temperature: 59.1ºC
- MIDI
Profile: [default.sh](http://192.168.1.53/ui-midi-options)
Fine Tuning: [440 Hz](http://192.168.1.53/ui-midi-options)
Master Channel: [off](http://192.168.1.53/ui-midi-options)
Single Active Channel: [on](http://192.168.1.53/ui-midi-options)
ZS3 SubSnapShots: [off](http://192.168.1.53/ui-midi-options)
- SOFTWARE
zyncoder: [testing (1609f8d)](https://github.com/zynthian/zyncoder/commit/1609f8dc2c134e9e879bd29334f53513db1ff295)
zynthian-ui: [testing (789ba16)](https://github.com/zynthian/zynthian-ui/commit/789ba160e4f37a1ec619729d0fc516849441ad46)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
This is due to misunderstanding of various indices, i.e.

- Layer / channel / chain index
- Offset within all layers of first visible channel
- Position within visible channels
- Position within all chanels
- etc.

**Comment by riban-bw** [comment]
I am in the process of resolving this. I plan to use the layer as the identifier / object associated with each fader strip rather than the MIDI channel which was previously done and caused this confusion. I hope to have if fixed soon.

**Comment by riban-bw** [comment]
I have submitted pull request https://github.com/zynthian/zynthian-ui/pull/421 that fixes this. Awaiting validation and merge.

**Comment by jofemodo** [comment]
It works pretty well now. Closing!
