### ISSUE TITLE
False encoder events triggered

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#624]
**Describe the bug**
Each time an encoder is rotated there are events triggered for all encoders, not just the adjusted one.

**To Reproduce**
1. Within mixer view, rotate SELECT encoder

**Expected behaviour**
Select encoder action occurs.

**Actual behaviour**
Select encoder action occurs and also each other encoder.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: [HifiBerry DAC+ ADC PRO](http://192.168.1.53/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.1.53/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.1.53/hw-wiring)
GPIO Expander: [MCP23017](http://192.168.1.53/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 58% (542M/923M)
SD Card: 49% (14G/29G)
Temperature: 59.1ºC
- MIDI
Profile: [default.sh](http://192.168.1.53/ui-midi-options)
Fine Tuning: [440 Hz](http://192.168.1.53/ui-midi-options)
Master Channel: [off](http://192.168.1.53/ui-midi-options)
Single Active Channel: [on](http://192.168.1.53/ui-midi-options)
ZS3 SubSnapShots: [off](http://192.168.1.53/ui-midi-options)
- SOFTWARE
zyncoder: [testing (1609f8d)](https://github.com/zynthian/zyncoder/commit/1609f8dc2c134e9e879bd29334f53513db1ff295)
zynthian-ui: [testing (789ba16)](https://github.com/zynthian/zynthian-ui/commit/789ba160e4f37a1ec619729d0fc516849441ad46)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
Detected during debugging. Adding breakpoints after each `lib_zyncore.get_value_flag_zynpot` call shows that this returns true for all encoders after any have changed state. This is a screenshot of my GPI config:

![image](https://user-images.githubusercontent.com/3158323/158602482-8a0ec118-f257-4c71-8b30-06858d4843ce.png)

**Comment by jofemodo** [comment]
Sorry @riban-bw !!

I can't reproduce this issue. It works like a charm for me. I've a v4 over my desk.
Could you send the log?

Thanks!

**Comment by riban-bw** [comment]
This is a V3. What log would you like to see. It is immediatly obvious if you run with a debugger and set breakpoints after each `if lib_zyncore.get_value_flag_zynpot` call within `zyncoder_read` function.

**Comment by jofemodo** [comment]
OK! I see. But it's only in the mixer, so it doesn't seem a problem with the zyncoder library. Let me do some research ...

**Comment by jofemodo** [comment]
Solved!
