### ISSUE TITLE
Selecting program from PROG MIDI-Learn fails

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#625]
**Describe the bug**
Selecting a program from the list of programs (PROG MIDI-Learn view) fails with error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to layer control view
2. Press SNAPSHOT to show CTRL MIDI-Learn
3. Press SNAPSHOT to show PROG MIDI-Learn
4. Add a program if necessary
5. Select a program

**Expected behaviour**
Program is loaded and return to layer control view.

**Actual behaviour**
Screen does not change and error in log:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "zynthian_gui.py", line 2167, in cb_keybinding
    zyngui.callable_ui_action(action)
  File "zynthian_gui.py", line 1124, in callable_ui_action
    self.zynswitch_short(3)
  File "zynthian_gui.py", line 1427, in zynswitch_short
    self.screens[self.current_screen].switch_select('S')
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 285, in switch_select
    self.click_listbox(None, t)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 271, in click_listbox
    self.select_action(self.index, t)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_zs3_learn.py", line 93, in select_action
    self.zyngui.screens['layer'].set_midi_chan_zs3(midich, zs3_index)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 561, in set_midi_chan_zs3
    if changed and self.zyngui.active_screen in ['control','audio_mixer']:
AttributeError: 'zynthian_gui' object has no attribute 'active_screen'
```

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: [HifiBerry DAC+ ADC PRO](http://192.168.1.53/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.1.53/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.1.53/hw-wiring)
GPIO Expander: [MCP23017](http://192.168.1.53/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 72% (672M/923M)
SD Card: 49% (14G/29G)
Temperature: 55.8ºC
- MIDI
Profile: [default.sh](http://192.168.1.53/ui-midi-options)
Fine Tuning: [440 Hz](http://192.168.1.53/ui-midi-options)
Master Channel: [off](http://192.168.1.53/ui-midi-options)
Single Active Channel: [on](http://192.168.1.53/ui-midi-options)
ZS3 SubSnapShots: [off](http://192.168.1.53/ui-midi-options)
- SOFTWARE
zyncoder: [testing (fa32f4a)](https://github.com/zynthian/zyncoder/commit/fa32f4a360d7cc8f7b6a37189294878483ab6ae7)
zynthian-ui: [testing (c65f375)](https://github.com/zynthian/zynthian-ui/commit/c65f375dd48b172d2062ac26e45f11b517477b68)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
May be related to recent changes in screen navigation.

**Comment by jofemodo** [comment]
It should work now. Please update and test!

**Comment by riban-bw** [comment]
Almost! Short press SELECT on a program selects the correct program but does not close the PROG MIDI_Learn screen.

**Comment by jofemodo** [comment]
It should work better now. BTW, i improved the ZS3 navigation workflow, so now you can also learn a program selecting a "free" slot from the UI.

**Comment by riban-bw** [comment]
Cool! The new behaviour of short press SELECT on a free program wasn't expected but makes sense. We should validate that inconsistent behaviour here (no context menu on free programs) is not too confusing. Thanks for sorting this.
