### ISSUE TITLE
After Clean All the list highlight is hidden

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#626]
**Describe the bug**
After selecting _Clean All" in the _Main_ menu the (red) highlight bar is missing from the list.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to _Main_ menu
2. Select  _Clean All_

**Expected behaviour**
All layers are removed and _Main_ menu shows (red) selection highlight bar.

**Actual behaviour**
All layers are removed but (red) selection highlight bar missing from _Main_ menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/159284806-1ac445c5-580d-46f4-b889-3b89220a15fa.png)

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: [HifiBerry DAC+ ADC PRO](http://192.168.1.53/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.1.53/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.1.53/hw-wiring)
GPIO Expander: [MCP23017](http://192.168.1.53/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 55% (514M/923M)
SD Card: 49% (14G/29G)
Temperature: 51.5ºC
- MIDI
Profile: [default.sh](http://192.168.1.53/ui-midi-options)
Fine Tuning: [440 Hz](http://192.168.1.53/ui-midi-options)
Master Channel: [off](http://192.168.1.53/ui-midi-options)
Single Active Channel: [off](http://192.168.1.53/ui-midi-options)
ZS3 SubSnapShots: [off](http://192.168.1.53/ui-midi-options)
- SOFTWARE
zyncoder: [testing (fa32f4a)](https://github.com/zynthian/zyncoder/commit/fa32f4a360d7cc8f7b6a37189294878483ab6ae7)
zynthian-ui: [testing (c65f375)](https://github.com/zynthian/zynthian-ui/commit/c65f375dd48b172d2062ac26e45f11b517477b68)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
There seems to be some interference between populating various list views. Class _zynthian_gui_layer_ still has code to populate list but this is not a used view. The first instance of listbox interference comes when filling list in _zynthian_gui_layer_ but this also happens when filling lists in admin view, etc.

**Comment by jofemodo** [comment]
I can't reproduce this. Could you check if it's a consistent bug, or does it depend of special conditions?

**Comment by riban-bw** [comment]
This has been fixed by recent changes to screen handling, cheers!
