### ISSUE TITLE
Cannot select presets in Fluidsynth

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#627]
**Describe the bug**
After creating a Fluidsynth layer it is not possible to select other presets.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add _New Synth Layer_, FluidSynth SF2 Player, MIDI CH#1, ACBass
2. Short press BACK to show preset list
3. Short press BACK to show bank list
4. Select another bank, e.g. Analog Saw

**Expected behaviour**
Analog Saw is selected.

**Actual behaviour**
ACBass/bassnasal remains selected.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: [HifiBerry DAC+ ADC PRO](http://192.168.1.53/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.1.53/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.1.53/hw-wiring)
GPIO Expander: [MCP23017](http://192.168.1.53/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 64% (593M/923M)
SD Card: 49% (14G/29G)
Temperature: 55.3ºC
- MIDI
Profile: [default.sh](http://192.168.1.53/ui-midi-options)
Fine Tuning: [440 Hz](http://192.168.1.53/ui-midi-options)
Master Channel: [off](http://192.168.1.53/ui-midi-options)
Single Active Channel: [off](http://192.168.1.53/ui-midi-options)
ZS3 SubSnapShots: [on](http://192.168.1.53/ui-midi-options)
- SOFTWARE
zyncoder: [testing (fa32f4a)](https://github.com/zynthian/zyncoder/commit/fa32f4a360d7cc8f7b6a37189294878483ab6ae7)
zynthian-ui: [testing (e21e279)](https://github.com/zynthian/zynthian-ui/commit/e21e279f94cfa5a781dd47d9e519f67ef3c30de9)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
If you initially load a preset within a bank with several presets then subsequent attempts to change bank show the original bank of presets, not the selected bank.

**Comment by jofemodo** [comment]
This is solved too. Please, update and test!

**Comment by riban-bw** [comment]
Thanks!
