### ISSUE TITLE
Support additional switches on native RPi GPIO (while MCP is used as well)

### ISSUE THREAD

**Issue by wanthalf** [zynthian/zynthian-issue-tracking#628]
Input is not supported both on native RPi GPIOs and MCP at the same time. Free GPIOs could be used for additional input without the need to connect another MCP, just because of one or two buttons.

The issue has been discussed here:
https://discourse.zynthian.org/t/extra-switches-now-customizable-from-webconf/2765/64

I have a home-made Zynthian with the standard encoders and 4 buttons connected to the MCP, and I added an extra button for panic/power-off connected to one of the unused native GPIO on the RPi. Then I couldn't find any way to configure the fifth button, because the GPIOs cannot be assigned when there is already an MCP connected. @jofemodo admits that "the zyncoder.c code is a mess" and unfortunately, I have to admit I just haven't been able to find a head and tail in the code either :)

**Comment by jofemodo** [comment]
This should work now. You should be capable of configuring any pin in the RBPi as a zynswitch.
