### ISSUE TITLE
Zynthian User Guide needs an Update for Audio issues

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#63]
To control audio files from an external controller the user needs 
the values for the transport buttons. Most best in all forms: CC#, MMS, Notes

**Comment by jofemodo** [comment]
The current values for controlling the CUIA (Callable UI Actions) are already available in the wiki:

http://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#Controlling_the_UI_with_MIDI_messages

BTW, currently, i wouldn't use "Transport commands" for zynthian's MIDI/Audio recorder commands because there is no synchronization protocol or time-code implementation yet.

Thanks

**Comment by Mickinator** [comment]
Hi Fernando,

I only see record start & stop knobs for audio and midi. 4 knobs.
I do not see transport play, wind, rewind,pause. And a poti for volume 
would be great.

I don‘t wont to record. I only want to start and stop audio files

von Norbert Schreiber gesendet

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-issue-tracking] Zynthian User Guide needs 
an Update for Audio issues (#63)
Datum: 02.10.2019, 18:04 Uhr
An: zynthian/zynthian-issue-tracking <
zynthian-issue-tracking@noreply.github.com
<mailto:zynthian-issue-tracking@noreply.github.com> >
CC: Mickinator <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

The current values for controlling the CUIA (Callable UI Actions) are 
already available in the wiki:

http://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#Controlling_the_UI_with_MIDI_messages
<http://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#Controlling_the_UI_with_MIDI_messages>

BTW, currently, i wouldn't use "Transport commands" for zynthian's 
MIDI/Audio recorder commands because there is no synchronization protocol 
or time-code implementation yet.

Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-issue-tracking/issues/63?email_source=notifications&email_token=ANJNSQILQNFPR6I6OUM4EK3QMTA73A5CNFSM4I2DGI3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAFJCVQ#issuecomment-537563478> 
, or mute the thread

**Comment by jofemodo** [comment]
Exactly what i told you. No "transport" buttons because there is not a proper "transport implementation" ... Please, open a separated request for this ;-)
