### ISSUE TITLE
Better display of effects chain

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#632]
**Is your feature request related to a problem? Please describe.**
It is possible to add audio and MIDI effects to a layer. This forms a chain of plugins which may be in series or parallel at each link of the chain. The UI shows this with ASCII characters but it is quite difficult to comprehend the chain from this display.

**Describe the solution you'd like**
It would be advantageous to display the chain more graphically so that users may clearly see the path through the chain.

**Describe alternatives you've considered**
Using different Unicode characters and spaces the indication may be clearer. Ideally a full graphical representation with GUI blocks and paths.

**Additional context**
I have made some changes locally that may be an improvement:
![image](https://user-images.githubusercontent.com/3158323/159917259-ad52a4a4-efa6-407e-aea3-ce1fa7b4cacc.png)

**Comment by jofemodo** [comment]
Let's go forward with the alternate solution. It will be very useful until we have a better graphic representation.

**Comment by jofemodo** [comment]
The alternate solution has been implemented in https://github.com/zynthian/zynthian-ui/pull/425
I leave open awaiting for a more graphic solution, although i must say that the current view is enough for me. Most of "real life" chains are simple and we don't need more. The graphic viewer is cool and can be useful for complex chains, but it's not a priority.

**Comment by jofemodo** [comment]
Question: Should be move the Add/Remove All options after the FX-chain list? I feel that it could be more clean and easy to understand, but then we need a kind of "header" to clarify what is the list following ...

**Comment by jofemodo** [comment]
Check it now ;-)

**Comment by riban-bw** [comment]
Yep - that is a better order for the layer options menu items. I think the layer options menu should not close after manipulating the chain. I want to add / move / remove items in the chain and see the resulting chain, then possibly manipulate some more, e.g. add three effects at the same time. I find the menu closing between each operation to be awkward.

**Comment by jofemodo** [comment]
Try now ;-)

**Comment by riban-bw** [comment]
Nope! Add audio effect to end of chain closes the layer option screen.

**Comment by jofemodo** [comment]
Yes, adding an audio effect will bring you to control. It's the same workflow when adding a layer (bank => preset => control).
Currently it's not a trivial change, and also, it's not so clear that this workflow is not right for most people. Most of times you only want to add an effect and test the sound and adjust parameters. We should ask the community about it. I think a deeper discussion could be interesting.

**Comment by riban-bw** [comment]
Apart from the contention on navigation after adding effect this is now implemented so I will close the ticket. Navigation changes can be implemented if user testing prove beneficial.
