### ISSUE TITLE
Bug: Zynthian sometimes crashes when attempting to power off

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#633]
**Describe the bug**
When attempting to power down (long push on select, then press yes or click select again), Zynthian crashes and displays the error screen, then restarts.

**To Reproduce**
1. Load snapshot with Zynaddsubfx (layer 1), Obxd (layer 2), and Linux sampler (layer 3)
2. Long click select in order to power down
3. Press Yes on screen or click select again
4. Error splash screen is displayed
5. Zynthian starts up again (without rebooting), i.e. the user inteface starts up again, but the product is not rebooted (for instance, it's possible to have an ssh session active throughout the whole sequence).

**Expected behavior**
Zynthian should power down with no errors.

**Setup:**
- SD image
2021-09-25-zynthianos-stable.img 
- HARDWARE: Zynthian kit v4.4 (4 GB)
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20, MCP23008@0x21, ADS1115@0x48, MCP4728@0x61
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-25
Memory: 3% (121M/3839M)
SD Card: 44% (12G/29G)
Temperature: 54.5�C
Overclock: Disabled
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Receive Mode: Stage (Omni On)
ZS3 SubSnapShots: on
MIDI to Output: On
Master Channel: 16
- SOFTWARE
zyncoder: testing (fa32f4a)
zynthian-ui: testing (84574ea)
zynthian-sys: testing (c13855a)
zynthian-data: testing (398527d)
zynthian-webconf: testing (55658b6)

**Additional context**
Adding a printout of the status returned from zynthian_gui.py in zynthian.sh (see https://github.com/zynthian/zynthian-ui/pull/427) reveals that zynthian_gui.py exits with exit code 132, meaning Illegal instruction (i.e. corresponding to the SIGILL signal, meaning that the CPU tried to execute an illegal instruction). 

This is further confirmed by following extract from the log, obtained by issuing the command `systemctl status zynthian` while Zynthian is attempting to power down:
```
Mar 25 22:35:08 zynthian startx[517]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Mar 25 22:35:11 zynthian startx[517]: ZynCore: Setting-up 8 x Zynswitches...
Mar 25 22:35:11 zynthian startx[517]: ZynCore: Setting-up 4 x Zynpots (zyncoders)...
Mar 25 22:35:11 zynthian startx[517]: New instance of zynseq
Mar 25 22:35:11 zynthian startx[517]: **zynseq initialising as zynthstep**
Mar 25 22:35:14 zynthian startx[517]: ./zynthian.sh: line 160:   584 Illegal instruction     ./zynthian_gui.py
Mar 25 22:35:15 zynthian startx[517]: /zynthian/config/img/fb_zynthian_error_ip.png is 480x320 PNG image, color type RGB
Mar 25 22:35:15 zynthian startx[517]:   Zooming image by 100%...done
Mar 25 22:35:15 zynthian startx[517]:   Merging...done
Mar 25 22:35:15 zynthian startx[517]:   Building XImage...done
```

I can't figure out exactly which combination of layers triggers this behavior. If I take the above mentioned snapshot with three layers, the power down attempt crashes every time. If I remove one of the layers (any one), it works fine. I've tried another snapshot with 11 layers which crashed Zynthian during power down. I removed some layers, still crashed, but at four layers power down worked fine. It seems to be related to the number of configured layers, the more layers that are configured the greater the chance of it crashing, even though there doesn't seem to be an absolute number which causes the problem.

An observation is that when the power down sequence is initiated, the log says `WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!' a couple of times, which seems reasonable as the system is busy taking things down, but then it looks like it starts up ZynCore and zynseq before crashing (see the above log). Why does it try to start up things while it is in the power down sequence?

**Comment by jofemodo** [comment]
OK! I can reproduce the issue. But no idea ... 
@riban-bw , could it be related with the "pexpect" expedient?

**Comment by jofemodo** [comment]
BTW, my layer setup is:

+ NoizeMaker
+ ZynADdSubFX
+ OBXd
+ Sfizz

And the error very similar:

```
Mar 27 03:29:32 z2-01 startx[28678]: ZynCore: Setting-up 30 x Zynswitches...
Mar 27 03:29:32 z2-01 startx[28678]: ZynCore: Setting-up 4 x Zynpots (RV112)...
Mar 27 03:29:32 z2-01 startx[28678]: ZynCore: RV112 poll thread created successfully
Mar 27 03:29:32 z2-01 startx[28678]: New instance of zynseq
Mar 27 03:29:32 z2-01 startx[28678]: **zynseq initialising as zynthstep**
Mar 27 03:29:34 z2-01 startx[28678]: ./zynthian.sh: line 163:  3118 Illegal instruction     ./zynthian_gui.py

```

**Comment by jofemodo** [comment]
If the issue would exist only when powering off, i could capture and force the poweroff, but the error code is also generated when simply stopping the service. We need to locate the "source" of the error code.

**Comment by jofemodo** [comment]
The detailed sequence:

```
INFO:zynthian_gui.stop: STOPPING ZYNTHIAN-UI ...
INFO:zynthian_gui.osc_end: ZYNTHIAN-UI OSC server stopped
DEBUG:zynthian_gui_layer.remove_all_layers: Mute layer 5 => 3#JV/YK Chorus ...
DEBUG:zynthian_gui_layer.drop_from_fxchain: Dropping from FX-chain Obxd-00 => YK_Chorus-01
DEBUG:zynthian_layer.del_audio_out: Disconnecting Audio Output Obxd-00 => YK_Chorus-01
DEBUG:zynthian_gui_layer.remove_all_layers: Mute layer 4 => 10#JV/YK Chorus ...
DEBUG:zynthian_gui_layer.drop_from_fxchain: Dropping from FX-chain sfizz-00 => YK_Chorus-00
DEBUG:zynthian_layer.del_audio_out: Disconnecting Audio Output sfizz-00 => YK_Chorus-00
DEBUG:zynthian_gui_layer.remove_all_layers: Mute layer 3 => 10#SF ...
DEBUG:zynthian_gui_layer.remove_all_layers: Mute layer 2 => 3#JV/Obxd ...
DEBUG:zynthian_gui_layer.remove_all_layers: Mute layer 1 => 2#ZY ...
DEBUG:zynthian_gui_layer.remove_all_layers: Mute layer 0 => 1#JV/Noize Mak3r ...
DEBUG:zynthian_gui_layer.remove_all_layers: Remove layer 5 => 3#JV/YK Chorus ...
DEBUG:zynthian_gui_layer.remove_all_layers: Remove layer 4 => 10#JV/YK Chorus ...
DEBUG:zynthian_gui_layer.remove_all_layers: Remove layer 3 => 10#SF ...
DEBUG:zynthian_gui_layer.remove_all_layers: Remove layer 2 => 3#JV/Obxd ...
DEBUG:zynthian_gui_layer.remove_all_layers: Remove layer 1 => 2#ZY ...
DEBUG:zynthian_gui_layer.remove_all_layers: Remove layer 0 => 1#JV/Noize Mak3r ...
DEBUG:zynthian_gui_engine.stop_unused_engines: Stopping Unused Engine 'JV/1' ...
INFO:zynthian_engine.stop: Stoping Engine Jalv/Noize Mak3r
WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
DEBUG:zynthian_gui_engine.stop_unused_engines: Stopping Unused Engine 'ZY' ...
INFO:zynthian_engine.stop: Stoping Engine ZynAddSubFX
WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
DEBUG:zynthian_gui_engine.stop_unused_engines: Stopping Unused Engine 'JV/3' ...
INFO:zynthian_engine.stop: Stoping Engine Jalv/Obxd
DEBUG:zynthian_gui_engine.stop_unused_engines: Stopping Unused Engine 'SF/4' ...
DEBUG:zynthian_gui_engine.stop_unused_engines: Stopping Unused Engine 'JV/5' ...
INFO:zynthian_engine.stop: Stoping Engine Jalv/YK Chorus
DEBUG:zynthian_gui_engine.stop_unused_engines: Stopping Unused Engine 'JV/6' ...
INFO:zynthian_engine.stop: Stoping Engine Jalv/YK Chorus
DEBUG:zynthian_config.get_disabled_midi_in_ports: DISABLED_MIDI_IN = ['']
DEBUG:zynthian_config.get_enabled_midi_out_ports: ENABLED_MIDI_OUT = ['ttymidi:MIDI_out']
DEBUG:zynthian_config.get_enabled_midi_fb_ports: ENABLED_MIDI_FB = ['']
DEBUG:zynthian_gui_config.set_midi_config: MMC Bank Change CCNum: 0
DEBUG:zynthian_gui_config.set_midi_config: MMC Bank Change UP: None
DEBUG:zynthian_gui_config.set_midi_config: MMC Bank Change DOWN: None
DEBUG:zynthian_gui_config.set_midi_config: MMC Program Change UP: None
DEBUG:zynthian_gui_config.set_midi_config: MMC Program Change DOWN: None
INFO:zynthian_gui_admin.stop_rtpmidi: STOPPING RTP-MIDI
INFO:zynthian_gui_admin.stop_qmidinet: STOPPING QMIDINET
INFO:zynthian_gui_admin.stop_touchosc2midi: STOPPING touchosc2midi
INFO:zynthian_gui_admin.stop_aubionotes: STOPPING aubionotes
DEBUG:zynthian_gui.wait_threads_end: Awaiting threads to end ...
DEBUG:zynthian_gui.wait_threads_end: Remaining 3 active threads.
INFO:zynthian_gui.zyngine_refresh: EXITING ZYNTHIAN-UI ...
INFO:zynthian_gui.<module>: Exit with code 0 ...

./zynthian.sh: line 163:  5269 Segmentation fault      ./zynthian_gui.py
```

I can't see nothing specially bad, except the 3 threads remaining. Normally, there are 2 threads remaining at the end of the exit sequence. The problem could be related with this extra thread ...

**Comment by jofemodo** [comment]
It seems to be Jalv processes. @riban-bw, i think it's related with the "other" issue with Jalv.

**Comment by polluxsynth** [comment]
I did some debugging last night to try and narrow the problem down, not very successfully.

One strange thing I thought was that in zynthian_gui:wait_threads_end, when I added a printout of which threads were alive before and in the timeout loop, sometimes either all four threads had died, other times the control thread was the only one still alive, yet threading.active_count() still returned 3 or 4. So it seems that .is_alive() wasn't consistent with .active_count().

Indeed, in the printout above, the loop after `Awaiting threads to end ...` clearly exits with all four threads dead since it prints out `Remaining 3 active threads`with no message that the timeout has been passed.

In the cases where the control thread was remaining, extending the loop count from 20 to 100 still didn't give the control thread time to stop. 

I also tried running zyngui "manually", by stopping the zynthian service (`systemctl stop zynthian`), then running `/usr/bin/startx ./zynthian_gui.py` (after setting up the appropriate environment variables). Everything started as expected, but this time, when attempting to power down, it went fine, with no 'illegal instruction'. (I was hoping to eventually attach a debugger to the process, and this was the first step).

I did learn a bit about the workings of parts of the Zynthian UI though, like what the different threads do...

Isn't the `ZynCore: Setting-up 30 x Zynswitches...` et al printout worrying? It indicates that the zyncore lib is being restarted in a situation where it shouldn't ? EDIT: On the other hand, I can't find that printout anywhere else in the debug log, so perhaps it's something that zyncore prints out when Zynthian is starting up, but for whatever reason the actual printout is deferred until the process is being stopped? EDIT: This printout comes at the same place also when the shutdown behaves normally, so I suppose it's just a quirk of the logging design (printfs from the zyncoder library seem to end up after all other log entries?).

EDIT: While experimenting, going from 3 to 2 layers, removing a Zynaddsubfx layer, resulted in normal poweroff behavior, so after the restart I tried purposely killing zynaddsubfx with a SIGILL (`killall -SIGILL zynaddsubfx') to see if the SIGILL signal would carry over to the controlling process, but it didn't. There was a short buzz of sound probably as the last buffer of generated sound got looped a few times in some JACK buffer before the port was disconnected (the autoconnector), but the GUI kept running as before (albeit with the Zynaddsubfx layer now silent).

Another thing I did was enable core dumping (`ulimit -c unlimited`) in zynthian.sh, and then after the crash run gdb on the core file. Without a meaningful context there wasn't that much information that I found useful (but I'm no ace with GDB on the other hand). The instruction that triggered the SIGILL in this case was a `cdpge` instruction, i.e. a (conditional, hence `ge`) co-processor data operation on coprocessor 15 (the system coprocessor). This led me to speculate that there is some internal race causing code to be executed while the process is being terminated (from what I can make out, coprocessor access is handled by the instruction itself generateing an illegal instruction trap, which is then handled by a software interrupt, so if the trap handler has been removed but there is still running code trying to access the coprocessor, the result would be a SIGILL).

EDIT: More tests: killing the individual engines (`kill -9 <engine-process>`), then trying to power off results in the same behavior as if the engines were still running.

EDIT: Yet another observation: From the time that `Exit with code 0` is printed until the Illegal instruction printout, it takes about 3 or 4 seconds, both in terms of the timestamps shown in the debug log, and also in terms of the perceived delay between the two printouts. So it seems that from the time that exit() is called, "something" is going on in the application before it crashes.

EDIT: So, as others who've been working with Zynthian much more than I have probably already know, the three remaining threads at zyngui exit are not the ones that have been started from zyngui itself (i.e. the logging, status and control threads, as well as the autoconnector thread), but rather the MainThread, one from zynthian_engine_mixer, and one called Dummy-n, where n is an arbitrary (low) number, like 7 or 10. Not sure where this one comes from; according to the docs I've been able to find, certain threading method calls return a Dummy thread as a placeholder, but in this case it is an active thread, so not sure where it comes from or what its for.

EDIT: Sorry for this lengthy post, I figured it might be helpful to publish my findings as I go along.

I've discovered the following: Changing the while condition of the loop in zyngui::wait_threads_end() to `n>0`, i.e. unconditonally always waits the whole timeout, and lengthening the timeout to `n=100` (i.e. 10 seconds), consistently does not cause the SIGILL Furthermore, adding a printout wihin the loop reveals that when n=69, a bunch (like, 7 or 8) of `WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!` messages are printed out. More research is needed of course, but instinctively this indicates that there's some callback handler which has not been properly disabled when exiting.

**Comment by polluxsynth** [comment]
I think I found the problem: https://github.com/zynthian/zynthian-ui/pull/428 .

With this fix Zynthian has shut down cleanly every time under the preconditions given in this issue (monitoring the debug log while the unit was shutting down).

I wonder if this really indicates an underlying problem with the Python JACK client class, but at any rate I think the suggested fix is good practice.

**Comment by jofemodo** [comment]
It seems to work like a charm!! Thanks a lot!
