### ISSUE TITLE
Bug: Two-valued CC parameters require more clicks than two-valued OSC parameters

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#634]
**Describe the bug**
In order to change a two-valued CC based parameter, such as Zynaddsubfx:mode:sustain, several encoder clicks are needed, whereas to change a two-valued OSC based parameter, such as Zynaddsubfx:mode:drum mode, only one encoder click is needed.

**To Reproduce**
1. Go to a Zynaddsubfx layer
2. Navigate to mode page
3. Note how it takes multiple clicks to change the sustain parameter (CC 64) but only one to change the drum mode

**Expected behavior**
Two-valued parameters should require a single click to change them. Otherwise, a user might conclude that parameters which require multiple clicks are broken in some way because nothing apparently happens.

**Setup:**
- SD image
2021-09-25-zynthianos-stable.img 
- HARDWARE: Zynthian kit v4.4 (4 GB)
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20, MCP23008@0x21, ADS1115@0x48, MCP4728@0x61
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-25
Memory: 3% (121M/3839M)
SD Card: 44% (12G/29G)
Temperature: 54.5�C
Overclock: Disabled
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Receive Mode: Stage (Omni On)
ZS3 SubSnapShots: on
MIDI to Output: On
Master Channel: 16
- SOFTWARE
zyncoder: testing (fa32f4a)
zynthian-ui: testing (84574ea)
zynthian-sys: testing (c13855a)
zynthian-data: testing (398527d)

**Additional context**
Currently I'm running Zynaddsubfx built from master, but that doesn't affect the Zynthian UI.

**Comment by jofemodo** [comment]
Hi @polluxsynth !

This is duplicated in https://github.com/zynthian/zynthian-issue-tracking/issues/629.
I will close this and will address the problem on #629, OK?

**Comment by polluxsynth** [comment]
Sure, no problem.
