### ISSUE TITLE
Zynpot operating as unsigned integer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#636]
**Describe the bug**
Accessing zynpot (set/get) via Python results in negative values being preseted as high value positive values. It seems that access to zynpot from Python is interpreting encoder values as unsigned integers. Direct access to zyncoder via Python does present as unsigned integers.

This is evident in on-screen keyboard driven from CUIA /  QWERTY keyboard. Pressing "Down" arrow when "1" is highlighted does not move to "Enter" as it should. Debug shows the value changes to high positive integer, not "-1" as expected. Debug shows access to library setting or getting -1 results in value being set or got at high positive integer.

**Comment by jofemodo** [comment]
Ups!! Well done, Mr. @riban-bw !! You hunted a good bug!!
But it's not python-related but a bad-type problem in zyncoder's code.
Thanks a lot!
