### ISSUE TITLE
Ensure smooth migration to next stable release

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#637]
**Is your feature request related to a problem? Please describe.**
When the next stable version is released users should not encounter issues with the migration. 

**Describe the solution you'd like**
- Existing snapshots should continue to operate
- Any snapshot migration changes should result in the same operation
- User and system presets should continue to operate and present in same or similar way
- Audio levels should not change
- MIDI mapping should remain intact
- Changes of workflow should be documented and highlighted in release notes
- Regression testing should be run (ideally)
- Hardware button configuration continues to work (or documented what has changed)

**Describe alternatives you've considered**
Just let users complain...

**Additional context**
We should track (and add to / modify) these things to reduce impact on users.

**Comment by jofemodo** [comment]
Hi @riban-bw !

I've simplified audio routing by removing from the list the per-zynmixer-strip entries. Now you route/unroute from the mixer by checking a unique "mixer" entry that adds/removes the "mixer pseudo-port" to the list. This simplified "audio_out" list, containing pseudo-port entries, is what is saved/restored from the snapshot, sanitized as needed to avoid snapshot version problems.

A new layer's function, get_audio_out_ports(), calculates in run-time the true list of jack ports to be routed. It's only called from autoconnect. For the rest of zynthian code, the "pseudo-port" list is modified, saved, restored, etc.

I think it's a good solution and completely solves the snapshot compatibility problem. Old "stable" snapshots are loaded without issues on the testing branch, including complex ones, like "three on three". In the other hand, making "testing" snaphots to be loaded on stable is a single-line change, really simple. I will push this tiny change in stable and will test how it works when turning-back from testing to stable.

Regards,

**Comment by jofemodo** [comment]
Done! Switching to testing and coming back to stable now seems to work. Saved snapshots also seems to work in both directions. Anyway, all this must be tested with greater detail before releasing the "testing quarentine" ;-)

**Comment by jofemodo** [comment]
**Important Note:** Due to new "parameter grouping" on some LV2 plugins like OBXd, Dexed, NoizeMaker, etc. some controller values are lost when loading older snapshots. This is not totally recoverable when going back to stable because some of this grouping was already merged on stable (zynthian-data/lv2-custom dir). ZynAddSubFX also have some parameter renaming/resorting.

We should think a little bit about this kind of changes. I mean, how can we keep compatibility when parameters are renamed on synth engines? Sometimes changes the LV2 ttl definition, sometimes changes the synth engine OSC interface (i.e. ZynAddSubFX), etc. It's a nice maintainance bourdel ;-)

**Comment by jofemodo** [comment]
I've been reviewing this and most of changes on LV2 plugins due to grouping and re-ordering have no impact on snapshot backward compatibility. Anyway, the problem still is there and we should think about how to deal with this kind of issues when they arises.

**Comment by jofemodo** [comment]
Please, test changing from stable to testing and changing back from testing to stable again. We need to be sure this works fine before asking people to try testing again ;-)

Regards

**Comment by riban-bw** [comment]
This snapshot is not reconnecting system:capture to Gain_2x2.
[018-steppin out_3pat.zip](https://github.com/zynthian/zynthian-issue-tracking/files/8568892/018-steppin.out_3pat.zip)

**Comment by jofemodo** [comment]
I just tested on last masterfx branch and it loads and reconnects everything.

**Comment by jofemodo** [comment]
Ohhhh!  Come on!! You can do it better!! Give me a snapshot from stable that doesn't work on testing!
Or better, let's test masterfx snapshots on stable ... jejeje!! ;-DD

**Comment by riban-bw** [comment]
Nope! Not working on my masterfx branch. System:capture not being connected to Gain_2x2:

![image](https://user-images.githubusercontent.com/3158323/165624857-42b5b7f4-76b5-4876-830c-3cfdb33dab11.png)

This is a snapshot that wyleu posted in another ticket so I tested it.

**Comment by jofemodo** [comment]
Ups! It seemd connected, but you are right. Now it's fixed!

**Comment by jofemodo** [comment]
We are soooo close now ...

**Comment by jofemodo** [comment]
@riban-bw  added a fix on load_snapshot to fix MPlayer routing: 

https://github.com/zynthian/zynthian-ui/commit/79779c5c2306204a8cd64374e175a543d55a2404

I see you don't like to mark your commits for referencing the issues. I do like a lot ;-)

**Comment by riban-bw** [comment]
I suggest this ticket be used to track progress of 22.05 (22.06?) testing.

**Comment by riban-bw** [comment]
Much work has been done to ensure smooth migration to 2210 release.
