### ISSUE TITLE
Zynthian.org is down. Wiki unavailable.

### ISSUE THREAD

**Issue by tstex** [zynthian/zynthian-issue-tracking#64]
Zynthian.org is down. Wiki unavailable.

**Comment by jofemodo** [comment]
OK! Services are restored now. I just changed the root server and i'm learning to ride the new horse, ihujuuuu!!! ;-)

Thanks for warning!

**Comment by riban-bw** [comment]
zynthian.org seems to be down again. I have been trying to connect for a couple of hours so it looks like a real outage rather than a blip.

**Comment by jofemodo** [comment]
The new root server is not stable. It freezes every few days and i don't know where the problem is.
Perhaps i should look for a real expert...

**Comment by TheKikGen** [comment]
Still down...

**Comment by Baggypants** [comment]
What is your server running & running on?

**Comment by erwincoumans** [comment]
zynthian is down again? Is there any mirror to download images?

**Comment by b0bje** [comment]
everything zynthian is down again...any other ways to get in touch with users ? irc/reddit/something else ?

**Comment by jofemodo** [comment]
All services have been migrated to a new root server, from Xen to KVM (proxmox). Everything seems to be solid rock now and stability has been restablished.
