### ISSUE TITLE
Cannot add audio effect to layer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#640]
**Describe the bug**
Attempt to add an audio effect to a layer fails with error.

**To Reproduce**
1. Add synth layer
2. Add audio effect to synth layer

**Expected behaviour**
Audio effect added.

**Actual behaviour**
ERROR:zynthian_gui_layer.add_to_fxchain: Error chaining Audio Effect (name 'aout_ports' is not defined)

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: [HifiBerry DAC+ ADC PRO](http://192.168.8.230/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.8.230/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.8.230/hw-wiring)
I2C: [MCP23017@0x20](http://192.168.8.230/hw-wiring)
Profile: [z2_v1](http://192.168.8.230/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 66% (611M/923M)
SD Card: 59% (16G/29G)
Temperature: 49.4ºC
Overclock: [Disabled](http://192.168.8.230/hw-options)
- MIDI
Profile: [default.sh](http://192.168.8.230/ui-midi-options)
Tuning: [440 Hz](http://192.168.8.230/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.8.230/ui-midi-options)
ZS3 Sub-SnapShots: [Off](http://192.168.8.230/ui-midi-options)
MIDI to Output: [On](http://192.168.8.230/ui-midi-options)
Master Channel: [off](http://192.168.8.230/ui-midi-options)
- SOFTWARE
zyncoder: [testing (e236925)](https://github.com/zynthian/zyncoder/commit/e2369251a5456539c8d79e218c8e096accfe0f54)
zynthian-ui: [testing (6275d64)](https://github.com/zynthian/zynthian-ui/commit/6275d64f97ddf36c1646b940b358fadfd3d66fa8)
zynthian-sys: [testing (a5e66e4)](https://github.com/zynthian/zynthian-sys/commit/a5e66e4a9119d6ad2504bf78f774fcf33eb4d2fa)
zynthian-data: [testing (10e1f9f)](https://github.com/zynthian/zynthian-data/commit/10e1f9f0e3da196775bda4b8c6fd54a425c3e65c)
zynthian-webconf: [testing (729cc9b)](https://github.com/zynthian/zynthian-webconf/commit/729cc9b4113fd53cea512709028969d389a7d7af)

**Comment by jofemodo** [comment]
It's already solved. Please update.
