### ISSUE TITLE
Switch Aeolus to Suloea

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-issue-tracking#643]
**Is your feature request related to a problem? Please describe.**

Aeolus will only work on the first four midi channels

**Describe the solution you'd like**
Switch to using Suolea https://github.com/paulfd/suloea which can run multiple instances on any midi port

**Additional context**
Moving all engines to lv2 will make preset management easier.

**Comment by Baggypants** [comment]
Build and tested running on zynthian stable.

**Comment by jofemodo** [comment]
@riban has improved aeolus so it works quite nicely now. No more fixed channel limitations, we can adjust reverb, etc
So, i think we are not going to change in the short term.
