### ISSUE TITLE
Update to 5.15 kernel

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#644]
**Is your feature request related to a problem? Please describe.**
I suffer many xruns on my Zynthian 3 with RPi3. [steveb described](https://discourse.zynthian.org/t/solved-xrun-every-110-seconds-with-usb-audio-interface/6854/12?u=riban) how updating to kernel 5.15 significantly improves this.

**Describe the solution you'd like**
Testing update to use kernel 5.15. Next stable release image to use kernel 5.15. Next stable update to use kernel 5.15.

**Describe alternatives you've considered**
Suffer the clicks.

**Additional context**
This kernel doesn’t have the [commit originally referenced 2](https://github.com/raspberrypi/linux/commit/d5f871f89e21bb71827ea57bd484eedea85839a0) but it does have a couple 2 of others 2 which may be helping.

**Comment by riban-bw** [comment]
@jofemodo please implement in build system.

**Comment by jofemodo** [comment]
rpi-update bumps to 5.15. I'm testing with latest testing branch on Z2.

**Comment by jofemodo** [comment]
It seems to work flawlessly. I would add a rpi-update to the 2209 update process.

**Comment by jofemodo** [comment]
No problems until now. It seems safe to include a rpi-update in the update script.
