### ISSUE TITLE
Zynseq thows error when scrolling through keymaps

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#646]
**Describe the bug**
Selecting a keymap for a pattern in step sequencer can give an error in the log.

**To Reproduce**
1. Open pattern editor
2. From menu select "Scale"
3. Rotate SELECT encoder quickly

**Expected behaviour**
Each keymap is shown.

**Actual  behaviour**
Fast scrolling triggers error:
```
Apr 27 03:35:59 zynthian startx[4410]: ERROR:zynthian_gui.refresh_status: list index out of range
Apr 27 03:35:59 zynthian startx[4410]: Traceback (most recent call last):
Apr 27 03:35:59 zynthian startx[4410]:   File "./zynthian_gui.py", line 1880, in refresh_status
Apr 27 03:35:59 zynthian startx[4410]:     self.screens[self.current_screen].refresh_status(self.status_info)
Apr 27 03:35:59 zynthian startx[4410]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_stepsequencer.py", line 583, in refresh_status
Apr 27 03:35:59 zynthian startx[4410]:     self.child.refresh_status()
Apr 27 03:35:59 zynthian startx[4410]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 968, in refresh_status
Apr 27 03:35:59 zynthian startx[4410]:     self.draw_grid()
Apr 27 03:35:59 zynthian startx[4410]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 685, in draw_grid
Apr 27 03:35:59 zynthian startx[4410]:     self.draw_row(index)
Apr 27 03:35:59 zynthian startx[4410]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 593, in draw_row
Apr 27 03:35:59 zynthian startx[4410]:     self.draw_cell(step, row)
Apr 27 03:35:59 zynthian startx[4410]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 617, in draw_cell
Apr 27 03:35:59 zynthian startx[4410]:     note = self.keymap[row + self.keymap_offset]["note"]
Apr 27 03:35:59 zynthian startx[4410]: IndexError: list index out of range
```

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: [HifiBerry DAC+ ADC PRO](http://192.168.8.230/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.8.230/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.8.230/hw-wiring)
I2C: [MCP23017@0x20](http://192.168.8.230/hw-wiring)
Profile: [z2_v1](http://192.168.8.230/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 54% (500M/923M)
SD Card: 60% (16G/29G)
Temperature: 69.3ºC
Overclock: [Disabled](http://192.168.8.230/hw-options)
- MIDI
Profile: [default.sh](http://192.168.8.230/ui-midi-options)
Tuning: [440 Hz](http://192.168.8.230/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.8.230/ui-midi-options)
ZS3 Sub-SnapShots: [Off](http://192.168.8.230/ui-midi-options)
MIDI to Output: [On](http://192.168.8.230/ui-midi-options)
Master Channel: [off](http://192.168.8.230/ui-midi-options)
- SOFTWARE
zyncoder: [testing (e236925)](https://github.com/zynthian/zyncoder/commit/e2369251a5456539c8d79e218c8e096accfe0f54)
zynthian-ui: [masterfx (727a4f6)](https://github.com/zynthian/zynthian-ui/commit/727a4f6e506866ad792028ecf5b50d300b5fc25c)
zynthian-sys: [testing (a5e66e4)](https://github.com/zynthian/zynthian-sys/commit/a5e66e4a9119d6ad2504bf78f774fcf33eb4d2fa)
zynthian-data: [testing (10e1f9f)](https://github.com/zynthian/zynthian-data/commit/10e1f9f0e3da196775bda4b8c6fd54a425c3e65c)
zynthian-webconf: [testing (729cc9b)](https://github.com/zynthian/zynthian-webconf/commit/729cc9b4113fd53cea512709028969d389a7d7af)

**Additional context**
Almost certainly poor handling of encoder acceleration. This has changed recently so probably needs an extra check.

**Comment by jofemodo** [comment]
Is this fixed?

**Comment by riban-bw** [comment]
Fixed by recent fixes and optimisations of menu.
