### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#648]
**Describe the bug**
The following button operations trigger unexpected actions:

- Short press LAYER from preset list goes to Main Menu but should do nothing
- Short press LEARN/SHOT from preset list kinda toggles Favourites but not well - is this required?
- Short press LAYER from bank list goes to Main Menu but should do nothing
- Short press LEARN/SHOT from bank list kinda toggles Favourites but not well - is this required?
- Short press BACK from ZynPad goes back to previous screen, e.g. menu. Maybe this isn't desirable?
- Short press LAYER from ZynPad shows menu - should this be bold LAYER?
- Short press BACK from Audio Levels does nothing - should return to previous menu
- Short press LEARN/SHOT from Audio Levels switches to layer MIDI-Learn
- Short press LAYER from selector, e.g. Engine selection shows Main Menu but leaves self in screen history - should do nothing

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: [HifiBerry DAC+ ADC PRO](http://192.168.8.230/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.8.230/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.8.230/hw-wiring)
I2C: [MCP23017@0x20](http://192.168.8.230/hw-wiring)
Profile: [z2_v1](http://192.168.8.230/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 30% (278M/923M)
SD Card: 60% (16G/29G)
Temperature: 55.8ºC
Overclock: [Disabled](http://192.168.8.230/hw-options)
- MIDI
Profile: [default.sh](http://192.168.8.230/ui-midi-options)
Tuning: [440 Hz](http://192.168.8.230/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.8.230/ui-midi-options)
ZS3 Sub-SnapShots: [Off](http://192.168.8.230/ui-midi-options)
MIDI to Output: [On](http://192.168.8.230/ui-midi-options)
Master Channel: [off](http://192.168.8.230/ui-midi-options)
- SOFTWARE
zyncoder: [testing (e236925)](https://github.com/zynthian/zyncoder/commit/e2369251a5456539c8d79e218c8e096accfe0f54)
zynthian-ui: [masterfx (727a4f6)](https://github.com/zynthian/zynthian-ui/commit/727a4f6e506866ad792028ecf5b50d300b5fc25c)
zynthian-sys: [testing (a5e66e4)](https://github.com/zynthian/zynthian-sys/commit/a5e66e4a9119d6ad2504bf78f774fcf33eb4d2fa)
zynthian-data: [testing (10e1f9f)](https://github.com/zynthian/zynthian-data/commit/10e1f9f0e3da196775bda4b8c6fd54a425c3e65c)
zynthian-webconf: [testing (729cc9b)](https://github.com/zynthian/zynthian-webconf/commit/729cc9b4113fd53cea512709028969d389a7d7af)

**Additional context**
These observations are based on testing and documentation creation for the pending 2205 release. There are some changes of behaviour from previous versions to improve consistent behaviour.

**Comment by jofemodo** [comment]
I comment one by one. Fixes have been done on masterfx branch.

> Short press LAYER from preset list goes to Main Menu but should do nothing

Fixed!

> Short press LEARN/SHOT from preset list kinda toggles Favourites but not well - is this required?

Yes. This is the original and prefered way. The favorites pseudobank was added for "touchies" but i don't like too much and i would prefer to remove it when we figure a better way (perhaps removing touch interface? };-DD )
BTW, i've improved the way it works and now it's more consistent.

> Short press LAYER from bank list goes to Main Menu but should do nothing

Fixed!

>Short press LEARN/SHOT from bank list kinda toggles Favourites but not well - is this required?

Already explained. It should work better now.

> Short press BACK from ZynPad goes back to previous screen, e.g. menu. Maybe this isn't desirable?

What about going to mixer?  But it should be consistent with Audio & MIDI recorder, Audio Levels, etc.
Done!

> Short press LAYER from ZynPad shows menu - should this be bold LAYER?

From my POV:
   + short-layer => zynpad menu
   + bold-layer => main menu (this action should be global, same than bold-back => mixer)
Done!

> Short press BACK from Audio Levels does nothing - should return to previous menu

For being consistent, it should back to mixer.
Done!

> Short press LEARN/SHOT from Audio Levels switches to layer MIDI-Learn

Fixed! Now it triggers Audio Levels control MIDI learn.

> Short press LAYER from selector, e.g. Engine selection shows Main Menu but leaves self in screen history - should do nothing

Fixed!

**Comment by riban-bw** [comment]
Cool - well done!

Thanks for fixing favourites toggle. There is a small issue with it. If you press SNAPSHOT to show Favourites then press BACK to navigate to bank list, "*** Favorites ***" is not highlighted.

(As much fun as it was trying every combination of navigation / button press, it would be good if there was an automated test method for this!!!)

Also if you toggle Favourites on and off then subsequent navigation from control screen skips the preset list, i.e.

- Enter chain control screen
- Press BACK to access preset list
- Press LEARN/SHOT to show favourites
- Press LEARN/SHOT to hide favourites (you end up back in contrl screen)
- Press BACK
Expect to reach preset list but actually reach bank list.


Also, replacing an audio effect in a synth chain shows the list of Engines with first effect plugin (engine) shown. It would be optimal to select the engine that is being replaced. I notices when I was stepping through engines and each replace put me back at the start of the list. (I guess that isn't navigation but...)

**Comment by jofemodo** [comment]
>Press LEARN/SHOT to hide favourites (you end up back in contrl screen)
Not in my zynthian. You should go back to presets and so it does in my zynthians. Please update to latest testing (masterfx is already merged).

Except by this (you shouldn't back to control after clicking "learn" to hide favorites),  this is the expected behaviour . When you click back from presets you go to banks, one click more and yo return to control. No other way of reaching banks.

I already fixed the highlighting detail ;-)

**Comment by jofemodo** [comment]
Can we close this? ;-)

**Comment by riban-bw** [comment]
He he,,, almost! I think the encoder switch navigation is almost right:
- Replace engine should highlight existing engine

There are some touch navigations that need resolving...
- ~~Bold touch topstrap in preset list goes to main menu - should go to Audio Mixer~~
- ~~Bold touch topstrap in bank list goes to main menu - should go to Audio Mixer~~
- ~~Bold touch bank should show context menu (context not implemented - subject of a feature request)~~
- ~~ZynPad bold topstrap should (maybe) go to mixer (currently there is a menu option to do this)~~
- ~~Bold touch pad sometimes goes to arranger - probably related to change in view history - By design if sequence has multiple tracks.~~
- ~~Arranger bold topstrap should (maybe) got to mixer (currently there is a menu option to do this)~~
- ~~Arranger toggle play unavailable to touch (not navigation but in my navigation/actions chart) - Click top left~~
- Arranger toggle mute unavailable (not critical)
- ~~Pattern Editor bold topstrap should (maybe) go to mixer (currently there is a menu option to do this)~~
- ~~Pattern Editor can't toggle playback - Click top left~~
- ~~Drag note vertically in pattern editor adjusts velocity of subsequently added notes but not selected note~~
- Drag note horizontally in pattern editor adjusts duration of note but can't do fine adjustment (maybe not critical but nice to have) - should be separate feature request.
- Engine Control view - can't access XY controller - should be separate feature request
- ~~Bold press on topstrap in Chain Options goes to Main menu - should go to Mixer~~

**Comment by jofemodo** [comment]
Done "Replacing engine/FX should highlight current one".

**Comment by riban-bw** [comment]
Recent changes to encoder interface and other changes requires retesting of all navigation from all controllers including:
- Rotary encoders
- Switches
- Touch
- Mouse including wheel
- (QWERTY) keyboard
- CUIA
- OSC

**Comment by riban-bw** [comment]
Review of hardware encoder control:

- Layer options menu: Short press SNAPSHOT should do nothing
- Layer options menu: Bold press LAYER should do nothing (or close options menu so it is not shown when returning)
- Layer options menu: Long press LAYER should do nothing (or close options menu so it is not shown when returning)
- Layer options menu: Long press BACK should do nothing (or close options menu so it is not shown when returning)
- Main menu: Short press SNAPSHOT should do nothing
- Engine menu: Short press SNAPSHOT should do nothing
- Engine menu: Bold press LAYER should do cancel engine selection so subsequent BACK does not go to engine menu
- MIDI channel menu: Short press SNAPSHOT should do nothing
- MIDI channel: Bold press LAYER should do cancel engine selection so subsequent BACK does not go to engine menu

Review of touch & mouse interface:

No issues found.

**Comment by riban-bw** [comment]
Fixed most of the encoder navigation issues. There are some global actions triggered by long press which I have not changed. I suggest we live with them for a while and garner user feedback.

QWERTY keyboard control is currently broken. I suggest we move the zyncoder polling to the zyngui class and get it to trigger on_zyncoder events within views. This allows keyboard mapping to be assigned to on_zyncoder events as required.

Testing of CUIA and OSC should be deferred until decision on zyncoder handling as these interact similarly.
