### ISSUE TITLE
Multiple soundcard init order

### ISSUE THREAD

**Issue by jardous** [zynthian/zynthian-issue-tracking#65]
using midi controller Berhinger U-Control UMA25S that has a builtin audio interface causes that at boot time, this interface is initialized as default one and there no sound coming from the zynthian outputs. From the Web UI I do not see the volume sliders and aplay -l says that the Behringer device has index 0, the hifiberry has index 2 (or 1 sometimes)

**To Reproduce**
1. Plug a USB audio interface 
2. Reboot

**Expected behavior**
The hifiberry is alway default with index=0

**Setup:**
 - SD-image
 - Hardware Config Kit V3
 - Software Version Latest nightly build

**Comment by jardous** [comment]
```
root@zynthian:~# cat /proc/asound/modules 
 0 snd_usb_audio
 1 snd_usb_audio
 2 snd_soc_hifiberry_dacplusadc

root@zynthian:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: CODEC [USB Audio CODEC], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: sndrpihifiberry [snd_rpi_hifiberry_dacplusadc], device 0: HiFiBerry DAC+ADC HiFi multicodec-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by jardous** [comment]
adding

`options snd slots=snd_soc_hifiberry_dacplusadc,snd_usb_audio`

in _/lib/modprobe.d/aliases.conf_

seems to do the trick. This line defines the order of device initialization

**Comment by jofemodo** [comment]
This issue is solved, my friend.
Please, reconfigure your sound device (or your kit) from the webconf, restart and it will work.

**Comment by jofemodo** [comment]
Please, read this:

https://discourse.zynthian.org/t/multiple-usb-devices-on-boot-now-it-works/3240

Thanks

**Comment by jardous** [comment]
Hello - thanks for pointing me to that. Unfortunately those drop selections in web-ui does not seem to work properly so I am never able to select something else (but this seems like a different issue)

**Comment by jofemodo** [comment]
When you have selected a "kit", some hardware configuration options are disabled because these values are enforced by kit selection. You can access all configuration options by selecting "custom" kit, although you shouldn't need to do that normally.

Simply go to kit selection, select your kit if not already selected, click save and reboot.

Regards
