### ISSUE TITLE
Ability to select file for AudioPlayer engine

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#652]
**Is your feature request related to a problem? Please describe.**
There is a generator engine / plugin called "AudioPlayer" but Zynthian does not offer a mechanism to select the file for it to play.

**Describe the solution you'd like**
A file browser / list of files should open when a control button is clicked.

**Describe alternatives you've considered**
It's fairly useless as-is.

**Additional context**
There is another feature request elsewhere for a file browser.

**Comment by jofemodo** [comment]
This would be useful in a few places:

+ selecting impulse response files for some convolution reverb (LV2)
+ selecting sample files for sampler plugins (for instance samplv1, drumkv1)
+ etc.

I had no time to think a good solution including a consistent workflow.

**Comment by riban-bw** [comment]
The audio player engine was abridge only on my system as a partially developed prototype. I have now developed this into a fully featured engine which uses banks too access folders and presets to access files.
