### ISSUE TITLE
Replacing synth sometimes does not route audio or MIDI

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#653]
**Describe the bug**
When replacing an existing engine within a chain the audio and MIDI is sometimes not routed for the new engine.

**To Reproduce**
1. Add PianoTeq on channel 1
2. From chain option menu, replace with PianoTeq LV2

**Expected behaviour**
Engine is replaced and routing re-established.

**Actual behaviour**
Engine is replaced but not routed.

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/165628584-063a0de1-919d-40da-a3d6-57e56ef7fb22.png)

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: [HifiBerry DAC+ ADC PRO](http://192.168.8.230/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.8.230/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.8.230/hw-wiring)
I2C: [MCP23017@0x20](http://192.168.8.230/hw-wiring)
Profile: [z2_v1](http://192.168.8.230/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 62% (581M/923M)
SD Card: 60% (16G/29G)
Temperature: 51.5ºC
Overclock: [Disabled](http://192.168.8.230/hw-options)
- MIDI
Profile: [default.sh](http://192.168.8.230/ui-midi-options)
Tuning: [440 Hz](http://192.168.8.230/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.8.230/ui-midi-options)
ZS3 Sub-SnapShots: [Off](http://192.168.8.230/ui-midi-options)
MIDI to Output: [On](http://192.168.8.230/ui-midi-options)
Master Channel: [off](http://192.168.8.230/ui-midi-options)
- SOFTWARE
zyncoder: [testing (e236925)](https://github.com/zynthian/zyncoder/commit/e2369251a5456539c8d79e218c8e096accfe0f54)
zynthian-ui: [masterfx (b8821b6)](https://github.com/zynthian/zynthian-ui/commit/b8821b6d5e2b0c5ce94afc66b7ed5caccec1fca5)
zynthian-sys: [testing (a5e66e4)](https://github.com/zynthian/zynthian-sys/commit/a5e66e4a9119d6ad2504bf78f774fcf33eb4d2fa)
zynthian-data: [testing (10e1f9f)](https://github.com/zynthian/zynthian-data/commit/10e1f9f0e3da196775bda4b8c6fd54a425c3e65c)
zynthian-webconf: [testing (729cc9b)](https://github.com/zynthian/zynthian-webconf/commit/729cc9b4113fd53cea512709028969d389a7d7af)

**Additional context**
I had Calf Monosynth on channel 1 first then replaced with Pianoteq then enabled Pianoteq LV2 in webconf then replaced with Pianoteq LV2. I have not been able to reproduce on demand so may be some corner case.

**Comment by jofemodo** [comment]
Can you reproduce with other engines?
I found that Pianoteq LV2 doesn't work if VNC is not enabled. Could you check this too?

**Comment by jofemodo** [comment]
I just updated to Pianoteq v7.5.4 (previous fixing a regression bug on the webconf's install panel) and now everything seems to work. And i can't reproduce this issue ;-)

BTW, i've updated the trial install script and the next SD images will include the latest version v7.5.4.

Regards,.

**Comment by riban-bw** [comment]
Have not been able to reproduce this for a while and tested okay in latest testing so closing ticket.
