### ISSUE TITLE
setBfree does not work well with mixer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#656]
**Describe the bug**
Adding a multi-channel setBfree configuration results in a range of issues with the mixer.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add setBfree - Hammond Emulator, MIDI Channel 1, Split Pedals + Lower + Upper, Sine, Blues 1

**Expected behaviour**
SetBfree added as a single or multiple chains with corresponding mixer controls.

**Actual behaviour**
- SetBfree added as a single engine connected to mixer input 3
- Three chains are displayed in the mixer
- Mixer strips 1 & 2 controls have no effect
- Preset selection for Lower and Pedals is not complete
- Adding effect to strip 1 moves the chain to mixer channel 1
- Subsequently adding effect to strip 2 inserts the effect before effect on chain 1

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: z2_v1
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 51% (477M/923M)
SD Card: 60% (16G/29G)
Temperature: 53.7ºC
Overclock: Disabled
- MIDI
Profile: default.sh
Tuning: 440 Hz
Receive Mode: Stage (Omni On)
ZS3 Sub-SnapShots: Off
MIDI to Output: On
Master Channel: off
- SOFTWARE
zyncoder: testing (e236925)
zynthian-ui: testing (5a396b9)
zynthian-sys: testing (15d5d4c)
zynthian-data: testing (10e1f9f)
zynthian-webconf: testing (09fbf91)

**Additional context**
I have not necessarily documented all the side-effects but surfice to say that this is suboptimal behaviour. I don't think it is necessarily any worse than it has historically been so don't think it warrants fixing before 2205 release but we need to consider a solution. Maybe use of LV2 plugin as detailed by baggypants will offer a better implementation.

**Comment by jofemodo** [comment]
The plan for chainification is to flat all engines using several MIDI channels, so, for instance, setBfree engine will use a single mixer strip (it forms a single audio chain) but it would receive (listen to) several MIDI channels. The controllers for the different manuals will be accessible in a unified list of pages. Presets would be engine-wide, but you could have presets that only affect upper manual, etc. Something similar would be done for Aeolus.

Of course, improving the LV2 support for setBfree, as detailed by @baggypants is also an interesting way to follow, but i don't want to remove the standalone engine, as it have a number of advantages for organ players.

Regards,

**Comment by riban-bw** [comment]
This is resolved by chainification (oram).
