### ISSUE TITLE
MIDI learn for Mixer faders.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#661]
**Is your feature request related to a problem? Please describe.**
It is a limitation of control.
The Motor61 vertical sliders and master should operate the zynmixer.

 
![image](https://user-images.githubusercontent.com/79083/168425351-67353efd-787d-4532-94e5-e8aa498977e5.png)

**Describe the solution you'd like**
A mechanism to assign mixer faders in some fashion a'la MIDI learning in the parameters page 

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/79083/168425210-0a856624-ccc3-4dad-8cfb-98764ffb0288.png)
Other MIDI Kontrollers are available.

Seems a sensible control loop to close to allow dynamic management of parameters. Should be embodied into a device description set up.

**Comment by riban-bw** [comment]
Absolutely want to implement this but how to assign? Maybe we should change the learn function to a bold press of Learn so that it may be used in mixer and be consistent across the device. I actually quite like the idea because switching to learn mode feels like a configuration option rather than performance and so should require more assertive action.

**Comment by riban-bw** [comment]
I think this may best be implemented by using zynthian_controller objects for each parameter (fader, mute, solo, etc.) which will take some refactoring. Maybe we should treat the mixer as an immutable layer/chain. This would allow common interface with its output chain as with other chains. (Currently we need to check for main mix output chain any treat differently.) I quite like the idea of the mixer being chain zero. What did your think @jofemodo?

I suggest we defer such change until after next stable release. It would fit nicely into the chainification work planned.

**Comment by wyleu** [comment]
Can I easily implement this by patching a config file for the moment ?

**Comment by riban-bw** [comment]
Easily? No! Mixer is OSC enabled so you could use a MIDI/OSC bridge.

**Comment by riban-bw** [comment]
Something like this: [midi2osc.zip](https://github.com/zynthian/zynthian-issue-tracking/files/8749822/midi2osc.zip)

**Comment by riban-bw** [comment]
MIDI learn implemented for mixer.
