### ISSUE TITLE
Bug: Terminado is missing from image

### ISSUE THREAD

**Issue by Wishy-Thinking** [zynthian/zynthian-issue-tracking#669]
**Describe the bug**
On a newly burned 2022-06-04-zynthianos-testing image, zynthian-webconf service fails to start. `journalctl -u zynthian-webconf` indicates this is due to missing python module terminado.

The source of the issue is probably that the `zynthian-sys/scripts/recipes/install_terminado.sh` script runs ./setup.py, but the Terminado project recently [switched to the flit build backend](https://github.com/jupyter/terminado/commit/bc51dc0960b5aeb831ddab9a2d87b3b7491d3e7f)

I'm not familiar with the reason why the recipe script is used to manually build the module when building the Zynthian image, but I'm able to fix the issue by running `pip3 install terminado`. The zythian-webconf service automatically starts, and I'm able to connect to the web interface and use the terminal.

**To Reproduce**
1. Burn 2022-06-04-zynthianos-testing image to SD card
2. Power on Zynthian
3. Webconf fails to start
4. ssh to Zynthian
5. `journalctl -u zynthian-webconf` reports "ModuleNotFoundError: No module named 'terminado'"

**Expected behavior**
Webconf starts and web interface is accessible.

**Setup:**
 - SD-image: 2022-06-04-zynthianos-testing
 - Hardware Config: Custom
 - Software Version: Testing from 2022-06-04

**Comment by Wishy-Thinking** [comment]
Use `pip3 install terminado==0.13.3` to avoid updating tornado, which is pinned at version 4.1 in the setup scripts.

**Comment by riban-bw** [comment]
Still missing in testing image 2202-08-30.

**Comment by riban-bw** [comment]
Now installed in staging image.
