### ISSUE TITLE
Wrong knob allocation on Note Range & Transpose page

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#680]
**Description**
On the Note Range and Transpose page, two of the knobs are swapped, so that the left key range is governed by the learn/shot knob (upper right) and the octave transpose is governed by the back knob (lower left).

**To Reproduce**
1. Go to Note Range and Transpose page
2. Attempt to change the octave transpose and/or left key range using the associated knobs
(Using the touch screen works fine for octave transpose; key range appears not to be adjustable using the touch screen)

**Expected behavior**
Upper right knob controls octave transpose and lower left knob controls left key range.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO]
Display: [ZynScreen 3.5 (v1)]
Wiring: [MCP23017_ZynScreen]
I2C: [MCP23017@0x20, MCP23008@0x21, ADS1115@0x48, MCP4728@0x61]

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-25
Memory: 11% (429M/3839M)
SD Card: 42% (12G/29G)
Temperature: 39.4ºC
Overclock: [Disabled]

MIDI
Profile: [default.sh]
Tuning: [440 Hz]
Receive Mode: [Stage (Omni On)]
ZS3 Sub-SnapShots: [On]
MIDI to Output: [On]
Master Channel: [off]

SOFTWARE
zyncoder: testing (c0338cc)
zynthian-ui: testing (3102b0f)
zynthian-sys: testing (410875b)
zynthian-data: testing (cc6a503)
zynthian-webconf: testing (706d78d)

**Additional context**
I've not downloaded a fresh SD image, but rather done upgrades from time to time.

**Comment by riban-bw** [comment]
Fixed in testing and next stable release candidate.

**Comment by polluxsynth** [comment]
FWIW, upgraded to the latest testing and verified that it's now working as expected.
