### ISSUE TITLE
Helm portamento has wrong type of controller

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#705]
**Is your feature request related to a problem? Please describe.**
Helm portamento_type should probably be a list. It is currently a float. Also Portamento is probably time so the label / value should represent this.

**Describe the solution you'd like**
Add a list for the options available for portamento type.
Show portamento value scaled to suit its actual units.

**Describe alternatives you've considered**
None

**Additional context**
May be able to do this by customising the ttl.

**Comment by jofemodo** [comment]
This is adressed  by https://github.com/zynthian/zynthian-issue-tracking/issues/706. 
Customized TTLs allow these 3 things, among others:

+ Rename control paramaters
+ Group control parameters
+ Add ticks/labels to control parameters

Regards

**Comment by riban-bw** [comment]
I am working on improvements to Helm parameters. I will close this issue and update #706.
