### ISSUE TITLE
Move audio levels to admin menu

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#720]
**Is your feature request related to a problem? Please describe.**
The audio levels view allows configuration of soundcard parameters including input / output gain, control switches, etc. This used to be the main mechanism for setting input and output level but since the mixer implementation the audio levels view has become a configuration tool rather than an artistic workflow tool.

**Describe the solution you'd like**
Move access to the audio levels view to be within the admin menu. This makes the main menu cleaner. Consider renaming to avoid the use of "mixer" which may be confused with the mixer module and view.

**Describe alternatives you've considered**
Leave it where it is. I don't think it fits there and can confuse users looking for artistic modules

**Additional context**
We may wish to consider reviewing implementation. It currently uses an engine. We may wish to implement a more direct access to alsa, e.g. via a dedicated library. But on the other hand, it works.

**Comment by jofemodo** [comment]
Accessing ALSA mixer is complex and documentation is poor. When i tried, i couldn't find a decent library that fullfilled our needs, so i decided to use the CLI interface. Of course, accessing the ALSA API directly or via library would be much better.

**Comment by jofemodo** [comment]
Regarding moving the audio levels to Admin. I'm not sure it's a good decission. Tweaking the audio levels is something you want to be fast and accessible. I think it's important enough to be in the main menu. Think about it. In your PC you are one-click from accessing the "audio mixer". Zynthian is a dedicated audio computer, so accessing this functionality shouldn't be hidden in the admin menu.

**Comment by riban-bw** [comment]
I would expect a user to configure their musical device's core audio once when they set it up then not revisit unless they have some change in their physical setup. It feels like a configuration tool in the main menu but if you think it belongs then we can leave it.

You will notice I recently tweaked the titled separators in the menus. Maybe ALSA control can go down to the "SYSTEM" section. It is currently in the "APPS" section.

**Comment by jofemodo** [comment]
I think it's right in the main menu, I will close this.
