### ISSUE TITLE
Improve sequencer playmode symbols

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#729]
**Is your feature request related to a problem? Please describe.**
Sequencer play mode is indicated by icons, some of which not descriptive nor correct, e.g. loop should show that loop can stop during loop, not carry on afterwards.

**Describe the solution you'd like**
Change the icons to better represent each mode.

**Additional context**
Modes are:
- DISABLED
- ONESHOT plays once but stops immediately on request 
- LOOP repeats playback but stops on request at next sync point (e.g. bar boundary) 
- ONESHOTALL plays once, always playing to end of sequence 
- LOOPALL repeats playback, stopping at end of sequence after request to stop

**Comment by jofemodo** [comment]
This is already done!
