### ISSUE TITLE
Selecting Z2 kit in webconf breaks V4 device

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#734]
**Describe the bug**
Selecting kit Z2 in webconf will break an V4, Zynthian will not boot to a network reachable OS. User must remove microSD and change settings manually or re-flash image.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to webconf HARDWARE->Kit
2. Select Z2
3. Save and reboot

**Expected behaviour**
Zynthian reboots with Z2 display or maybe doesn't start fully if config needs further tweaks.

**Actual behaviour**
Zynthian fails to boot to an OS with working network. 

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: ZynADAC
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20, MCP23008@0x21, ADS1115@0x48, MCP4728@0x60
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 6% (126M/1872M)
SD Card: 70% (19G/29G)
Temperature: 61.8ºC
Overclock: Medium
USB Storage: 5% (9.7G/235G)
- MIDI
Profile: default.sh
Tuning: 440 Hz
Receive Mode: Stage (Omni On)
ZS3 Sub-SnapShots: On
MIDI to Output: On
Master Channel: 16
- SOFTWARE
zyncoder: testing (6eb5496)
zynthian-ui: testing (68c0485)
zynthian-sys: testing (af606bf)
zynthian-data: testing (45b44f9)
zynthian-webconf: testing (706d78d)

**Additional context**
I performed this test during last development cycle. Due to the adverse impact and effort required to recover I have not repeated the test.

**Comment by jofemodo** [comment]
This is solved for sure!
