### ISSUE TITLE
terminado not installed in testing image

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#735]
**Describe the bug**
Testing image https://os.zynthian.org/test/2022-08-24-zynthianos-testing.zip does not have terminado installed and hence webconf refuses to start.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download image https://os.zynthian.org/test/2022-08-24-zynthianos-testing.zip
2. Flash to microSD
3. Boot Zynthian with this image
4. Connect to webconf

**Expected behaviour**
Webconf is running.

**Actual behaviour**
Webconf is not running.

**Additional context**
Reported by Tabula on forum. Manually installing terminado with pip3 resolved the issue. I observe that terminado is also available via deb package from standard repositories.

**Comment by jofemodo** [comment]
Terminado is installed in the scripts. This error is probably spurious. Anyway, i will test again with the latest testing image;-)

**Comment by riban-bw** [comment]
It seemed to be repeatable by the reporter. Let's validate with the release (candidate) images.

**Comment by riban-bw** [comment]
Duplicate of #669. It looks like this has been an issue for a while. See the comment in #669 which may give a clue as to the problem / solution.
