### ISSUE TITLE
mod-ui is not working in latest generated testing images

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#738]
mod-ui is not working in latest generated testing images:

https://os.zynthian.org/test/

The problem is that latest versions of mod-host doesn't work with currently used jackd version (1.9.14) and it needs a recent version. Installing a more recent version of jackd results in zynthian's UI segfaulting all the time, so **we have a real problem here!**

**Comment by jofemodo** [comment]
From my POV we have 2 options here:

+ Stick to a mod-ui version that works with current jackd
+ Solve the real problem: recent versions of jackd cause zynthian-ui to segfault

Regards,

**Comment by riban-bw** [comment]
I suggest we stick to a working version of mod-ui for the next release of zynthian then investigate why zynthian is failing with later version of jackd in the next development cycle. It may be beneficial to reconsider the audio layer with the option to move to pipewire or update to later version of jackd.

**Comment by riban-bw** [comment]
This seems to be working now. Can we close this issue?

**Comment by jofemodo** [comment]
Workaround: Set mod-host repo to a working position that doesn't need Jackd's JackTickDouble.

git checkout 0d1cb5484f5432cdf7fa297e0bfcc353d8a47e6b

**Comment by jofemodo** [comment]
> This seems to be working now. Can we close this issue?

I just fixed, so i don't think it could work in an updated system until now.

**Comment by jofemodo** [comment]
It works now, but real problem is still there. We can't update no latest jackd because UI segfaults.

**Comment by riban-bw** [comment]
Shall we close this issue? Mod-ui now works, even if it is stuck at an older version. The issue title describes an issue that is now resolved.
