### ISSUE TITLE
On Testing MIDI LOG generates X-run's and errors in log.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#739]
**Describe the bug**
Select MIDI Log in Webconf, errors are generated in journalctl -f and X-runs appear on GUI.

**To Reproduce**
1. Go to MIDI Log
2. Play MIDI notes on keyboard
3. See error

**Expected behavior**
MIDI Log should be the canonical representation, and provide an accurate representation of the zynthian's interpretation of MIDI details at many point in the chain.

It doesn't work at the moment for me.

**Screenshots**
![image](https://user-images.githubusercontent.com/79083/187032218-6d5a21c1-ee7e-412c-bcb8-9f93085be846.png)

**Additional context**
[midi_log2.txt](https://github.com/zynthian/zynthian-issue-tracking/files/9438063/midi_log2.txt)
[midi_log.txt](https://github.com/zynthian/zynthian-issue-tracking/files/9438064/midi_log.txt)

**Comment by wyleu** [comment]
Partial workaround use qmidinet to pipe MIDI to external machine and run aseqdump there....

![image](https://user-images.githubusercontent.com/79083/187033722-0f508ead-d5ee-4138-995b-e662aae6e40c.png)

**Comment by riban-bw** [comment]
Another workaround is to install and run gmidimonitor in a VNC view on the Zynthian.

**Comment by wyleu** [comment]
Where do you get that...?

**Comment by riban-bw** [comment]
Oops! Typo! 

`apt install gmidimonitor`

**Comment by wyleu** [comment]
Anyone else seen this is or is it a wyleu only phenomena?

**Comment by riban-bw** [comment]
I am not seeing this issue. If I load "FluidR3 GM" snapshot to populate 15 chains, replace first chain with Pianoteq, open webconf MIDI log then play some pianoteq notes I do not see xruns. Not even if I play "Take 5" SMF to exercise many chains. (I see one xrun at start/end of SMF during loop play but that is another issue.)

Do you see this immediately after opening MIDI log or must you wait some time. Are there other elements affecting this? Could your device be on the edge (power, heat, etc.)?

**Comment by wyleu** [comment]
Well it's working now ...
![zynthian_midi_log](https://user-images.githubusercontent.com/79083/198269467-e87af000-4bd6-4015-bd91-3a80b74438f8.png)

Give me a chance to run it across the family.
