### ISSUE TITLE
Access to Audio-FX presets

### ISSUE THREAD

**Issue by TabulaNul** [zynthian/zynthian-issue-tracking#740]
**Is your feature request related to a problem? Please describe.**
We can access to the presets when you start with an audio chain or a synth chain.
But when we insert an audio effect after an existing engine (Synth Chain or Audio Chain), you can't access the presets.

**Describe the solution you'd like**
In the "Chain Option>Audio FX Options" submenu, we should add other entries next to "Replace" and "Remove", we should add "Presets", to be able to access the presets, and "Save Preset", to be able to save them

**Describe alternatives you've considered**
none

**Comment by riban-bw** [comment]
I think the workflow should be that selecting a page of parameters in the control view then pressing BACK to access presets should show the list of presets for the appropriate plugin. Currently it always shows the presets for the first (root) engine in the chain.
