### ISSUE TITLE
When creating a MOD-UI layer fails, a ghost layer remains, confusing mixer and layer management

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#745]
**Describe the bug**
When creating a MOD-UI layer fails, a ghost layer remains, confusing mixer and layer management. It seems to recycle some data from recently deleted layers.

**To Reproduce**
1. Create a mod-ui layer. As mod-ui is currently broken, it will fail
2. Wait until it fails and see the result

**Expected behavior**
It should fail without creating any ghost layer. An error message should be nice, but this whould be addressed in a different ticket.

**Setup:**
 - Z2 prototype
 - latest testing branch

**Additional context**
Sep 03 15:29:02 z2-01 startx[3343]: ERROR:zynthian_engine_modui.api_post_request: POST call to MOD-UI API: 500 => http://localhost:8888/jack/set_midi_devices
Sep 03 15:29:02 z2-01 startx[3343]: ERROR:zynthian_gui_layer.add_layer_midich: maximum recursion depth exceeded in comparison
Sep 03 15:33:32 z2-01 startx[3343]: ERROR:zynthian_engine_modui.task_websocket: Connection Closed & MOD-UI stopped. Finishing...

**Comment by riban-bw** [comment]
This may be related to the chain management mods I am working on. I will investigate.

**Comment by jofemodo** [comment]
What "chain management" mods?

**Comment by jofemodo** [comment]
It seems to be solved after latest changes.
