### ISSUE TITLE
Headphone level forgotten after restart

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#750]
**Describe the bug**
There is a Headphones level setting in the Audio Levels first page for Z2. This resets to zero after reboot or restart. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Set headphone audio level to 7
2. Reboot

**Expected behaviour**
Headphone level set to previous value.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://zynthian/hw-audio)
Display: [Z2 Display](http://zynthian/hw-display)
Wiring: [Z2_V3](http://zynthian/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://zynthian/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-09-18
Memory: 4% (156M/3839M)
SD Card: 39% (11G/29G)
Temperature: 43.8ºC
Overclock: [Maximum](http://zynthian/hw-options)
- MIDI
Profile: [default.sh](http://zynthian/ui-midi-options)
Tuning: [440 Hz](http://zynthian/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://zynthian/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://zynthian/ui-midi-options)
MIDI to Output: [On](http://zynthian/ui-midi-options)
Master Channel: [16](http://zynthian/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2dd7230)](https://github.com/zynthian/zyncoder/commit/2dd7230d19ffec787f8d29deab87982bee446303)
zynthian-ui: [testing (c6533fe)](https://github.com/zynthian/zynthian-ui/commit/c6533fe74b07b53bb3b478547a089384793ca860)
zynthian-sys: [testing (eb2f945)](https://github.com/zynthian/zynthian-sys/commit/eb2f945c0ef3c4c8463a85f7e2c2acf70f5408bb)
zynthian-data: [testing (8ab0438)](https://github.com/zynthian/zynthian-data/commit/8ab04381c46980bb5a4c626d1fe618a52f11b12e)
zynthian-webconf: [testing (544870f)](https://github.com/zynthian/zynthian-webconf/commit/544870fb1efb29dff5487d01721937cc24c0c123)

**Additional context**
This is expected out-of-the-box behaviour.

**Comment by riban-bw** [comment]
Setting "Audio Levels on Snapshots" will implement the desired behaviour. I suggest that users will expect this behaviour out-of-the-box so this option should perhaps be enabled by default.

Changing "Audio Levels on Snapshots" in webconf causes Zynthian to restart (which may be undesirable and unexpected behaviour) but the volume is not saved to last snapshot so after the restart this issue persists. Users may believe the fix has not been applied.

**Comment by riban-bw** [comment]
As discussed, @jofemodo please set default configuration to save audio levels to snapshot and default headphone level to 7.

**Comment by jofemodo** [comment]
It's fixed! 
https://github.com/zynthian/zynthian-sys/commit/975c1f83b17681f2ddb5128c243c6733e54c19c8
