### ISSUE TITLE
PRESET CUIA seems to work on chain 1 only

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#751]
**Describe the bug**
Configuring a button to trigger "PRESET" CUIA seems to always jump to chain 1, not the currently selected chain.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add several synth chains
2. Configure a button to trigger CUIA PRESET, e.g. Z2 V3 layout
3. Select chain 2 in the mixer view
4. Press button

**Expected behaviour**
Chain 2 preset view displayed.

**Actual behaviour**
Chain 1 preset view displayed.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://zynthian/hw-audio)
Display: [Z2 Display](http://zynthian/hw-display)
Wiring: [Z2_V3](http://zynthian/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://zynthian/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-09-18
Memory: 4% (156M/3839M)
SD Card: 39% (11G/29G)
Temperature: 43.8ºC
Overclock: [Maximum](http://zynthian/hw-options)
- MIDI
Profile: [default.sh](http://zynthian/ui-midi-options)
Tuning: [440 Hz](http://zynthian/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://zynthian/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://zynthian/ui-midi-options)
MIDI to Output: [On](http://zynthian/ui-midi-options)
Master Channel: [16](http://zynthian/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2dd7230)](https://github.com/zynthian/zyncoder/commit/2dd7230d19ffec787f8d29deab87982bee446303)
zynthian-ui: [testing (c6533fe)](https://github.com/zynthian/zynthian-ui/commit/c6533fe74b07b53bb3b478547a089384793ca860)
zynthian-sys: [testing (eb2f945)](https://github.com/zynthian/zynthian-sys/commit/eb2f945c0ef3c4c8463a85f7e2c2acf70f5408bb)
zynthian-data: [testing (8ab0438)](https://github.com/zynthian/zynthian-data/commit/8ab04381c46980bb5a4c626d1fe618a52f11b12e)
zynthian-webconf: [testing (544870f)](https://github.com/zynthian/zynthian-webconf/commit/544870fb1efb29dff5487d01721937cc24c0c123)

**Additional context**
Sometimes nothing happens. I think before the preset screen has been displayed for the first time.

**Comment by riban-bw** [comment]
It seems to show the preset screen that was last shown, e.g. If chain 1 preset list was last viewed then pressing switch on any chain will show chain 1. If chain 2 preset list was last viewed then pressing switch on any chain will show chain 2. If no preset list has been shown then pressing the switch appears to do nothing.

**Comment by jofemodo** [comment]
Sorry Brian, i can't reproduce this issue in my Z2. Could you re-confirm and try to add more context info?

**Comment by riban-bw** [comment]
I can't get button 1 to trigger any UI actions now. If I configure button 1 to trigger "UI Action Release" with short-press triggering "Screen Preset" (or "Screen Stepseq") the button seems to do nothing.

**Comment by jofemodo** [comment]
This is too old!
