### ISSUE TITLE
No connection between Zynthian Mixer and OSC application - Testing Version

### ISSUE THREAD

**Issue by ToFFmashines** [zynthian/zynthian-issue-tracking#753]
Unable to connect Zynthian Mixer with OSC application.
zynthian-ui: testing (c6533fe)

From OSC client ( on Open stage control) is sending message for connection with Zynthian
(DEBUG, OSC) Out:  { address: '/mixer/heartbeat', args: [ { type: 's', value: '' } ] } To: 192.XXX.YYY.TTT:1370

From UIlog
Sep 19 17:57:47 zynthian startx[3243]: INFO:zynthian_gui.osc_cb_all: OSC MESSAGE '/mixer/heartbeat' from 'osc.udp://192.XXX.YYY.ZZZ:8080/'
Sep 19 17:57:47 zynthian startx[3243]: WARNING:zynthian_gui.osc_cb_all: Failed to add OSC client registration 192..XXX.YYY.ZZZ

I have the interface ready for the mixer, but I lack proper communication between Zynthian and the Open Stage Control server/client
![picture-4](https://user-images.githubusercontent.com/75641620/191074500-b444e232-807f-4535-9474-cb05cab7603e.jpg)

**Comment by jofemodo** [comment]
Is this fixed or improved? Some change?

**Comment by ToFFmashines** [comment]
It fixed, I will publish an OSC template in the near future.

**Comment by ToFFmashines** [comment]
template is available on https://discourse.zynthian.org/t/zynthian-osc-cuia-over-open-stage-control-template/7217/5?u=toff
