### ISSUE TITLE
Disable automute

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#755]
**Is your feature request related to a problem? Please describe.**
By default automute is enabled. This can cause clicks and unexpected / undesirable muting / gating.

**Describe the solution you'd like**
Default configuration to disable automute.

**Describe alternatives you've considered**
All users told to disable manually.

**Additional context**
This issue was reported in the forum and a fix was to disable ALSA mixer auto mute feature.

**Comment by jofemodo** [comment]
It's solved too.

**Comment by jofemodo** [comment]
https://github.com/zynthian/zynthian-sys/commit/a6e0e9c42b09bf312c12ae1ca9fef38d1e806182
