### ISSUE TITLE
Set headphone level to sensible level by default

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#758]
**Is your feature request related to a problem? Please describe.**
A fresh install of Zynthian sets the headphone level to 0. This is very quiet and results in most users having to increase this.

**Describe the solution you'd like**
It may be advantageous to set the default headphone level to mid-point, e.g. 7.

**Describe alternatives you've considered**
Whisper so you can hear the output.

**Additional context**
I think this probably only impacts Z2 which has a dedicated headphone amplifier.

**Comment by jofemodo** [comment]
It's solved!
