### ISSUE TITLE
Wrong path shown for some FluidSynth voices

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#764]
**Describe the bug**
The topstrap shows the _path_ which includes the MIDI channel, engine, bank and preset. Sometimes this is incorrect.

**To Reproduce**
Steps to reproduce the behaviour:
I haven't figured out how to reliably reproduce but it has occurred several times.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-09-25
Memory: 19% (743M/3838M)
SD Card: 41% (12G/29G)
Temperature: 44.3ºC
Overclock: [Maximum](http://z2/hw-options)
USB Storage: [62% (1.2G/1.9G)](http://z2/lib-captures)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [off](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [staging-2209 (2dd7230)](https://github.com/zynthian/zyncoder/commit/2dd7230d19ffec787f8d29deab87982bee446303)
zynthian-ui: [testing (8414371)](https://github.com/zynthian/zynthian-ui/commit/841437192768704c37471d91ad6209d4d484a0ed)
zynthian-sys: [staging-2209 (de806bf)](https://github.com/zynthian/zynthian-sys/commit/de806bfe30e5b73f6612907ae10cfc43784180e6)
zynthian-data: [staging-2209 (9669355)](https://github.com/zynthian/zynthian-data/commit/96693558a2bfb639638613f8113463b690cb7668)
zynthian-webconf: [staging-2209 (443b323)](https://github.com/zynthian/zynthian-webconf/commit/443b323e2d7766d283f50cc1eb85b0adeaa921cf)

**Additional context**
The last time this occurred the display showed "6#FluidSynth > Acoustic Guitars/SFX". SFX is in AirFont320. These two soundfonts are adjacent. I did not have any Acoustic Guitar patches loaded.

**Comment by jofemodo** [comment]
Could it be related to favorites?

**Comment by riban-bw** [comment]
I am fairly sure favourites were not involved during this.

**Comment by jofemodo** [comment]
I can't reproduce, sorry. Well, i don't know what/how to reproduce ...
