### ISSUE TITLE
Duplicate MOD-UI Pedals of same type not listing in ZynGUI

### ISSUE THREAD

**Issue by Jimi-Heinrich** [zynthian/zynthian-issue-tracking#765]
**Describe the bug**
Duplicate MOD-UI Pedals of same type not listing in ZynGUI

**To Reproduce**
1. In MOD-UI place two pedals of the same kind, e.g. "Crossfade"

**Expected behavior**
In ZynGUI you should be able to address both seperatly, but you can't. Only *one* of them shows up.

**Screenshots**
![Bildschirmfoto 2022-10-02 um 09 18 49](https://user-images.githubusercontent.com/60140248/193444877-3fd65270-af71-4fd9-97c2-efde52d337d9.png)

![Bildschirmfoto 2022-10-02 um 09 19 37](https://user-images.githubusercontent.com/60140248/193444903-37bfabb8-bb54-41c2-811c-2f18654f4ec5.png)

**Setup:**
Raspbian GNU/Linux 10 (buster) 
Build Date: 2020-09-05 
Memory: 2% (217M/7899M) 

zyncoder: stable (7c09738) 
zynthian-ui: stable (30294c8) 
zynthian-sys: stable (0bd40a7) 
zynthian-data: stable (82571e7) 
zynthian-webconf: stable (7961552)

Raspberry Pi 4 Model B Rev 1.4 
Soundcard: HifiBerry DAC+ ADC PRO 
Display: ZynScreen 3.5 (v1) 
Wiring: MCP23017_ZynScreen 
GPIO Expander: MCP23017

**Comment by jofemodo** [comment]
This is fixed!
