### ISSUE TITLE
Limit USB speed to 12Mb/s: option prevents mouse working.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#77]
**Describe the bug**
Turning on the Limit USB speed to 12Mb/s: option in audio prevents mouse functionality.

**To Reproduce**
1. Check operation of mouse with zynthian with cursor on.
2. Select Limit USB speed to 12Mb/s: option in Audio
3. Reboot
4. Check mouse operation

**Expected behavior**
A mouse should still function and multiple instances of USB keyboards should be operational with the Select Limit USB speed to 12Mb/s: option in Audio selected 

HARDWARE
Raspberry Pi 3 Model B Rev 1.2
Soundcard: AudioInjector
Display: Generic HDMI Display
Wiring: DUMMIES
SYSTEM
Hostname: zynthian (192.168.1.9 )
OS: Raspbian GNU/Linux 10 (buster)
Memory: 13% (125M/926M)
SD Card: 38% (11G/29G)
MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
QmidiNet: False
TouchOSC: False
SOFTWARE
zyncoder: master (f01eb07)
zynthian-ui: master (d82d176)
zynthian-sys: master (011666c)
zynthian-data: master (c8d15e7)
zynthian-webconf: master (21a234a)
LIBRARY
Snapshots: 0
User Presets: 8
User Soundfonts: 0
Audio Captures: 0
MIDI Captures: 0

**Comment by jofemodo** [comment]
I just confirmed this. Really curious ... and quite annoying, BTW! ;-(
Probably RBPi4 don't have this problem because you don't need to use the USB-speed-limit flag.
I will do my research ...

**Comment by Baggypants** [comment]
Mice typically try to auto-negotiate to USB 1.0 @1.5MB/s speed. As opposed to the more common 1.1 @12MB/s

**Comment by Baggypants** [comment]
You can blame Microsoft. https://www.fastcompany.com/3060705/an-oral-history-of-the-usb

**Comment by wyleu** [comment]
This makes Pi3 self builds a real pain to configure . . . (sorry)

**Comment by wyleu** [comment]
Is this fixed?   I'm running zynthian-ceedl.local with a mouse and 12Mbits on & I'm not getting stuck notes as far as I can see. ... Ill try it with another keyboard connected....

**Comment by jofemodo** [comment]
I didn't change anything regarding this. I will try to see if it's solved (perhaps a rbpi's firmware update?)

**Comment by wyleu** [comment]
No longer need to select 12Mbits option and it seems to be working with multiple USB midi connections (Motor 61 + USB Midi connection) & a mouse.

**Comment by wyleu** [comment]
Well either with 12M/bit option selected or not I don't seem to get stuck notes and the mouse works so let's assume the gods of Pi have modified something deep in the guts that makes it all well. 

Closed

**Comment by smiths73v3** [comment]
I encountered this issue, but no longer have problems on RPi4 since it does not require 12M/bit. The research I did seemed to indicate this was deep in the USB driver, and you have an either/or problem here. I think this issue should be "do not fix"
