### ISSUE TITLE
Staging-2210: some UI options in webconf don't work

### ISSUE THREAD

**Issue by le51** [zynthian/zynthian-issue-tracking#771]
**Describe the bug**
some UI options in webconf don't work:

**To Reproduce**
* Enable Onscreen Buttons: checking the box => no buttons
* Enable cursor: disabling has no effect, cursor still there

**Setup:**
 - SD-image: staging-2210
 - Hardware Config: Custom, 5inch DSI touch display 800x480
 - Software Version: Zynthian-UI [(84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)

**Comment by le51** [comment]
https://discourse.zynthian.org/t/new-stable-version-is-almost-here-staging-2210/7269/12?u=le51

I've just seen this, so it's normal and new behaviour with touchscreen buttons

**Comment by riban-bw** [comment]
As you have observed, onscreen button behaviour has changed and is working by design, i.e. buttons only appear when necessary.

Cursor is showing and hiding as per configuration. I cannot see an issue with the cursor.
