### ISSUE TITLE
[SooperLooper] Selecting Loop and Mixing

### ISSUE THREAD

**Issue by TabulaNul** [zynthian/zynthian-issue-tracking#772]
**Is your feature request related to a problem? Please describe.**
After recording loops, I often want to mix the loops. My fingers are too big to tweak with gui widgets, and the "Wet volume" widget in too close to the limit of the screen, i cannot play with it.
"Selected loop" and "Wet volume" in the same menu page would be more efficient

**Describe the solution you'd like**
In "Levels 1" we can replace "Threshold" by "selected loop"
In the "Levels 2" Menu page, there is one place left, we can add "Wet Volume" there. 
Or redesign the Menu Pages.

**Describe alternatives you've considered**
Redesign the Gui widgets : Bigger button for MUTE, RECORD, SELECTING LOOP, WET VOLUME (the screen is not very precise), delete some.
Move "Wet volume", it is too close to the limit of the screen, we cannot interact precisely with it.

**Additional context**
a crappy jpeg example, sorry for the poor quality
![crappy](https://user-images.githubusercontent.com/77055912/194722781-5813bd87-adb9-4981-a1af-5a48546605e9.jpg)

Raspberry Pi 4 Model B Rev 1.2
Audio: [HifiBerry DAC+ ADC PRO]
Display: [ZynScreen 3.5 (v1)
Wiring: [MCP23017_ZynScreen]
I2C: [MCP23017@0x20]

**Comment by riban-bw** [comment]
I would like to consider a variety of workflows before making changes. We should aspire for optimal UI for the most common workflows.

**Comment by TabulaNul** [comment]
I totally agree, the actual sooperlooper widget is already efficient for most uses. And before changing anything, we need to know which workflow is best for everyone.
But changing control settings, to interact in the same time with "selected loop" and "wet" (the volume of each loop) is a tiny change, and I think it could be appreciate. My Zynthian screen isn't accurate enough to effectively select loops, and turn down the volume.

**Comment by Baggypants** [comment]
I use a Nintendo DS stylus to manipulate the SooperLooper screen, that helps a lot.

**Comment by riban-bw** [comment]
The pages have changed since this report but there was still a spare slot on the levels page so I added a loop select controller. This is duplicated on the next page, "Global Loop". I also fixed some issues with loop selection so this should now be resolved.

Fix commited to vangelis (testing) ready for next point release.
