### ISSUE TITLE
Error 500 when trying to access backup/restore via webconf

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#775]
**Describe the bug**
Attempts to access the backup / restore page on webconf result in an error "500: Internal Server Error" in the web browser.

**To Reproduce**
Steps to reproduce the behaviour:
1. Within webconf navigate to SYSTEM->Backup / Restore

**Expected behaviour**
Backup / Restore page shows.

**Actual behaviour**
500: Internal Server Error shown in web browser.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 23% (899M/3838M)
SD Card: 45% (12G/29G)
Temperature: 44.3ºC
Overclock: [Maximum](http://z2/hw-options)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2f62d59)](https://github.com/zynthian/zyncoder/commit/2f62d59b8a88b5309246b63af3679309ca3428bf)
zynthian-ui: [testing (b73169e)](https://github.com/zynthian/zynthian-ui/commit/b73169ea252e084c9f2009634f8b886f846b89ce)
zynthian-sys: [testing (84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)
zynthian-data: [testing (21d0966)](https://github.com/zynthian/zynthian-data/commit/21d0966a438b1e437b84f053a8f5b3e733d11484)
zynthian-webconf: [testing (0214bd2)](https://github.com/zynthian/zynthian-webconf/commit/0214bd2f24018514e09ecbdd3c24bac5cc0177f7)

**Additional context**
webconf logs:

```
ERROR:tornado.application:Uncaught exception GET /sys-backup (192.168.1.168)
HTTPServerRequest(protocol='http', host='z2', method='GET', uri='/sys-backup', version='HTTP/1.1', remote_ip='192.168.1.168', headers={'Host': 'z2', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (X11; CrOS aarch64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'Referer': 'http://z2/', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8', 'Cookie': 'advanced_view=1; user="2|1:0|10:1665124656|4:user|8:cm9vdA==|eb0e02172ffc9557f3cd1b671589df3088496489faf95ffa5be1056dc78c1067"'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 2626, in wrapper
    return method(self, *args, **kwargs)
  File "/home/pi/zynthian-webconf/lib/system_backup_handler.py", line 57, in get
    self.do_get("BACKUP/RESTORE", errors)
  File "/home/pi/zynthian-webconf/lib/system_backup_handler.py", line 73, in do_get
    config_backup_items = get_backup_items(SystemBackupHandler.CONFIG_BACKUP_ITEMS_FILE)
  File "/home/pi/zynthian-webconf/lib/system_backup_handler.py", line 41, in get_backup_items
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/zynthian/config/config_backup_items.txt'
ERROR:tornado.access:500 GET /sys-backup (192.168.1.168) 141.26ms
```

**Comment by riban-bw** [comment]
I added some error handling to allow the page to be shown but it looks like the configuration file that specifies the files to backup is missing from the latest image.

**Comment by riban-bw** [comment]
@jofemodo I think maybe an update script may not be working as expected? There are copies of these files in /zynthian/zynthian-sys/config so maybe they are supposed to be copied to /zynthian/config during first boot?

**Comment by Baggypants** [comment]
A symlink fixes it.

**Comment by jofemodo** [comment]
Is this fixed by https://github.com/zynthian/zynthian-webconf/commit/b3cdde1083cd9a83632c7d44ff031d9b569b93b7?
Please confirm.

**Comment by jofemodo** [comment]
I think it's fixed now.
