### ISSUE TITLE
Modulation wheel does not work after changing MIDI channel

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#776]
**Describe the bug**
If Calf Monosynth is running on a MIDI channel other than channel 1, modulation wheel CC1 is not detected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Calf Monosynth with MIDI channel 2
2. Send CC1 messages on channel 2 (or any if set to stage mode) 

**Expected behaviour**
Modulation wheel controller on MIDI Controllers page changes value and sound modulated.

**Expected behaviour**
No changes evident.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 6% (236M/3838M)
SD Card: 45% (13G/29G)
Temperature: 44.8ºC
Overclock: [Maximum](http://z2/hw-options)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2f62d59)](https://github.com/zynthian/zyncoder/commit/2f62d59b8a88b5309246b63af3679309ca3428bf)
zynthian-ui: [testing (b05eb40)](https://github.com/zynthian/zynthian-ui/commit/b05eb402a8c9771dfb84eacc1811be7234b48cba)
zynthian-sys: [testing (84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)
zynthian-data: [testing (21d0966)](https://github.com/zynthian/zynthian-data/commit/21d0966a438b1e437b84f053a8f5b3e733d11484)
zynthian-webconf: [staging-2210 (b3cdde1)](https://github.com/zynthian/zynthian-webconf/commit/b3cdde1083cd9a83632c7d44ff031d9b569b93b7)

**Additional context**
There is a "MIDI Channel" controller which will limit reception to the specified channel with 0 appearing to be omni but this does not seem to help and also seems to be offset by 1, i.e. passes MIDI channel 2 when 1 is selected.
Other synths do respond to CC1 when on other MIDI channels so it appears to be an issue with Calf Monosynth (rather than a Zynthian module).

**Comment by riban-bw** [comment]
Upstream source code is at https://github.com/calf-studio-gear/calf/blob/master/src/monosynth.cpp. The relevant section of code is at https://github.com/calf-studio-gear/calf/blob/master/src/monosynth.cpp#L735 - monosynth_audio_module::control_change(). This has a flaw in its MIDI channel detection.

If its MIDI channel parameter is set to zero then it processes the CC (omni-mode). If set to a higher value it checks the incoming MIDI has the same channel then processes the CC. This means that you can't set to only listen to channel 0. That is fine for Zynthian that benefits from an engine listening in omni mode as Zynthian only sends relevant messages to each engine. This doesn't explain why CC is being ignored for non-zero (1) MIDI channel.

**Comment by riban-bw** [comment]
Ignore the upstream issue (which I will report separately). The problem here only occurs after changing MIDI channel of a chain within Zynthian.

- Add synth chain with channel 1
- Change MIDI channel
- CC1 stops working

**Comment by jofemodo** [comment]
Fixed by https://github.com/zynthian/zynthian-ui/commit/83b65741991037d53eb374d69c1db6469813915c

**Comment by riban-bw** [comment]
This fix breaks some functionality. You can not use an external MIDI controller to adjust parameters of any engines unless they are in the active chain. Example workflow:

- Bass line sequenced on MIDI channel 1
- Live playing on MIDI channel 2
- Adjust filter cutoff of bass line with external MIDI controller

I think a good solution would be to allow MIDI CC to be sent to all chains. When changing a chain's MIDI channel, reassign the channel of the parameters that are still mapped to their default CC.

**Comment by riban-bw** [comment]
Closing this ticket (again) because the implementation is working by design. A (partial) work-around may be to use MIDI cloning. We can revisit behaviour during future architectural changes.
