### ISSUE TITLE
Crash when changing state with switch or knob

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#777]
**Describe the bug**
The UI sometimes crashes when changed by means of a button or encoder.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change state, e.g. show a menu

**Expected behaviour**
State changes.

**Actual  behaviour**
Crash, sometimes associated with "corrupted size vs. prev_size" error.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 5% (220M/3838M)
SD Card: 45% (13G/29G)
Temperature: 44.8ºC
Overclock: [Maximum](http://z2/hw-options)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2f62d59)](https://github.com/zynthian/zyncoder/commit/2f62d59b8a88b5309246b63af3679309ca3428bf)
zynthian-ui: [testing (21ff4ca)](https://github.com/zynthian/zynthian-ui/commit/21ff4cae2e48ae749897a48d65a3f877a3bfc902)
zynthian-sys: [testing (84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)
zynthian-data: [testing (21d0966)](https://github.com/zynthian/zynthian-data/commit/21d0966a438b1e437b84f053a8f5b3e733d11484)
zynthian-webconf: [staging-2210 (b3cdde1)](https://github.com/zynthian/zynthian-webconf/commit/b3cdde1083cd9a83632c7d44ff031d9b569b93b7)

**Additional context**
This seems to be a fairly recent (past couple of months) new issue. I have only seen it occur when using the enoders and switches, not VNC which may point to a zyncore issue.

**Comment by riban-bw** [comment]
This is likely to be one of the c/c++ libraries. I suspect this issue occurred approx. mid-September. (Recorded on 2022-10-03.)  The following libs have been touched since then:

- zyncoder
- zynmixer
- zynseq (I think issue began before these changes)

We should also look at access to c/c++ libs from Python. Changes may have triggered the issue.

**Comment by riban-bw** [comment]
Access to osc_server sometimes occurs after `osc_server.free()` has been called. This sometimes manifests as a warning in the log but it is plausible that this may trigger a memory access issue in the liblo library. Python garbage collector will free resources when the server is de-referenced so `free()` may not be required.

I have commented the `free()` line out to see if this resolves the issue. We should check what is calling the server after it is stopped though - if it gets cleaned up by GC we may still see the issue. Maybe we should explicitly de-reference osc_server, e.g. `self.osc_server = None` which may reduce the risk of it being accessed (unless some thread oddity means the reference remains intact - but one would hope that means GC won't free it).

**Comment by jofemodo** [comment]
Is this fixed?? I think yes ...

**Comment by jofemodo** [comment]
Here:
https://github.com/zynthian/zynthian-ui/commit/6cf59e9dcd5ae8711c7fdc34051888000c143051
and here:
https://github.com/zynthian/zynthian-ui/commit/adda5eb082dce12f8185971369ac240ec435480a

Yes?

**Comment by riban-bw** [comment]
No this is not fixed. I had several occurrences of this crash yesterday. I plan to create versions of the zynthian libraries with debug symbols and attach gdb to the running instance of zynthian_gui in a bid to capture a backtrace. This may also be possible with core dump but I have not yet succeeded in creating one. (Maybe for the same reason that debug symbols are required.)

**Comment by riban-bw** [comment]
I have fixed some potential crashes in the zynthian libraries which _may_ have accounted for this issue. I have not experienced the crash since making these changes so will close the ticket but keep a watchful eye for recurrence or regression.
