### ISSUE TITLE
Stuck notes when adding / playing notes in pattern editor with Calf Monosynth

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#778]
**Describe the bug**
When a note is added to a pattern for Calf Monosynth it gets stuck on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Calf Monosynth to a chain
2. Add a note to a pattern associated with the same MIDI channel

**Expected behaviour**
Note is added and played briefly.

**Actual behaviour**
Note is added and plays continually.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 5% (220M/3838M)
SD Card: 45% (13G/29G)
Temperature: 44.8ºC
Overclock: [Maximum](http://z2/hw-options)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2f62d59)](https://github.com/zynthian/zyncoder/commit/2f62d59b8a88b5309246b63af3679309ca3428bf)
zynthian-ui: [testing (21ff4ca)](https://github.com/zynthian/zynthian-ui/commit/21ff4cae2e48ae749897a48d65a3f877a3bfc902)
zynthian-sys: [testing (84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)
zynthian-data: [testing (21d0966)](https://github.com/zynthian/zynthian-data/commit/21d0966a438b1e437b84f053a8f5b3e733d11484)
zynthian-webconf: [staging-2210 (b3cdde1)](https://github.com/zynthian/zynthian-webconf/commit/b3cdde1083cd9a83632c7d44ff031d9b569b93b7)

**Additional context**
Also happens when note played from pattern editor keyboard. Okay for other instruments so may be an upstream issue but playing notes normally is okay.

**Comment by riban-bw** [comment]
Pattern editor sends note-on with velocity zero for note-off events which may be the cause of this issue.

I just tested and monosynth does not support note-on with velocity 0 for note-off messages.

**Comment by riban-bw** [comment]
I have reported the issue upstream: https://github.com/calf-studio-gear/calf/issues/319.

We could work-around this by sending note-off in the pattern editor.

**Comment by riban-bw** [comment]
This also affects the playback of patterns, i.e. zynseq plays patterns with note-on+vel=0.

**Comment by jofemodo** [comment]
Is it also fixed for SMF  player?
jackd input ports only accept unrolled midi (not running status), The docs say:

**jack_midi_event_write(...)**

_Clients must not write more than data_size bytes into this buffer. Clients must write normalised MIDI data to the port - no running status and no (1-byte) realtime messages interspersed with other messages (realtime messages are fine when they occur on their own, like other messages)._

**Comment by riban-bw** [comment]
It is now!
