### ISSUE TITLE
Can't set UI Action Push actions in webconf

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#779]
**Describe the bug**
Can't set up UI Action Push switches in Customizable Switches in webconf.

**To Reproduce**
- Go to webconf
- Scroll down to Customizable Switches
- Select UI Action Push for an action
- The Push: field is now a text field, whereas in earlier versions it was a dropdown list, where things like 'Arrow left' could  be selected.
- Attempting to enter **Arrow up** in the text field does not bring about the expected action when a button is pushed.

**Expected behavior**
It should be possible to set UI Action Push to Arrow up etc as before.

**Screenshots**
Old webconf (Testing):
![zynthian-switchconf](https://user-images.githubusercontent.com/6740739/196011520-94ecd3a5-a1b4-4306-a682-ab00098ea852.png)
New webconf (Staging-2210):
![zynthian-switches-staging](https://user-images.githubusercontent.com/6740739/196011546-a910763f-678c-4ee3-9fda-2f0cc311c20c.png)

**Setup:**
 - SD-image: Staging-2210
 - Hardware Config
 Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO](http://zynthian.local/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian.local/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian.local/hw-wiring)
I2C: [MCP23017@0x20, MCP23008@0x21, ADS1115@0x48, MCP4728@0x61](http://zynthian.local/hw-wiring)
 - Software Version
zyncoder: staging-2210 (5308a1f)
zynthian-ui: [staging-2210 (b73169e)](https://github.com/zynthian/zynthian-ui/commit/b73169ea252e084c9f2009634f8b886f846b89ce)
zynthian-sys: [staging-2210 (84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)
zynthian-data: [staging-2210 (21d0966)](https://github.com/zynthian/zynthian-data/commit/21d0966a438b1e437b84f053a8f5b3e733d11484)
zynthian-webconf: [staging-2210 (b3cdde1)](https://github.com/zynthian/zynthian-webconf/commit/b3cdde1083cd9a83632c7d44ff031d9b569b93b7)

**Comment by TabulaNul** [comment]
I experimented this issue too. 

The solution I found:
- save your "Customize profiles" twice with a different name to prevent it from disappearing.
- delete profile
- You should see the old webconf behavior

<img width="1139" alt="Capture d’écran 2022-10-17 à 11 17 41" src="https://user-images.githubusercontent.com/77055912/196139794-748438a3-e870-4df0-b13b-d36f957e5522.png">

**Comment by polluxsynth** [comment]
Thanks, I followed your steps, and can confirm that the old drop down boxes returned.

However, after setting up the actions as I wanted, and clicking the black Save bar at the bottom of the page, when the page reloaded, the boxes were again text boxes, albeit filled in with what seems to be the correct strings to set this up (see below). 

I can confirm that the buttons behave as I expect them to given the action settings.

![zynthian-switchconf-workedaround](https://user-images.githubusercontent.com/6740739/196293102-96c7c4bc-32f2-48e9-9672-089d8e0f43c6.png)

**Comment by jofemodo** [comment]
Solved! (not for Z2, @riban)

**Comment by polluxsynth** [comment]
Confirmed.
