### ISSUE TITLE
QMIDInet needs input output selection

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#78]
**Is your feature request related to a problem? Please describe.**
When using multiple qmidinet zynthians loops are created because network input data appears on network output
**Describe the solution you'd like**
The ability to specify a zynthian as Qmidi net input OR output

**Describe alternatives you've considered**
Not really got a fix for this one at the moment

**Additional context**
Multiple zynthian rigs have great potential but this is a limiting element at the moment.

**Comment by jofemodo** [comment]
Currently:
- QMidiNet input data is sent to MIDI-OUT, same than any other MIDI input (MIDI-USB, aubio).
- QMidinet input data is also sent to the engines.
- QMidiNet input data should never appear in QMidiNet output.

I implemented the router mechanism some time ago. If you are experimenting this, then things are not working as expected and we have a "regression".

**Comment by wyleu** [comment]
It's only since I've had three zynth's up and running I'll see if I can pin it down, certainly I've had MIDI howl around...

**Comment by jofemodo** [comment]
Some news/extra info about this, @wyleu ?

**Comment by wyleu** [comment]
Not fired up 3 machines in a while. 
I've got two now with qmidinet turned on on both...
zynthian-amp2.local
4 layers MIDI 1,2,3,4
zynthian-motor.local
2 layers one of which is an effects layer audio input..
layer 3 & layer 15.

See if I can break it.

**Comment by wyleu** [comment]
It seems pretty reliable between two machines . I will fire up a third.

**Comment by wyleu** [comment]
Ok running three zynth's all with qmidinet turned on...
Adding a n Audio in effects channel as channel 16 obviously has interesting effects as CUIA events are interpreted on that machine !!

No effects obvious yet. (except the 12Mbit/mouse hold on issue). I'll give it some abuse.

**Comment by wyleu** [comment]
Seems to be ok with 3 machines on the net and a separate instance of qmidinet running on a separate linux machine. . . . 
I'll try to break it some more over the next week and if I can't I'll close the ticket.
