### ISSUE TITLE
Update ZynAddSubFX to version 3.0.6

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#780]
**Is your feature request related to a problem? Please describe.**
The ZynAddSubFX version included in Zynthian is 3.0.5, which is quite old by now. Version 3.0.6 includes a number of improvements, one of them being a voice limit features whereby the user can control the maximum number of voices a patch uses (the corresponding parameter is already in the Zynthian UI). (Zyn-fusion issue 303). This is great on a resource limited platform such as Zynthian. Many ZynAddSubFX patches are very tight on resources, but some are not and will benefit from the ability to limit the number of voices playing at any one time.

Another bugfix is fixing the channels being swapped, which happens when using ZynAddSubFX in the 'multi' mode where each voice has its own JACK port. (Zyn-fusion issue 330), which is the way Zynthian uses ZynAddSubFX. A related fix is the muting of parts in multi mode (Zyn-fusion issue 327); where the last audio buffer was looped even if a part was muted. This could cause buzzing sounds in Zynthian when reconfiguring ZynAddSubFX.

Yet another minor thing is improved portemento handling (Zyn-fusion issue 304).

**Describe the solution you'd like**
Bring in ZynAddSubFX version 3.0.6

**Describe alternatives you've considered**
Another alternative would be to bring in master, as it seems rather stable at the moment. Or convince the ZynAddSubFX maintainer to release a 3.0.7 as it's been a while since 3.0.6 was released too, and there have been a number of albeit minor things fixed since then.

**Additional context**
It's very easy to build ZynAddSubFX directly on Zynthian, it basically builds, including dependency handling, directly out of the box. Not sure how easy it would be to build a proper package though.

**Comment by riban-bw** [comment]
We currently use the version of ZynAddSubFX from KXStudio repository which is 3.0.5. v3.0.6  was released on 22nd January 2022. I have [reported 1](https://github.com/KXStudio/Repository/issues/295) upstream to KXStudio so let’s see if they fix this. I would prefer they do it than we take on the burden of managing this package.

**Comment by polluxsynth** [comment]
Makes sense.

Failing that, does it have to be from KXStudio? I've noted that Debian Bookworm has 3.0.6 (https://packages.debian.org/search?keywords=zynaddsubfx) and has an armhf port, but I have far to little experience with bringing in packages from different sources to know if it there would be any issues with that.

**Comment by riban-bw** [comment]
Using a different Debian release doesn't work. Each release provides versions of libraries and dependencies are often not meet between releases. Bookworm may be released mid-2023 and we would need to do substantial testing before migrating to it so that won't be any time soon. Let's see what the guys over at KX do. They are pretty good so maybe we won't have long to wait. In the meantime, remember to reverse your zynaddsubfx ears.

**Comment by polluxsynth** [comment]
Yes, true, I did actually have a look at the dependencies for the Bullseye package, and most of them were actually met by Buster, except system level packages such as libc6 and libstdc++6; I'm convinced the reason for those dependencies are simply related to the compiler version that has been used and not a true dependency of zynaddsubfx itself, because I routinely build zynaddsubfx from source on Zynthian to keep up with zynaddsubfx master, but nevertheless it does make the Bullseye package unusable. We'll see what KX comes up with.

**Comment by jofemodo** [comment]
It's updated in Oram.

**Comment by polluxsynth** [comment]
Yeay!
