### ISSUE TITLE
Stuck notes during SMF playback

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#781]
**Describe the bug**
Sometimes there are stuck notes (note on without note off) when playing SMF.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Calf Monosynth
2. Play SMF

**Expected behaviour**
SMF plays as expected.

**Actual behaviour**
SMF plays but some notes get stuck on.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 18% (724M/3838M)
SD Card: 46% (13G/29G)
Temperature: 43.3ºC
Overclock: [Maximum](http://z2/hw-options)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [testing (9acfdb6)](https://github.com/zynthian/zyncoder/commit/9acfdb6dfe8edf99a7a904c6c9b5465ff7f05f80)
zynthian-ui: [testing (adda5eb)](https://github.com/zynthian/zynthian-ui/commit/adda5eb082dce12f8185971369ac240ec435480a)
zynthian-sys: [testing (84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)
zynthian-data: [testing (21d0966)](https://github.com/zynthian/zynthian-data/commit/21d0966a438b1e437b84f053a8f5b3e733d11484)
zynthian-webconf: [staging-2210 (b3cdde1)](https://github.com/zynthian/zynthian-webconf/commit/b3cdde1083cd9a83632c7d44ff031d9b569b93b7)

**Additional context**
The cause may be that SMF sends note off commands as note-on with velocity zero but Calf Monosynth does not support this.

**Comment by riban-bw** [comment]
SMF supports running status as do various other hardware devices. We should fix this by decoding running status in MIDI router. It would be advantageous to optionally enable running status in MIDI outputs.

**Comment by jofemodo** [comment]
jackd input ports only accept unrolled midi (not running status), The docs say:

jack_midi_event_write(...)

Clients must not write more than data_size bytes into this buffer. Clients must write normalised MIDI data to the port - no running status and no (1-byte) realtime messages interspersed with other messages (realtime messages are fine when they occur on their own, like other messages).

SMF player should unroll running status for writing normalised MIDI to the jackd ports. Perhaps this is the problem.
