### ISSUE TITLE
After changing MIDI channel the chain is shown in wrong position in mixer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#786]
**Describe the bug**
Each chain is shown in the mixer view in the order of MIDI channel (chain index). After changing MIDI channel the chain does not change position until its options menu is opened and closed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add chains with MIDI channels 1 & 2
2. Goto mixer view
3. Change first chain's MIDI channel to 3
4. Back to mixer view

**Expected behaviour**
Chain with MIDI channel 2 is shown on left of chain with MIDI channel 3.

**Actual behaviour**
Chain with MIDI channel 2 is shown on right of chain with MIDI channel 3.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 17% (676M/3838M)
SD Card: 47% (13G/29G)
Temperature: 47.7ºC
Overclock: [Maximum](http://z2/hw-options)
USB Storage: [27% (64G/235G)](http://z2/lib-captures)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [testing (5354775)](https://github.com/zynthian/zyncoder/commit/53547753b331e904c8556048bd33aeafa6bc4d72)
zynthian-ui: [testing (a4e835e)](https://github.com/zynthian/zynthian-ui/commit/a4e835eb051e26ea8a77ef126b7b34a8928ad386)
zynthian-sys: [testing (84ed19c)](https://github.com/zynthian/zynthian-sys/commit/84ed19cbdbe2a3b11411bd6606a79727f73157b8)
zynthian-data: [testing (21d0966)](https://github.com/zynthian/zynthian-data/commit/21d0966a438b1e437b84f053a8f5b3e733d11484)
zynthian-webconf: [staging-2210 (b3cdde1)](https://github.com/zynthian/zynthian-webconf/commit/b3cdde1083cd9a83632c7d44ff031d9b569b93b7)

**Additional context**
The view remains wrong until the chain options menu is opened and closed.
The chain options menu is opened for the chain expected at that position, not the one that the user pressed on which is confusing and could be problematic.
Other actions like opening control view do operate on the shown chain.

**Comment by jofemodo** [comment]
This is for you, darling!

**Comment by riban-bw** [comment]
The mixer view shows the chains in the order they appear in root_layers. This is used for chain identification, e.g. left/right arrow keys move through this list so the UI is showing the correct representation of the data. My attempt to sort this in the UI was wasted.

The list must get updated by something when the chain options is opened again. More investigation required...

**Comment by riban-bw** [comment]
Fixed! The chains are now displayed in the ascending MIDI channel order even after changing MIDI channel. The fault was using the existing root layers list without updating it. Calling the getter function performed the reordering by MIDI channel.
