### ISSUE TITLE
Update documentation for 2210 release

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#788]
**Is your feature request related to a problem? Please describe.**
Before release of next stable version of Zynthian the user documentation needs to be updated to match the software.

**Describe the solution you'd like**
Ideally this has a workflow and tutorial based design.

**Describe alternatives you've considered**
Tweak existing documentation to better match changes or eave as is and look unprofessional!

**Additional context**
There is already an updated version of the user guide [here](https://wiki.zynthian.org/index.php/TESTING_Zynthian_UI_Users_Guide). Given the minimal time and effort available before 2210 release we should probably use this as the basis and consider improvements to documentation later.

**Comment by riban-bw** [comment]
Various eyes are reviewing updated user guide. Let's get this right and use it as day zero docs.

**Comment by jofemodo** [comment]
Current documentation has been updated and it matches latest stable now.
