### ISSUE TITLE
Zynthian not recieving All Note Off Command (MIDI CC#123 Value 0)

### ISSUE THREAD

**Issue by Jimi-Heinrich** [zynthian/zynthian-issue-tracking#789]
Zynthian not recieving All Note Off Command (MIDI CC#123 Value 0)

**To Reproduce**
1. setup a synth engine
2. play some notes and hold them 
3. try to use All Note Off Command

**Expected behavior**
All notes should turn off.

**Setup:**
- Zynhtian Kit 3 upgraded to Pi4
- staging 2210, latest update (23 Oct. 22)

**Comment by riban-bw** [comment]
All CC are being sent to the engines which only action "learned CC". We should probably exclude _Channel Mode Messages_ from this process.

**Comment by riban-bw** [comment]
A fix has been pushed to _testing_branch but needs to be validated by @jofemodo before merging with _staging_.
