### ISSUE TITLE
Missing Volume sliders on WebUI with multiple MIDI devices and Hifiberry DAC+

### ISSUE THREAD

**Issue by smiths73v3** [zynthian/zynthian-issue-tracking#79]
**Describe the bug**
Missing Volume sliders on WebUI with multiple MIDI devices and Hifiberry DAC+

**To Reproduce**
Connect multiple MIDI devices to zynth. Power up and check WebUI Hardware->Audio for volume sliders

**Expected behavior**
Volume sliders should be present

**Setup:**
 - Buster 1.0.0-RC1 
 - Rpi4, Custom Kit, Hifiberry DAC+, MCP2307_Extras, Generic HDMI
 - Axiom 61 USB MIDI
 - Oxygen 25 USB MIDI
 - SOFTWARE
 - - zyncoder: master (8b7bfbd)
 - - zynthian-ui: master (06b1f6d)
 - - zynthian-sys: master (31662f2)
 - - zynthian-data: master (1c7f04d)
 - - zynthian-webconf: master (08c533b)

**Additional context**
Loading alsamixer at ssh prompt brings up Oxygen25 MIDI device "Card 0"
  "This devices does not have any controls"

```
root@zynthian:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 2: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
 Subdevices: 0/1
  Subdevice #0: subdevice #0
```

```
root@zynthian:~# aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=O25
    Default Audio Device
sysdefault:CARD=O25
    Default Audio Device
default:CARD=U61
    Default Audio Device
sysdefault:CARD=U61
    Default Audio Device
default:CARD=sndrpihifiberry
    snd_rpi_hifiberry_dacplus,
    Default Audio Device
sysdefault:CARD=sndrpihifiberry
    snd_rpi_hifiberry_dacplus,
    Default Audio Device
dmix:CARD=sndrpihifiberry,DEV=0
    snd_rpi_hifiberry_dacplus,
    Direct sample mixing device
dsnoop:CARD=sndrpihifiberry,DEV=0
    snd_rpi_hifiberry_dacplus,
    Direct sample snooping device
hw:CARD=sndrpihifiberry,DEV=0
    snd_rpi_hifiberry_dacplus,
    Direct hardware device without any conversions
plughw:CARD=sndrpihifiberry,DEV=0
    snd_rpi_hifiberry_dacplus,
    Hardware device with all software conversions
```

**Comment by jofemodo** [comment]
This should be already solved! Just update ...
