### ISSUE TITLE
Encoder switches stop working after cleaning layers

### ISSUE THREAD

**Issue by Jimi-Heinrich** [zynthian/zynthian-issue-tracking#790]
Encoder switches stop working after cleaning layers

**To Reproduce**
1. create a layer, set as default and reboot
2. go to clean layers
3. Encoder switches stop working, rotating still works

**Expected behavior**
 Encoder switches should work

**Setup:**
Staging 2210, lates update 23 Oct 22

**Comment by jofemodo** [comment]
Sorry, i can't reproduce this issue. You should give more details, including the hardware setup, etc. A screenshot from the webconf's dashboard could be fine.

**Comment by Jimi-Heinrich** [comment]
Here is the  machine

![Specs](https://user-images.githubusercontent.com/60140248/197467406-9c0139d1-1be1-48bb-93f1-ac8d3f8e3ffa.png)

And here a short vid, demonstrating it.

https://user-images.githubusercontent.com/60140248/197467951-338a50fd-07bc-4e81-82a0-87e8ee9bf4f4.mov

The snapshot is rather large. It contains a Soundfont /w 350MB.

Addidtional info. The snapshot contains a MOD-UI Layer which uses the monitor routing for getting audio into MID-UI. This is disabled by default in RC2210.

When I load a different Snapshot without FluidSynth, I am able to "clean all Layers" (shouldn't that read 'Chain' now?). It just happens, if FluidSynth is part of the mix.

**Comment by riban-bw** [comment]
Please update to ensure all fixes are applied.
If the issue persists, please provide a snapshot that triggers this issue.
"Clean All" does not refer to "Layers", even in your video!

**Comment by Jimi-Heinrich** [comment]
I updated just now. **It does work as expected** yay! :)

_"Clean All" does not refer to "Layers", even in your video!_ 

I'm confused--- I know they are calles "Chains" now... but what do you mean?

**Comment by riban-bw** [comment]
You said:

`I am able to "clean all Layers" (shouldn't that read 'Chain' now?).`
