### ISSUE TITLE
Hanging notes over DIN-MIDI input with MIDI Clock

### ISSUE THREAD

**Issue by Jimi-Heinrich** [zynthian/zynthian-issue-tracking#791]
Synth-Chains get hanging notes when inputing via DIN-MIDI with MIDI Clock

**To Reproduce**
1. create Synth Chain
2. connect external keyboard via DIN-MIDI
3. send MIDI Clock from external keyboard
4. play notes on external keyboard
5. hanging notes occur in Synth Chain

**Expected behavior**
No hanging notes occur.

**Setup:**
staging 2210, update 23 Oct, 22

**Additional context**
tried same keyboard without adding MIDI clock, NO hanging notes.
keyboard is sending active sensing (MIDI real time message FE) – does NOT produce hanging notes

**Comment by jofemodo** [comment]
Sorry, i can't reproduce with my keyboard (behringer mötor 61).
What is the brand & model of the keyboard you use? Have you tested with a different keyboard or controller?

**Comment by riban-bw** [comment]
Is it true that both active sensing and MIDI clock need to be sent to trigger the issue?
Does the keyboard implement running status?
Does the keyboard send MIDI note-off or MIDI note-on with zero velocity?
How often do notes stick?
How rapidly must you play to trigger the issue?

Please provide MIDI logs during the fault.

**Comment by riban-bw** [comment]
I have a WX11 wind synth sending monophonic note on/off, active sensing, breath CC & pitch wheel. This is going through an Alesis HR-16 which is merging with its own MIDI clock. This feeds the physical MIDI input on the Zynthian. I have not yet heard any stuck notes having played for a few minutes.

**Comment by Jimi-Heinrich** [comment]
I figured it is the G2X forgetting certain notes. Look here:

CH#04 NOTE_ON 62, Vel: 89
CH#04 NOTE_ON 50, Vel: 73
CH#04 NOTE_ON 69, Vel: 81
CH#04 NOTE_ON 57, Vel: 61
CH#04 NOTE_ON 59, Vel: 60
CH#04 NOTE_OFF 59, Vel: 64
**CH#04 NOTE_OFF 0, Vel: 64**
CH#04 NOTE_OFF 57, Vel: 64
CH#04 NOTE_OFF 62, Vel: 64
CH#04 NOTE_OFF 69, Vel: 64
CH#04 CONTROL_CHANGE 64 => 0
CH#04 CONTROL_CHANGE 123 => 0
CH#04 CONTROL_CHANGE 64 => 0

HANGING NOTES:
CH#04 NOTE_ON 50, Vel: 67
CH#04 NOTE_OFF 50, Vel: 64

I use the "Note Zone" Object of the G2X. And obviously it injects a NOTE_OFF 0 from time to time. 
When I play directly into the Zynthian even with Active Sensing and MIDI-Clock it doesn't happen.

Thank you guys for poking me into the right direction. Getting the ALL NOTE OFF back would suffice for me as of now. Or I have to rethink my hardware setup routing.

I guess this can be **closed**.
