### ISSUE TITLE
PianoTeq crashes during ZS3 MIDI learn

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#798]
**Describe the bug**
Sending a MIDI program change during ZS3 MIDI learn can crash PianoTeq.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable ZS3 Program Change mode
2. Add Pianoteq chain
3. Press SNAPSHOT twice to enable ZS3 MIDI learn
4. Send MIDI Program Change 13 on MIDI channel 1 (0)

**Expected behaviour**
ZS3 is created / updated for PC#13.

**Actual behaviour**
ZS3 is created / updated for PC#13 but Pianoteq crashes.

**Screenshots**
![Screenshot 2022-10-24 15 03 39](https://user-images.githubusercontent.com/3158323/197954292-9c12e6b2-3357-48b5-81a2-4837c2dc06e5.png)

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 15% (600M/3838M)
SD Card: 49% (13G/29G)
Temperature: 43.8ºC
Overclock: [Maximum](http://z2/hw-options)
USB Storage: [27% (64G/235G)](http://z2/lib-captures)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [staging-2210 (98c3df2)](https://github.com/zynthian/zyncoder/commit/98c3df25193485902ecdd2da4a312e5a3c87843b)
zynthian-ui: [staging-2210 (d962ac1)](https://github.com/zynthian/zynthian-ui/commit/d962ac13174ff3d452c01c438990a7e3e32f3f1a)
zynthian-sys: [staging-2210 (b723fb3)](https://github.com/zynthian/zynthian-sys/commit/b723fb3d3a07c596a569c067a6f45c17e2344edb)
zynthian-data: [staging-2210 (c95d786)](https://github.com/zynthian/zynthian-data/commit/c95d7869b8604566bf76331e3b20d810d326a3c5)
zynthian-webconf: [staging-2210 (7df8271)](https://github.com/zynthian/zynthian-webconf/commit/7df82714d38b84bb5ae8cefb8dbc861a83a4d9f1)

**Additional context**
This may not occur on first program change. Adding two ZS3 using  different instrument packs then swapping between them with MIDI program change recalling each ZS3 triggers it within a few iterations.

**Comment by riban-bw** [comment]
We need to report to Modartt so need to gather information, logs, methods to reproduce, etc. The command line that Zynthian used to trigger my last crash was:

`/zynthian/zynthian-sw/pianoteq6/pianoteq --multicore max --midi-channel all --midimapping Zynthian-3 --preset MKII Spark`

After a crash, each time Pianoteq starts it complains about the previous crash and requests user input to remove configuration file.

**Comment by riban-bw** [comment]
It looks like each time PT decides it has crashed or been force shutdown it increments its xml tag `<VALUE name="crash_detect" val="1"/>` in /root/.config/Modartt/Pianoteq75\ STAGE.prefs. When that hits `2` it warns the user which blocks program. I cannot see a command line parameter to ignore this flag. We could work-around this by removing the flag in the configuration file when starting PT.

**Comment by riban-bw** [comment]
I pushed a work-around for this which clears the crash flag from Pianoteq's configuration file and logs to Zynthian log. This should allow PT to start up after crashes without blocking but we should avoid PT from closing down incorrectly.

~~Maybe PT sometimes takes longer than 0.2s to close then `zynthian_engine::stop()` performs a forced termination.~~ I tested this by checking for `isactive()` before force terminate and it does not appear to be active - although maybe the app is still active after it reports detached.

**Comment by linuxnow** [comment]
I have made some tests with VNC open and I've come to understand why Program Change was so slow.

Taking my snapshot as a reference, I can call PC11 and PC12 and the Pianoteq instance accepts the instrument change without restarting. But whenever I send any other PC it crashes and restarts. When it has crashed 2 or 3 times, it asks if you want to reset your preferences.

But, I can change the instruments using their menus, the instrument change is super fast  and it does not crash. It happens in the stable version and in the staging version.

I had always found that the instrument change took too long, but I had never opened the VNC interface to see what was going on.

The problem happens only when using Program Change with Pianoteq.

**Comment by riban-bw** [comment]
It is not crashing but being restarted by Zynthian. The crash was probably an occasional side effect of this process. You are right that Pianoteq can change instruments promptly so we should review why we are closing and restarting. It _may_ be due to limitations of control in previous versions of Pianoteq. Since 7.5 it has included a remote protocol so we may be able to improve things but this might not suit those users who have Pianoteq 6 licenses. We may need to use a bit of logic around that.

**Comment by riban-bw** [comment]
I have raised issue #803 requesting better handling of Pianoteq preset changes. We should probably still investigate why Pianoteq thinks it is crashing but the issue may become mute if we are able to gracefully close using the API. I am closing this issue.
