### ISSUE TITLE
Pattern editor drum maps not loading

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#799]
**Describe the bug**
The pattern editor should show the names of the instruments for some engines, e.g. drums. This has stopped working for some including Red Zeppplin 5.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Red Zeppelin 5 chain with MIDI channel 1
2. Open pattern editor for sequence 1

**Expected behaviour**
Pattern editor shows drum names.

**Actual behaviour**
Pattern editor shows piano keyboard.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 26% (1023M/3838M)
SD Card: 49% (13G/29G)
Temperature: 47.2ºC
Overclock: [Maximum](http://z2/hw-options)
USB Storage: [27% (64G/235G)](http://z2/lib-captures)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [staging-2210 (98c3df2)](https://github.com/zynthian/zyncoder/commit/98c3df25193485902ecdd2da4a312e5a3c87843b)
zynthian-ui: [testing (73b508b)](https://github.com/zynthian/zynthian-ui/commit/73b508b3d6dc97498ef96fb1503c39c063db0649)
zynthian-sys: [staging-2210 (b723fb3)](https://github.com/zynthian/zynthian-sys/commit/b723fb3d3a07c596a569c067a6f45c17e2344edb)
zynthian-data: [staging-2210 (c95d786)](https://github.com/zynthian/zynthian-data/commit/c95d7869b8604566bf76331e3b20d810d326a3c5)
zynthian-webconf: [staging-2210 (7df8271)](https://github.com/zynthian/zynthian-webconf/commit/7df82714d38b84bb5ae8cefb8dbc861a83a4d9f1)

**Additional context**
I went through these recently and got them working. I wonder if the name format of presets has changed.

**Comment by riban-bw** [comment]
The current implementation uses the displayed name with reference to engine, bank and preset. This does not scale well. If a user adds a preset then it won't be recognised and no drum map will be shown.

We should use a better method of detecting drum engines / presets. Maybe the configuration defines the engine, bank, preset with wildcard comparison, e.g. `<engine>.<bank>.<preset>` might look like `Red Zeppelin 5.*.*`.

**Comment by jofemodo** [comment]
In the "old good times", channel 10 was used for drums, and this would be an "easy way", but it doesn't fit "modern silly-users times". The approach you are using is probably the only way: list of drum "presets" + some heuristics
I would take a look and try to think a little bit about it ...

**Comment by jofemodo** [comment]
I did some improvements that could be enough for closing this. Please review and  tell me if you think it's enough.

**Comment by jofemodo** [comment]
I will close this. The last commits mitigates the problem quite a bit.
Further improvement should be addressed by a separated ticket.
