### ISSUE TITLE
Issues with Foo YC20 Organ

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#800]
**Describe the bug**
The Foo YC20 Organ uses approx. 30% CPU load whilst idle. This is a lot of processing for such a simple sound module. Should this be in the list of plugins enabled by default? Maybe it is thought to be sufficiently important to include this emulator?

The volume is very low for this engine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Foo YC20 Organ chain
2. Measure CPU load, e.g. `jack_cpu_load`

**Expected behaviour**
Load is low.

**Expected behaviour**
Load is high.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-06
Memory: 12% (494M/3838M)
SD Card: 49% (14G/29G)
Temperature: 43.3ºC
Overclock: [Maximum](http://z2/hw-options)
USB Storage: [27% (64G/235G)](http://z2/lib-captures)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [staging-2210 (98c3df2)](https://github.com/zynthian/zyncoder/commit/98c3df25193485902ecdd2da4a312e5a3c87843b)
zynthian-ui: [testing (73b508b)](https://github.com/zynthian/zynthian-ui/commit/73b508b3d6dc97498ef96fb1503c39c063db0649)
zynthian-sys: [staging-2210 (b723fb3)](https://github.com/zynthian/zynthian-sys/commit/b723fb3d3a07c596a569c067a6f45c17e2344edb)
zynthian-data: [staging-2210 (1d8054a)](https://github.com/zynthian/zynthian-data/commit/1d8054a9d2f099ae277047a7d1624caa9ce3339f)
zynthian-webconf: [staging-2210 (7df8271)](https://github.com/zynthian/zynthian-webconf/commit/7df82714d38b84bb5ae8cefb8dbc861a83a4d9f1)

**Additional context**
This engine uses faust modelling which is heavy on CPU (not optimal for Raspberry Pi). From [kvraudio website](https://www.kvraudio.com/product/foo_yc20_by_foo):

Flaws:
- Touch vibrato is not emulated.
- Takes quite a bit of CPU power.

**Comment by TabulaNul** [comment]
I agree with you. We already have many synths, we should focus on the more stable ones enabled by default.
Foo YC20 Organ is decent, but not a game-changing synth, and if it takes 30% of the CPU, that's really too much for this kind of synth.
