### ISSUE TITLE
7" Display setting kernel options prevent working.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#804]
**Describe the bug**
If you select the 7" touchscreen option in display you have to remove the kernel options and the refereing line...

**To Reproduce**
1. Select display 7" Touchscreen
2. Click on Save
3. Reboot

**Expected behavior**
I expect to see the GUI screen on the 7" screen. It  shows black

**Screenshots**
This works....
![zynthian-rack-display_new](https://user-images.githubusercontent.com/79083/198606941-0fcc8a1d-afc5-44f0-badf-a60551d2697c.png)

**Setup:**
![zynthian_rack_software_bug](https://user-images.githubusercontent.com/79083/198608003-74d98c37-7fba-4971-aebd-0c8daed6ea3e.png)

**Additional context**
Not sure what the new stuff does but it stops my 7" screens working (Two different machines)

**Comment by jofemodo** [comment]
It's solved now ...
