### ISSUE TITLE
Warn of restart after saving wiring changes

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#808]
**Is your feature request related to a problem? Please describe.**
After making changes to wiring, e.g. extra button functionality, pressing Save will cause Zynthian to restart. This is not obvious and may interfere with user workflow.

**Describe the solution you'd like**
Avoid restarting Zynthian or if necessary to restart, warn in webconf that a restart will occur.

**Describe alternatives you've considered**
Don't change anything - ever!!!

**Additional context**
This is disconcerting and may interrupt a user's session.

**Comment by jofemodo** [comment]
You are right. We should be capable of reloading wiring layout config without restarting zynthian.
I will work on this after new stable ...

**Comment by jofemodo** [comment]
It's done now!
