### ISSUE TITLE
MIDI Router adding Pitchbend message to NOTE ON message

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#81]
When a MIDI NOTE ON message is sent to Zynthian via ttyMIDI or USB MIDI the Zynthian router gets an additional PITCHBEND=0 message. This seems odd and may have the capacity to upset modules.

**To Reproduce**
1. Use webconf MIDI Monitor to monitor MIDI input.
2. Press a MIDI key.
3. Note MIDI ON message logged.
4. Use webconf MIDI Monitor to monitor ZynMidiRouter Main.
5. Press a MIDI key.
6. Note MIDI ON and PITCHBEND messages logged.

**Expected behavior**
Only MIDI ON message should be logged.

**Screenshots**
MIDI Input
![image](https://user-images.githubusercontent.com/3158323/69656503-975c1f80-1070-11ea-850f-5ff31f0f1777.png)

ZynMidiRouter Main
![image](https://user-images.githubusercontent.com/3158323/69656546-aba01c80-1070-11ea-98ad-63ca44749dd8.png)

**Setup:**
SD Image 
Buster Nightly 2019-10-20 updated.

HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ light
Display: Sainsmart 1.8
Wiring: I2C_HWC
GPIO Expander: No detected

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (c02b3ce)
zynthian-sys: master (c16eb29)
zynthian-data: master (d7648f7)
zynthian-webconf: master (813b47d)
 - Software Version

**Additional context**
This may have been related to an issue with stuck notes where MIDI NOTE OFF was being transformed to MIDI NOTE ON message.

**Comment by jofemodo** [comment]
As i explained in the forum, this is the zynthian “tuning” system. It’s been there for a while … more than 2 years now!! AFAIK, it works OK!
FYI, tuning is "internal", so only the engines receive these "tuning" messages. They are not included in any MIDI output.

**Comment by jofemodo** [comment]
More info ...

When real pitch-wheel messages are received from a controller, the received pitch is added to the precalculated "tuning" pitchbend value. Received pitchbend is tracked, so any new note message will be played accordingly to the tuning pitchbend + real pitch-wheel value. Of course, i take care of not going out of the pitchbend range, etc..

Although we tested all this carefully, it's quite tricky and could be hidden effects to discover. As you are a extremely good tester, please, don't hesitate to review the feature and test again ;-)
