### ISSUE TITLE
Wrong preset or bank list shown during preset selection of a chained engine

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#810]
**Describe the bug**
When selecting the preset of an engine in a chain, the root engine's preset list is shown briefly before returning to the control view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add FluidSynth chain with AirFont320 soundfont (or other with long list of preset)
2. Add effect with presets, e.g. SooperLooper
3. Select effect in control view and access its preset list
4. Exit preset list, e.g. select a preset or press BACK
 
**Expected behaviour**
Return to control view.
 
**Actual  behaviour**
Shows list of presets for Fluidsynth before returning to control view.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: [ZynADAC](http://192.168.1.51/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.1.51/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.1.51/hw-wiring)
I2C: [MCP23017@0x20, MCP23008@0x21, ADS1115@0x48](http://192.168.1.51/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-28
Memory: 8% (167M/1872M)
SD Card: 40% (12G/29G)
Temperature: 55.5ºC
Overclock: [Medium](http://192.168.1.51/hw-options)
- MIDI
Profile: [default.sh](http://192.168.1.51/ui-midi-options)
Tuning: [440 Hz](http://192.168.1.51/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.1.51/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://192.168.1.51/ui-midi-options)
MIDI to Output: [Off](http://192.168.1.51/ui-midi-options)
Master Channel: [off](http://192.168.1.51/ui-midi-options)
- SOFTWARE
zyncoder: [staging-2210 (98c3df2)](https://github.com/zynthian/zyncoder/commit/98c3df25193485902ecdd2da4a312e5a3c87843b)
zynthian-ui: [staging-2210 (62051e5)](https://github.com/zynthian/zynthian-ui/commit/62051e58d58030a7c9f55f6e3d629c8b0b12d1d7)
zynthian-sys: [staging-2210 (8c7e2ac)](https://github.com/zynthian/zynthian-sys/commit/8c7e2ac6b8a1209f73f2319f74a326d75bd03d8d)
zynthian-data: [staging-2210 (3bbc39c)](https://github.com/zynthian/zynthian-data/commit/3bbc39cb3febe968dd2be3155f547db1848dba71)
zynthian-webconf: [staging-2210 (b60b529)](https://github.com/zynthian/zynthian-webconf/commit/b60b5292d056a3966ddf105a6399ef3bd85bdba7)

**Additional context**
When leaving the preset (or bank?) view the current layer is restored which populates the bank and preset views. The preset (or bank) view is still displayed hence the wrong (or at least unexpected) content is displayed.

**Comment by jofemodo** [comment]
Fixed by: https://github.com/zynthian/zynthian-ui/commit/6324f9fbf0651b5fa8da7b8c32c47ec31ce1171f
