### ISSUE TITLE
Bug: Arpeggiator not working correctly

### ISSUE THREAD

**Issue by dComposer** [zynthian/zynthian-issue-tracking#813]
**Describe the bug**
ArpModes Up, Played, and Random work properly. ArpMode Down just repeats the lowest note in a played chord. ArpModes Up-Down and Up-Down (Alternative) act as generators and play whatever notes they want with nothing held down on the keyboard.

LatchMode set to On works properly, refuses to unlatch when set back to Off.

OctaveSpread transposes notes to higher octaves but jumbles the order of the arpeggiated notes of the chord.

**To Reproduce**
1. Create Midi chain
2. Add arpeggiator
3. Route midi to synth chain
4. Hold down a chord on the keyboard while adjusting ArpMode, LatchMode, and OctaveSpread.

**Expected behavior**
ArpMode should work as intended. LatchMode should unlatch when set to off, OctaveSpread should spread the arpeggio across the intended octaves in the correct order.

**Setup:**
 - SD-image: 2211
 - Hardware Config: v4 kit
 - Software Version: 2211

**Comment by riban-bw** [comment]
I am not seeing these issues.

With a simple synth engine (MDA DX10 epiano) I held a chord and adjusted parameters:

- BPM adjusted the arpeggio rate
- ArpMode changed behaviour: up, down, etc.
- LatchMode played the arpeggio after releasing the chord until LatchMode disabled
- Divisions changed arpeggio the rate / pattern
- Sync adjusted arpeggio rate to match sequencer tempo (when running)
- NoteLength changed duration of each note in arpeggio
- OctaveSpread distributed the notes across multiple octaves
- OctaveMode changed the order of notes in the octave spread

The octave spread/mode is odd behaviour but this presumably is how the [upstream](https://github.com/moddevices/mod-arpeggiator-lv2) project intends it.
