### ISSUE TITLE
Webconf rename files dissappear

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#815]
**Describe the bug**
Make a recording with the audio player, name file from webconf. File Disappears.

**To Reproduce**
1. Make Audio recording 
2. Confirm recording plays in audio player
3. Use webconf to rename recording
4. File doesn't reappear after refresh.

**Expected behavior**
File renamed and appears in captures list

**Setup:**
![image](https://user-images.githubusercontent.com/79083/200134492-050a6aef-016c-4d53-ac62-4df57ee807f6.png)

**Additional context**
It would be nice if,now we have a GUI keynboard option, the ability to rename was available in the GUI audioplayer options.

**Comment by wyleu** [comment]
I do have multi recording selected on the one channel....
![image](https://user-images.githubusercontent.com/79083/200135530-6f0c4102-d615-43ef-bb64-1a5065449b07.png)

**Comment by riban-bw** [comment]
Webconf is using first '.' as separator for extension. Should use last '.'.

**Comment by riban-bw** [comment]
This only affects files with a dot in their name. I have pushed a fix that we should probably deploy as a hot fix.
