### ISSUE TITLE
Preset preload doesn't work as expected in Z2

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#817]
**Describe the bug**
When preloading presets, engine's selected preset is restored when touching any pot and list selected preset reloaded again when pressing a note.

**To Reproduce**
1. Create a synth chains with a engine that takes some time to load presets (Odin2, for instance)
2. Enable preset preload from admin menu
3. Navigate to the preset screen and preload a preset by pressing a note
4. Touch any knob => the engine's selected preset is restored
5. Press a note => the list selected preset is reloaded again

**Expected behavior**
When touching a knob, preset shouldn't be reloaded!

**Setup:**
 - latest stable 2211
 - Z2 prototype

**Comment by riban-bw** [comment]
I don't think this is urgent. It is only affecting Z2. I suggest removing Urgent flag and targeting at 2211.1 point release.
