### ISSUE TITLE
After receiving ZS3 PC, control screen is not refreshed.

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#818]
**Describe the bug**
After receiving ZS3 PC, control screen is not refreshed. New active chain is not shown!

**Expected behavior**
Control screen  show the active chain always.

**Setup:**
 - Latest Stable 2211
 - Z2 & V4

**Additional context**
This is specially important in stage mode. In multitimbral mode, we could choose to "not restore" the active chain from the ZS3.

**Comment by linuxnow** [comment]
Do you need testing?

**Comment by linuxnow** [comment]
Works as expected in _testing_ and _pianoteq_rpcjson_api_
