### ISSUE TITLE
Python crypt is deprecated

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#819]
**Describe the bug**
Python `crypt` module is deprecated since version 3.11, will be removed in version 3.13:

The [crypt](https://docs.python.org/3/library/crypt.html#module-crypt) module is deprecated (see [PEP 594](https://peps.python.org/pep-0594/#crypt) for details and alternatives). The [hashlib](https://docs.python.org/3/library/hashlib.html#module-hashlib) module is a potential replacement for certain use cases.

**Setup:**
Zynthian 2211.

**Additional context**
We should replace use of crypt before it stops working. This may be some time (Bullseye seems to use Python 3.9). This module is used by webconf to authenticate login.

**Comment by riban-bw** [comment]
Bookworm is currently using Python 3.11 so we still have a little time but we should resolve this soon.

**Comment by riban-bw** [comment]
Python `crypt` module is used by:

- zynthian-webconf/lib/login_handler.py
- zynthian-webconf/lib/security_config_handler.py

I suggest we demote the urgency and bump this into the next release after Oram. It isn't blocking Oram release but we should resolve ASAP.

**Comment by riban-bw** [comment]
@jofemodo, you changed the milestone. Are you planning to fix this in Oram or should we switch it back to oram+1?

**Comment by jofemodo** [comment]
I replaced by PAM stuff. Nice ;-)
