### ISSUE TITLE
Discrete values not detected correctly

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#821]
**Describe the bug**
If an engine has a parameter with discrete values and it passes the labels but not the values (ticks), Zynthian calculates the values but this is not always correctly calculated.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-10-29
Memory: 9% (352M/3838M)
SD Card: 45% (12G/29G)
Temperature: 47.2ºC
Overclock: [Maximum](http://z2/hw-options)
USB Storage: [28% (64G/235G)](http://z2/lib-captures)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [Off](http://z2/ui-midi-options)
Master Channel: [off](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [stable (98c3df2)](https://github.com/zynthian/zyncoder/commit/98c3df25193485902ecdd2da4a312e5a3c87843b)
zynthian-ui: [testing (8c900ba)](https://github.com/zynthian/zynthian-ui/commit/8c900bad9feebb68eb7166e6a86546d0352a788c)
zynthian-sys: [testing (6e0de1e)](https://github.com/zynthian/zynthian-sys/commit/6e0de1ec1f1ba01edeec9fa2c4c1ded2ff7f9b25)
zynthian-data: [testing (bc3e5fb)](https://github.com/zynthian/zynthian-data/commit/bc3e5fb36f7debce628bb5ec1a7338d6e337fa70)
zynthian-webconf: [testing (bec0a78)](https://github.com/zynthian/zynthian-webconf/commit/bec0a7833555d0b1b33a2fa0814463ee9b4c754f)

**Additional context**
The range should span the full range including min and max values.

**Comment by jofemodo** [comment]
Steps to reproduce the problem?
A case of bad behaviour, please ...
