### ISSUE TITLE
ZS3 in multi-timbral mode does not save engine/chain parameters/settings

### ISSUE THREAD

**Issue by Ejdzi2** [zynthian/zynthian-issue-tracking#823]
ZS3 in multi-timbral mode does not save any engine/chain parameters/settings except choosed preset. In stage mode all seems ok and changing Program Change recall saved settings.

1. Setting mult-timbral mode and Program Change ZS3 in admin menu
1. Creating chain's layout (may be a simple one:  CH1, ZY>Bank/Preset1)
3. Saving ZS3 (any method)
4. Changing preset (CH1, ZY>Bank/Preset2), changing some engine parameters (eg. volume, panning, filter, portamento, etc) and/or changing chain settigs (eg. cloning, key range etc)
5. Saving another ZS3
6. Recaling first ZS3 change Preset2 to Preset1 but engine parameters and chain settings remaining unchanged (as set for second ZS3)

**Expected behavior**
Expected (as it is in Stage Mode) to recall ZS3 with all saved parameters and engine settings not only Preset changing.

**Setup:**

HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO]
Display: [PiTFT 2.8 Resistive]
Wiring: [MCP23017_EXTRA]
I2C: [MCP23017@0x20]
SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-11-01
Memory: 3% (151M/3839M)
SD Card: 42% (12G/29G)
Temperature: 55.5ºC
Overclock: [Disabled]
SOFTWARE
zyncoder: stable (98c3df2)
zynthian-ui: [stable (f15cbd3)]
zynthian-sys: [stable (6e0de1e)]
zynthian-data: [stable (9180393)]
zynthian-webconf: [stable (bec0a78)]

**Comment by jofemodo** [comment]
OK! I can reproduce the issue. Let me solve it.

**Comment by linuxnow** [comment]
I can confirm this behaviour, modified parameters are not saved or restored when in multi-timbral mode

**Comment by andresnecochea** [comment]
Sorry if I'm late, but almost a week ago I have the same problem.

**Comment by jofemodo** [comment]
Finally i could reproduce the error. The error occurs only when Audio Levels are saved in state.
I just pushed a fix to stable & testing. Please, update and test.
