### ISSUE TITLE
Inability to output to any output except 1 and 2

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#824]
**Is your feature request related to a problem? Please describe.**
Devices like the Behringer 1820 have many outputs and there is no way of routing output ot other output pairs or indeed optical outputs.
**Describe the solution you'd like**
The ability to choose which outputs are used

**Describe alternatives you've considered**
Nothing obvious.

**Additional context**
![image](https://user-images.githubusercontent.com/79083/201755796-8e3e5e40-703c-4114-a89f-688c405ec8c7.png)

**Comment by riban-bw** [comment]
This is resolved in _oram_. The main mixbus can now be routed to any pair of outputs. This may be suboptimal because they are paired and because only the main mixbus offers this routing.

**Comment by riban-bw** [comment]
I have fixed audio routing and implemented the ability to direct route to any physical output as well as any chain from any audio chain. The only thing I think may be suboptimal is that direct outputs are paired, e.g. 1+2, 3+4, etc.

**Comment by riban-bw** [comment]
I have added mono / stereo direct output routing. The list consists of each individual (mono) output and each consecutive (odd/even) pairs, e.g. 1, 2, 1+2. I was worried the list would be too long or confusing but I think it works fine and gives a suitable level of flexibility. Someone who wants to pair 1+9 can implement their own algorithm! I will close this ticket as complete.
