### ISSUE TITLE
Mod Wheel and Expression pedal don't work as they did in 202109 release

### ISSUE THREAD

**Issue by linuxnow** [zynthian/zynthian-issue-tracking#825]
**Describe the bug**
I use SCC Expressive Strings, exactly the same version now included in the latest release.
In 202109 the Mod Wheel and the Expression pedal could control the volume when using SCC Expressive Strings.
In 202211 they do nothing, although the MIDI CCs are received.

**To Reproduce**
Steps to reproduce the behaviour:
Try SCC Expressive Strings in 202109 release, you can control the volume using the Mod Wheel (CC 1) or the expression pedal (CC 11).
Try the same in 202211. Nothing happens.

**Expected behavior**
When using SCC Expressive Strings CC1, the Mod Wheel should control the volume of the notes; using CC111 you control the volume with the expression pedal.

**Setup:**
 - SD-image: 202211

 - Hardware Config: Standard V4 Kit
   Raspberry Pi 4 Model B Rev 1.2
   Audio: [HifiBerry DAC+ ADC PRO]
   Display: [ZynScreen 3.5 (v1)]
   Wiring: [MCP23017_ZynScreen]
   I2C: [MCP23017@0x20
   Profile: [v4_stage]

 - Software Version
   zyncoder: stable (98c3df2)
   zynthian-ui: [stable (f15cbd3)
   zynthian-sys: [stable (6e0de1e)
   zynthian-data: [stable (9180393)
   zynthian-webconf: [stable (bec0a78)

**Additional context**
I've tested it with a fresh install just in case

**Comment by linuxnow** [comment]
Another difference between 202109 and latest version that could be related can be observed checking MIDI Log:
-in 202109 CC messages are seen in the default ZynMidiRouter Main
-in testing CC messages are not displayed in ZynMidiRouter Main, you have to select ZynMidiRouter Network-

I don't know if this helps.

**Comment by jofemodo** [comment]
It's solved in testing. I hope to merge on stable ASAP.

**Comment by linuxnow** [comment]
Fixed! Thank you!
