### ISSUE TITLE
Add host name to backup utility file name

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#826]
**Is your feature request related to a problem? Please describe.**
BAckups use zynthian as their default name. Using the host name of the machine would help significantly in multi zynth implementations.

**Describe the solution you'd like**
The seed for the file name should include the hostname so 
zynthian-pedal_data_backup20221115-113037.zip  rather than 
zynthian_data_backup20221115-113037.zip  for a machine named zynthian-pedal

**Describe alternatives you've considered**
Requires external name handling with all the traditional name creep characteristics.

**Comment by jofemodo** [comment]
This seems to be duplicated:

https://github.com/zynthian/zynthian-issue-tracking/issues/311
