### ISSUE TITLE
Pianoteq 8 missing Guitar preset in the UI

### ISSUE THREAD

**Issue by wanthalf** [zynthian/zynthian-issue-tracking#830]
The "Classical Guitar" preset of Pianoteq 8 is missing in the UI.
Obviously missing in https://github.com/zynthian/zynthian-ui/blob/testing/zyngine/zynthian_engine_pianoteq.py

**Comment by jofemodo** [comment]
It should be fixed by https://github.com/zynthian/zynthian-ui/pull/466
