### ISSUE TITLE
Powersave mode: Touching the blanked screen should not trigger any other actions than waking up the system.

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#837]
**Describe the bug**
When the screen is blank and I touch it in order to wake it up, the touch is registered and the specific action (menu etc.) is immediately triggered. This is dangerous as it causes unwanted behaviour of the system.

**To Reproduce**
- let screen go blank
- touch the screen to wake it up

**Expected behavior**
The blanked touchscreen is interpreting any touch just as a wake up call and does not trigger any action. In order to avoid triggering anything when the finger by accident touches the screen twice, I would suggest the following behaviour:
- The first registered touch and any other touches within a specific time span (let's say 200ms) will be interpreted as wake up calls. After the 200ms the screen will start to respond to touch actions.

**Comment by jofemodo** [comment]
This has sense. We will fix it ;-)
