### ISSUE TITLE
Individual settings for power saving and screen blanking

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#838]
I do want to use the power saving mode in order to keep the CPU cool, but not use the screen blanking (see my other related bug reports). So I think it would be good to be able to configure both individually.
Suggestion: The existing power save delay remains, but a checkbox is added: "Blank screen when in power save mode".

**Comment by wyleu** [comment]
Fan control as well?

**Comment by jofemodo** [comment]
We are not going to make things more complex. If you enable "Power Saving", you sign for the full package. If you don't like, then you disable. Simpler is better ;-)
