### ISSUE TITLE
 Encoder switches False trigger in the latest Zynthian update

### ISSUE THREAD

**Issue by sinitsinmike** [zynthian/zynthian-issue-tracking#839]
I have built a DIY Zynthian. I have used it sinse 2020. I had no issues whatsoever.
The only complaint I had in an older Zynthian version is that MIDI recorder was very slow. After hitting record I had to wait for 10-15 seconds. And that’s on Raspverry Pi 4 version B.
A few weeks ago I got myself a new SD card and installed a new version of Zynthian.
There was no hardware modifications, the only difference is the version of Zynthian.
Now when I press CTRL-2 (back) button I get to Mixer, so all is working correctly.
But, in a few seconds Admin window opens just by itself.
Also, when I click other control button sometimes CTRL-4 (select) long press false triggers and I’m getting Turn Off dialogue.
I have tested with oscilloscope and there’s no false trigger on the encoder contacts. There’s no voltage spikes. I’ve checked and rechecked all the wiring, and as I said before there was no HW modifications to my build. So the difference is in Zynthian soft.
My build is simple and all encoders and switches go directly to raspberry Pi 4 header. I do not use MCP23017.
As for the sound output I use a cheap pcm5102 board, configured as Hifiberry dac + Light.
Screen: HDMI Waveshare 5 USB.
My wiring:
![wiring](https://user-images.githubusercontent.com/11144305/210429730-c623c326-f64e-4d6b-ba06-b9dd11b6ed78.jpeg)
My DAC:
![DAC](https://user-images.githubusercontent.com/11144305/210429782-a27e919a-2c94-4f89-a758-dab99c5e05cc.jpeg)

User [gilrain](https://discourse.zynthian.org/u/gilrain) has the same issue.

![user 2](https://user-images.githubusercontent.com/11144305/210429673-6d8a5d04-381b-40b0-9eb7-380ac7183fd8.png)

**Comment by jofemodo** [comment]
Encoder code has been refactored/optimized and now having debouncing capacitors in your encoders & switches is mandatory. Please, consider adding these capacitors to your design. If you already have them, please, tell me the values you used.

Thanks!

**Comment by sinitsinmike** [comment]
Hello. Yes, I do have debouncing caps soldered on to my encoders.
Caps values are correct.
I did an experiment. I bought MCP23017 and soldered those encoders to it.
Now it works. But that's not a fix for the issue, it is a workaround :)

**Comment by miotislucifugis** [comment]
Having the same problem even after add coupling caps on all the encoders and switches.  Similar hardware config as the original poster.     I tried first with .1uf  but then increased it to  .47uf with no apparent change or reduction in the "phantom" long press.  Reduced the caps to 0.01uf same results.        Pretty much everytime I click encoder #4, three seconds later it asks if I want to power down.   Switch is connected to WiringPi 4 = Pin 16 - GPIO 16.      Perhaps the encoder code has been "optimized" too much?!

**Comment by riban-bw** [comment]
Will one of the reporters please check the _oram_ image? (Need to flash the new image from download, not update from existing 2401 or earlier.) We are now using different libraries and there _may_ have been some other changes to the libs. It would be useful to hear whether this issue persists in the next version before we investigate further.

**Comment by sinitsinmike** [comment]
Hello! Can you please add a link to oram image in question?

Thank you!

**Comment by sinitsinmike** [comment]
Also, should I expect increase/decrease in overall performance after installing it?

**Comment by riban-bw** [comment]
https://os.zynthian.org/test/2024-02-20-zynthianos-bookworm-aarch64-oram-2402.zip

Performance should improve but this is an early alpha test so we having done any benchmark tests yet.
