### ISSUE TITLE
CUIA command to directly switch to looper (SCREEN_LOOPER ?)

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#840]
A CUIA command to directly switch to sooperlooper would be very handy. It should work because there is only one looper instance running anyway. The obvious message would be “SCREEN_LOOPER”.

**Comment by jofemodo** [comment]
We have to discuss this (@riban). I don't like adding CUIAs for specific engines.

**Comment by riban-bw** [comment]
I agree with @jofemodo that it is undesirable or difficult to scale a CUIA message for specific processors. It could be done but I think it would be unwieldy. Difficult to maintain and awkward for users.

What you can do already (in _oram_ branch) is to send a CUIA "chain_control" with the chain index as a parameter. (The parameter is an integer number indicating the index of the chain relative to its position in the mixer view. 1=first (left-most) chain. 0=Main mixbus chain.) This will show the control view for the chain. If the chain is an audio chain (e.g. main mixbus) and only has Sooperlooper plugin then this will be the processor that is shown.

This could possibly be further enhanced with a CUIA to select the active processor within a chain or adding an extra (optional) parameter to _chain_control_ that selects the processor but for now I will close this ticket as there is a way to do the request.
