### ISSUE TITLE
Misleading terms in advanced MIDI settings

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#845]
It took me a while to figure out that "Enable System Messages (Transport)" actually enables routing of these messages from the inputs to the outputs. My assumption was that this only relates to the reception and generation of transport messages, but not routing. On the other hand we have the option "Route MIDI to Output Ports". For me this usage of "MIDI" is generic and thus implies System Realtime (Transport!) events. So with this option disabled, I would not expect a single clock message being routed. I would suggest the following options:
- Enable MIDI through -> This will route all MIDI messages without restrictions.
- Enable System Messages (Transport)  -> This only enables / disables Zynthian's use of System Messages, but not the routing.

And just in case the existing option for transport message is only controlling the routing, then I would simply use "Route System Messages (Transport)".

**Comment by jofemodo** [comment]
It's solved in testing. Please, test and confirm.
