### ISSUE TITLE
No way of performing MIDI learn in parameters without encoders.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#846]
**Describe the bug**
No way of performing MIDI learn in parameters without encoders.

**To Reproduce**
1. Go to Chain Parameter page
2. Click on 'Learn'
3. You need to choose an encoder to identify the parameter. This cannot be done with touchscreen only

**Expected behavior**
A mechanism should exist to select the parameter from the gang of four.

**Comment by jofemodo** [comment]
Add what about the pure-touch learning mechanism? I just tested and it worked like a charm ...

**Comment by riban-bw** [comment]
Indeed this is possible:

- Go to Chain Parameter page
- Click on 'Learn'
- Drag a controller with touch

The drag will change the controller value as per normal and identify it as the learning controller.
