### ISSUE TITLE
Potentially ear and equipment damaging noise when moving plugins up and down the audio chain

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#847]
**Describe the bug**
The audio engine is not muted when moving a plugin up- and down an effects chain. This can lead to potentially ear and equipment damaging noise.

**To Reproduce**
1. Load three plugins in an audio effects chain. Example: Calf Vintage Delay, Shiroverb, Calf Multi Chorus
2. Try to move the last plug in up the chain (e.g. the chorus before the reverb)
3. OUCH !

**Expected behavior**
The audio chain gets muted until the move and re-initialization of the plugins involved is complete.

**Setup:**
 - SD-image: Latest 1122
 - Hardware Config: Pi4 with external USB audio interface (TC Helicon Go Twin)

**Comment by riban-bw** [comment]
Good catch! I have implemented the rather blunt fix of muting the main output whilst audio routing occurs then restoring the main output's previous mute state. I also removed the audio routing stage if manipulating a non-audio chain.
