### ISSUE TITLE
QMIDINET not patched ...

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#850]
**Describe the bug**
Qmidinet isn't connecting on start up.
It appears in patchage but is not connected.  
Once it's connected in patchage it works 

**To Reproduce**

1. Go to admin
2. Select qmidinet
3. Run sequence 
4. See error Remote qmidinet devices do not recieve midi and zynthian doesn't accept it.

**Expected behavior**
qmidinet functionality over IP network

**Screenshots**
![qmidinet](https://user-images.githubusercontent.com/79083/220432122-b8505036-0087-4c6a-aa0d-bb775191e6a5.png)

**Setup:**
![zynthian-rack_qmidinet_bug](https://user-images.githubusercontent.com/79083/220432273-fdc75ce3-7e41-4962-8d71-6d1a7cea8075.png)

**Comment by riban-bw** [comment]
Fixed in _oram_.
