### ISSUE TITLE
A few new definitions for audo_config_handler.py

### ISSUE THREAD

**Issue by STGitUser** [zynthian/zynthian-issue-tracking#852]
**Is your feature request related to a problem? Please describe.**

Just a few new definitions for some current and some older audio interfaces.  
Three old interfaces are: Lexicon Alpha, Creative-EMU 0202, M-Audio M-Track Plus 2

The two new definitions are for audio chipsets commonly found in current USB audio interfaces and headphone adapters available on Amazon and elsewhere.  These are: GeneralPlus USB and  C-Media Electronics (Unitek Y-247A) USB

Here are the five new definitions that I have tested.  These are formatted to insert into the existing python file.

        ['Lexicon Alpha', {
                'SOUNDCARD_CONFIG': '',
                'JACKD_OPTIONS': '-P 70 -t 2000 -s -d alsa -d hw:Alpha -r 44100 -p 256 -n 2 -X raw',
                'SOUNDCARD_MIXER': ''
        }],
        ['Creative-EMU 0202', {
                'SOUNDCARD_CONFIG': '',
                'JACKD_OPTIONS': '-P 70 -t 2000 -s -d alsa -d hw:USB -r 44100 -p 256 -n 2 -X raw',
                'SOUNDCARD_MIXER': ''
        }],
        ['M-Audio M-Track Plus 2', {
                'SOUNDCARD_CONFIG': '',
                'JACKD_OPTIONS': '-P 70 -t 2000 -s -d alsa -d hw:Plus -r 44100 -p 256 -n 2 -X raw',
                'SOUNDCARD_MIXER': 'Mic Left,Mic Right,M-Audio M-Track Plus Left,M-Audio M-Track Plus Right'
        }],
        ['GeneralPlus USB', {
                'SOUNDCARD_CONFIG': '',
                'JACKD_OPTIONS': '-P 70 -t 2000 -s -d alsa -d hw:Device -r 44100 -p 256 -n 2 -X raw',
                'SOUNDCARD_MIXER': 'Speaker Left,Speaker Right,Mic Left,Mic Right,Auto Gain Control'
        }],
        ['C-Media Electronics (Unitek Y-247A) USB', {
                'SOUNDCARD_CONFIG': '',
                'JACKD_OPTIONS': '-P 70 -t 2000 -s -d alsa -d hw:Device -r 44100 -p 256 -n 2 -X raw',
                'SOUNDCARD_MIXER': ''
        }],

**Comment by jofemodo** [comment]
Thanks a lot! I just added the new definitions!
I have not these devices so i can't test with them. Please, if possible, update and test.

**Comment by jofemodo** [comment]
d366ee0
