### ISSUE TITLE
A zynthian left recording will use all the SSD 

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#853]
**Is your feature request related to a problem? Please describe.**
A zynthian left recording will use all the SSD and then be unable to load default snapshots when restarted in this condition

**Describe the solution you'd like**
There exists a predefined limit when recording will stop to allow workspace to remain

**Describe alternatives you've considered**
I manually delete the audio files recorded and default chains load again.

**Comment by jofemodo** [comment]
This is duplicated in:

https://github.com/zynthian/zynthian-issue-tracking/issues/801
