### ISSUE TITLE
Testing appears to be reading incoming midi messages wrong from Teensy

### ISSUE THREAD

**Issue by jpaskaruk** [zynthian/zynthian-issue-tracking#854]
I have created a midi controller on a Teensy. I can provide code and details, but it's using the `usbMIDI.sendNoteOn()` and `.sendNoteOff()` commands from the Teensy standard library. Drumstick Midi Monitor on my Arch machine shows the correct notes and velocities (0) for every switch and knob (standard controls, the intention is to recreate a bog standard Zynthian as a starting point). 

Here is what I see in Drumstick Midi Monitor for encoders up down and the eight switches:

> 0,0.0041,0:1,,ALSA Port subscribed,0:1,129:0,
> 1898,3.9561,0:1,,ALSA Port subscribed,24:0,129:0,
> 1898,3.9565,0:1,,ALSA Port subscribed,24:0,129:0,
> 
> 3513,7.3201,24:0,16,Note on,16,0,
> 3843,8.0071,24:0,16,Note on,17,0,
> 5150,10.7301,24:0,16,Note on,18,0,
> 5842,12.1742,24:0,16,Note on,19,0,
> 6790,14.1498,24:0,16,Note on,22,0,
> 7353,15.3224,24:0,16,Note on,23,0,
> 8029,16.7332,24:0,16,Note on,20,0,
> 8888,18.5209,24:0,16,Note on,21,0,
> 
> 9927,20.6821,24:0,16,Note on,90,0,
> 10021,20.8781,24:0,16,Note off,90,0,
> 10555,21.9911,24:0,16,Note on,91,0,
> 10651,22.1901,24:0,16,Note off,91,0,
> 11570,24.1061,24:0,16,Note on,92,0,
> 11676,24.3271,24:0,16,Note off,92,0,
> 12200,25.4181,24:0,16,Note on,93,0,
> 12319,25.6651,24:0,16,Note off,93,0,
> 
> 12911,26.8981,24:0,16,Note on,94,0,
> 12988,27.0601,24:0,16,Note off,94,0,
> 13459,28.0401,24:0,16,Note on,95,0,
> 13504,28.1351,24:0,16,Note off,95,0,
> 14085,29.3451,24:0,16,Note on,96,0,
> 14105,29.3861,24:0,16,Note off,96,0,
> 14762,30.7561,24:0,16,Note on,97,0,
> 14806,30.8471,24:0,16,Note off,97,0,
> 

And here is what I see in Zynthian's midi monitor:

> Encoders up down:
> CH#16 NOTE_OFF 16, Vel: 64
> CH#16 NOTE_OFF 17, Vel: 64
> CH#16 NOTE_OFF 18, Vel: 64
> CH#16 NOTE_OFF 19, Vel: 64
> CH#16 NOTE_OFF 20, Vel: 64
> CH#16 NOTE_OFF 21, Vel: 64
> CH#16 NOTE_OFF 22, Vel: 64
> CH#16 NOTE_OFF 23, Vel: 64
> 
> Encoder Buttons:
> CH#16 NOTE_OFF 90, Vel: 64
> CH#16 NOTE_OFF 90, Vel: 0
> CH#16 NOTE_OFF 91, Vel: 64
> CH#16 NOTE_OFF 91, Vel: 0
> CH#16 NOTE_OFF 93, Vel: 64
> CH#16 NOTE_OFF 93, Vel: 0
> CH#16 NOTE_OFF 92, Vel: 64
> CH#16 NOTE_OFF 92, Vel: 0
> 
> Other Buttons:
> CH#16 NOTE_OFF 94, Vel: 64
> CH#16 NOTE_OFF 94, Vel: 0
> CH#16 NOTE_OFF 95, Vel: 64
> CH#16 NOTE_OFF 95, Vel: 0
> CH#16 NOTE_OFF 96, Vel: 64
> CH#16 NOTE_OFF 96, Vel: 0
> CH#16 NOTE_OFF 97, Vel: 64
> CH#16 NOTE_OFF 97, Vel: 0
> 

I am on Testing branch, using a HifiBerry Dac+ for audio and a Waveshare 7" HDMI+USB monitor. Anecdotally, I have sent midi notes from this Teensy to multiple other devices, so I am pretty sure we have uncovered a genuine bug, and it looks like a bit size mismatch to me. 

I am active on the discourse as JTode if you need any logs or system files or the Teensy code, but as I said, it's all extremely standard stuff on that end.

**Comment by jpaskaruk** [comment]
If I am correct and this is a bug, please feel free to send me back some directives as to what files need to be modified to fix it, and I will have a go at taking care of my own bug. I would love that, seriously.

**Comment by riban-bw** [comment]
This is expected behaviour. You are sending note-on with zero velocity which MIDI 1.0 specification states should be interpreted as note-off.

**Comment by jpaskaruk** [comment]
Neat! There's a bit in the UI guide that looked to me like it suggested
sending vel 0 - I must have misunderstood the passage, but I assumed that
since velocity is not being used, and since we're using midi notes in a
not-playing-notes way, that it was ignored. I did not know that the
misattribution of the message type was built right into the spec.
