### ISSUE TITLE
Record SD Image ID within a file for each build

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#86]
It would be advantageous to be able to deduce which SD Image a device was derived from. This is particularly useful during fault diagnostics.

**Describe the solution you'd like**
During the SD Image build process, write details of the build to a file within the build, e.g. "2019-11-26-zynthianos-buster-lite-1.0.0".

**Describe alternatives you've considered**
It may be possible to derive this information from existing data within the build, e.g. content and create date of /etc/os-release:

```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@zynthian:~# cat /etc/issue
Raspbian GNU/Linux 10 \n \l

stat /etc/os-release
  File: /etc/os-release -> ../usr/lib/os-release
  Size: 21              Blocks: 0          IO Block: 4096   symbolic link
Device: b302h/45826d    Inode: 22273       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-10-19 22:27:23.194898489 +0100
Modify: 2019-09-09 14:42:06.000000000 +0100
Change: 2019-10-19 22:05:34.800116694 +0100
 Birth: -
```
**Additional context**
This would provide missing info for issue #85.

**Comment by jofemodo** [comment]
OK! It's done. I've added a file containing build timestamp and the platform for which it is optimized for.

**Comment by jofemodo** [comment]
I've added the build date to the webconf's dashboard and it will start showing something valid with the new images. BTW, also added temperature and wifi status ;-)

https://github.com/zynthian/zynthian-webconf/commit/498dad559cf3df295917e0223a96aca732acf935
