### ISSUE TITLE
Add MIDI Learn to Note Range & transpose 

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#861]
**Is your feature request related to a problem? Please describe.**
When in not learning mode allow a TR encoder to enter MIDI Learn and allow a specific MIDI note on this particular Chain to be allocated to a MIDI event so events can be generated from specific MIDI controllers and produced as MIDI note events.

This would aid MIDI trigger from switches that might only be able to generate specific and preset MIDI address, and the zynthian would fulfil it's swiss army objective of providing MIDI remapping.

**Comment by jofemodo** [comment]
Sorry. I don't understand the request, @wyleu! Could you explain the use-case?

**Comment by wyleu** [comment]
I've forgotten it, but it was insight at the time.

Adding general MIDI functionality on this page to modify MIDI streams so the transpose function could be mapped to a MIDI note to allow 12 bar blues type transposition in playing a sequence on this channel.
