### ISSUE TITLE
Snapshot rename doesn't update snapshot list on return.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#862]
**Describe the bug**
IF you save a new snapshot with a name when you return to the Snapshot list after clicking enter in Rename the snapshot list does not include the snapshot you have just added.

IT is however there if you re-enter the snapshort menu.

**To Reproduce**
1. Go to Snapshots 
2. Click on Save As New Snapshot
3.Enter Name
4. Press Enter
5. Added snapshot not reflected in list...

**Expected behavior**
I would expect to see the snapshot I have just added appear in the list as confirmation it has been successfully saved

**Screenshots**

I have just added snapshot fred to this system...

![zynthian-snapshot_list](https://user-images.githubusercontent.com/79083/229361610-aa2d7044-5d37-4199-98ea-8c26ce3f9b1d.png)

**Setup:**
![zynthian-rack-software](https://user-images.githubusercontent.com/79083/229361650-c303f260-0a5d-41ef-a575-24b4b4a2e36f.png)

**Comment by jofemodo** [comment]
This is already fixed.
