### ISSUE TITLE
After using the setBfree engine, sustain pedal remains on

### ISSUE THREAD

**Issue by linuxnow** [zynthian/zynthian-issue-tracking#866]
**Describe the bug**
Use a chain with setBfree, then change to another chain (sfizz, Pianoteq...)via MIDI PC and ZS3 and the sustain pedal remains on, no matter what you have in your ZS3 snapshot

**To Reproduce**
1. Configure a setBfree chain
2. Configure another chain with pianoteq or sfizz
3.  Save a subsnapshot with both chains with sustain pedal off
4. USe the setBfree chain
5. Switch to the other chain using ZS3
6. The sustain pedal remains on no matter how you saved your chain

**Expected behavior**
If I save the snapshoit without sustain, it should restore withourtsustain

**Setup:**
 - SD-image: testing
 - Hardware Config: v4.6
 - Software Version: latest

**Additional context**
If you recall the snapshot twice (send 2 MIDI PC) the  sustain pedal is set to the snapshot value.

I seems like when are recalling snapshots there are some params that are not recalled, I'm rporting the sustain pedal but I think that volume and some filters like resonance suffer the same problem, I will recheck

**Comment by linuxnow** [comment]
This still happens in 202305-16 image fully updated.
Seems like the sustain pedal value stored in the snapshot (off) is not loaded properly util you reccall the zs3 snapshot for the second time. setBfree does not have values for sustain pedal.

It's very annoying because when you are playing live you don''t want to recall to recall the snapshot twice and you don¡t want to rush to your sustain pedal to stop the sustained notes.

**Comment by linuxnow** [comment]
This bug is still there. No restoriung the sustain pedal (or any other value not present in the current preset) when recalling another preset sis very annoying in live performances.

**Comment by riban-bw** [comment]
I cannot reproduce this with the _oram_ branch. The steps to reproduce do not show any step where the sustain pedal is pressed. There is a step that says to use setBfree but not any specific operations. Are you saying that sustain gets asserted without ever having pressed a pedal?

Also, setBfree does not have sustain which is a bit confusing (but may be a clue to the issue you are experiencing.)

Please check if this is still occuring and add any extra steps required to reproduce.

**Comment by jofemodo** [comment]
In setBfree, sustain pedal is used to toggle rotary speed from slow to fast.
It seems to work in Oram.
