### ISSUE TITLE
Zynthian V4: Cannot update

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#867]
**Describe the bug**
If I try to update my ZV4 I see a "Stop-Sign"

**To Reproduce**
1. Go to "Software/Update"
2. 2. Go to "Update"
4. See error "Stop-Sign"

*
![Bildschirmfoto von 2023-04-29 13-38-37](https://user-images.githubusercontent.com/55761217/235300580-67ede904-0b6a-46be-9b0d-83fc7730a798.png)
*Screenshots**

**Setup:**
 - SD-image: 2021-09-25-zynthianos-stable
 - Hardware Config: Zynthian V4
 - Software Version

**Additional context**
The snapshots are not shown. See Picture 2
![Bildschirmfoto von 2023-04-29 13-43-41](https://user-images.githubusercontent.com/55761217/235300724-6c7bff9f-bf79-4b12-9e1f-2954b05284b5.png)

**Comment by jofemodo** [comment]
2021-09-25-zynthianos-stable is not updateable never more. You have to download and install the new stable image: 

https://os.zynthian.org/zynthianos-last-stable.zip

Regards,
