### ISSUE TITLE
Include DIGITS Phase Modulation Plugin

### ISSUE THREAD

**Issue by Jeremias-A-Queiroz** [zynthian/zynthian-issue-tracking#868]
Hello

The DIGITS plugin (http://www.extentofthejam.com/) is now available under the GNU license. It's a very nice plugin that rescues the synthesis of the late Casio CZ. I think this plugin (mainly because it's free software) would be a great addition to Zynthian's palette.

**Comment by jofemodo** [comment]
Yes, t would be a nice addition, but ti's not available as LV2 plugin, so we it can be run in zynthian.
Let's hope some brave coder port the code.
