### ISSUE TITLE
WiFi does not start in latest testing 20230512  zynthian-sys: testing (da5b0aa)

### ISSUE THREAD

**Issue by linuxnow** [zynthian/zynthian-issue-tracking#869]
**Describe the bug**
WiFi does not start

**To Reproduce**
1. Activate wifi via webconf
2. Command '/zynthian/zynthian-sys/sbin/set_wifi.sh on' returned non-zero exit status 255.

**Expected behavior**
WiFi scrip does not work

**Screenshots**

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
zyncoder: testing (7b35470)
zynthian-ui: [testing (88f763b)](https://github.com/zynthian/zynthian-ui/commit/88f763b8c470f395f4e4d3c06fa950859bbb1ca0)
zynthian-sys: [testing (da5b0aa)](https://github.com/zynthian/zynthian-sys/commit/da5b0aac74519b56b949393dc246531889cc9391)
zynthian-data: [testing (a6a7a59)](https://github.com/zynthian/zynthian-data/commit/a6a7a59245f87b8f8eb33e7adf4dfde51266e4e0)
zynthian-webconf: [testing (0ed9e62)](https://github.com/zynthian/zynthian-webconf/commit/0ed9e62425738bbdfa5f6ddad52ccb47bc822b22)

**Additional context**
This is the latest testing commit and software update as stated above.

**Comment by jofemodo** [comment]
I found the wifi issue. For some reason, a firmware update was triggered on the staging-2305’s first update. This shouldn’t had happened and it’s been solved now, but those who already did it, can solve the problem by running this command:

`apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel`

And then rebooting and updating again.

**Comment by linuxnow** [comment]
Works in latest testing!
