### ISSUE TITLE
Add arpeggiator

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#87]
It would be advantageous to add an arpeggiator to the Zynthian. An arpeggiator is a tool to allow the individual notes of a chord to be automatically played sequentially. This may be from lowest to highest note (up), highest to lowest (down), both (bounce), randomly or some more complex predefined pattern.

It would be good to be able to insert an arpeggiator in the MIDI path. Currently that may best be implemented with an LV2 plugin in MOD-UI but future implementation may allow the MIDI chain to be manipulated.

**Describe alternatives you've considered**
Arpeggiator may be implemented in external controllers like MIDI keyboards but this may not be available to all (in fact probably only a few) so adding to Zynthian is useful.
It could be implemented in code within the Zynthian MIDI handling but a separate plugin may prove more flexible.

**Additional context**
There are some arpegigator LV2 plugins available including [simple-arpeggiator-lv2](https://github.com/johanberntsson/simple-arpeggiator-lv2) and [QMidiArp](http://qmidiarp.sourceforge.net/qmidiarp_doc_en_arp.html).

I compiled simple-arpeggiator-lv2 but it seg faulted. I did not try to fix this for long so do not know how difficult it would be to make it work.

I installed QMidiArp package from Debian repository and copied to Zynthian LV2 plugin folder and it works fine. It does not support bounce (up & down) out of the box and the sequence editor is not exposed via LV2 but it provides the other basic arpeggiator patterns, allows sync to internal or external clock with control of internal clock rate, steps of timing (x1, x2, x4, etc) and more complex predefined patterns as well as other parameters I haven't investigated. This looks like a good contender. The bounce (up / down) pattern may be able to be added by using the full product on another machine, creating a pattern then saving it as a preset.

I recommend installing QMidiArp from Debian archive in standard Zynthian build.

**Comment by riban-bw** [comment]
Actually, one can launch QMidiArp X11 application on the Zynthian using X-forwarding and edit the patterns and preset on the box. This may not allow bounce to be implemented though so I may submit a feature request upstream for that. (I am quite surprised that such an obvious and commonly implemented feature is missing from an application that has far more complex features!)

**Comment by jofemodo** [comment]
With the implementation of zynthian-ui#243 and the "arpeggiator LV2-plugin", we could close this.  Of course, it could be improved, but we have a basic arppegiator.
