### ISSUE TITLE
Add Gate out reversed to zynaptik configuration 

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#870]
**Is your feature request related to a problem? Please describe.**
The Zynaptik board provides Data  out but this is only one polarity, since these could be used for generating both positive going and negative going transitions it would be beneficial to allow extra options in the drop down list to allow these to be reversed,. Similar to the Sustain pedal reverse found on many controllers.

**Describe alternatives you've considered**
Rewiring of connected devices requiring digital inverters to assert the correct transition. This could be fixed in software and configuration.

**Comment by riban-bw** [comment]
The logic is currently inverted, i.e. note-on command will trigger a logic low (0V) whilst note-off command will trigger a logic high (5V) on the gate output. As a minimum we should invert the logic so that the current implementation is correct. This is a bug. Subsequent enhancement to offer configurable invert logic is a nice to have that may be added later.

I am adding this to 2305 milestone for the inverted logic bug to be corrected. After this is fixed it can be taken off that milestone and the feature request can remain.

**Comment by riban-bw** [comment]
The same issue exists with gate inputs, i.e. a 5V will send a NOTE-OFF event. I can see the fix for the gate output in zynaptik.c:
```
void zynaptik_midi_to_cvout(jack_midi_event_t *ev) {
                if (zyncvouts[i].midi_event_temp!=(ev_data & zyncvouts[i].midi_event_mask)) continue;
 
                if (event_type==NOTE_ON && ev->buffer[2]>0) {
-                       //fprintf(stderr, "ZYNAPTIK MIDI TO CVGATE-OUT %d NOTE-ON => %d, %d\n", zyncvouts[i].midi_num, ev->buffer[1], ev->buffer[2]);
+                       fprintf(stderr, "ZYNAPTIK MIDI TO CVGATE-OUT %d NOTE-ON => %d, %d\n", zyncvouts[i].midi_num, ev->buffer[1], ev->buffer[2]);
                        if (zyncvouts[i].val>0) {
-                               digitalWrite(zynswitches[zyncvouts[i].midi_num].pin,1);
+                               digitalWrite(zynswitches[zyncvouts[i].midi_num].pin,0);
                        }
                        zyncvouts[i].val = ev->buffer[1]<<7;
                        //set_zynaptik_cvout(i, zyncvouts[i].val);
                        refresh_zynaptik_cvouts();
                        usleep(50);
-                       digitalWrite(zynswitches[zyncvouts[i].midi_num].pin,0);
+                       digitalWrite(zynswitches[zyncvouts[i].midi_num].pin,1);
                }
                else if (event_type==NOTE_OFF || event_type==NOTE_ON) {
-                       //fprintf(stderr, "ZYNAPTIK MIDI TO CVGATE-OUT %d NOTE-OFF => %d\n", zyncvouts[i].midi_num, ev->buffer[1]);
+                       fprintf(stderr, "ZYNAPTIK MIDI TO CVGATE-OUT %d NOTE-OFF => %d\n", zyncvouts[i].midi_num, ev->buffer[1]);
                        if (zyncvouts[i].val==ev->buffer[1]<<7) {
                                zyncvouts[i].val = 0;
                                //set_zynaptik_cvout(i, zyncvouts[i].val);
                                refresh_zynaptik_cvouts();
-                               digitalWrite(zynswitches[zyncvouts[i].midi_num].pin,1);
+                               digitalWrite(zynswitches[zyncvouts[i].midi_num].pin,0);
                        }
                }
...
```
but I haven't found the equivalent for the gate input yet.

**Comment by jofemodo** [comment]
It's solved by https://github.com/zynthian/zyncoder/commit/4d6f385f316ab75441c9469e8f06c58145c9fd94

**Comment by riban-bw** [comment]
Is there a configuration that can set the polarity of the GPI? Do we need to modify webconf?
