### ISSUE TITLE
Synths not loading / sounding

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#873]
**Describe the bug**
Several synths including Calf Monosynth and amsynth are not making any sound after loading.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a synth chain with Calf Monosynth
2. Play keyboard

**Expected behaviour**
Audio is heard from the output.

**Expected behaviour**
No audio is heard from the output.

**Setup:**
 - HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20, MCP23008@0x21, ADS1115@0x48
 - SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-05-15
Memory: 12% (239M/1849M)
SD Card: 42% (12G/29G)
Temperature: 54.0ºC
Overclock: None
 - MIDI
Profile: default.sh
Tuning: 440 Hz
Receive Mode: Stage (Omni On)
ZS3 Sub-SnapShots: On
MIDI to Output: Off
Master Channel: off
 - SOFTWARE
zyncoder: staging-2305 (49d1ce2)
zynthian-ui: staging-2305 (e347ab6)
zynthian-sys: staging-2305 (018a7ff)
zynthian-data: staging-2305 (a6a7a59)
zynthian-webconf: staging-2305 (fa466e7)

**Additional context**
Log errors:
```
May 16 14:26:16 zynthian1 startx[1645]: ERROR:zynthian_engine.proc_cmd: Can't exec engine command: preset http://calf.sourceforge.net/factory_presets#monosynth_Barkline => End Of File (EOF). Exception style platform.
May 16 14:26:16 zynthian1 startx[1645]: <pexpect.pty_spawn.spawn object at 0xebc75b10>
May 16 14:26:16 zynthian1 startx[1645]: command: /usr/local/bin/jalv.gtk
May 16 14:26:16 zynthian1 startx[1645]: args: ['/usr/local/bin/jalv.gtk', '--jack-name', 'Calf_Monosynth-00', 'http://calf.sourceforge.net/plugins/Monosynth']
May 16 14:26:16 zynthian1 startx[1645]: buffer (last 100 chars): b''
May 16 14:26:16 zynthian1 startx[1645]: before (last 100 chars): b'preset http://calf.sourceforge.net/factory_presets#monosynth_Barkline\r\n'
May 16 14:26:16 zynthian1 startx[1645]: after: <class 'pexpect.exceptions.EOF'>
May 16 14:26:16 zynthian1 startx[1645]: match: None
May 16 14:26:16 zynthian1 startx[1645]: match_index: None
May 16 14:26:16 zynthian1 startx[1645]: exitstatus: None
May 16 14:26:16 zynthian1 startx[1645]: flag_eof: True
May 16 14:26:16 zynthian1 startx[1645]: pid: 3801
May 16 14:26:16 zynthian1 startx[1645]: child_fd: 42
May 16 14:26:16 zynthian1 startx[1645]: closed: False
May 16 14:26:16 zynthian1 startx[1645]: timeout: 20
May 16 14:26:16 zynthian1 startx[1645]: delimiter: <class 'pexpect.exceptions.EOF'>
May 16 14:26:16 zynthian1 startx[1645]: logfile: None
May 16 14:26:16 zynthian1 startx[1645]: logfile_read: None
May 16 14:26:16 zynthian1 startx[1645]: logfile_send: None
May 16 14:26:16 zynthian1 startx[1645]: maxread: 2000
May 16 14:26:16 zynthian1 startx[1645]: ignorecase: False
May 16 14:26:16 zynthian1 startx[1645]: searchwindowsize: None
May 16 14:26:16 zynthian1 startx[1645]: delaybeforesend: 0
May 16 14:26:16 zynthian1 startx[1645]: delayafterclose: 0.1
May 16 14:26:16 zynthian1 startx[1645]: delayafterterminate: 0.1
May 16 14:26:16 zynthian1 startx[1645]: searcher: searcher_re:
May 16 14:26:16 zynthian1 startx[1645]:     0: re.compile(b'\n> ')
```

**Comment by riban-bw** [comment]
VNC is enabled. It seems that jalv.gtk is not working properly. It exits after logging `Trace/breakpoint trap`.

**Comment by jofemodo** [comment]
Could it be this change to jalv engine?

https://github.com/zynthian/zynthian-ui/commit/88f763b8c470f395f4e4d3c06fa950859bbb1ca0

It would be easy to revert.
