### ISSUE TITLE
x42 Instrument Tuner should be enabled by default

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#875]
**Describe the bug**
We should have the x42 Instrument Tuner LV2 plugin enabled so that it appears in the list of plugins by default. We have worked on this to make it work well and it is a valuable plugin so should be one of the plugins enabled out-of-the-box.

**Comment by jofemodo** [comment]
https://github.com/zynthian/zynthian-sys/commit/4ad1ae341bae5820edc4cbcacea6b31cb26574f2
