### ISSUE TITLE
ALL NOTES OFF does not clear CV/Gate outputs

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#876]
**Describe the bug**
Sending ALL NOTES OFF does not clear any CV/Gate connected devices.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect an analogue synth to Zynaptik CV/Gate output
2. Play and hold a note
3. Trigger ALL NOTES OFF from Zynthian

**Expected behaviour**
Gate should clear and analogue synth should silence.

**Actual behaviour**
Gate remains asserted and analogue synth continues to sound.

**Setup:**
 - HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: [Behringer UMC1820](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
I2C: [MCP23017@0x20, MCP23008@0x21, ADS1115@0x48, ADS1115@0x4A, MCP4728@0x60](http://zynthian1.4sar/hw-wiring)
 - SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-05-15
Memory: 17% (325M/1849M)
SD Card: 42% (12G/29G)
Temperature: 56.4ºC
Overclock: [None](http://zynthian1.4sar/hw-options)
 - MIDI
Profile: [default.sh](http://zynthian1.4sar/ui-midi-options)
Tuning: [440 Hz](http://zynthian1.4sar/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://zynthian1.4sar/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://zynthian1.4sar/ui-midi-options)
MIDI to Output: [On](http://zynthian1.4sar/ui-midi-options)
Master Channel: [off](http://zynthian1.4sar/ui-midi-options)
 -  SOFTWARE
zyncoder: [testing (3436386)](https://github.com/zynthian/zyncoder/commit/3436386b8e84585b1584c20cb7cc353d823b8bd8)
zynthian-ui: [testing (ba026fa)](https://github.com/zynthian/zynthian-ui/commit/ba026fa72475d333e266766697467d7868893901)
zynthian-sys: [testing (ea11b93)](https://github.com/zynthian/zynthian-sys/commit/ea11b9360e71698595ba113386e958147c1f81d6)
zynthian-data: [testing (a6a7a59)](https://github.com/zynthian/zynthian-data/commit/a6a7a59245f87b8f8eb33e7adf4dfde51266e4e0)
zynthian-webconf: [testing (fa466e7)](https://github.com/zynthian/zynthian-webconf/commit/fa466e7c4804b9a3dc9f8344280ba939ec240108)

**Additional context**
This is with recent patches applied to fix CV/Gate output including monophonic MIDI.

**Comment by riban-bw** [comment]
zynaptik_midi_to_cvout filters events based on the zyncvouts midi_event_mask which makes it tricky to react to CC 120/123 for CV/Gate (note-on/off) configured outputs. We may need some more logic. This may also allow other controls to pass, e.g. pitchbend.

**Comment by jofemodo** [comment]
It's implemented now. See:

https://github.com/zynthian/zynthian-ui/commit/c3a877cf5a46e5de5a2b2bd21561c8e4e925b104
