### ISSUE TITLE
WaveShare 3.5B V2, rotated display

### ISSUE THREAD

**Issue by janbonisch** [zynthian/zynthian-issue-tracking#885]
**WaveShare 3.5B V2**
The display does not work properly, the splashscreen is rotated and then the user interface is also rotated, a part is missing, it cannot be used.

**To Reproduce**
Make a new image from version 2023-06-03, then use webconfig to set the WaveShare 3.5B V2 display. 

**Expected behavior**
A properly oriented and usable user interface is expected.

**Setup:**
 - [SD-image 2023-06-03](https://os.zynthian.org/2023-06-03-zynthianos-stable-2306.zip)
 - Hardware Config: Raspberry Pi 4 Model B 8GB, IQaudIO Pi-Digi+, https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(B)
 - Software Version:
zyncoder: stable (44bbd40)
zynthian-ui: stable (c300c4d)
zynthian-sys: stable (ced7923)
zynthian-data: stable (052465e)
zynthian-webconf: stable (eb278db)

**Additional context**
After a short research, it was found that the display configuration must be set as follows:
<pre>dtoverlay=waveshare35b-v2:rotate=90,swapxy=1,invertx=1</pre>
instead of the original:
<pre>dtoverlay=waveshare35b-v2
#dtoverlay=waveshare35b-v2:rotate=90,swapxy=1,invertx=1
#dtoverlay=ads7846,cs=1,penirq=17,penirq_pull=2,speed=1000000,keep_vref_on=1,swapxy=1,pmax=255,xohms=60,xmin=200,xmax=3900,ymin=200,ymax =3900
</pre>
Why are there commented lines that don't use in the configuration?

**Comment by jofemodo** [comment]
Some people use the display physically rotated. Simply uncomment and use the configuration that works for you. If i change it, other users will complain about it.
