### ISSUE TITLE
MIDI playback transport is not enabled when audio player shown

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#888]
**Describe the bug**
The "ALT" behaviour of transport buttons is to control the MIDI player but this is not true when the audio player is shown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open audio player
2. Press "ALT" to enable alt mode
3. Press play button

**Expected behaviour**
MIDI player starts playing.

**Actual behaviour**
Audio player starts playing.

**Setup:**
 - HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://zynthian-v5b/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5b/hw-display)
Wiring: [V5](http://zynthian-v5b/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://zynthian-v5b/hw-wiring)
Profile: [v5](http://zynthian-v5b/hw-wiring)
 - SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-06-03
Memory: 9% (361M/3839M)
SD Card: 45% (13G/29G)
Temperature: 55.0ºC
Overclock: [Maximum](http://zynthian-v5b/hw-options)
 - MIDI
Profile: [default.sh](http://zynthian-v5b/ui-midi-options)
Tuning: [440 Hz](http://zynthian-v5b/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://zynthian-v5b/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://zynthian-v5b/ui-midi-options)
MIDI to Output: [Off](http://zynthian-v5b/ui-midi-options)
Master Channel: [off](http://zynthian-v5b/ui-midi-options)
 - SOFTWARE
zyncoder: [stable (6d54a48)](https://github.com/zynthian/zyncoder/commit/6d54a482e5bd00e3a05e52769045aad6300f1cc0)
zynthian-ui: [stable (67b6afa)](https://github.com/zynthian/zynthian-ui/commit/67b6afab22a90c42fe09f12628ba3775e9c618f1)
zynthian-sys: [stable (c0f40e8)](https://github.com/zynthian/zynthian-sys/commit/c0f40e82bbed51150a98203ea687034156dfbe15)
zynthian-data: [stable (052465e)](https://github.com/zynthian/zynthian-data/commit/052465ea7283287b8eeb5a15c11046fbcad24465)
zynthian-webconf: [stable (d92c31d)](https://github.com/zynthian/zynthian-webconf/commit/d92c31d304acd97e0a13bbece283093ed50b1774)

**Additional context**
It seems reasonable that when in the audio player the transport buttons control audio player but the ALT transport buttons control the MIDI player.

**Comment by jofemodo** [comment]
"ALT" behavior is contextual and can be defined for each screen. Anyway, there is an ALT global default, that is "MIDI transport".
