### ISSUE TITLE
Bug: stable 2306: no usb automount 

### ISSUE THREAD

**Issue by luemmel76** [zynthian/zynthian-issue-tracking#890]
**Describe the bug**
no automount of usb disk, `lsblk` in the terminal list it as sda1

**To Reproduce**
1. write stable-2306.img on microsd
2. stick usb disk into usb port
3. bott system and wait till setup is complete
4. look in web ui main screen under system there is no USB Storage

**Expected behavior**

**Screenshots**

**Setup:**
**SD-image:** 2023-06-03-zynthianos-stable-2306.img

**Hardware Config**
Raspberry Pi 4 Model B Rev 1.4
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage

**Software Version**
zyncoder: stable (44bbd40)
zynthian-ui: stable (c300c4d)
zynthian-sys: stable (ced7923)
zynthian-data: stable (052465e)
zynthian-webconf: stable (eb278db)

**Additional context**
with 2022-11-01-zynthianos-stable-2211.img the usb automount works.

**Comment by luemmel76** [comment]
In the meantime i've testet two other images from https://os.zynthian.org/test/ :

- 2023-05-17-zynthianos-staging-2305.img
- 2023-06-12-zynthianos-stable_2306.img

Result: both without usb disk automount

Something must have changed between 2022-11-01-zynthianos-stable-2211.img and 2023-05-17-zynthianos-staging-2305.img ...

**Comment by jofemodo** [comment]
To resume, kernel masters decided to alter the way udev works and now the user-space scripts triggered by udev rules are jailed in a sandbox without possibility of mounting nor accessing the network. A new paradigm has emerged: udisks2+udevil+devmon, so i've proceeded to replace usbmount on zynthian and reconfigure everything and make the needed changes so everything can work with the new methodology.
