### ISSUE TITLE
Add AIDA-X plugin

### ISSUE THREAD

**Issue by danmigdev** [zynthian/zynthian-issue-tracking#896]
**Is your feature request related to a problem? Please describe.**
Missing AIDA-X plugin is a great plugin that could attract guitar players in the Zynthian world. Currently it is more flexible than NAM since it has more parameters to control amp tone.

**Comment by jofemodo** [comment]
Integration is still incomplete, but the plugin is added and works nicely. For using it from the zynthian UI, some presets must be created using the native GUI (VNC).
