### ISSUE TITLE
no delay time synchronizing of "calf vintage delay" plugin

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#900]
**Describe the bug**
Calf Vintage Delay plugin will not be synchronized to external clock (jack transport)

**To Reproduce**
1. using the calf vintage delay as an fx within audio chain
2. Setting to external midi clock synching in Tempo menu. An external source delivers Start, Stop and Clock Midi Events.
3. Setting of calf vintage delay to “Host Sync”
4. Start the external midi clock

The audible delay has always the same delay time independent of the external tempo. It is only influenced by the knob “Host BPM”. BTW, this knob should not be there...

**Expected behavior**
BPM synchronized with external clock.

**Setup:**
- Hardware config: V4 regular zynthian
- stable release
- 
**Additional context**
On a desktop computer the following was observed: Calling the calf vintage delay via "carla" plugin manager, the expected behaviour was observed; calling it via "jalv" no syncing was observed.

**Comment by jofemodo** [comment]
https://discourse.zynthian.org/t/syncing-calf-delay-plugin-to-external-midi-clk-not-working/8330

**Comment by jofemodo** [comment]
I've patched jalv for solving this issue:

https://github.com/zynthian/jalv/commit/364bef1ed74b43f1855e8b9f04aacf79f623371a

It works, but i'm not sure it's a good solution. The documentation about LV2 sync is quite "thin".
