### ISSUE TITLE
Bookworm aarch64 build

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#907]
+ Partition expansion doesn't work.
+ Webconf's MIDI log  is broken in bullseye aarch64 build. It seems webconf can't open MIDI ports (library problem?)

**Comment by jofemodo** [comment]
Webconf's MIDI log is fixed!

**Comment by riban-bw** [comment]
I think MIDI log is broken again.

**Comment by jofemodo** [comment]
And it's fixed again. Also webconf terminal and others.
Indeed, bookworm-aarch64 migration is basically finished and a testing image has been released (oram).
Now we need to debug it to perfection.
