### ISSUE TITLE
Error setting brightness

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#908]
**Describe the bug**
When Zynthian starts it logs an error:
```
WARNING:zynthian_gui_brightness_config.init_ctrls: Can't set display brightness!
```

**To Reproduce**
1. Monitor logs
2. Start Zynthian

**Expected behavior**
No error message

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: [Behringer UMC1820](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48](http://zynthian1.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-06-01
Memory: 7% (136M/1872M)
SD Card: 54% (15G/29G)
Temperature: 53.5ºC
Overclock: [Medium](http://zynthian1.4sar/hw-options)
- MIDI
Profile: [default.sh](http://zynthian1.4sar/ui-midi-options)
Tuning: [440 Hz](http://zynthian1.4sar/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://zynthian1.4sar/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://zynthian1.4sar/ui-midi-options)
MIDI to Output: [On](http://zynthian1.4sar/ui-midi-options)
Master Channel: [off](http://zynthian1.4sar/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2736d73)](https://github.com/zynthian/zyncoder/commit/2736d7366767028274e919469b289d378c67a86e)
zynthian-ui: [testing (18047f1)](https://github.com/zynthian/zynthian-ui/commit/18047f113c5354f29148f032da99469e198464df)
zynthian-sys: [testing (5b85b59)](https://github.com/zynthian/zynthian-sys/commit/5b85b59e007d38a163a0fef8717bdbb7be60e361)
zynthian-data: [testing (1321e5d)](https://github.com/zynthian/zynthian-data/commit/1321e5d1ce0d75ef8963bf0f0c9a00218c748bb5)
zynthian-webconf: [testing (15682e4)](https://github.com/zynthian/zynthian-webconf/commit/15682e4ac91c65c3b4158a80af1671dc94dc7b33)

**Additional context**
The error occurs in `set_display_brightness()` because the file (device) `'/sys/class/backlight/rpi_backlight/brightness'` does not exist.

**Comment by riban-bw** [comment]
Should there be a change to sys to enable / install the backlight brightness device?

**Comment by riban-bw** [comment]
Indeed - the result is that the LEDs dim but the display does not.

**Comment by jofemodo** [comment]
If the display doesn't support brightness adjustment (i.e. there is no kernel support for it), it gives a "warning".
The brightness screen autodetect this and it's hidden in the admin menu. For me, it's OK like this, but if you want to propose an improvement, my ears are open ;-)
