### ISSUE TITLE
amsynth in MOD-UI crashes Zynthian

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#91]
**Describe the bug**
Attempts to ad amsynth to MOD-UI result in Zynthian restarting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Within MOD-UI, add amsynth to pedalboard
2. See error

**Expected behaviour**
amsynth plugin is added to pedalboard and operates correctly.

**Actual behaviour**
Zynthian restarts.

**Setup:**
SD-image
Buster nightly 2019-10-20 updated 2019-11-27

HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ light
Display: Sainsmart 1.8
Wiring: I2C_HWC
GPIO Expander: No detected

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (c02b3ce)
zynthian-sys: master (c16eb29)
zynthian-data: master (d7648f7)
zynthian-webconf: master (813b47d)

**Additional context**
It looks like amsynth is properly available for MOD-UI [see here](https://pedalboards.moddevices.com/plugins/aHR0cDovL2NvZGUuZ29vZ2xlLmNvbS9wL2Ftc3ludGgvYW1zeW50aA==)

**Comment by jofemodo** [comment]
It's solved on recent SD images that install amsynth from KVX repos.
