### ISSUE TITLE
When changing repositories, Webconf puts up a Reboot button in red bar, which invites the user to interrupt the update while running - possibly making Zynthian unable to boot!

### ISSUE THREAD

**Issue by tunagenes** [zynthian/zynthian-issue-tracking#911]
**Describe the bug**
When changing repositories, Webconf puts up a Reboot button in red bar, which invites the user to interrupt the update while running - possibly making Zynthian unable to boot!

**To Reproduce**
In WebConf - from the “SOFTWARE” menu at the top, select “Repositories”,
click the “Advanced view” and unclick “Stable”,
then select testing from all the pullown menus,
observe that the red bar with reboot button is popped up while the update is running.

**Expected behavior**
There are a wide variety of ways to fix this and I don't want to create a lot of work.  Thoughts:
simple fix - just don't put up the reboot button.  Or have a warning message next to it.
if it's easy to know when the update is finished - put it up then.  or
put up a checkbox to reboot when completed.

**Comment by jofemodo** [comment]
It's already solved.
