### ISSUE TITLE
Users should be warned about data corruption risk when using recording to SDCard

### ISSUE THREAD

**Issue by henning** [zynthian/zynthian-issue-tracking#913]
**Is your feature request related to a problem? Please describe.**

Audio Recording to SDCard instead of external USB stick can lead to data corruption of the SDCard in some, probably rare but possible cases. That can mean data los of everysthing the users created since they made the last backup of the SDCard.

This situation is mentioned in the documentation([Zynthian_UI_User_Guide_-_V1/V4](https://wiki.zynthian.org/index.php/Zynthian_UI_User_Guide_-_V1/V4) and [Zynthian_UI_User_Guide_(oldstable-2109)](https://wiki.zynthian.org/index.php/Zynthian_UI_User_Guide_(oldstable-2109)) - but not in the latest V5 docs) , but it's not guaranteed that users always read this part and are aware of it. 
Also, it can happen that they dont realize that their USB stick isn't properly inserted or connected for some reason.

This has been discussed for example in 
https://discourse.zynthian.org/t/is-recording-to-sdcard-stilll-dangerous/8663/10

**Describe the solution you'd like**

There should be a warning dialog informing the user of the possible risk, so they can make an informed decision to take the risk.

The users should have the option to accept the risk once right now, or forever and not being warned again, this decision should be saved in the device settings.

**Describe alternatives you've considered**

The only other alternative would be to ensure in other ways that data corruption can not happen at all. 
That might mean at least to solve #801 where the corruption can happen due to a full disk, but there might also be other cases.

Maybe more research would be needed to understand the cause of the data corruption. 
Maybe using a more stable(journaling)  filesystem on the sdcard *could* help - but it's probably not very easy to switch to something like ext4 or btrfs, and it will make accessing the SDCard data e.g. for backups by users that dont use Linux on their Desktop machines very difficult.

The dialog is currently the thing that is the simplest and fastest to implement.

**Comment by riban-bw** [comment]
I would prefer to avoid warnings for unlikely and avoidable risks. We should look at ways to reduce sick risks. I think development effort is better targeted at making the device work reliably and robustly.

**Comment by henning** [comment]
Short: if you think this issue should be closed and things approached differently, I'm fine with it.

Longer background:

I totally agree it's better to make sure the that no data corruption happens than inform users about the possibility.

In the case at hand I saw the warning in the wiki documentation and hence my way of thinking is: if this risk is worth to be documented then it seems to be relevant enough that I as a user must be aware of it, even when not having read that specific sentence in the documentation. 

I also wanted to try to implement it myself, but realized it's not as easy as I thought to get started with development - I wanted to setup a local development environment, but came to a point where it seemed that I cannot run code easily outside of the real device for development testing. I wanted to come back to the forum and ask for advice about this, but didn't find the time for it...

In the meantime i also tried the usage of the usb storage and it worked out of the box, but it's lacking some user feedback so the user knows that the usb storage they put in is really working and used by zynthian and not dropped, e.g for being wrongly formatted etc. But that's another case.

**Comment by riban-bw** [comment]
Thanks for all this useful info and feedback. I recommend disucssing development environments in the forum. I will close this ticket because I think the risk of corruption is low and it would be cumbersome to implement some kind of warning system.
