### ISSUE TITLE
Headphones control (and audio output) is missing in the latest stable.

### ISSUE THREAD

**Issue by multim0** [zynthian/zynthian-issue-tracking#914]
**Describe the bug**
After flashing new image with stable 2308 RB Pi headphones as debug audio output is not available anymore.
It is not showed both on audio outputs screen and in admin menu as toggle option.

I've found out that zynthian_engine_alsa_mixer.py [stable branch](https://github.com/zynthian/zynthian-ui/blob/3ce8a5e0f22d4007a5460f61869678b5c78d6f69/zyngine/zynthian_engine_alsa_mixer.py#L148) exception is thrown:
`AttributeError: '/home/pi/zyncoder/build/libzyncore.so: undefined symbol: set_hpvol'`
For now I've dirty removed this new check `not callable(lib_zyncore.set_hpvol) and` and this workaround seems to result in both RB Pi headphones option displayed in admin menu and on audio outputs screen. Output is sending signal after toggling option in admin menu.

**Expected behavior**
1) Using RB Pi headphone output should be available as a custom option (as before).
2) In case of error it should be logged in ui logs

**Screenshots**
![New-stable-audio-stage-2023-10-28-110731](https://github.com/zynthian/zynthian-issue-tracking/assets/36331301/338ea03f-9589-4aab-a218-9469b4053cfd)

**Setup:**
Image Version:
 - stable (2023-08-25-zynthianos-stable-2308.img)

Hardware Version:
 - V4.3 with HifiBerry DAC+ ADC STAGE

 Software Version:
- zyncoder: stable (83acc8b)
- zynthian-ui: stable (3ce8a5e)
- zynthian-sys: stable (37e06cc)
- zynthian-data: stable (1321e5d)
- zynthian-webconf: stable (f7d0f1e)

**Comment by multim0** [comment]
From what I've found for now, it seems that `lib_zyncore.set_hpvol` is only available in zyncoder library built for V5 (zyncontrol_v5.c), and not for V4.

I do not feel strong in C/python interop to provide a PR with fix, but it seems that there is a need to check for zynthian (or library) version when the RB Pi headphones are initialized.

**Comment by jofemodo** [comment]
Now it seems to be totally solved ;-)
