### ISSUE TITLE
Rename audio capture names

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#917]
**Is your feature request related to a problem? Please describe.**
The audio inputs are described as "Audio Capture" and "system:capture_1". This is not common language used by musicians, producers, etc.

**Describe the solution you'd like**
Rename the "Audio Capture" menu as "Audio Inputs".
Rename "system:capture_x" inputs as "Input 1", "Input 2", etc.

**Additional context**
This is likely to require some rules to handle different audio devices but mostly we are dealing with system:capture_x inputs which could be programatically renamed to replace "system:capture_" with "Input ".

**Comment by jofemodo** [comment]
Let's do it, although "system capture" is pretty clear to me ;-)

**Comment by riban-bw** [comment]
In fact this is already mostly done. We now have:

Chain options menu entries: 
- Audio In
- Audio Out

Audio In menu title: "Capture Audio from..."
Audio Out menu title: "Send Aduio to..."

Audio Input list entries: "Audio Input x"
Audio Output list entries: "Audio Output x"

I think this works well, even the "Capture Audio from" seems okay in this context.
