### ISSUE TITLE
LaunchKey Mini not triggering zynpad

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#919]
**Describe the bug**
Plugging in a Launchkey Mini to Zynthian does detect and configure the Launchkey to show the zynpad states but pressing a pad on the Launchkey Mini does not trigger pads in Zynthian.

**To Reproduce**
1. Plugin in Launchkey Mini
2. If you are lucky it is detected by zynthian and configured - this does not always happen!
3. Show Zynpad screen
4. Observe that Launchkey Mini buttons are configured to mimic Zynpad pads
5. Press pad in Zynpad - sequence starts and Launchkey pad starts to pulse (this can sometimes fail or take many seconds to react!)
6. Press pad on Launchkey Mini

**Expected behaviour**
Zynpad starts and stops sequences when Launchkey Mini pad is pressed

**Actual behaviour**
Zynpad ignores Launchkey Mini pad presses. Configuration of Launchkey Mini is intermittent / unreliable. Launchkey Mini reaction to Zynpad press is unreliable / slow.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://192.168.1.110/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://192.168.1.110/hw-display)
Wiring: [V5](http://192.168.1.110/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://192.168.1.110/hw-wiring)
Profile: [v5](http://192.168.1.110/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-08-25
Memory: 6% (233M/3839M)
SD Card: 50% (14G/29G)
Temperature: 47.7ºC
Overclock: [Maximum](http://192.168.1.110/hw-options)
- MIDI
Profile: [default.sh](http://192.168.1.110/ui-midi-options)
Tuning: [440 Hz](http://192.168.1.110/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.1.110/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://192.168.1.110/ui-midi-options)
MIDI to Output: [On](http://192.168.1.110/ui-midi-options)
Master Channel: [off](http://192.168.1.110/ui-midi-options)
- SOFTWARE
zyncoder: [testing (7ada795)](https://github.com/zynthian/zyncoder/commit/7ada795dfa0ab269bba18345d9712d64231c0c65)
zynthian-ui: [testing (5d8b779)](https://github.com/zynthian/zynthian-ui/commit/5d8b779ceeddccc902f4139fda8b60f7d532a3a7)
zynthian-sys: [testing (ad43f0a)](https://github.com/zynthian/zynthian-sys/commit/ad43f0abeaf8d08b689da5e8663d15e81589416d)
zynthian-data: [testing (1321e5d)](https://github.com/zynthian/zynthian-data/commit/1321e5d1ce0d75ef8963bf0f0c9a00218c748bb5)
zynthian-webconf: [testing (1d12e3f)](https://github.com/zynthian/zynthian-webconf/commit/1d12e3fb5b4a57c09473d69665227c0486bd7d1f)

**Additional context**
This is on a V5 running _testing_ branch.

**Comment by riban-bw** [comment]
MIDI message sent by LaunchKey Mini on USB MIDI 2 interface when pad pressed:
```
CH#01 NOTE_ON 96, Vel: 78
```
and released:
```
CH#01 NOTE_OFF 96, Vel: 64
```

**Comment by jofemodo** [comment]
I suppose this is solved, right?
