### ISSUE TITLE
V5 USB type B connector not working

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#920]
**Describe the bug**
Plugging the V5 USB type-B connector to a host does not show a USB MIDI connection on either machine.

**To Reproduce**
1. Plug USB type B connector of V5 to a host PC (or USB type A connector of another Zynthian)

**Expected behavior**
Zynthian is shown as a USB MIDI device on the host computer. Host computer and Zynthian can send and receive MIDI to each other.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://192.168.1.110/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://192.168.1.110/hw-display)
Wiring: [V5](http://192.168.1.110/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://192.168.1.110/hw-wiring)
Profile: [v5](http://192.168.1.110/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-08-25
Memory: 6% (233M/3839M)
SD Card: 50% (14G/29G)
Temperature: 47.7ºC
Overclock: [Maximum](http://192.168.1.110/hw-options)
- MIDI
Profile: [default.sh](http://192.168.1.110/ui-midi-options)
Tuning: [440 Hz](http://192.168.1.110/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.1.110/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://192.168.1.110/ui-midi-options)
MIDI to Output: [On](http://192.168.1.110/ui-midi-options)
Master Channel: [off](http://192.168.1.110/ui-midi-options)
- SOFTWARE
zyncoder: [testing (7ada795)](https://github.com/zynthian/zyncoder/commit/7ada795dfa0ab269bba18345d9712d64231c0c65)
zynthian-ui: [testing (5d8b779)](https://github.com/zynthian/zynthian-ui/commit/5d8b779ceeddccc902f4139fda8b60f7d532a3a7)
zynthian-sys: [testing (ad43f0a)](https://github.com/zynthian/zynthian-sys/commit/ad43f0abeaf8d08b689da5e8663d15e81589416d)
zynthian-data: [testing (1321e5d)](https://github.com/zynthian/zynthian-data/commit/1321e5d1ce0d75ef8963bf0f0c9a00218c748bb5)
zynthian-webconf: [testing (1d12e3f)](https://github.com/zynthian/zynthian-webconf/commit/1d12e3fb5b4a57c09473d69665227c0486bd7d1f)

**Additional context**

**Comment by riban-bw** [comment]
I remade the cable connection and it seems to be working better but I am not convinced this was the issue as I have seen the interface work for a while then stop after the USB cable is removed and replaced. I will do some more testing...

**Comment by jofemodo** [comment]
Some advance? The units i've tested work OK.

**Comment by jofemodo** [comment]
I will close as i can't reproduce with my units. Perhaps the ribbon cable/adapter is not well tied or faulty.
