### ISSUE TITLE
Snapshots with favorite presets

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-issue-tracking#922]
I am using favorites on the dexed engine and have a snapshot which uses one of this favorite presets.

Then I was exporting the snapshot and imported it into a zynthian which hasn’t that sound configured as favorite.
The snapshot was loaded and the sound was there, but the preset in the mixer was void and if you enter the layer you don’t see the sound name either.
I had to look into the snapshot file to get that knowledge back and save it back.
Without looking into the code:
Maybe a serialization of the preset is used for comparison and the snapshot flag of the preset let’s the zynthian think, they are different sounds.

Steps to reproduce:
- Create Dexed Layer
- Create favorite preset
- Save as Snapshot
- Export Snapshot
- Use a different zynthian that has not this preset as favorite
- Import Snapshot

Now the snapshot is loaded and works, but the preset filename doesn't show.

**Comment by jofemodo** [comment]
Hi @mheidt !

This issue is solved in chain_manager branch.
As it's a low-impact issue and effort to cherry-pick from chain-manager is big, i'm not going to back-port it to current testing/stable.
