### ISSUE TITLE
Raspberry Pi5 Support for Zynthian

### ISSUE THREAD

**Issue by hlnorris3** [zynthian/zynthian-issue-tracking#926]
Pi5's are entering general distribution. Performance boost would a benefit to the headless users.

At least a "testing" branch that would have Pi5 support. 64 bit would be ideal but 32 bit would be fine for initial evaluation.

Can't think of an alternative.

Understood that ideally this would be part of a Zynthian hardware release supporting Pi5 but headless would be fine for some users in the interim.

**Comment by maarthome** [comment]
Hi All,

That would be great!! Zynthian on PI5!! :-)

Best wishes to you all,

Maarten

**Comment by riban-bw** [comment]
@jofemodo is working on RPi5 integration. There are many issues to resolve, both software and hardware. I will assign this to @jofemodo who may update with occasional progess reports.

**Comment by maarthome** [comment]
I'm eagerly awaiting this great adaptation
Thank you all for the great work!!

(I enjoy the anticipation just like that of the upcoming spring....it can't come soon enough)

Maarten

**Comment by riban-bw** [comment]
Raspberry Pi 5 is now mostly supported. This ticket is an aspirational request and is no longer serving any useful purpose, e.g. we are not tracking specific issues here. I will close this issue and we can open new tickets for any specific issues with RPi5 integration. @jofemodo I believe there remains an issue with audio input. Will you open a suitable ticket for that?
