### ISSUE TITLE
MIDI range/transpose not working as expected for chains

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#927]
**Describe the bug**
The MIDI key range and transpose now works on chains (zmops). If two chains are configured with the same MIDI channel but each has a different key range, one would expect each chain to only sound for notes within its own range.  Both chains sound on each round.

**To Reproduce**
1. Add two Fluidsynth chains on MIDI channel 1
2. Configure each chain with different key ranges
3. Configure a MIDI input as multitimbral
4. Play notes on MIDI keyboard in each key range

**Expected behaviour**
The notes played in first key range should sound only chain 1 and notes played in second key range should only sound chain 2.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://zynthian-v5.4sar/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5.4sar/hw-display)
Wiring: [V5](http://zynthian-v5.4sar/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://zynthian-v5.4sar/hw-wiring)
Profile: [v5](http://zynthian-v5.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-08-25
Memory: 24% (939M/3839M)
SD Card: 25% (14G/57G)
Temperature: 46.2ºC
Overclock: [Maximum](http://zynthian-v5.4sar/hw-options)
- MIDI
Profile: [default.sh](http://zynthian-v5.4sar/ui-midi-options)
Tuning: [440 Hz](http://zynthian-v5.4sar/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://zynthian-v5.4sar/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://zynthian-v5.4sar/ui-midi-options)
MIDI to Output: [Off](http://zynthian-v5.4sar/ui-midi-options)
Master Channel: [16](http://zynthian-v5.4sar/ui-midi-options)
- SOFTWARE
zyncoder: [chain_manager (c6d7b9e)](https://github.com/zynthian/zyncoder/commit/c6d7b9e07b405b006ac712f04c5de940eacafb44)
zynthian-ui: [chain_manager (336bb27)](https://github.com/zynthian/zynthian-ui/commit/336bb279a5c661c2e6e4c82035d1c817ce2a18e3)
zynthian-sys: [chain_manager (ba266d3)](https://github.com/zynthian/zynthian-sys/commit/ba266d3130e1ca1d8acde3800a0fa754095e8b4a)
zynthian-data: [chain_manager (b49acd6)](https://github.com/zynthian/zynthian-data/commit/b49acd6a83cb6b0a65800388cb900b5e370f23e4)
zynthian-webconf: [chain_manager (328e14e)](https://github.com/zynthian/zynthian-webconf/commit/328e14e5b2d00167fc539f7d99f69af244d383b7)

**Additional context**
This is best demonstrated in multitimbral mode.

**Comment by jofemodo** [comment]
Indeed, if you do so, both chains play unison. This is because of how multichain engines work. For fixing this, we should detach engine's internal MIDI channels from  chain MIDI channel. Not trivial.

**Comment by riban-bw** [comment]
This is improved by the introduction of MIDI Channel mode (or whatever it is called in admin menu) but still fails for engines that use a single instance and use MIDI channel to drive each voice, e.g. Fluidsynth, ZynAddSubFx.

**Comment by riban-bw** [comment]
The MIDI channel sent from zynmididrouter should be the MIDI channel that the processor expects, i.e. for Fluidsynth the first output should be driven from MIDI channel 1 and the second output from MIDI channel 2. Zynmidirouter should know this and use these channels for its zmop handling. The zmip handling is where the user facing MIDI channel configuration applies, i.e. when a user assigns 2 Fluidsynth chains to MIDI channel 1 then the enabled zmips on channel 1 should send towards both zmops but the zmop should then alter the channel number to suit its target processor.

The keysplit should apply after that zmop remapping of MIDI channel. 

The description of zynmidirouter that I wrote says:
```
Post-Output processing
======================

Before actually sending a message to an output, further processing is performed:

- Filter note range
- Transpose
- Filter on MIDI channel
- Filter on source / destination (routing)
- Translate MIDI channel
- Addition of pitchbend message if fine tuning enabled (currently a global configuration but could be per output)
```

Maybe we could move the "Filter note range" and "Transpose" to after "Translate MIDI channel".

**Comment by riban-bw** [comment]
Actually, looking at the code, we don't need to move things around. We just need to translate to the correct MIDI channel. `zmop->midi_chans` holds these channels and we may be able to populate them with the channels required by the processor, e.g. Fluidsynth's MIDI channel for output 1, 2, etc.

**Comment by riban-bw** [comment]
Ah! Actually I think that `zmop->midi_chans` is used for selecting which input channels are used. There may need to be a further translation to the MIDI channel that the processor requires. This feels wrong - like there is a transpose happening at the wrong point or an incorrect translastion. For example:

A chain that is set to MIDI channel 1 expects incoming MIDI channel 1 messages (in multi-timbral mode) or messages on any channel when any chain with the same MIDI channel is selected (in active mode). It is not the MIDI channel that is actually being used by active mode but instead the chain. The MIDI channel of the final messages should match what the corresponding processor expects.

**Comment by riban-bw** [comment]
I am testing a solution that uses the zmop `midi_chans[]` mapping. It seems to work but is likely to break / change behaviour of MIDI filters. I need to test further. The MIDI filters effected might not be needed...

**Comment by riban-bw** [comment]
I have pushed a dev branch `bug/927-midi_range` that fixes this. It uses zynmidirouter `zmop.midi_chans` to map the MIDI channel for Fluidsynth and ZynAddSubFx. Both of these synths now use 1-to-1 mapping of MIDI channel to part which means that Fluidsynth can use its default routing.

This works well to solve this problem and I haven't yet found any regression but this needs more testing and review. @jofemodo please review.

**Comment by jofemodo** [comment]
I just implemented the same for Linuxsampler. Also added a "reset" in the base class to avoid problems when replacing engine.
