### ISSUE TITLE
zynthian_ctrldev_base: `init()` not called on multiple inheritance

### ISSUE THREAD

**Issue by oscaracena** [zynthian/zynthian-issue-tracking#932]
**Describe the bug**

The class `zynthian_ctrldev_base` defines a method called `init()`, which is called at the end of `__init__()`. There are two more classes that inherits from `zynthian_ctrldev_base`: `zynthian_ctrldev_zynpad` and `zynthian_ctrldev_zynmixer`, and both overrides the `init()` method.

If you create a third class which inherits from `zynthian_ctrldev_zynpad` AND `zynthian_ctrldev_zynmixer`, only the `init()` of the first inherited class will be called. Interesting enough, the constructor of all super-classes is called.

This avoids, for example, the registration of the corresponding signals (which is done in `init()`).

---

A way of fixing this is by adding `super().init()` at the end of `init()` in all derived classes:

```diff
diff --git a/zyngine/ctrldev/zynthian_ctrldev_base.py b/zyngine/ctrldev/zynthian_ctrldev_base.py
index 292a959b..1303b8dd 100644
--- a/zyngine/ctrldev/zynthian_ctrldev_base.py
+++ b/zyngine/ctrldev/zynthian_ctrldev_base.py
@@ -54,7 +54,7 @@ class zynthian_ctrldev_base:
        # Initialize control device: setup, regisater signals, etc
        # It *SHOULD* be implemented by child class
        def init(self):
-               logging.debug("Init() for {}: NOT IMPLEMENTED!".format(type(self).__name__))
+               self.refresh()
 
        # End control device: restore initial state, unregister signals, etc
        # It *SHOULD* be implemented by child class
@@ -102,10 +102,10 @@ class zynthian_ctrldev_zynpad(zynthian_ctrldev_base):
                super().__init__(state_manager, idev_in, idev_out)
 
        def init(self):
-               self.refresh()
                # Register for zynseq updates
                zynsigman.register_queued(zynsigman.S_STEPSEQ, self.zynseq.SS_SEQ_PLAY_STATE, self.update_seq_state)
                zynsigman.register_queued(zynsigman.S_STEPSEQ, self.zynseq.SS_SEQ_REFRESH, self.refresh)
+               super().init()
 
        def end(self):
                # Unregister from zynseq updates
@@ -170,10 +170,10 @@ class zynthian_ctrldev_zynmixer(zynthian_ctrldev_base):
                super().__init__(state_manager, idev_in, idev_out)
 
        def init(self):
-               self.refresh()
                zynsigman.register_queued(zynsigman.S_CHAIN_MAN, self.chain_manager.SS_SET_ACTIVE_CHAIN, self.update_mixer_active_chain)
                zynsigman.register_queued(zynsigman.S_CHAIN_MAN, self.chain_manager.SS_MOVE_CHAIN, self.refresh)
                zynsigman.register_queued(zynsigman.S_AUDIO_MIXER, self.zynmixer.SS_ZCTRL_SET_VALUE, self.update_mixer_strip)
+               super().init()
 
        def end(self):
                zynsigman.unregister(zynsigman.S_CHAIN_MAN, self.chain_manager.SS_SET_ACTIVE_CHAIN, self.update_mixer_active_chain)

```

Here is a simple example of this behaviour:

[test.py.txt](https://github.com/zynthian/zynthian-issue-tracking/files/13890390/test.py.txt)

**Setup:**
 - branch: `chain_manager`
 - commit: `07337a0`

**Comment by oscaracena** [comment]
I've added a PR with the proposed fix: zynthian/zynthian-ui#487 😉

**Comment by jofemodo** [comment]
Hi Oscar!

Your solution seems to work, but ...

I would like to think a little bit about this. The super() is designed for allowing "cooperative multiple inheritance", the python manual says. I don't fully understand this concept yet, and this night it's too late for such a deep dive, jeje! Perhaps you want to try: 

https://docs.python.org/3/library/functions.html#super
https://rhettinger.wordpress.com/2011/05/26/super-considered-super/

Perhaps we should use the 2-parameter form of super() and use this "cooperative multiple inheritance" paradigm.

Regards,

**Comment by oscaracena** [comment]
I understand why you would like to give it a second thought, as multiple inheritance is always "fun" 😅 I've checked the Python's documentation you reference, and there it says:

> There are two typical use cases for super. [...] The second use case is to support cooperative multiple inheritance in a dynamic execution environment. [...] Good design dictates that such implementations have the same calling signature in every case [...] For both use cases, a typical superclass call looks like this:
>
> ```python
> class C(B):
>    def method(self, arg):
>        super().method(arg)
> ```

I think this is the proposed (in the PR) way of using super(). I've delegated Python to do the method resolution for us, and it does it very straightforward, calling both super-classes in the order defined, which is what we need.

Another alternative, as you pointed out, is leaving the code as is, and then call `super()` explicitly in the most derived class (i.e. in the final controller device class). But, as we want both super-classes' `init()` to be called (the whole purpose of this), the derived class must call `super()` twice (one with the first parent class, and another with the second), which would result in two calls to the `refresh()` function (which is not better).

I'm not particularly fond of multiple inheritance (specially when we are not using mix-ins but classes with a common ancestor) but I think that (at least in this case) Python handles it very well. 

What do you think?

**Comment by jofemodo** [comment]
I don't like the root's class init() method calls "refresh()". I would prefer to not implement init() in the root class.
Regarding the 2 calls to the  "refresh()" function, we would need to call both refresh methods from the 2 ancestors, as they refreshes different parts of the device, right? Indeed, you moved the refresh() call to the root's init() function, but as you said, constructors from both ancestors are called, and init() is called from each constructors, calling refresh. I suppose each constructor calls a different version on init() & refresh(), or not? I want to make some tests to understand how this works.

**Comment by oscaracena** [comment]
In the attached example (`test.py.txt`), the `refresh()` is called only once, when the base class constructor calls its `init`. I was not sure whether each of the derived classes would have a refresh, but I'm sure that the final class (the Most Derived Class) will have just one :D 

But I see your point. You want to avoid implementing the `init` in the base class, which is fine. Let's find out another solution then.

**Comment by oscaracena** [comment]
I've added another example (`test2.py.txt`) which mimics the current implementation. The MRO of the most derived class, called C, is [`C, B1, B2, A`], where B1 and B2 are the classes that C inherits from, both inheriting from A (the classic diamond).

As expected, calling `super().init()` in `C.init()`, resolves to `B1.init()`. What is interesting is that calling `super(B1, self).init()` in `C.init()` does not resolve to `B1.init()` neither to B1's parent class (A), but to `B2.init()`. 

What I mean is that you have a set of classes that forms the MRO of C, and using `super()` you can obtain the next item in the list. If you pass C, it returns B1, if you pass B1, it returns B2, and only passing B2, it returns A. So, in order to call both `init()` from C, you need to do something like this:

```python
class C(B1, B2):
    def init(self):
        super().init()          # -> B1.init()
        super(B1, self).init()  # -> B2.init()
``` 

Which is even less intuitive! 😅 

[test2.py.txt](https://github.com/zynthian/zynthian-issue-tracking/files/13949065/test2.py.txt)

**Comment by jofemodo** [comment]
OK! I was making some tests with this code structure:

```
class Root:
	def __init__(self):
		print("Root constructor")
		self.init()

	def init(self):
		print("Root init")
		self.refresh()
	
	def refresh(self):
		print("Root refresh")


class A(Root):
	def __init__(self):
		print("A constructor")
		super().__init__()

	def init(self):
		print("A init")
		super().init()
	
	def refresh(self):
		print("A refresh")
		
class B(Root):
	def __init__(self):
		print("B constructor")
		super().__init__()

	def init(self):
		print("B init")
		super().init()
	
	def refresh(self):
		print("B refresh")
		
class C(A, B):
	def __init__(self):
		print("C constructor")
		super().__init__()

	def init(self):
		print("C init")
		super().init()
	
	def refresh(self):
		print("C refresh")


c = C()

```

It's curious how super() does work. 
Although i'm not fully convinced yet, i will merge your proposal and if needed, we can re-think about it in the future.

**Comment by oscaracena** [comment]
I think we cross-commented 😄 Did you see my previous answer?

**Comment by jofemodo** [comment]
Yes.You are right. It's not intuitive at all!
