### ISSUE TITLE
chain_manager branch fails after update from stable.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#933]
**Describe the bug**
Chain_manager branch does not start from clena stable build after update

**To Reproduce**
1. Burn SSD from stable ( 7/1/2024)
2. Start and configure zynthian
3. Update to chain_manager branch

**Expected behavior**
Chain_manager branch runs

**Screenshots**
Locks up on zynthian splash screen

**Setup:**
zyncoder: chain_manager (8cb54ca)
zynthian-ui: chain_manager (5a81546)
zynthian-sys: chain_manager (95642f2)
zynthian-data: chain_manager (a1d0f98)

 HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: Behringer UMC1820
Display: Pi 7 Touchscreen Display 800x480
Wiring: MCP23017_ENCODERS
I2C: MCP23017@0x20
Profile: v4_studio
zynthian-webconf: chain_manager (3534fb6)

Resetting to stable allows a clean reboot...

**Comment by riban-bw** [comment]
I perofmed a clean install of stable then updated via webconf to chain manager with no issue.
