### ISSUE TITLE
Global tuning not working with setBfree

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#934]
Global tuning not working with setBfree.

1. load a snapshot  based on setBfree
2. Go to MIDI option and change the general tuning for example lowering A to G# and Save
3. Play some notes on setBfree and you understand that the tuning is unchanged

**Expected behavior**
The Expected behavior is that the notes played on setBfree follow the new global tuning.

**Setup:**
 - SD-image: 2308
 - Hardware Config: v4

**Comment by jofemodo** [comment]
You don't say where are you changing the tuning. I must suppose you mean "webconf" ;-)
Please, be extremely detailed when reporting an issue. I think i've repeated this a thousand times. We can't fix anything if we don't have the details.

BTW, if you change a full semitone, this could be consider a transposition and it could be done more easily from the UI, accessing the "Note range & transpose" in the chain options.

**Comment by jofemodo** [comment]
I've been reviewing of tuning does work with setBfree and this is what i've re-discovered:

+ setBfree engine must be restarted after changing the global tuning. It can't be changed on-the-fly.
+ Tuning frequency is rounded to the lower integer number, so be careful when specifying not integer tuning frequencies.

Please, confirm these 2 tips and tell me if this solve the issue for you.

Regards,

**Comment by Piattica** [comment]
I created 2 MIDI profiles
![image](https://github.com/zynthian/zynthian-issue-tracking/assets/97229963/b687a2ec-81ea-4951-a57a-a54cc6948e75)

swicthing either on webconf either on Zynthian HW and reloading setbfree nothing changes in terms of tune

zyncoder: [stable (c452d2b)](https://github.com/zynthian/zyncoder/commit/c452d2bb36430b57969e249f48fdf1ed4fe3c44d)
zynthian-ui: [stable (f19f78c)](https://github.com/zynthian/zynthian-ui/commit/f19f78cd0a9472f78315755d2e67963d3c564504)
zynthian-sys: [stable (7a69951)](https://github.com/zynthian/zynthian-sys/commit/7a69951b17861a6f827b075ec52859eccf861ef2)
zynthian-data: [stable (5a40e04)](https://github.com/zynthian/zynthian-data/commit/5a40e04760f475855e8e4eff3f2e0f70a07cf971)
zynthian-webconf: [stable (7e74565)](https://github.com/zynthian/zynthian-webconf/commit/7e74565527035c804a8c57b123e14d4b323f7756)

Build Date: 2024-01-16

**Comment by riban-bw** [comment]
I confirm that changing the global tuning only has effect after restarting setBfree. Maybe we should add a trigger that does this.

**Comment by jofemodo** [comment]
Hi @Piattica !

I checked and tuning works after restarting setBfree. Could you check in Oram Bookworm?

Thanks

**Comment by Piattica** [comment]
Ciao #Jofemodo
I did in this way:
1) load a empty snapshot
2) admin > global transpose > +3 (for example)
3) load a snapshot based on zynaddsubfx (for example)
4) found that global transpose is 0: **it seems that snapshot cancel the global transpose**
