### ISSUE TITLE
global MIDI transpose

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#935]
**Is your feature request related to a problem? Please describe.**
I play in a blues group where guitar and bass are usually tuned -1 semitone. This pratique is common in blues groups.
To play with them I should play all songs transposing keyboard music sheets.

**Describe the solution you'd like**
all keyboard workstations usually have in setting menu a master or global transpose MIDI setting, so my request is to **have in MIDI option a global transpose  that can be saved in the MIDI profile**.

**Describe alternatives you've considered** 
I would double all the snapshots to have versione tuned a semitone lower.

**Comment by riban-bw** [comment]
This sounds eminently sensible. As a work-around you could set the transpose of each chain using the chain's context menu entry, "Note Range & Transpose". It is more labourious but it will do what you want until someone implements this feature.

**Comment by Piattica** [comment]
yes, I understand

thank you
*       Paolo Piattica
 *


Il giorno lun 19 feb 2024 alle ore 16:21 riban-bw ***@***.***>
ha scritto:

**Comment by riban-bw** [comment]
This is implemented in oram branch.

**Comment by Piattica** [comment]
Thank you a lot.

Paolo Piattica

Il mer 21 feb 2024, 09:53 Jośe Fernando Moyano ***@***.***>
ha scritto:
