### ISSUE TITLE
zynthian-ui: `zynthian_gui_zynpad.py` throws IndexError when updating pad status

### ISSUE THREAD

**Issue by oscaracena** [zynthian/zynthian-issue-tracking#936]
**Describe the bug**
The function `refresh_pad()` raises an `IndexError` when PAD is updated with `SEQ_STOPPINGSYNC` or `SEQ_LASTPLAYSTATUS` (value = 5), there are not enough images in `self.state_icon[self.zynseq.col_in_bank]`.

**To Reproduce**
1. Start Zynthian
2. Open sequencer
3. Press a pad
4. Press another pad in the same group
5. See console output for error

**Setup:**
 - branch: `chain_manager`
 - commit: `fbd1376`

**Comment by oscaracena** [comment]
The exact missing icon is for state `SEQ_STOPPINGSYNC`.

**Comment by oscaracena** [comment]
I've added a PR here: zynthian/zynthian-ui#488 :wink:

**Comment by jofemodo** [comment]
There was an easier solution: fix the indentation in the refresh_pad() function.
I don't think we need more icons here ... yet ;-)

**Comment by jofemodo** [comment]
Thanks a lot!!

**Comment by oscaracena** [comment]
> There was an easier solution: fix the indentation in the refresh_pad() function. I don't think we need more icons here ... yet ;-)

Oh, I see 😅 Yes, a better solution. I didn't like the icons either 😄
