### ISSUE TITLE
zynthian-ui: Zynpad, last pad not updated

### ISSUE THREAD

**Issue by oscaracena** [zynthian/zynthian-issue-tracking#937]
**Describe the bug**
The last pad (last column + last row) is not updated when its playing status changes. It also does not send `SS_SEQ_PLAY_STATE` signal.

**To Reproduce**
1. Open the sequencer
2. Press/click on the last sequence pad

**Expected behavior**
On first play, a "playing" status icon should appear, and also its progress bar.

**Setup:**
 - branch: `chain_manager`
 - commit: `fbd1376`

**Comment by oscaracena** [comment]
The problem is in `zynseq.py`, in `update_state/update_progress` methods. They use `libseq.getStateChange/libseq.getProgress`, passing `num_seq - 1` (where `num_seq = self.col_in_bank ** 2`) as the end sequence to check. BUT, both functions (defined in C++) already does not include the endpoint, checking effectively one less pad.

**Comment by oscaracena** [comment]
I've sent a PR here: zynthian/zynthian-ui#489 😉

**Comment by jofemodo** [comment]
Merged!! Thanks a lot!
