### ISSUE TITLE
Audio player has one play added to loop mode

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#938]
**Is your feature request related to a problem? Please describe.**
A sample can be played by MIDI key control in the audio player but the sample ceases as soon as the key is lifted.

Adding a  list of options in loop on the audioplayer similar to the play modes in zynseq would allow a MIDI keyboard to be used to play samples to their completion rather than having to hold the key down.
This would also allow a certain amount o similarity of concept to the zynseq components that would allow these areas to be combined in some way. 

**Describe the solution you'd like**
The ability to select One shot in an audio player mode.

This avoids the implementation of sustain pedals to hold on notes.

**Comment by riban-bw** [comment]
I am tempted to put this functionality in the sequencer. We are designing sequencer workflows that may suit this and sequence pads can be triggered by external devices so I think it likely that this request may be superseded by other developments.

**Comment by riban-bw** [comment]
This is added to oram branch.

There are two new modes which makes 4 "loop" modes:

- One-shot (Plays whilst requested. Stops at end crop end marker.)
- Loop (Plays whilst requested. Loops at loop markers.)
- Play all (Like one-shot but MIDI note-on plays to crop end marker.)
- Toggle-play (MIDI note-on toggles between play & stop.)
