### ISSUE TITLE
Construct a Zynthian device driver for the DuoPiano

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#941]
**Is your feature request related to a problem? Please describe.**
The DUOPiano requires a note to be sent to the MIDI port over USB to wake it up
This functionality was previously provided by manual configuration of udev rules ( /etc/udev/rules.d/80-midikbd.rules)
which ran a shell script with parameters (/var/local/wake_kbd.sh)

ON the introduction of the new zynthian driver mechanism this functionality should be written as a Zyndevice 

**Describe the solution you'd like**
Detect the presence of a DUO Piano and provide it as a driver 

**Describe alternatives you've considered**
The script detailed above

> root@zynthian-rack2:/var/local# cat wake_kbd.sh 
> #!/bin/sh
> echo " Running..."
> echo $1
> if [ $# -gt 0 ]
> then
>   /usr/bin/amidi -p hw:$1,0,0 -S 90 00 00
> fi

> root@zynthian-rack2:/etc/udev/rules.d# cat 80-midikbd.rules 
> SUBSYSTEM=="sound", ATTRS{idVendor}=="7777", ATTRS{idProduct}=="8899", ACTION=="add", RUN+="/var/local/wake_kbd.sh %s{number}",ATTRS{number}

**Comment by riban-bw** [comment]
This is now working in state_manager.
