### ISSUE TITLE
Bug: Unable to see cursor on HDMI monitor when Enable cursor is selected

### ISSUE THREAD

**Issue by TKConrad** [zynthian/zynthian-issue-tracking#942]
**Describe the bug**
The cursor is not shown on an HDMI-connected monitor after upgrading to the latest Zynthian build "2024-01-16-zynthianos-stable-2401.zip". The system still responds to mouse clicks and the position of the cursor, but the cursor itself is not shown on the screen. This makes it nearly impossible to accurately select options using the mouse. There does not appear to be a keyboard equivalent for moving around the different options on a window other than up and down in a selection list.

**To Reproduce**

1. Boot Zynthian
2. In web configuration, go to Interface... UI Options
3. Select "Enable cursor" (if not already selected)
4. Save
5. Reboot Zynthian

**Expected behavior**
The cursor is displayed.

**Actual behavior**
The cursor is not displayed, although the mouse still interacts with the system.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.1
Audio: HifiBerry DAC+
Display: Generic HDMI Display
Wiring: DUMMIES
I2C: Not detected
Profile:

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2024-01-16
Memory: 15% (577M/3838M)
SD Card: 42% (12G/29G)
Temperature: 52.1ºC
Overclock: None

SOFTWARE
zyncoder: stable (c452d2b)
zynthian-ui: stable (f19f78c)
zynthian-sys: stable (bd44c64)
zynthian-data: stable (1321e5d)
zynthian-webconf: stable (6b74794)

**Additional context**
I have reproduced this consistently ever since upgrading to stable-2401 from [https://os.zynthian.org/2024-01-16-zynthianos-stable-2401.zip](https://os.zynthian.org/2024-01-16-zynthianos-stable-2401.zip). The cursor is not shown after doing a fresh image onto the SD card without any config restores.

**Comment by wyleu** [comment]
Confirmed with No mouse connected and with a mouse connected, during session and from power up.

Start up produced no cursor.
![20240123_15h44m58s_grim](https://github.com/zynthian/zynthian-issue-tracking/assets/79083/f534f86e-53d8-4aeb-842f-9fa1315a940c)

Powered off machine with mouse connected...

Restarted, No Cursor.

HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [HifiBerry DAC+ ADC PRO]
Display: [Generic 4k HDMI Display]
Wiring: [DUMMIES]
I2C: [Not detected]
Profile: [v4_stage

 SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-06-29
Memory: 6% (267M/3839M)
SD Card: 56% (16G/29G)
Temperature: 56.4ºC
Overclock: [None]

 SOFTWARE
zyncoder: [stable (c452d2b)]
zynthian-ui: [stable (f19f78c)]
zynthian-sys: [stable (bd44c64)]
zynthian-data: [stable (1321e5d)]
zynthian-webconf: [stable (6b74794)]

**Comment by wyleu** [comment]
"There does not appear to be a keyboard equivalent for moving around the different options on a window other than up and down in a selection list."

The UI keybinding page in the Webconf Interface page  gives the default Qwerty keyboard settings and allows them to be modified...

http://zynthian.local/ui-keybind

**Comment by TKConrad** [comment]
Thanks wyleu. I have reviewed the key binding UI and can't find a keyboard equivalent that allows you to move around to the different areas of a Zynthian screen, other than scrolling up and down in a list by using the up and down arrows. The right and left arrows typically move you to other screens, such as other MIDI channels, rather than allowing you to select the controls shown for a particular instrument on a particular channel.

**Comment by wyleu** [comment]
> Thanks wyleu. I have reviewed the key binding UI and can't find a keyboard equivalent that allows you to move around to the different areas of a Zynthian screen, other than scrolling up and down in a list by using the up and down arrows. The right and left arrows typically move you to other screens, such as other MIDI channels, rather than allowing you to select the controls shown for a particular instrument on a particular channel.


Probably best to take this out of this ticket. It's not really relevant to the issue discussed. Maybe start a forum post.

If you don't mind We should edit these components out of the ticket leaving just the reported bug.

**Comment by Piattica** [comment]
the same for me:
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO](http://zynthian.local/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian.local/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian.local/hw-wiring)
I2C: [MCP23017@0x20](http://zynthian.local/hw-wiring)
Profile: [v4_stage](http://zynthian.local/hw-wiring)
 SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2024-01-16
Memory: 11% (890M/7899M)
SD Card: 31% (18G/59G)
Temperature: 57.4ºC
Overclock: [None](http://zynthian.local/hw-options)
 MIDI
Profile: [default.sh](http://zynthian.local/ui-midi-options)
Tuning: [440 Hz](http://zynthian.local/ui-midi-options)
ZS3 (SubSnapShots): [On](http://zynthian.local/ui-midi-options)
Preload Presets: [On](http://zynthian.local/ui-midi-options)
MIDI to Output: [Off](http://zynthian.local/ui-midi-options)
Master Channel: [off](http://zynthian.local/ui-midi-options)
 SOFTWARE
zyncoder: [stable (c452d2b)](https://github.com/zynthian/zyncoder/commit/c452d2bb36430b57969e249f48fdf1ed4fe3c44d)
zynthian-ui: [stable (f19f78c)](https://github.com/zynthian/zynthian-ui/commit/f19f78cd0a9472f78315755d2e67963d3c564504)
zynthian-sys: [stable (bd44c64)](https://github.com/zynthian/zynthian-sys/commit/bd44c64d21328c76a47aeeecc2c555f2ac30fc9e)
zynthian-data: [stable (1321e5d)](https://github.com/zynthian/zynthian-data/commit/1321e5d1ce0d75ef8963bf0f0c9a00218c748bb5)
zynthian-webconf: [stable (6b74794)](https://github.com/zynthian/zynthian-webconf/commit/6b74794e9df3f120cf82f6bd9500f29262f3312b)
 LIBRARY
Snapshots: [128](http://zynthian.local/lib-snapshot)
User Presets: [5](http://zynthian.local/lib-presets)
User Soundfonts: [1410](http://zynthian.local/lib-soundfont)
Audio Captures: [0](http://zynthian.local/lib-captures)
MIDI Captures: [48](http://zynthian.local/lib-captures)
 NETWORK
Hostname: [zynthian](http://zynthian.local/sys-security)
Wifi: [on](http://zynthian.local/sys-wifi)
IP: [169.254.160.217 192.168.1.18](http://zynthian.local/sys-wifi)
RTP-MIDI: [Off](http://zynthian.local/ui-midi-options)
QMidiNet: [Off](http://zynthian.local/ui-midi-options)

**Comment by fuzzySi** [comment]
Same issue here: cursor not visible on new install with updated software. Running standalone on a Pi 4, so a cursor would be really helpful!

Raspberry Pi 4 Model B Rev 1.4
Audio: [RBPi Headphones](http://192.168.1.175/hw-audio)
Display: [Generic HDMI Display](http://192.168.1.175/hw-display)
Wiring: [DUMMIES](http://192.168.1.175/hw-wiring)
I2C: [Not detected](http://192.168.1.175/hw-wiring)
Profile:

zyncoder: [stable (c452d2b)]
zynthian-ui: [stable (f19f78c)]
zynthian-sys: [stable (77b48c1)]
zynthian-data: [stable (44a652c)]
zynthian-webconf: [stable (6b74794)]

**Comment by wyleu** [comment]
**This is fixed by** 

zyncoder: [chain_manager (6fe8277)]
zynthian-ui: [chain_manager (65da228)]
zynthian-sys: [chain_manager (1ea050c)]
zynthian-data: [chain_manager (4555a9a)]
zynthian-webconf: [chain_manager (37d9e55)]

**Comment by TKConrad** [comment]
> **This is fixed by**
> 
> zyncoder: [chain_manager (6fe8277)] zynthian-ui: [chain_manager (65da228)] zynthian-sys: [chain_manager (1ea050c)] zynthian-data: [chain_manager (4555a9a)] zynthian-webconf: [chain_manager (37d9e55)]

Thanks @wyleu, I downloaded the update and rebooted my Raspberry Pi and confirmed that it works! Much appreciated!

Regards,
TK
