### ISSUE TITLE
Bug:  MIDI CAPTURE DEVICES and ACTI / OMNI / MULTI modes issue

### ISSUE THREAD

**Issue by ToFFmashines** [zynthian/zynthian-issue-tracking#952]
**Describe the bug**
Zynthian is set with:

- Engine Sfizz on midi channel 1 with select MULTI- Network MIDI-IN and unselect OMNI - Widi Bud Pro Midi 

- Engine Sfizz on midi channel 2 with unselect MULTI- Network MIDI-IN and select OMNI - Widi Bud Pro Midi 

Issue is in that midi signal from Widi Bud Pro Midi is going to channel 1, where is unselect and where it has nothing to do. Is visible by ZynMidi route ch#1 in Midi Log.

**To Reproduce**
Connections:
Zynthian is conntroled by Bespoke from PC over rtp-midi
WIDI BUD Pro is connected over USB
![zynthian 9](https://github.com/zynthian/zynthian-issue-tracking/assets/75641620/3c44d481-b131-4123-a3c7-a13a6d1aec6e)
Setting of Midi in for ch#1
![capture-midi-in-1](https://github.com/zynthian/zynthian-issue-tracking/assets/75641620/ebe70308-4e96-435d-896c-9fd5edd603f9)
Setting of Midi in for ch#2
![capture-midi-in-2](https://github.com/zynthian/zynthian-issue-tracking/assets/75641620/88ee6a73-7dfa-4811-bbaa-769a01fdb3f3)

**Expected behavior**
The midi signal from the Widi Bud Pro will only go to channel 2

**Setup:**
HARDWARE
Raspberry Pi 400 Rev 1.1
Audio: Behringer UMC404HD
Display: WaveShare 7 HDMI+USB 1024x600
Wiring: DUMMIES
I2C: Not detected
Profile:
 SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-08-25
Memory: 6% (246M/3839M)
SD Card: 65% (37G/59G)
Temperature: 45.7ºC
Overclock: None
 SOFTWARE
zyncoder: [testing (c452d2b)](https://github.com/zynthian/zyncoder/commit/c452d2bb36430b57969e249f48fdf1ed4fe3c44d)
zynthian-ui: [testing (f19f78c)](https://github.com/zynthian/zynthian-ui/commit/f19f78cd0a9472f78315755d2e67963d3c564504)
zynthian-sys: [testing (77b48c1)](https://github.com/zynthian/zynthian-sys/commit/77b48c183092cd54c241531ae8751f7c9044ea5f)
zynthian-data: [testing (44a652c)](https://github.com/zynthian/zynthian-data/commit/44a652cc3d0723f4b201d2e9c3a7d202e634b54f)
zynthian-webconf: [testing (6b74794)](https://github.com/zynthian/zynthian-webconf/commit/6b74794e9df3f120cf82f6bd9500f29262f3312b)

**Additional context**
Snapshots
[018-example-widi.zip](https://github.com/zynthian/zynthian-issue-tracking/files/14318648/018-example-widi.zip)

**Comment by jofemodo** [comment]
Sorry, i can't reproduce the issue in stable branch.
I loaded your snapshot and MIDI from the "OMNI" device doesn't reach chain 2, only chain 1.

**Comment by ToFFmashines** [comment]
Please can you try this:
Channel #1   -  selected OMNI controler 1,
                     -  unselected OMNI controler 2,
Channel #2   -  unselected OMNI controler 1,
                     -  selected OMNI controler 2,

**Comment by jofemodo** [comment]
Sorry, i can't reproduce the issue in stable branch.
I loaded your snapshot and MIDI from the "OMNI" device doesn't reach chain 2, only chain 1.
