### ISSUE TITLE
Initial boot shows upsidedown boot messages

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#955]
**Describe the bug**
The initial boot of an _osram_ image shows the boot messages upside down on the screen of a V5.

**To Reproduce**
1. Flash 2024-02-20-zynthianos-bookworm-aarch64-oram-2402.zip
2. Start Zynthian

**Expected behaviour**
Boot is pretty!

**Actual behaviour**
Boot messages scroll on screen and are upside down.

**Setup:**
* SYSTEM
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 11% (448M/3793M)
SD Card: 52% (15G/29G)
Temperature: 47.7ºC
Overclock: [Maximum](http://zynthian-v5.4sar/hw-options)
USB/sda1-usb-SMI_USB_DISK_3.1: [2% (2.7G/235G)](http://zynthian-v5.4sar/lib-captures)
* MIDI & UI
Tuning: [440 Hz](http://zynthian-v5.4sar/ui-midi-options)
Master Channel: [Off](http://zynthian-v5.4sar/ui-midi-options)
Preload Presets: [On](http://zynthian-v5.4sar/ui-midi-options)
ZS3 (SubSnapShots): [On](http://zynthian-v5.4sar/ui-midi-options)
Power Save: [10 minutes](http://zynthian-v5.4sar/ui-options)
Audio Levels on Snapshots: [On](http://zynthian-v5.4sar/ui-options)
* SOFTWARE
zyncoder: [oram (9ea5d33)](https://github.com/zynthian/zyncoder/commit/9ea5d33491e6d7d491917ebb36442fdd126348b4)
zynthian-ui: [oram (f2d7b4c)](https://github.com/zynthian/zynthian-ui/commit/f2d7b4cf4d6c36b285dd3e4f2d15916e73e06b4e)
zynthian-sys: [chainman_bookworm (23c689f)](https://github.com/zynthian/zynthian-sys/commit/23c689f07f856aa5f20ba76656f9f709ca19853e)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (37d9e55)](https://github.com/zynthian/zynthian-webconf/commit/37d9e55f447a4656f56ab8128aeb0087a61a8b66)

**Additional context**
This was the first boot. Subsequent reboot did not exhibit this behaviour but did show "Failed to start backlight service" message before splash screen.

**Comment by jofemodo** [comment]
I've changed the default kit configuration so now it's V5 that have the DSI screen rotated from the kernel parameters.
For HDMI screens there is no rotation, so it should be solved now.
For testing, take the current oram-bookworm image, update to the last and run "set_first_boot.sh". Then boot and see the result.

Regards
