### ISSUE TITLE
Oram broken after update

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#956]
**Describe the bug**
After initial boot, config and reboot I performed an update from admin menu. Subsequent reboot failed with error screen.

This is due to errors with libsndfile and hence audioplayer not building. Issues include:

- Wrong repo in `/etc/apt/sources.list.d/zynthian.list` which still points to bullseye but should point to bookworm.
- Wrong deb file uploaded. Should be the later one I send to @jofemodo that did not suffix package names with '1'.

These issues need resolving urgently as they break the update and are not subsequently resolvable without manual intervention.

To work around this temporarily  I did the following manual steps but the above fixes should be applie.

- Edit `/etc/apt/sources.list.d/zynthian.list` changing `buster` to `bookworm`
- `apt install libsndfile1-zyndev`
- `/zynthian/zynthian-ui/zynlibs/zynaudioplayer/build.sh`

These steps are only here to help others currently stuck.

**Comment by mheidt** [comment]
@riban-bw 
I just installedbookworm  and did a successful update.

**Comment by riban-bw** [comment]
V3 did not get the right libsndfile. I wonder if the update fully works.

**Comment by jofemodo** [comment]
I think this can be closed now.
