### ISSUE TITLE
Webconf file uploader not allowing file browsing (Firefox)

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#958]
**Describe the bug**
Installing a Pianoteq binary involves using webconf upload feature. Clicking on the "Click and choose" link does not open the local file browser. You can drag and drop from a file manager window but the click and choose option should also work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Access webconf from Firefox web browser
2. Open SOFTWARE->Pianoteq page
3. Click "Upload Binary / PTQ"
4. Click on the "Click and choose" link

**Expected behaviour**
A file selection window shows.

**Screenshots**
![image](https://github.com/zynthian/zynthian-issue-tracking/assets/3158323/77ac75b7-fb7b-461a-ac50-87aac0087fec)

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://zynthian-v5/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5/hw-display)
Wiring: [V5](http://zynthian-v5/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://zynthian-v5/hw-wiring)
Profile: [v5](http://zynthian-v5/hw-wiring)
- SYSTEM
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 17% (668M/3793M)
SD Card: 53% (15G/29G)
Temperature: 43.8ºC
Overclock: [Maximum](http://zynthian-v5/hw-options)
USB/sda1-usb-SMI_USB_DISK_3.1: [2% (2.7G/235G)](http://zynthian-v5/lib-captures)
- MIDI & UI
Tuning: [440 Hz](http://zynthian-v5/ui-midi-options)
Master Channel: [Off](http://zynthian-v5/ui-midi-options)
Preload Presets: [On](http://zynthian-v5/ui-midi-options)
ZS3 (SubSnapShots): [On](http://zynthian-v5/ui-midi-options)
Power Save: [10 minutes](http://zynthian-v5/ui-options)
Audio Levels on Snapshots: [On](http://zynthian-v5/ui-options)
- SOFTWARE
zyncoder: oram (9ea5d33)
zynthian-ui: [oram (b943349)](https://github.com/zynthian/zynthian-ui/commit/b94334987e0f14e6c22ace35e77c3a89f2e237e3)
zynthian-sys: [chainman_bookworm (8b76273)](https://github.com/zynthian/zynthian-sys/commit/8b76273c30f0ae179297c62acf8100e2a0994f20)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (37d9e55)](https://github.com/zynthian/zynthian-webconf/commit/37d9e55f447a4656f56ab8128aeb0087a61a8b66)

**Additional context**
This is observed with Firefox 123.0 (64-bit) installed from snap on Ubuntu 22.04.3 LTS.
Chromium works as expected on the same platform.

**Comment by jofemodo** [comment]
I can't reproduce the issue with latest oram and FireFox 115.5.0ESR
