### ISSUE TITLE
Webconf enable multichannel recording doesn't seem to do anything

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#960]
**Describe the bug**
In webconf INTERFACE-UI Options there is an option called, "Enable multichannel recording". This is enabled by default. Unchecking the box and saving causes Zynthian to restart and the webpage to refresh but the checkbox reappears asserted and there seems to be no change in behaviour in Zynthian.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to webconf INTERFACE-UI Options
2. Uncheck "Enable multichannel recording"
3. Check availability of multichannel recording in main UI

**Expected behaviour**
Webconf checkbox remains unchecked. Multichannel recording option disabled in main UI.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://zynthian-v5/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5/hw-display)
Wiring: [V5](http://zynthian-v5/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://zynthian-v5/hw-wiring)
Profile: [v5](http://zynthian-v5/hw-wiring)
- SYSTEM
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 12% (480M/3793M)
SD Card: 53% (15G/29G)
Temperature: 45.7ºC
Overclock: [Maximum](http://zynthian-v5/hw-options)
USB/sda1-usb-SMI_USB_DISK_3.1: [2% (2.7G/235G)](http://zynthian-v5/lib-captures)
- MIDI & UI
Tuning: [440 Hz](http://zynthian-v5/ui-midi-options)
Master Channel: [Off](http://zynthian-v5/ui-midi-options)
Preload Presets: [On](http://zynthian-v5/ui-midi-options)
ZS3 (SubSnapShots): [On](http://zynthian-v5/ui-midi-options)
Power Save: [10 minutes](http://zynthian-v5/ui-options)
Audio Levels on Snapshots: [On](http://zynthian-v5/ui-options)
- SOFTWARE
zyncoder: oram (9ea5d33)
zynthian-ui: [oram (b943349)](https://github.com/zynthian/zynthian-ui/commit/b94334987e0f14e6c22ace35e77c3a89f2e237e3)
zynthian-sys: [chainman_bookworm (8b76273)](https://github.com/zynthian/zynthian-sys/commit/8b76273c30f0ae179297c62acf8100e2a0994f20)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (37d9e55)](https://github.com/zynthian/zynthian-webconf/commit/37d9e55f447a4656f56ab8128aeb0087a61a8b66)

**Additional context**
I can't remember why we added this option. It may have been because the multichannel recording option was cluttering the main UI. Maybe this is no longer required and can be removed.

**Comment by jofemodo** [comment]
This option should be removed from UI options. It's not a very good place for it. Perhaps we could totally remove it.
