### ISSUE TITLE
Bug: Webconf "Reboot" message obsures useful screen elements

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#963]
**Describe the bug**
If webconf has detected the system requires a reboot before changes fully apply it shows a red banner at the bottom of the screen saying, "Zynthian needs to reboot to apply your changes!" with a, "REBOOT NOW!" button. This banner obscures content in the webconf which can include save buttons which are often at the bottom of the screen.

**To Reproduce**
1. Go to webconf
2. Make a change that triggers a restart message, e.g. change audio interface mixer controls
3. Go to a view that has a save button, e.g. Audio page

**Expected behaviour**
All webconf content is visible.

**Screenshots**
![image](https://github.com/zynthian/zynthian-issue-tracking/assets/3158323/b845d043-b7d6-4455-9228-1bb4b2c0e572)

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [Behringer UMC1820](http://zynthian-v5-64.4sar/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5-64.4sar/hw-display)
Wiring: [V5](http://zynthian-v5-64.4sar/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x4A](http://zynthian-v5-64.4sar/hw-wiring)
- SYSTEM
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 22% (848M/3793M)
SD Card: 54% (15G/29G)
Temperature: 51.6ºC
Overclock: [Maximum](http://zynthian-v5-64.4sar/hw-options)
USB/sda1-usb-SMI_USB_DISK_3.1: [2% (2.7G/235G)](http://zynthian-v5-64.4sar/lib-captures)
- MIDI & UI
Tuning: [440 Hz](http://zynthian-v5-64.4sar/ui-midi-options)
Master Channel: [Off](http://zynthian-v5-64.4sar/ui-midi-options)
Preload Presets: [On](http://zynthian-v5-64.4sar/ui-midi-options)
ZS3 (SubSnapShots): [On](http://zynthian-v5-64.4sar/ui-midi-options)
Power Save: [10 minutes](http://zynthian-v5-64.4sar/ui-options)
Audio Levels on Snapshots: [On](http://zynthian-v5-64.4sar/ui-options)
- SOFTWARE
zyncoder: [oram (9ea5d33)](https://github.com/zynthian/zyncoder/commit/9ea5d33491e6d7d491917ebb36442fdd126348b4)
zynthian-ui: [oram (2dff5c3)](https://github.com/zynthian/zynthian-ui/commit/2dff5c362c373428889ccee6b993353465a29bca)
zynthian-sys: [chainman_bookworm (a843448)](https://github.com/zynthian/zynthian-sys/commit/a843448763bfc1bcfbe99c5c8c0970ced9081a0d)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (a5442c1)](https://github.com/zynthian/zynthian-webconf/commit/a5442c1c0110a9acbb6ebbd6dae4bb4297407311)

**Additional context**
It would make sense for the reboot banner to be in its own div / frame / whatever that did not overlap the core content. Another option may be to move it to the top and colour the top bar (although I am not sure how that would show on a smaller screen like phone).

**Comment by jofemodo** [comment]
This is fixed.
