### ISSUE TITLE
Restoring ZS3 does not apply audio input changes. 

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#965]
**Describe the bug**
The audio input routing is saved and restored by ZS3 but the actual routing changes do not occur.

**To Reproduce**
1. Add an audio input chain
2. Save ZS3
3. Change audio input selection
4. Save ZS3
5. Restore each ZS3

**Expected behaviour**
The audio input routing changes to match that saved in the ZS3.

**Actual behaviour**
Indication of audio input routing changes as expected but actual routes are not changed.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [Behringer UMC1820](http://zynthian-v5-64.4sar/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5-64.4sar/hw-display)
Wiring: [V5](http://zynthian-v5-64.4sar/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x4A](http://zynthian-v5-64.4sar/hw-wiring)
- SYSTEM
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 18% (705M/3793M)
SD Card: 56% (16G/29G)
Temperature: 53.0ºC
Overclock: [Maximum](http://zynthian-v5-64.4sar/hw-options)
USB/sda1-usb-SMI_USB_DISK_3.1: [2% (2.7G/235G)](http://zynthian-v5-64.4sar/lib-captures)
- MIDI & UI
Tuning: [440 Hz](http://zynthian-v5-64.4sar/ui-midi-options)
Master Channel: [Off](http://zynthian-v5-64.4sar/ui-midi-options)
Preload Presets: [On](http://zynthian-v5-64.4sar/ui-midi-options)
ZS3 (SubSnapShots): [On](http://zynthian-v5-64.4sar/ui-midi-options)
Power Save: [10 minutes](http://zynthian-v5-64.4sar/ui-options)
Audio Levels on Snapshots: [On](http://zynthian-v5-64.4sar/ui-options)
- SOFTWARE
zyncoder: [oram (9ea5d33)](https://github.com/zynthian/zyncoder/commit/9ea5d33491e6d7d491917ebb36442fdd126348b4)
zynthian-ui: [oram (28d1b0f)](https://github.com/zynthian/zynthian-ui/commit/28d1b0f7964875d86e3e579557dfd28a8cf27383)
zynthian-sys: [chainman_bookworm (a843448)](https://github.com/zynthian/zynthian-sys/commit/a843448763bfc1bcfbe99c5c8c0970ced9081a0d)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (1c00133)](https://github.com/zynthian/zynthian-webconf/commit/1c00133dedd7d60223c053ebecc5562eae4acd2d)

**Additional context**
Making a subseqent manual change will correct all the routing. The chain routing needs to be built and auto connect run.

It may be considered unexpected behaviour for routing to change between ZS3 recalls in which case it should not be saved / restored and indication should not change.

**Comment by jofemodo** [comment]
I can't reproduce. 
It's probably fixed for some recent update. I will close.
