### ISSUE TITLE
Bookworm is truncating USB MIDI device names making some unusable

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#966]
**Describe the bug**
The alsa names for some USB MIDI devices are being truncated, e.g. LaunchKey MiniDI Mk 3 only presents its first (keyboard) port and not its second that Zynthian uses for MIDI device management. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Plug in a USB MIDI device with two ports, e.g. LaunchKey Mini Mk3

**Expected behaviour**
Device works fully.

**Actual behaviour**
Only first interface works, e.g. only keyboard.

**Setup:**

**Additional context**

It looks like alsa changed its naiming convention about kernel 5.15. It now seems to repeat the name which gives not useful additional info and pushes the name length beyond the available 32 chars (31+NULL terminator). This is a serious upstream issue that has existed for a couple of years already.

Non-working 64-bit Bookworm:
```
(venv) root@zynthian-v5-64:~# amidi -l
Dir Device    Name
IO  hw:1,0,0  UMC1820 MIDI 1
IO  hw:2,0    f_midi
IO  hw:3,0,0  Launchkey Mini MK3 Launchkey Mi
IO  hw:3,0,1  Launchkey Mini MK3 Launchkey Mi
```

Working 32-bit buster:
```
root@zynthian-v5:~# amidi -l
Dir Device    Name
IO  hw:1,0,0  UMC1820 MIDI 1
IO  hw:3,0    f_midi
IO  hw:4,0,0  Launchkey Mini MK3 MIDI 1
IO  hw:4,0,1  Launchkey Mini MK3 MIDI 2
```

**Comment by riban-bw** [comment]
The new alsa naming convention concatinates two fields - the first is the device name and the second is the endpoint name. Both may be 31 characters long but alsa only allocates 32 byte buffer which leads to truncation of the endpoint name which often has unique distinguising info, e.g. Launchkey Mini MK3 MIDI &  Launchkey Mini MK3 DAW.

This is an upstream issue but there doesn't seem to have been any effort to resolve since it was changed (about 2 years ago). There might be a way to use some udev rules to rename USB MIDI devices based on their endpoint names which should be the default in alsa but isn't.

**Comment by jofemodo** [comment]
This is fixed too ;-)
Thanks @riban-bw !
