### ISSUE TITLE
Oram 64 fails with 500 on WAV file upload with full /tmp directory...

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#970]
**Describe the bug**
Uploading multiple wav files fails with full tmp directory.

**To Reproduce**
1. Go to Captures
2. Upload selection of a few ( 10~) Files
3. Press Upload
4. See 500 error

**Expected behavior**
Should upload the audio files to the limit of on system file system space.

**Screenshots**

(venv) root@zynthian-rack:~# df -h  
Filesystem      Size  Used Avail Use% Mounted on
udev            3.6G     0  3.6G   0% /dev
tmpfs           782M  9.4M  772M   2% /run
/dev/mmcblk0p2   28G   15G   13G  54% /
tmpfs           3.9G  103M  3.8G   3% /dev/shm
tmpfs           5.0M   28K  5.0M   1% /run/lock
tmpfs           100M   20K  100M   1% /tmp
tmpfs            20M   32K   20M   1% /var/log
tmpfs           200M     0  200M   0% /var/tmp
/dev/mmcblk0p1  510M   62M  449M  13% /boot/firmware
tmpfs           782M     0  782M   0% /run/user/0
(venv) root@zynthian-rack:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.6G     0  3.6G   0% /dev
tmpfs           782M  9.4M  772M   2% /run
/dev/mmcblk0p2   28G   15G   13G  54% /
tmpfs           3.9G  103M  3.8G   3% /dev/shm
tmpfs           5.0M   28K  5.0M   1% /run/lock
tmpfs           100M  100M     0 100% /tmp
tmpfs            20M   32K   20M   1% /var/log
tmpfs           200M     0  200M   0% /var/tmp
/dev/mmcblk0p1  510M   62M  449M  13% /boot/firmware
tmpfs           782M     0  782M   0% /run/user/0

**Setup:**

zyncoder: [oram (d56cd41)](https://github.com/zynthian/zyncoder/commit/d56cd41118f13b5197ba43cd779d744cc0328e87)
zynthian-ui: [oram (e88da07)](https://github.com/zynthian/zynthian-ui/commit/e88da07b5894cf61cf7939edfaa0ff1a77ef563c)
zynthian-sys: [chainman_bookworm (c518eab)](https://github.com/zynthian/zynthian-sys/commit/c518eab4f5758c4c538ed96ceffacff9015b28d1)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (b679e9a)](https://github.com/zynthian/zynthian-webconf/commit/b679e9ae6270e4d61821aefa47252346ce15f0a1)

**Comment by jofemodo** [comment]
Currently, "/tmp" directory is memory mounted to reduce SD writing and avoid corruption issues.
Uploading big files should use a in-disk directory.

**Comment by riban-bw** [comment]
The default size of the /tmp file is small (100MB). This causes various issues with processes that use /tmp (including file upload). I have temporarily, manually increased the size of /tmp to resolve some issues I have had with building packages.

Maybe there is a way to dynamically control the size of /tmp so that it can grow on demand, preferably shrinking back to a default size after some timeout.

**Comment by riban-bw** [comment]
I believe some work on temp folders was done. Is this fixed?

**Comment by jofemodo** [comment]
Yes. I managed to upload SFZ files >1GB without issues. Not tested with audios, but it should be the same.
