### ISSUE TITLE
Oram64 category selector in Add Synth Chain doesn't function

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#975]
**Describe the bug**
The Category option in the Add Synth Chain sub menu displays the option of one of three categories but doesn't alter the display upon selection 

**To Reproduce**
1. Go to Add Synth Chain
2. Modify Category
3. See error   Displayed engines do not change

**Expected behavior**
Categories should repopulate the engine list upon change.

**Setup:**
oram 1/4/2024

zyncoder: [oram (d56cd41)](https://github.com/zynthian/zyncoder/commit/d56cd41118f13b5197ba43cd779d744cc0328e87)
zynthian-ui: [oram (059a291)](https://github.com/zynthian/zynthian-ui/commit/059a291bf90fcc1986d5e4aeb2b550d6508c5bc0)
zynthian-sys: [chainman_bookworm (4d85e0e)](https://github.com/zynthian/zynthian-sys/commit/4d85e0e785c26307646c2b8341a4dde5a5204e4f)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (68024b8)](https://github.com/zynthian/zynthian-webconf/commit/68024b8243f3d96fd5f5758e330939d9fb1d19d2)

**Additional context**
FluidSynth, Linux Sampler and Sfizz  are not accessible as Engines.

**Comment by mheidt** [comment]
related to:
https://github.com/zynthian/zynthian-issue-tracking/issues/972

**Comment by wyleu** [comment]
Closed under #972
