### ISSUE TITLE
Terminal launcher in VNC desktop fails

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#976]
**Describe the bug**
The VNC desktop allows viewing of naitive GUIs. It also has a menu bar with launchers for Patchage and Terminal. The Terminal launcher does not work in the bookworm image.

**To Reproduce**
1. Enable VNC
2. Access VNC-ENGINES
3. Click on the "Terminal" button in the top bar

**Expected behaviour**
Terminal opens.

**Actual behaviour**
Eror message, `Failed to launch preferred application for category "Terminal Emulator"`

**Screenshots**
![image](https://github.com/zynthian/zynthian-issue-tracking/assets/3158323/0c6a0a59-7a26-4537-8f8a-ac0e6d0ba2a6)

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [Behringer UMC1820](http://zynthian-v5-64.4sar/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5-64.4sar/hw-display)
Wiring: [V5](http://zynthian-v5-64.4sar/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x4A](http://zynthian-v5-64.4sar/hw-wiring)
- SYSTEM
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 25% (968M/3793M)
SD Card: 71% (20G/29G)
Temperature: 48.2ºC
Overclock: [Maximum](http://zynthian-v5-64.4sar/hw-options)
USB/sda1-usb-SMI_USB_DISK_3.1: [5% (9.7G/235G)](http://zynthian-v5-64.4sar/lib-captures)
- MIDI & UI
Tuning: [440 Hz](http://zynthian-v5-64.4sar/ui-midi-options)
Master Channel: [Off](http://zynthian-v5-64.4sar/ui-midi-options)
Preload Presets: [On](http://zynthian-v5-64.4sar/ui-midi-options)
ZS3 (SubSnapShots): [On](http://zynthian-v5-64.4sar/ui-midi-options)
Power Save: [10 minutes](http://zynthian-v5-64.4sar/ui-options)
Audio Levels on Snapshots: [On](http://zynthian-v5-64.4sar/ui-options)
- SOFTWARE
zyncoder: [oram (d56cd41)](https://github.com/zynthian/zyncoder/commit/d56cd41118f13b5197ba43cd779d744cc0328e87)
zynthian-ui: [oram (e5bf5d1)](https://github.com/zynthian/zynthian-ui/commit/e5bf5d124c49f9b21e8e2cdce5e2faa1b4879853)
zynthian-sys: [oram (28ecc46)](https://github.com/zynthian/zynthian-sys/commit/28ecc46be775282fe6b760fbc7f7750854d29fd9)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (68024b8)](https://github.com/zynthian/zynthian-webconf/commit/68024b8243f3d96fd5f5758e330939d9fb1d19d2)

**Additional context**
Maybe there is no terminal installed. Solution is to install terminal, e.g. `apt install xfce4-terminal`.

**Comment by riban-bw** [comment]
@jofemodo will you please add to the build: `xfce4-terminal`?

**Comment by jofemodo** [comment]
This is fixed now.

**Comment by jofemodo** [comment]
Done! It should be installed in the next update.
