### ISSUE TITLE
setBfree when Lower + Upper and CC #64

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#977]
**Describe the bug**
CC64 does not work as toggle swich for Rotary speed as it does in Upper manual preset.

With MIDI learn, sustain pedal works as temporary

**To Reproduce**
1. add Synth Chain
2. choose setBfree
3. set MIDI CH#1
4. choose Lower + Upper
5. choose Sine
6. choose Blues 1
7. play 

**Expected behavior**
When you press pedal set to CC #64 it does not work as toggle swich for Rotary speed as it works in Upper manual preset.

**Setup:**
Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO](http://zynthian.local/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian.local/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian.local/hw-wiring)
I2C: [MCP23017@0x20](http://zynthian.local/hw-wiring)
Profile: [v4_stage](http://zynthian.local/hw-wiring)

Raspbian GNU/Linux 10 (buster)
Build Date: 2024-01-16
Memory: 1% (141M/7899M)
SD Card: 40% (23G/59G)
Temperature: 51.1ºC
Overclock: [None](http://zynthian.local/hw-options)
USB/PC4: [1% (512/63M)](http://zynthian.local/lib-captures)
USB/ZYNTHIAN: [16% (1.2G/7.5G)](http://zynthian.local/lib-captures)

zyncoder: [stable (c452d2b)](https://github.com/zynthian/zyncoder/commit/c452d2bb36430b57969e249f48fdf1ed4fe3c44d)
zynthian-ui: [stable (f19f78c)](https://github.com/zynthian/zynthian-ui/commit/f19f78cd0a9472f78315755d2e67963d3c564504)
zynthian-sys: [stable (7a69951)](https://github.com/zynthian/zynthian-sys/commit/7a69951b17861a6f827b075ec52859eccf861ef2)
zynthian-data: [stable (5a40e04)](https://github.com/zynthian/zynthian-data/commit/5a40e04760f475855e8e4eff3f2e0f70a07cf971)
zynthian-webconf: [stable (7e74565)](https://github.com/zynthian/zynthian-webconf/commit/7e74565527035c804a8c57b123e14d4b323f7756)

**Comment by jofemodo** [comment]
It works for me. Sorry, i can't reproduce the issue.

**Comment by riban-bw** [comment]
This is working for me too. With two manuals enabled, CC64 toggles rotary for both, whichever manual (chain) is selected. I believe this is working by design. I will close the ticket but if you can provide a workflow that demonstrates a flaw then reopen with more info.
