### ISSUE TITLE
ORAM: after update submenus generate 500: Internal Server Error

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#979]
# Describe the bug
ORAM: after update submenus generate 500: Internal Server Error
# To Reproduce
1 create SD using BalenaEtcher and 2024-03-01-zynthianos-bookworm-aarch64-oram-2403.zip
2 switch on my zynthian
3 connect zynthian to ethernet 
4. open webconf and launch update
5. reboot
6. open webconf : submenus generate 500: Internal Server Error (excluded HELP submenu)

# Screenshots
If![image](https://github.com/zynthian/zynthian-issue-tracking/assets/97229963/24ab85d1-de20-4206-a41c-892b06f12d6c)
![image](https://github.com/zynthian/zynthian-issue-tracking/assets/97229963/b810b862-1e99-466b-b31a-abf1b8d7ad7e)

# Configuration
## Hardware
```
Raspberry Pi 3 Model B Rev 1.2
Audio: RBPi Headphones <--- DETECTED but mine is PiFi DAC+ v2.0
3,5inch RPi Display 480x320 XPT2046 touch controller
Display: Generic HDMI Display  <--- DETECTED but mine is 3,5inch RPi Display 480x320 XPT2046 touch controller
Wiring: DUMMIES
I2C: Not detected
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 51% (467M/908M)
SD Card: 47% (13G/28G)
Temperature: 41.9ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (a548b43) 
zynthian-ui: oram (d8f18de)
zynthian-sys: oram (9922f65)
zynthian-data: oram (64c5f91)
zynthian-webconf: oram (ae7fbc4)
```

**Comment by Piattica** [comment]
if can help: 
[first_boot.log](https://github.com/zynthian/zynthian-issue-tracking/files/14516178/first_boot.log)

**Comment by riban-bw** [comment]
This is resolved by reverting last change. The feature to add bug reporting in webconf (which was used by @Piattica to report this issue) is flawed. The code is being run on every page, not just the main dashboard. I removed the code and will have another go at this at a later date.
