### ISSUE TITLE
Adding SetBFree engine results in continuous progress icon

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#98]
**Describe the bug**
When adding setbfree as a new engine the Zynthian logo animates continuously and the configuration does not complete

**To Reproduce**
1. From main menu select "AddNEW Synth Layer"
2. Select "setBfree - Hammond Emulation"
3. Select "MIDI CH #97"
4. Select "Upper"
5. Select "Sine"
6. Zynthian logo starts to animate

**Expected behaviour**
Zynthian logo stops animating and selection of preset should be offered.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: No detected

SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: ???
Memory: 17% (162M/926M)
SD Card: 81% (11G/14G)
Temperature: 59.6ºC

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (15eafb9)
zynthian-sys: master (daf759a)
zynthian-data: master (3d44cc8)
zynthian-webconf: master (9fd249a)

**Log output**
Dec 20 09:05:13 zynthian startx[5852]: Exception in Tkinter callback
Dec 20 09:05:13 zynthian startx[5852]: Traceback (most recent call last):
Dec 20 09:05:13 zynthian startx[5852]: File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
Dec 20 09:05:13 zynthian startx[5852]: return self.func(*args)
Dec 20 09:05:13 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 664, in cb_keybinding
Dec 20 09:05:13 zynthian startx[5852]: self.zyngui.callable_ui_action(action)
Dec 20 09:05:13 zynthian startx[5852]: File "./zynthian_gui.py", line 605, in callable_ui_action
Dec 20 09:05:13 zynthian startx[5852]: self.zynswitch_short(3)
Dec 20 09:05:13 zynthian startx[5852]: File "./zynthian_gui.py", line 880, in zynswitch_short
Dec 20 09:05:13 zynthian startx[5852]: self.screens[self.active_screen].switch_select('S')
Dec 20 09:05:13 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 544, in switch_select
Dec 20 09:05:13 zynthian startx[5852]: self.click_listbox(None, t)
Dec 20 09:05:13 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 540, in click_listbox
Dec 20 09:05:13 zynthian startx[5852]: self.select_action(self.index, t)
Dec 20 09:05:13 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_bank.py", line 57, in select_action
Dec 20 09:05:13 zynthian startx[5852]: if self.zyngui.curlayer.set_bank(i):
Dec 20 09:05:13 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 143, in set_bank
Dec 20 09:05:13 zynthian startx[5852]: return self.engine.set_bank(self, self.bank_info)
Dec 20 09:05:13 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_engine_setbfree.py", line 301, in set_bank
Dec 20 09:05:13 zynthian startx[5852]: self.generate_config_file(midi_chans)
Dec 20 09:05:13 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_engine_setbfree.py", line 221, in generate_config_file
Dec 20 09:05:13 zynthian startx[5852]: with open(self.config_autogen_fpath, 'w+') as cfg_file:
Dec 20 09:05:13 zynthian startx[5852]: FileNotFoundError: [Errno 2] No such file or directory: '/zynthian/config/setbfree/.autogen.cfg'
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=32, step=1
Dec 20 09:05:13 zynthian startx[5852]: ZynMidiRouter: MIDI tuning frequency set to 440 Hz (8192)
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=24, step=1
Dec 20 09:05:13 zynthian startx[5852]: ZynMidiRouter: MIDI tuning frequency set to 440 Hz (8192)
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=32, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=84, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=60, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=24, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=8, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=144, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=0, pin_a=1, pin_b=0, midich=0, midictl=7, oscpath=(null), value=96, maxval=127, step=0
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=1, pin_a=3, pin_b=0, midich=0, midictl=80, oscpath=(null), value=64, maxval=127, step=8
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=2, pin_a=2, pin_b=0, midich=0, midictl=1, oscpath=(null), value=42, maxval=127, step=5
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=95, oscpath=(null), value=0, maxval=127, step=4
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=20, maxval=144, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=36, step=1
Dec 20 09:05:13 zynthian startx[5852]: Set up encoder i=3, pin_a=4, pin_b=0, midich=0, midictl=0, oscpath=(null), value=0, maxval=80, step=1
Dec 20 09:05:13 zynthian startx[5852]: ZynMidiRouter: MIDI tuning frequency set to 440 Hz (8192)
Dec 20 09:05:17 zynthian startx[5852]: WARNING:zynthian_gui_keybinding: Can't load keyboard binding config file '/zynthian/config/keybinding.yaml'. Using default.
Dec 20 09:05:17 zynthian startx[5852]: libjackpeak registering as 'jackpeak'.
Dec 20 09:05:17 zynthian startx[5852]: libjackpeak created input ports
Dec 20 09:05:20 zynthian startx[5852]: ERROR:zynthian_gui_layer: Invalid snapshot: [Errno 2] No such file or directory: '/zynthian/config/setbfree/.autogen.cfg'
Dec 20 09:05:20 zynthian startx[5852]: Traceback (most recent call last):
Dec 20 09:05:20 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 699, in load_snapshot
Dec 20 09:05:20 zynthian startx[5852]: self.layers[i].restore_snapshot_1(lss)
Dec 20 09:05:20 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 383, in restore_snapshot_1
Dec 20 09:05:20 zynthian startx[5852]: self.set_bank_by_name(snapshot['bank_name'])
Dec 20 09:05:20 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 153, in set_bank_by_name
Dec 20 09:05:20 zynthian startx[5852]: return self.set_bank(i,set_engine)
Dec 20 09:05:20 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 143, in set_bank
Dec 20 09:05:20 zynthian startx[5852]: return self.engine.set_bank(self, self.bank_info)
Dec 20 09:05:20 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_engine_setbfree.py", line 301, in set_bank
Dec 20 09:05:20 zynthian startx[5852]: self.generate_config_file(midi_chans)
Dec 20 09:05:20 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_engine_setbfree.py", line 221, in generate_config_file
Dec 20 09:05:20 zynthian startx[5852]: with open(self.config_autogen_fpath, 'w+') as cfg_file:
Dec 20 09:05:20 zynthian startx[5852]: FileNotFoundError: [Errno 2] No such file or directory: '/zynthian/config/setbfree/.autogen.cfg'
Dec 20 09:05:27 zynthian startx[5852]: ERROR:zynthian_gui_layer: Invalid snapshot: '/graph/arp/:bypass'
Dec 20 09:05:27 zynthian startx[5852]: Traceback (most recent call last):
Dec 20 09:05:27 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 705, in load_snapshot
Dec 20 09:05:27 zynthian startx[5852]: self.layers[i].restore_snapshot_2(lss)
Dec 20 09:05:27 zynthian startx[5852]: File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 415, in restore_snapshot_2
Dec 20 09:05:27 zynthian startx[5852]: self.controllers_dict[k].restore_snapshot(snapshot['controllers_dict'][k])
Dec 20 09:05:27 zynthian startx[5852]: KeyError: '/graph/arp/:bypass'
Dec 20 09:05:42 zynthian startx[5852]: ERROR:zynthian_autoconnect: Jack Audio XRUN!
Dec 20 09:05:42 zynthian startx[5852]: ERROR:zynthian_engine_modui: Connection Closed & MOD-UI stopped. Finishing...

I don't know whythere are MOD-UI entries in the log - I had not added MOD-UI since clearing all engines and rebooting, etc.

**Comment by jofemodo** [comment]
This bug is already fixed. Are your unit in master branch and updated to the last?

**Comment by riban-bw** [comment]
I did updates and reboots before reporting the issue but subsequently found webconf to be corrupt so am now flashing 2019-12-19-zynthianos-buster-lite-1.0.0. I will report success (and hopefully close ticket).

**Comment by riban-bw** [comment]
Flashed new image and updated and issue not present so closing.
