### ISSUE TITLE
Bug: oram-OS MOD-UI 

### ISSUE THREAD

**Issue by klangschmied** [zynthian/zynthian-issue-tracking#980]
# Describe the bug
MOD-Ui via Web-Config is not accessile
# To Reproduce
## Steps to reproduce the behavior:
1. Go to...
2. Click on...
3. Scroll down to...
 ## Expected behaviour
## Actual behaviour
A clear and concise description of what actually happens.
# Screenshots
# Additional context
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 12% (465M/3793M)
SD Card: 45% (13G/29G)
Temperature: 33.6ºC
Overclock: Maximum
USB/ZYNTHIAN: 1% (113M/15G)
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (a548b43) 
zynthian-ui: oram (d8f18de)
zynthian-sys: oram (9922f65)
zynthian-data: oram (64c5f91)
zynthian-webconf: oram (ae7fbc4)
```

**Comment by riban-bw** [comment]
There is almost no information in this bug report.

I cannot reproduce this issue.

- In UI, add a MOD-UI chain
- In webconf, refresh dashboard, e.g. click the zynthian icon in top left
- Select INTERFACE-MOD-UI

The MOD-UI web interface starts.

Be aware that an issue with upstream MOD-UI is that it requires significant processing in the web client so a slower machine can take a **long** time (like many minutes) to show its UI during which a _loading_ indication is shown. This is not the fault of Zynthian and a faster machine running the web client works better.
